# P2-G4 Local Agent 1: P4 Data Contract Audit

이 노트북은 모델 학습을 하지 않는다. P2-G3 `p4_handoff_candidate/shared/P4_HANDOFF_MANIFEST.json`가 가리키는 candidate 데이터와 bridge, manifest, registry를 독립적으로 다시 계산해 P4가 읽을 데이터 계약을 확정한다.

원본 P3 candidate 파일과 P3 노트북은 수정하지 않는다. 모든 새 산출물은 `workbook/p2/p2_4/p4_1_data_contract/` 아래에만 저장한다.

In [ ]:
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 240)


def find_repo_root(start: Path) -> Path:
    cur = start.resolve()
    for path in [cur, *cur.parents]:
        if (path / "scripts" / "p2_g4_1_data_contract_local1.py").exists():
            return path
    raise RuntimeError("repo root not found")


ROOT = find_repo_root(Path.cwd())
SCRIPT = ROOT / "scripts" / "p2_g4_1_data_contract_local1.py"
OUT_ROOT = ROOT / "workbook" / "p2" / "p2_4" / "p4_1_data_contract"
QA = OUT_ROOT / "qa"
PROFILES = OUT_ROOT / "profiles"
SAMPLES = OUT_ROOT / "samples"
LOGS = OUT_ROOT / "logs"
REPORTS = OUT_ROOT / "reports"
ARTIFACTS = OUT_ROOT / "artifacts"

print("ROOT:", ROOT)
print("SCRIPT:", SCRIPT)
print("OUT_ROOT:", OUT_ROOT)

ROOT: /home/sieg/projects-wsl/SBS_dataScience
SCRIPT: /home/sieg/projects-wsl/SBS_dataScience/scripts/p2_g4_1_data_contract_local1.py
OUT_ROOT: /home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract

## Gate Run - Execute Contract Script

In [ ]:
result = subprocess.run(
    [sys.executable, str(SCRIPT)],
    cwd=ROOT,
    text=True,
    capture_output=True,
)
print(result.stdout[-8000:])
if result.stderr.strip():
    print(result.stderr[-8000:])
if result.returncode != 0:
    raise RuntimeError(f"contract script failed: {result.returncode}")

summary = json.loads((REPORTS / "final_status.json").read_text(encoding="utf-8"))
display(pd.DataFrame([
    {
        "final_status": summary["final_status"],
        "fail_count": summary["fail_count"],
        "warn_count": summary["warn_count"],
        "output_root": summary["outputs"]["root"],
    }
]))

: 6366,
        "actual_with_structure_n": 6366,
        "registry_train_n": 5499,
        "actual_train_n": 5499,
        "registry_val_n": 1141,
        "actual_val_n": 1141,
        "registry_test_n": 858,
        "actual_test_n": 858,
        "registry_actual_mismatch_n": 0,
        "status": "PASS"
      },
      {
        "sample_id": "JOINT_EMP_PROG",
        "registry_usable_rows_n": 7389,
        "actual_usable_rows_n": 7389,
        "registry_with_structure_n": 6270,
        "actual_with_structure_n": 6270,
        "registry_train_n": 5428,
        "actual_train_n": 5428,
        "registry_val_n": 1121,
        "actual_val_n": 1121,
        "registry_test_n": 840,
        "actual_test_n": 840,
        "registry_actual_mismatch_n": 0,
        "status": "PASS"
      }
    ]
  },
  "gate7": {
    "registry_missing_n": 0,
    "all_null_active_feature_set_n": 0,
    "p4_use_column_n": 120,
    "target_candidate_n": 6,
    "feature_set_n": 4
  },
  "paths": {
    "D01_v2": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/dept_headcount_master_2024.parquet",
    "D02_v2": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/dept_outcomes_2024.parquet",
    "D03_v2": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/dept_master_2024_core.parquet",
    "D04_v2": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/wage_reference_by_major.parquet",
    "D05_v2": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/job_cert_bridge.parquet",
    "D08_v2_shared_candidate": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet",
    "bridge_campus_alias": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/bridge_campus_alias.csv",
    "bridge_department_alias": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/bridge_department_alias.csv",
    "bridge_department_major7_v2": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/bridge_department_major7_v2.csv",
    "bridge_outcome_headcount_v2": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/bridge_outcome_headcount_v2.csv",
    "bridge_school_alias": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/bridge_school_alias.csv",
    "department_model_column_registry": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/department_model_column_registry.csv",
    "dim_headcount_grain_definition": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/dim_headcount_grain_definition.csv",
    "dim_school_split": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/dim_school_split.csv",
    "model_sample_membership": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/model_sample_membership.parquet",
    "model_sample_registry": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/model_sample_registry.csv",
    "p4_feature_set_registry": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/p4_feature_set_registry.csv",
    "p4_target_candidate_registry": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/local1/p4_target_candidate_registry.csv",
    "shared_department_model_column_registry": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/department_model_column_registry.csv",
    "shared_dim_school_split": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/dim_school_split.csv",
    "shared_model_sample_membership": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/model_sample_membership.parquet",
    "shared_model_sample_registry": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/model_sample_registry.csv",
    "shared_p4_feature_set_registry": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/p4_feature_set_registry.csv",
    "shared_p4_target_candidate_registry": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/p4_target_candidate_registry.csv"
  },
  "hashes": {
    "D01_v2": "2f187b5af44c828d4107af12368029caf6b83b6254af75b9653b6402b8f1b0ce",
    "D02_v2": "45f8aa40f31e14b83b5d97f594abf89bb4a5aaa4bc67735767e19077d189f493",
    "D03_v2": "c6fd569052684502e5bab5758510d3cd945f68ddeaa47fdfb3e9bab803889dca",
    "D04_v2": "489caf15edbefa1ed0c30fdfa98dbe31096b36c219f6610dae69a2d5e49c47e5",
    "D05_v2": "f4447cf519bdf366e36851a68e6ec6b6605f9c9a591d96c911de4eece2327246",
    "D08_v2_shared_candidate": "598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962",
    "bridge_campus_alias": "8033c6f596aec13af52dd3cb255ba4414b6a03299cd0a9cb7c6e8c91a3f7a0fa",
    "bridge_department_alias": "2d380712d1220dab414976a8b0cc67708285dafe6f413e030e61fa953a1c936c",
    "bridge_department_major7_v2": "7a92574bd2d8928304cffb08ecbafa4a3ce2c3112a3afe19ae2852e16138fbab",
    "bridge_outcome_headcount_v2": "0ee76ab52f2f78e841ef341d740e9098cfafb1d7c1d277f577657d1b3d454bea",
    "bridge_school_alias": "c4ea27cd4a71a4b93189578c0f6f28463bfd1981fb9a5abb5f9f2b8768499dc3",
    "department_model_column_registry": "5871ec9ae36dd0e078eed403c67322784e3880d2fa82849671be45a6d252e126",
    "dim_headcount_grain_definition": "76857c3cebefbbcc9b3df77ea067c44f7cee0a4fe7517acf7fc946c5c3681a7e",
    "dim_school_split": "85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842c031e487e8f2a13583",
    "model_sample_membership": "ef7eb73a35e9a058959747272d1b1e832622c415adeb363754dcb0fcb507c830",
    "model_sample_registry": "b3389c0051d9b9eeca555f43cd8194d99574c2444df68cd8273232f7f9a553f8",
    "p4_feature_set_registry": "776c7072444b5abee02f9a20942ca24cff5ec5c684593299a2c8c43dbf7a6529",
    "p4_target_candidate_registry": "3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c99d5f106e6313b5247",
    "shared_department_model_column_registry": "5871ec9ae36dd0e078eed403c67322784e3880d2fa82849671be45a6d252e126",
    "shared_dim_school_split": "85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842c031e487e8f2a13583",
    "shared_model_sample_membership": "ef7eb73a35e9a058959747272d1b1e832622c415adeb363754dcb0fcb507c830",
    "shared_model_sample_registry": "b3389c0051d9b9eeca555f43cd8194d99574c2444df68cd8273232f7f9a553f8",
    "shared_p4_feature_set_registry": "776c7072444b5abee02f9a20942ca24cff5ec5c684593299a2c8c43dbf7a6529",
    "shared_p4_target_candidate_registry": "3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c99d5f106e6313b5247"
  },
  "final_status": "P4_DATA_CONTRACT_READY",
  "fail_count": 0,
  "warn_count": 1,
  "outputs": {
    "root": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract",
    "manifest_integrity_audit": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/manifest_integrity_audit.csv",
    "d01_grain_explanation": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/reports/D01_GRAIN_EXPLANATION.md",
    "p4_data_card": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/reports/P4_D08_DATA_CARD.md",
    "integrity_report": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/reports/P4_DATA_INTEGRITY_REPORT.md",
    "failed_checks": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/failed_checks.csv",
    "warn_checks": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/warn_checks.csv",
    "run_manifest": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/logs/run_manifest.json"
  }
}

             final_status  fail_count  warn_count                                        output_root
0  P4_DATA_CONTRACT_READY           0           1  /home/sieg/projects-wsl/SBS_dataScience/workbo...

In [ ]:
def read_csv(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, encoding="utf-8-sig", low_memory=False)


def show_csv(title: str, path: Path, n: int | None = None) -> pd.DataFrame:
    display(Markdown(f"### {title}\n`{path}`"))
    df = read_csv(path)
    display(df if n is None else df.head(n))
    print("shape:", df.shape)
    return df


def show_md(title: str, path: Path) -> None:
    display(Markdown(f"### {title}\n`{path}`"))
    display(Markdown(path.read_text(encoding="utf-8")))


def gate_summary(gate_name: str, payload: dict) -> None:
    display(Markdown(f"## {gate_name} Summary"))
    display(pd.DataFrame([payload]))

## Gate 0 - Manifest And Lineage Integrity

In [ ]:
gate_summary("Gate 0", summary["gate0"])
manifest_audit = show_csv("Manifest integrity audit", QA / "manifest_integrity_audit.csv")
display(manifest_audit[["artifact_name", "section", "path", "manifest_hash", "actual_hash", "hash_match", "manifest_shape", "actual_shape", "shape_match", "modified_after_manifest", "status"]])
display(manifest_audit["status"].value_counts(dropna=False).rename_axis("status").reset_index(name="rows"))

## Gate 0 Summary

   manifest_audit_rows  hash_mismatch_n  shape_mismatch_n  missing_n  modified_after_manifest_n  hard_fail_n
0                   37                0                 0          0                          0            0

### Manifest integrity audit
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/manifest_integrity_audit.csv`

,artifact_name,section,path,manifest_hash,actual_hash,hash_match,manifest_shape,actual_shape,shape_match,manifest_created_at,actual_mtime,modified_after_manifest,status
0,P4_HANDOFF_MANIFEST,manifest_self,/home/sieg/projects-wsl/SBS_dataScience/workbo...,b9ea9528b24630f15be8913012b40df81692d16e849120...,b9ea9528b24630f15be8913012b40df81692d16e849120...,True,NaN,NaN,True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
1,raw_excel,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,c767832c42fb2be505c4d9bb8ae0bc39891091f86c6ae8...,c767832c42fb2be505c4d9bb8ae0bc39891091f86c6ae8...,True,NaN,NaN,True,2026-07-12T21:47:51,2026-07-12T16:54:55,False,PASS
2,outcome_spine_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b61...,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b61...,True,NaN,"[10242, 17]",True,2026-07-12T21:47:51,2026-07-12T19:12:08,False,PASS
3,wage_reference_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,90f94f0b781d88a45a168a3b60095b16537a532de1dbee...,90f94f0b781d88a45a168a3b60095b16537a532de1dbee...,True,NaN,"[14, 66]",True,2026-07-12T21:47:51,2026-07-12T19:12:08,False,PASS
4,wage_quartile_reference_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,c46a158b418c8ec114af62a95d978692cc75890ff55006...,c46a158b418c8ec114af62a95d978692cc75890ff55006...,True,NaN,"[23, 10]",True,2026-07-12T21:47:51,2026-07-12T19:12:08,False,PASS
5,wage_column_contract_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,2431de62f6b0b8d3276b603d64f94c7cbdeaa4450aa79f...,2431de62f6b0b8d3276b603d64f94c7cbdeaa4450aa79f...,True,NaN,"[66, 10]",True,2026-07-12T21:47:51,2026-07-12T19:12:08,False,PASS
6,job_cert_bridge_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,e88fe083e07430f96f5549071cde674021048c3f482f69...,e88fe083e07430f96f5549071cde674021048c3f482f69...,True,NaN,"[24, 26]",True,2026-07-12T21:47:51,2026-07-12T19:12:09,False,PASS
7,D01_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,2f187b5af44c828d4107af12368029caf6b83b6254af75...,2f187b5af44c828d4107af12368029caf6b83b6254af75...,True,"[34969, 186]","[34969, 186]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
8,D02_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,45f8aa40f31e14b83b5d97f594abf89bb4a5aaa4bc6773...,45f8aa40f31e14b83b5d97f594abf89bb4a5aaa4bc6773...,True,"[10242, 37]","[10242, 37]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
9,D03_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,c6fd569052684502e5bab5758510d3cd945f68ddeaa47f...,c6fd569052684502e5bab5758510d3cd945f68ddeaa47f...,True,"[10242, 108]","[10242, 108]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
10,D04_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,489caf15edbefa1ed0c30fdfa98dbe31096b36c219f661...,489caf15edbefa1ed0c30fdfa98dbe31096b36c219f661...,True,"[14, 87]","[14, 87]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
11,D05_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,f4447cf519bdf366e36851a68e6ec6b6605f9c9a591d96...,f4447cf519bdf366e36851a68e6ec6b6605f9c9a591d96...,True,"[24, 32]","[24, 32]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
12,D08_v2_shared_candidate,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,598b68b31b5358dfd23839d4c138cc64838d05876b7791...,598b68b31b5358dfd23839d4c138cc64838d05876b7791...,True,"[10242, 151]","[10242, 151]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
13,bridge_campus_alias,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,8033c6f596aec13af52dd3cb255ba4414b6a03299cd0a9...,8033c6f596aec13af52dd3cb255ba4414b6a03299cd0a9...,True,"[229, 10]","[229, 10]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
14,bridge_department_alias,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,2d380712d1220dab414976a8b0cc67708285dafe6f413e...,2d380712d1220dab414976a8b0cc67708285dafe6f413e...,True,"[19990, 10]","[19990, 10]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
15,bridge_department_major7_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,7a92574bd2d8928304cffb08ecbafa4a3ce2c3112a3afe...,7a92574bd2d8928304cffb08ecbafa4a3ce2c3112a3afe...,True,"[10242, 8]","[10242, 8]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
16,bridge_outcome_headcount_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,0ee76ab52f2f78e841ef341d740e9098cfafb1d7c1d277...,0ee76ab52f2f78e841ef341d740e9098cfafb1d7c1d277...,True,"[10242, 17]","[10242, 17]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
17,bridge_school_alias,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,c4ea27cd4a71a4b93189578c0f6f28463bfd1981fb9a5a...,c4ea27cd4a71a4b93189578c0f6f28463bfd1981fb9a5a...,True,"[1919, 6]","[1919, 6]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
18,department_model_column_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,5871ec9ae36dd0e078eed403c67322784e3880d2fa8284...,5871ec9ae36dd0e078eed403c67322784e3880d2fa8284...,True,"[198, 6]","[198, 6]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
19,dim_headcount_grain_definition,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,76857c3cebefbbcc9b3df77ea067c44f7cee0a4fe7517a...,76857c3cebefbbcc9b3df77ea067c44f7cee0a4fe7517a...,True,"[6, 3]","[6, 3]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
20,dim_school_split,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842...,85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842...,True,"[200, 6]","[200, 6]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
21,model_sample_membership,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,ef7eb73a35e9a058959747272d1b1e832622c415adeb36...,ef7eb73a35e9a058959747272d1b1e832622c415adeb36...,True,"[10242, 17]","[10242, 17]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
22,model_sample_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,b3389c0051d9b9eeca555f43cd8194d99574c2444df68c...,b3389c0051d9b9eeca555f43cd8194d99574c2444df68c...,True,"[5, 12]","[5, 12]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
23,p4_feature_set_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,776c7072444b5abee02f9a20942ca24cff5ec5c6845932...,776c7072444b5abee02f9a20942ca24cff5ec5c6845932...,True,"[4, 7]","[4, 7]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
24,p4_target_candidate_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c...,3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c...,True,"[6, 4]","[6, 4]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
25,shared_department_model_column_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,5871ec9ae36dd0e078eed403c67322784e3880d2fa8284...,5871ec9ae36dd0e078eed403c67322784e3880d2fa8284...,True,"[198, 6]","[198, 6]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
26,shared_dim_school_split,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842...,85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842...,True,"[200, 6]","[200, 6]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
27,shared_model_sample_membership,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,ef7eb73a35e9a058959747272d1b1e832622c415adeb36...,ef7eb73a35e9a058959747272d1b1e832622c415adeb36...,True,"[10242, 17]","[10242, 17]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
28,shared_model_sample_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,b3389c0051d9b9eeca555f43cd8194d99574c2444df68c...,b3389c0051d9b9eeca555f43cd8194d99574c2444df68c...,True,"[5, 12]","[5, 12]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
29,shared_p4_feature_set_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,776c7072444b5abee02f9a20942ca24cff5ec5c6845932...,776c7072444b5abee02f9a20942ca24cff5ec5c6845932...,True,"[4, 7]","[4, 7]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
30,shared_p4_target_candidate_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c...,3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c...,True,"[6, 4]","[6, 4]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
31,decision_log,local1_logs,/home/sieg/projects-wsl/SBS_dataScience/workbo...,f97f96c57575d91494b96f1ad8691dbc8ce677e6e6995f...,f97f96c57575d91494b96f1ad8691dbc8ce677e6e6995f...,True,NaN,"[17, 13]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
32,transformation_log,local1_logs,/home/sieg/projects-wsl/SBS_dataScience/workbo...,9b2dbee2823f2d6c5b434a624dc3782a7224887e6169c7...,9b2dbee2823f2d6c5b434a624dc3782a7224887e6169c7...,True,NaN,"[4, 23]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
33,merge_audit,local1_logs,/home/sieg/projects-wsl/SBS_dataScience/workbo...,0cf9601d2de588cc6939055dc72006629d95e17f8e4c1f...,0cf9601d2de588cc6939055dc72006629d95e17f8e4c1f...,True,NaN,"[3, 17]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
34,schema_deviation_report,local1_logs,/home/sieg/projects-wsl/SBS_dataScience/workbo...,051a145e92aaf7aaf3e8464c22eed7ff699ca244b2d4d1...,051a145e92aaf7aaf3e8464c22eed7ff699ca244b2d4d1...,True,NaN,"[4, 6]",True,2026-07-12T21:47:51,2026-07-12T21:47:51,False,PASS
35,local2_D07_handoff,local2,/home/sieg/projects-wsl/SBS_dataScience/workbo...,f44c6f9e7a7539361dce301686144780e0ce588deb929b...,f44c6f9e7a7539361dce301686144780e0ce588deb929b...,True,"[7, 29]","[7, 29]",True,2026-07-12T21:47:51,2026-07-12T21:38:43,False,PASS
36,LOCAL2_HANDOFF_MANIFEST,local2,/home/sieg/projects-wsl/SBS_dataScience/workbo...,24609ead002563288af769758e91bf26b82f972e0be7e1...,24609ead002563288af769758e91bf26b82f972e0be7e1...,True,NaN,NaN,True,2026-07-12T21:47:51,2026-07-12T21:38:43,False,PASS

shape: (37, 13)

,artifact_name,section,path,manifest_hash,actual_hash,hash_match,manifest_shape,actual_shape,shape_match,modified_after_manifest,status
0,P4_HANDOFF_MANIFEST,manifest_self,/home/sieg/projects-wsl/SBS_dataScience/workbo...,b9ea9528b24630f15be8913012b40df81692d16e849120...,b9ea9528b24630f15be8913012b40df81692d16e849120...,True,NaN,NaN,True,False,PASS
1,raw_excel,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,c767832c42fb2be505c4d9bb8ae0bc39891091f86c6ae8...,c767832c42fb2be505c4d9bb8ae0bc39891091f86c6ae8...,True,NaN,NaN,True,False,PASS
2,outcome_spine_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b61...,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b61...,True,NaN,"[10242, 17]",True,False,PASS
3,wage_reference_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,90f94f0b781d88a45a168a3b60095b16537a532de1dbee...,90f94f0b781d88a45a168a3b60095b16537a532de1dbee...,True,NaN,"[14, 66]",True,False,PASS
4,wage_quartile_reference_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,c46a158b418c8ec114af62a95d978692cc75890ff55006...,c46a158b418c8ec114af62a95d978692cc75890ff55006...,True,NaN,"[23, 10]",True,False,PASS
5,wage_column_contract_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,2431de62f6b0b8d3276b603d64f94c7cbdeaa4450aa79f...,2431de62f6b0b8d3276b603d64f94c7cbdeaa4450aa79f...,True,NaN,"[66, 10]",True,False,PASS
6,job_cert_bridge_raw,source_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,e88fe083e07430f96f5549071cde674021048c3f482f69...,e88fe083e07430f96f5549071cde674021048c3f482f69...,True,NaN,"[24, 26]",True,False,PASS
7,D01_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,2f187b5af44c828d4107af12368029caf6b83b6254af75...,2f187b5af44c828d4107af12368029caf6b83b6254af75...,True,"[34969, 186]","[34969, 186]",True,False,PASS
8,D02_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,45f8aa40f31e14b83b5d97f594abf89bb4a5aaa4bc6773...,45f8aa40f31e14b83b5d97f594abf89bb4a5aaa4bc6773...,True,"[10242, 37]","[10242, 37]",True,False,PASS
9,D03_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,c6fd569052684502e5bab5758510d3cd945f68ddeaa47f...,c6fd569052684502e5bab5758510d3cd945f68ddeaa47f...,True,"[10242, 108]","[10242, 108]",True,False,PASS
10,D04_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,489caf15edbefa1ed0c30fdfa98dbe31096b36c219f661...,489caf15edbefa1ed0c30fdfa98dbe31096b36c219f661...,True,"[14, 87]","[14, 87]",True,False,PASS
11,D05_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,f4447cf519bdf366e36851a68e6ec6b6605f9c9a591d96...,f4447cf519bdf366e36851a68e6ec6b6605f9c9a591d96...,True,"[24, 32]","[24, 32]",True,False,PASS
12,D08_v2_shared_candidate,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,598b68b31b5358dfd23839d4c138cc64838d05876b7791...,598b68b31b5358dfd23839d4c138cc64838d05876b7791...,True,"[10242, 151]","[10242, 151]",True,False,PASS
13,bridge_campus_alias,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,8033c6f596aec13af52dd3cb255ba4414b6a03299cd0a9...,8033c6f596aec13af52dd3cb255ba4414b6a03299cd0a9...,True,"[229, 10]","[229, 10]",True,False,PASS
14,bridge_department_alias,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,2d380712d1220dab414976a8b0cc67708285dafe6f413e...,2d380712d1220dab414976a8b0cc67708285dafe6f413e...,True,"[19990, 10]","[19990, 10]",True,False,PASS
15,bridge_department_major7_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,7a92574bd2d8928304cffb08ecbafa4a3ce2c3112a3afe...,7a92574bd2d8928304cffb08ecbafa4a3ce2c3112a3afe...,True,"[10242, 8]","[10242, 8]",True,False,PASS
16,bridge_outcome_headcount_v2,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,0ee76ab52f2f78e841ef341d740e9098cfafb1d7c1d277...,0ee76ab52f2f78e841ef341d740e9098cfafb1d7c1d277...,True,"[10242, 17]","[10242, 17]",True,False,PASS
17,bridge_school_alias,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,c4ea27cd4a71a4b93189578c0f6f28463bfd1981fb9a5a...,c4ea27cd4a71a4b93189578c0f6f28463bfd1981fb9a5a...,True,"[1919, 6]","[1919, 6]",True,False,PASS
18,department_model_column_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,5871ec9ae36dd0e078eed403c67322784e3880d2fa8284...,5871ec9ae36dd0e078eed403c67322784e3880d2fa8284...,True,"[198, 6]","[198, 6]",True,False,PASS
19,dim_headcount_grain_definition,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,76857c3cebefbbcc9b3df77ea067c44f7cee0a4fe7517a...,76857c3cebefbbcc9b3df77ea067c44f7cee0a4fe7517a...,True,"[6, 3]","[6, 3]",True,False,PASS
20,dim_school_split,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842...,85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842...,True,"[200, 6]","[200, 6]",True,False,PASS
21,model_sample_membership,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,ef7eb73a35e9a058959747272d1b1e832622c415adeb36...,ef7eb73a35e9a058959747272d1b1e832622c415adeb36...,True,"[10242, 17]","[10242, 17]",True,False,PASS
22,model_sample_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,b3389c0051d9b9eeca555f43cd8194d99574c2444df68c...,b3389c0051d9b9eeca555f43cd8194d99574c2444df68c...,True,"[5, 12]","[5, 12]",True,False,PASS
23,p4_feature_set_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,776c7072444b5abee02f9a20942ca24cff5ec5c6845932...,776c7072444b5abee02f9a20942ca24cff5ec5c6845932...,True,"[4, 7]","[4, 7]",True,False,PASS
24,p4_target_candidate_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c...,3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c...,True,"[6, 4]","[6, 4]",True,False,PASS
25,shared_department_model_column_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,5871ec9ae36dd0e078eed403c67322784e3880d2fa8284...,5871ec9ae36dd0e078eed403c67322784e3880d2fa8284...,True,"[198, 6]","[198, 6]",True,False,PASS
26,shared_dim_school_split,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842...,85c2c851ddcfd02d5ead41dbd9424124e4ef1993347842...,True,"[200, 6]","[200, 6]",True,False,PASS
27,shared_model_sample_membership,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,ef7eb73a35e9a058959747272d1b1e832622c415adeb36...,ef7eb73a35e9a058959747272d1b1e832622c415adeb36...,True,"[10242, 17]","[10242, 17]",True,False,PASS
28,shared_model_sample_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,b3389c0051d9b9eeca555f43cd8194d99574c2444df68c...,b3389c0051d9b9eeca555f43cd8194d99574c2444df68c...,True,"[5, 12]","[5, 12]",True,False,PASS
29,shared_p4_feature_set_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,776c7072444b5abee02f9a20942ca24cff5ec5c6845932...,776c7072444b5abee02f9a20942ca24cff5ec5c6845932...,True,"[4, 7]","[4, 7]",True,False,PASS
30,shared_p4_target_candidate_registry,output_files,/home/sieg/projects-wsl/SBS_dataScience/workbo...,3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c...,3e48aaea329c4df989af2e078635fd7d7cd1677d5afd6c...,True,"[6, 4]","[6, 4]",True,False,PASS
31,decision_log,local1_logs,/home/sieg/projects-wsl/SBS_dataScience/workbo...,f97f96c57575d91494b96f1ad8691dbc8ce677e6e6995f...,f97f96c57575d91494b96f1ad8691dbc8ce677e6e6995f...,True,NaN,"[17, 13]",True,False,PASS
32,transformation_log,local1_logs,/home/sieg/projects-wsl/SBS_dataScience/workbo...,9b2dbee2823f2d6c5b434a624dc3782a7224887e6169c7...,9b2dbee2823f2d6c5b434a624dc3782a7224887e6169c7...,True,NaN,"[4, 23]",True,False,PASS
33,merge_audit,local1_logs,/home/sieg/projects-wsl/SBS_dataScience/workbo...,0cf9601d2de588cc6939055dc72006629d95e17f8e4c1f...,0cf9601d2de588cc6939055dc72006629d95e17f8e4c1f...,True,NaN,"[3, 17]",True,False,PASS
34,schema_deviation_report,local1_logs,/home/sieg/projects-wsl/SBS_dataScience/workbo...,051a145e92aaf7aaf3e8464c22eed7ff699ca244b2d4d1...,051a145e92aaf7aaf3e8464c22eed7ff699ca244b2d4d1...,True,NaN,"[4, 6]",True,False,PASS
35,local2_D07_handoff,local2,/home/sieg/projects-wsl/SBS_dataScience/workbo...,f44c6f9e7a7539361dce301686144780e0ce588deb929b...,f44c6f9e7a7539361dce301686144780e0ce588deb929b...,True,"[7, 29]","[7, 29]",True,False,PASS
36,LOCAL2_HANDOFF_MANIFEST,local2,/home/sieg/projects-wsl/SBS_dataScience/workbo...,24609ead002563288af769758e91bf26b82f972e0be7e1...,24609ead002563288af769758e91bf26b82f972e0be7e1...,True,NaN,NaN,True,False,PASS

  status  rows
0   PASS    37

## Gate 1 - D01 v2 Grain And Count Conservation

In [ ]:
gate_summary("Gate 1", summary["gate1"])
display(Markdown(f"**Grain sentence:** {summary['gate1']['d01_sentence']}"))
show_csv("D01 dtype and key profile", PROFILES / "d01_grain_profile.csv")
show_csv("D01 top missing columns", PROFILES / "d01_missing_top200.csv", n=40)
show_csv("D01 count conservation", QA / "d01_count_conservation.csv")
show_csv("D01 duplicate audit", QA / "d01_duplicate_audit.csv")
show_csv("D01 row-axis comparison", PROFILES / "d01_row_axis_comparison.csv", n=120)
show_md("D01 grain explanation", REPORTS / "D01_GRAIN_EXPLANATION.md")

## Gate 1 Summary

,d01_shape,raw_excel_shape,old_main_shape,d01_key,d01_key_nunique,d01_key_duplicate_n,d01_exact_duplicate_raw_columns_n,d01_lineage_missing_n,d01_unexplained_count_delta_n,d01_sentence
0,"[34969, 186]","[34969, 130]","[15727, 120]","[analysis_year, school_name_std, campus_name_s...",34969,0,0,0,0,D01의 한 행은 2024년 × 학교표준명 × 캠퍼스(본분교/제N캠퍼스) × 주야구...

**Grain sentence:** D01의 한 행은 2024년 × 학교표준명 × 캠퍼스(본분교/제N캠퍼스) × 주야구분 × 학위과정 × KEDI 학과코드의 구조자료 관측치이다.

### D01 dtype and key profile
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/d01_grain_profile.csv`

  dataset    dtype  column_count   rows  columns                                        key_columns  key_duplicate_rows  full_duplicate_rows  missing_cells
0  D01_v2    int64           109  34969      186  analysis_year|school_name_std|campus_name_std|...                   0                    0         144867
1  D01_v2   string            26  34969      186  analysis_year|school_name_std|campus_name_std|...                   0                    0         144867
2  D01_v2      str            24  34969      186  analysis_year|school_name_std|campus_name_std|...                   0                    0         144867
3  D01_v2    Int32            13  34969      186  analysis_year|school_name_std|campus_name_std|...                   0                    0         144867
4  D01_v2  Float32            10  34969      186  analysis_year|school_name_std|campus_name_std|...                   0                    0         144867
5  D01_v2  boolean             3  34969      186  analysis_year|school_name_std|campus_name_std|...                   0                    0         144867
6  D01_v2    Int16             1  34969      186  analysis_year|school_name_std|campus_name_std|...                   0                    0         144867

shape: (7, 9)

### D01 top missing columns
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/d01_missing_top200.csv`

   dataset                           column  missing_n  missing_rate    dtype
0   D01_v2                competition_ratio      24508      0.700849  Float32
1   D01_v2            admission_yield_ratio      24508      0.700849  Float32
2   D01_v2                            대학원구분      22394      0.640396      str
3   D01_v2            student_faculty_ratio      18370      0.525322  Float32
4   D01_v2       fulltime_faculty_share_pct      18370      0.525322  Float32
5   D01_v2        admit_per_applicant_ratio      14323      0.409591  Float32
6   D01_v2                   leave_rate_pct       5128      0.146644  Float32
7   D01_v2         female_student_share_pct       5128      0.146644  Float32
8   D01_v2  international_student_share_pct       5128      0.146644  Float32
9   D01_v2                             팩스번호       4773      0.136492      str
10  D01_v2                             전화번호       1230      0.035174      str
11  D01_v2                             홈페이지       1007      0.028797      str
12  D01_v2                               연도          0      0.000000      str
13  D01_v2                               학제          0      0.000000      str
14  D01_v2                              학교명          0      0.000000      str
15  D01_v2                             학교상태          0      0.000000      str
16  D01_v2                              본분교          0      0.000000      str
17  D01_v2                               시도          0      0.000000      str
18  D01_v2                              시군구          0      0.000000      str
19  D01_v2                               설립          0      0.000000      str
20  D01_v2                             주야구분          0      0.000000      str
21  D01_v2                               주소          0      0.000000      str
22  D01_v2                             우편번호          0      0.000000      str
23  D01_v2                             학위과정          0      0.000000      str
24  D01_v2                              대계열          0      0.000000      str
25  D01_v2                              중계열          0      0.000000      str
26  D01_v2                              소계열          0      0.000000      str
27  D01_v2                             학과코드          0      0.000000      str
28  D01_v2                              학과명          0      0.000000      str
29  D01_v2                           학과수_전체          0      0.000000    int64
30  D01_v2                           학과수_석사          0      0.000000    int64
31  D01_v2                           학과수_박사          0      0.000000    int64
32  D01_v2                        입학정원_학부_계          0      0.000000    int64
33  D01_v2                      정원내_입학정원_학부          0      0.000000    int64
34  D01_v2                      정원외_입학정원_학부          0      0.000000    int64
35  D01_v2                        모집인원_학부_계          0      0.000000    int64
36  D01_v2                      정원내_모집인원_학부          0      0.000000    int64
37  D01_v2                      정원외_모집정원_학부          0      0.000000    int64
38  D01_v2                         지원자_전체_계          0      0.000000    int64
39  D01_v2                         지원자_전체_남          0      0.000000    int64

shape: (186, 5)

### D01 count conservation
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/d01_count_conservation.csv`

                metric raw_excel_column             d01_column  raw_excel_sum    d01_sum  d01_minus_raw_excel  old_15727_csv_sum  d01_minus_old_15727_csv conservation_status       old_csv_difference_class
0   admission capacity        입학정원_학부_계   admission_capacity_n       570994.0   570994.0                  0.0           172239.0                 398755.0                PASS  scope_restored_from_raw_excel
1          recruitment        모집인원_학부_계          recruitment_n       730121.0   730121.0                  0.0           198196.0                 531925.0                PASS  scope_restored_from_raw_excel
2           applicants         지원자_전체_계           applicants_n      4313143.0  4313143.0                  0.0          1741880.0                2571263.0                PASS  scope_restored_from_raw_excel
3               admits         입학자_전체_계               admits_n       705185.0   705185.0                  0.0           276449.0                 428736.0                PASS  scope_restored_from_raw_excel
4    enrolled students         재적생_전체_계    enrolled_students_n      3007242.0  3007242.0                  0.0          1174581.0                1832661.0                PASS  scope_restored_from_raw_excel
5            graduates           졸업자_전체            graduates_n       634899.0   634899.0                  0.0           231967.0                 402932.0                PASS  scope_restored_from_raw_excel
6     fulltime faculty           전임교원_계     fulltime_faculty_n        86859.0    86859.0                  0.0            43123.0                  43736.0                PASS  scope_restored_from_raw_excel
7  nonfulltime faculty          비전임교원_계  nonfulltime_faculty_n       141428.0   141428.0                  0.0            64141.0                  77287.0                PASS  scope_restored_from_raw_excel

shape: (8, 10)

### D01 duplicate audit
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/d01_duplicate_audit.csv`

                                       audit_item                                                key  duplicate_rows status
0                  canonical_grain_duplicate_rows  analysis_year|school_name_std|campus_name_std|...               0   PASS
1                exact_duplicate_rows_raw_columns  all restored raw Excel columns excluding sourc...               0   PASS
2  legacy_grain_duplicate_rows_without_day_degree  analysis_year|school_name_std|campus_name_std|...               1   INFO
3                            lineage_missing_rows                   source_excel_row/raw_row_lineage               0   PASS

shape: (4, 4)

### D01 row-axis comparison
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/d01_row_axis_comparison.csv`

    axis      value  raw_excel_rows  old_15727_csv_rows  d01_rows
0   학위과정       대학과정           15526                7494     15526
1   학위과정      대학원과정           12575                7467     12575
2   학위과정     전문대학과정            6868                 766      6868
3   주야구분        계절제             155                   0       155
4   주야구분         야간            3943                   0      3943
5   주야구분     야간+계절제             244                   0       244
6   주야구분      야간+원격              18                   0        18
7   주야구분         원격             618                   0       618
8   주야구분         주간           15732                   0     15732
9   주야구분     주간+계절제              46                   0        46
10  주야구분      주간+원격              18                   0        18
11  주야구분        주야간           14002                   0     14002
12  주야구분    주야간+계절제              69                   0        69
13  주야구분     주야간+원격             124                   0       124
14  학교상태         기존           33657                   0     33657
15  학교상태         신설              25                   0        25
16  학교상태         폐교             458                   0       458
17  학교상태      학교명변경             829                   0       829
18    학제   각종대학(대학)              33                  29        33
19    학제       교육대학             150                 150       150
20    학제       기능대학             317                 129       317
21    학제       기술대학               5                   0         5
22    학제        대학교           14642                7314     14642
23    학제    방송통신대학교              36                   0        36
24    학제   사내대학(대학)               4                   1         4
25    학제   사내대학(전문)               3                   2         3
26    학제  사이버대학(대학)             480                   0       480
27    학제  사이버대학(전문)              37                   0        37
28    학제       산업대학             165                   0       165
29    학제   원격대학(대학)              11                   0        11
30    학제   원격대학(전문)              18                   0        18
31    학제      일반대학원            6960                6711      6960
32    학제       전공대학              67                   0        67
33    학제       전문대학            6426                 635      6426
34    학제      전문대학원             840                 637       840
35    학제      특수대학원            4775                 119      4775
36   본분교  본교(제1캠퍼스)           31141               13696     31141
37   본분교  본교(제2캠퍼스)            2807                1462      2807
38   본분교  본교(제3캠퍼스)             276                 203       276
39   본분교  본교(제4캠퍼스)              27                  27        27
40   본분교  분교(제1캠퍼스)             718                 339       718
41   대계열       공학계열            8736                4212      8736
42   대계열       교육계열            2980                1007      2980
43   대계열       사회계열            7974                3086      7974
44   대계열      예체능계열            4734                1920      4734
45   대계열       의약계열            2339                 928      2339
46   대계열       인문계열            3951                2109      3951
47   대계열       자연계열            4255                2465      4255

shape: (48, 5)

### D01 grain explanation
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/reports/D01_GRAIN_EXPLANATION.md`

# D01 Grain Explanation

D01의 한 행은 2024년 × 학교표준명 × 캠퍼스(본분교/제N캠퍼스) × 주야구분 × 학위과정 × KEDI 학과코드의 구조자료 관측치이다.

## 실제 행수 해석
- raw Excel sheet `학교별 학과별 주요 현황`에서 빈 행과 대계열 결측 행을 제거하면 **34,969행**이다.
- 기존 15,727행 CSV는 이 raw Excel을 모두 담은 원천이 아니라, 주야구분·학교상태 등 일부 축이 빠진 prefiltered 중간 산출물이다.
- D01 v2는 15,727행을 복제해 늘린 것이 아니라, raw Excel의 34,969행을 다시 읽어 `주야구분`, `학교상태`, `학위과정`, `본분교` 축을 보존한 구조 master다.

## 확정 grain
- key: `analysis_year|school_name_std|campus_name_std|day_evening_raw|degree_course|kedi_dept_code`
- canonical grain duplicate rows: `0`
- lineage missing rows: `0`

## Count conservation
- raw Excel 대비 D01 count 합계 불일치 metric 수: `0`
- 15,727행 CSV 대비 차이는 범위 복구(scope restoration)로 별도 기록했다.

## Gate 2 - D03/D08 Spine Integrity

In [ ]:
gate_summary("Gate 2", summary["gate2"])
show_csv("D03/D08 spine comparison", QA / "d03_d08_spine_comparison.csv")
show_csv("P4 spine key contract", ARTIFACTS / "p4_spine_key_contract.csv")
show_csv("D08 P4 composite key duplicate rows", QA / "d08_composite_key_duplicates.csv")
display(Markdown("### D08 normalized-name duplicate rows (punctuation-normalized raw names)"))
norm_dups = read_csv(QA / "d08_normalized_name_duplicate_rows.csv")
display(norm_dups)
print("shape:", norm_dups.shape)
display(Markdown("### D08 carried headcount UID duplicate rows"))
hc_dups = read_csv(QA / "d08_headcount_uid_duplicate_rows.csv")
display(hc_dups)
print("shape:", hc_dups.shape)
show_csv("D08 rate range audit", QA / "d08_rate_range_audit.csv")

## Gate 2 Summary

      d03_shape     d08_shape  p4_composite_key_duplicate_n  headcount_uid_composite_duplicate_n  normalized_name_duplicate_pair_rows  outcome_value_mismatch_n  rate_range_violation_n  inf_n
0  [10242, 108]  [10242, 151]                             0                                   18                                    8                         0                       0      0

### D03/D08 spine comparison
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/d03_d08_spine_comparison.csv`

                                            check actual              expected status
0                                   D03 row count  10242                 10242   PASS
1                                   D08 row count  10242                 10242   PASS
2                    D03 outcome_row_id duplicate      0                     0   PASS
3                    D08 outcome_row_id duplicate      0                     0   PASS
4          P4 raw outcome composite key duplicate      0                     0   PASS
5   D08 carried headcount UID composite duplicate     18  tracked as WARN only   WARN
6                            D03 to D08 lost rows      0                     0   PASS
7                         D08 extra rows over D03      0                     0   PASS
8                           D03-D08 order changed  False                 False   PASS
9            D03-D08 outcome value mismatch cells      0                     0   PASS
10                              P4 key null cells      0                     0   PASS
11                             D08 inf/-inf cells      0                     0   PASS

shape: (12, 4)

### P4 spine key contract
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/artifacts/p4_spine_key_contract.csv`

       key_column                                             source                                       role
0   analysis_year                                  D08.analysis_year                                  year axis
1   p4_school_uid                          raw exact school_name_raw                    outcome school identity
2   p4_campus_uid      raw exact school_name_raw + campus_name_raw_x                    outcome campus identity
3     p4_dept_uid  raw exact school_name_raw + campus_name_raw_x ...                outcome department identity
4  outcome_row_id                                        D02/D03/D08  stable row identity and final tie-breaker

shape: (5, 3)

### D08 P4 composite key duplicate rows
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/d08_composite_key_duplicates.csv`

Empty DataFrame
Columns: [analysis_year, outcome_row_id, school_name_raw, school_name_base_raw, school_name_std, campus_name_raw_x, campus_seq, campus_branch, campus_name_std_x, dept_name_raw, dept_name_std, dept_field_raw, dept_field_std, credit_forfeit_flag, selectivity_proxy_pct, a_rate_pct, cd_rate_pct, f_rate_pct, employment_rate_pct, health_employment_rate_pct, progression_rate_pct, vocational_college_progression_rate_pct, university_progression_rate_pct, graduate_school_progression_rate_pct, domestic_progression_rate_pct, overseas_progression_rate_pct, has_selectivity, has_employment, has_progression, rate_range_qa, source_file, source_sha256, campus_region_raw, dept_norm_strict, dept_norm_suffix_reduced, dept_token_signature, school_uid_x, headcount_row_id, match_stage, match_method, match_status, match_score, candidate_count, review_needed, unmatched_reason, match_evidence, candidate_headcount_row_ids, candidate_preview, campus_conflict_flag, degree_course_conflict_flag, major_conflict_flag, forbidden_modifier_conflict_flag, headcount_match_flag, headcount_grain_version, headcount_grain_uid, grain_resolution_method, grain_review_needed, raw_row_lineage, school_uid_y, campus_uid, dept_uid, kedi_dept_code, school_type, degree_course, school_status_raw, day_evening_raw, campus_name_raw_y, campus_name_std_y, region_sido, region_sigungu, hc_major_group_raw, hc_major_group_7, field_middle_name, field_small_name, admission_capacity_n, recruitment_n, applicants_n, admits_n, enrolled_students_n, leave_students_n, graduates_n, fulltime_faculty_n, nonfulltime_faculty_n, international_students_n, female_students_n, masters_students_n, doctoral_students_n, competition_ratio, admission_yield_ratio, admit_per_applicant_ratio, leave_rate_pct, female_student_share_pct, international_student_share_pct, student_faculty_ratio, fulltime_faculty_share_pct, log_enrolled_students, log_graduates, school_uid, major_group_7, major7_mapping_method, ...]
Index: []

shape: (0, 155)

### D08 normalized-name duplicate rows (punctuation-normalized raw names)

  outcome_row_id school_name_raw  campus_name_raw_x dept_name_raw        school_uid        campus_uid          dept_uid    match_method
0   OC2024_06719           연세대학교                NaN      문화・미디어전공  SCH_8c0fe037a811  CAM_367571cb81eb  DEP_b18217983866  manual_pending
1   OC2024_06721           연세대학교                NaN       문화미디어전공  SCH_8c0fe037a811  CAM_367571cb81eb  DEP_b18217983866  manual_pending
2   OC2024_07093           우석대학교                NaN  건축・인테리어디자인학과  SCH_a70179c6531f  CAM_43df7208b37c  DEP_a6fa296a6e7e  manual_pending
3   OC2024_07094           우석대학교                NaN   건축인테리어디자인학과  SCH_a70179c6531f  CAM_43df7208b37c  DEP_a6fa296a6e7e  manual_pending
4   OC2024_08822           충남대학교                NaN   미생물・분자생명과학과  SCH_822e5c0ba179  CAM_b3984d1a9914  DEP_eb13903b31fd  manual_pending
5   OC2024_08823           충남대학교                NaN    미생물분자생명과학과  SCH_822e5c0ba179  CAM_b3984d1a9914  DEP_eb13903b31fd  manual_pending
6   OC2024_09486           한남대학교                NaN     토목・환경공학전공  SCH_b87e76b8f78a  CAM_f1cc66bf9cca  DEP_1e8ebec67414  manual_pending
7   OC2024_09487           한남대학교                NaN      토목환경공학전공  SCH_b87e76b8f78a  CAM_f1cc66bf9cca  DEP_1e8ebec67414  manual_pending

shape: (8, 8)

### D08 carried headcount UID duplicate rows

   outcome_row_id school_name_raw campus_name_raw_x dept_name_raw        school_uid        campus_uid          dept_uid        match_method  candidate_count
0    OC2024_01602           고려대학교               NaN          경영학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_608b06fc070c        exact_strict                1
1    OC2024_01603           고려대학교               NaN          경제학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_69e8462a106a        exact_strict                1
2    OC2024_01606           고려대학교               NaN        국어국문학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_5775880d8f88        exact_strict                1
3    OC2024_01626           고려대학교               NaN          사회학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_01160bffef8e        exact_strict                1
4    OC2024_01632           고려대학교               NaN           수학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_6646d76a3796        exact_strict                1
5    OC2024_01643           고려대학교               NaN        영어영문학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_dffa1a933d14        exact_strict                1
6    OC2024_01665    고려대학교(세종)_분교             분교|세종          경영학부  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_608b06fc070c  exact_token_unique                1
7    OC2024_01667    고려대학교(세종)_분교             분교|세종          경제학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_69e8462a106a        exact_strict                1
8    OC2024_01675    고려대학교(세종)_분교             분교|세종        국어국문학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_5775880d8f88        exact_strict                1
9    OC2024_01696    고려대학교(세종)_분교             분교|세종          사회학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_01160bffef8e        exact_strict                1
10   OC2024_01698    고려대학교(세종)_분교             분교|세종           수학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_6646d76a3796        exact_strict                1
11   OC2024_01706    고려대학교(세종)_분교             분교|세종        영어영문학과  SCH_2bbd7221f5f5  CAM_32d9fdbd724b  DEP_dffa1a933d14        exact_strict                1
12   OC2024_03092     단국대학교_제2캠퍼스             제2캠퍼스         뉴뮤직학부  SCH_8444343be410  CAM_f17fd86f306c  DEP_0e4cb5dc34e5  exact_token_unique                1
13   OC2024_03093     단국대학교_제2캠퍼스             제2캠퍼스          뉴뮤직과  SCH_8444343be410  CAM_f17fd86f306c  DEP_0e4cb5dc34e5        exact_strict                1
14   OC2024_06699           연세대학교               NaN          경영학과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_93160d823e93        exact_strict                1
15   OC2024_06701           연세대학교               NaN         경제학전공  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_6c08d0a64880        exact_strict                1
16   OC2024_06708           연세대학교               NaN        국어국문학과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_40fc3d69b657        exact_strict                1
17   OC2024_06719           연세대학교               NaN      문화・미디어전공  SCH_8c0fe037a811  CAM_367571cb81eb  DEP_b18217983866      manual_pending                2
18   OC2024_06721           연세대학교               NaN       문화미디어전공  SCH_8c0fe037a811  CAM_367571cb81eb  DEP_b18217983866      manual_pending                2
19   OC2024_06740           연세대학교               NaN           수학과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_f35d2a4b373a        exact_strict                1
20   OC2024_06767           연세대학교               NaN           의학과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_bacbfde4e8ca        exact_strict                1
21   OC2024_06769           연세대학교               NaN           의예과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_31efbd40bac2        exact_strict                1
22   OC2024_06783           연세대학교               NaN           철학과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_b7d3235210f4        exact_strict                1
23   OC2024_06801    연세대학교(미래)_분교             분교|미래          경영학부  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_93160d823e93  exact_token_unique                1
24   OC2024_06803    연세대학교(미래)_분교             분교|미래         경제학전공  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_6c08d0a64880        exact_strict                1
25   OC2024_06804    연세대학교(미래)_분교             분교|미래        국어국문학과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_40fc3d69b657        exact_strict                1
26   OC2024_06831    연세대학교(미래)_분교             분교|미래          수학전공  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_f35d2a4b373a  exact_token_unique                1
27   OC2024_06837    연세대학교(미래)_분교             분교|미래           의학과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_bacbfde4e8ca        exact_strict                1
28   OC2024_06841    연세대학교(미래)_분교             분교|미래           의예과  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_31efbd40bac2        exact_strict                1
29   OC2024_06846    연세대학교(미래)_분교             분교|미래          철학전공  SCH_8c0fe037a811  CAM_cd6488ffd347  DEP_b7d3235210f4  exact_token_unique                1
30   OC2024_07093           우석대학교               NaN  건축・인테리어디자인학과  SCH_a70179c6531f  CAM_43df7208b37c  DEP_a6fa296a6e7e      manual_pending                2
31   OC2024_07094           우석대학교               NaN   건축인테리어디자인학과  SCH_a70179c6531f  CAM_43df7208b37c  DEP_a6fa296a6e7e      manual_pending                2
32   OC2024_08822           충남대학교               NaN   미생물・분자생명과학과  SCH_822e5c0ba179  CAM_b3984d1a9914  DEP_eb13903b31fd      manual_pending                2
33   OC2024_08823           충남대학교               NaN    미생물분자생명과학과  SCH_822e5c0ba179  CAM_b3984d1a9914  DEP_eb13903b31fd      manual_pending                2
34   OC2024_09486           한남대학교               NaN     토목・환경공학전공  SCH_b87e76b8f78a  CAM_f1cc66bf9cca  DEP_1e8ebec67414      manual_pending                3
35   OC2024_09487           한남대학교               NaN      토목환경공학전공  SCH_b87e76b8f78a  CAM_f1cc66bf9cca  DEP_1e8ebec67414      manual_pending                3

shape: (36, 9)

### D08 rate range audit
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/d08_rate_range_audit.csv`

                                     column  non_null_n  min         max  range_violation_n status
0                     selectivity_proxy_pct        3737  0.1  100.000000                  0   PASS
1                                a_rate_pct       10242  0.0  100.000000                  0   PASS
2                               cd_rate_pct       10242  0.0  100.000000                  0   PASS
3                                f_rate_pct       10242  0.0  100.000000                  0   PASS
4                       employment_rate_pct        7477  0.0  100.000000                  0   PASS
5                health_employment_rate_pct        7477  0.0  100.000000                  0   PASS
6                      progression_rate_pct        7587  0.0  100.000000                  0   PASS
7   vocational_college_progression_rate_pct        7587  0.0   50.000000                  0   PASS
8           university_progression_rate_pct        7587  0.0   25.000000                  0   PASS
9      graduate_school_progression_rate_pct        7587  0.0  100.000000                  0   PASS
10            domestic_progression_rate_pct        7587  0.0  100.000000                  0   PASS
11            overseas_progression_rate_pct        7587  0.0   18.181818                  0   PASS

shape: (12, 6)

                                     column  non_null_n  min         max  range_violation_n status
0                     selectivity_proxy_pct        3737  0.1  100.000000                  0   PASS
1                                a_rate_pct       10242  0.0  100.000000                  0   PASS
2                               cd_rate_pct       10242  0.0  100.000000                  0   PASS
3                                f_rate_pct       10242  0.0  100.000000                  0   PASS
4                       employment_rate_pct        7477  0.0  100.000000                  0   PASS
5                health_employment_rate_pct        7477  0.0  100.000000                  0   PASS
6                      progression_rate_pct        7587  0.0  100.000000                  0   PASS
7   vocational_college_progression_rate_pct        7587  0.0   50.000000                  0   PASS
8           university_progression_rate_pct        7587  0.0   25.000000                  0   PASS
9      graduate_school_progression_rate_pct        7587  0.0  100.000000                  0   PASS
10            domestic_progression_rate_pct        7587  0.0  100.000000                  0   PASS
11            overseas_progression_rate_pct        7587  0.0   18.181818                  0   PASS

## Gate 3 - Structure Match Verification

In [ ]:
gate_summary("Gate 3", summary["gate3"])
show_csv("Structure match integrity", QA / "structure_match_integrity.csv")
show_csv("match_method distribution", PROFILES / "structure_match_method_distribution.csv")
show_csv("Structure feature non-null by match_method", PROFILES / "structure_feature_non_null_by_match_method.csv")
show_csv("split x match_method", PROFILES / "split_by_match_method_crosstab.csv")
show_csv("major_group_7 x match_method", PROFILES / "major_group_7_by_match_method_crosstab.csv")
structure_sample = show_csv("Structure stratified sample seed=3085", SAMPLES / "structure_match_sample_seed3085.csv", n=120)
display(structure_sample["match_method"].value_counts(dropna=False).rename_axis("match_method").reset_index(name="sample_rows"))

## Gate 3 Summary

                           match_method_distribution  high_conf_match_n  high_conf_match_rate  auto_candidate_ge2_n  auto_campus_conflict_n  structure_context_mismatch_n
0  {'exact_strict': 8556, 'manual_pending': 1316,...               8561              0.835872                     0                       0                             0

### Structure match integrity
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/structure_match_integrity.csv`

                                        check  actual  expected status
0                            bridge row count   10242     10242   PASS
1             bridge outcome_row_id duplicate       0         0   PASS
2           candidate_count>=2 auto-confirmed       0         0   PASS
3              campus conflict auto-confirmed       0         0   PASS
4  manual_pending included in high confidence       0         0   PASS
5             unmatched rows deleted from D08       0         0   PASS
6  structural_match_eligible formula mismatch       0         0   PASS

shape: (7, 4)

### match_method distribution
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/structure_match_method_distribution.csv`

         match_method  rows
0        exact_strict  8556
1      manual_pending  1316
2           unmatched   365
3  exact_token_unique     5

shape: (4, 2)

### Structure feature non-null by match_method
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/structure_feature_non_null_by_match_method.csv`

,match_method,rows,admission_capacity_n_non_null_rate,recruitment_n_non_null_rate,applicants_n_non_null_rate,admits_n_non_null_rate,enrolled_students_n_non_null_rate,leave_students_n_non_null_rate,graduates_n_non_null_rate,fulltime_faculty_n_non_null_rate,nonfulltime_faculty_n_non_null_rate,international_students_n_non_null_rate,female_students_n_non_null_rate,masters_students_n_non_null_rate,doctoral_students_n_non_null_rate,competition_ratio_non_null_rate,admission_yield_ratio_non_null_rate,admit_per_applicant_ratio_non_null_rate,leave_rate_pct_non_null_rate,female_student_share_pct_non_null_rate,international_student_share_pct_non_null_rate,student_faculty_ratio_non_null_rate,fulltime_faculty_share_pct_non_null_rate,log_enrolled_students_non_null_rate,log_graduates_non_null_rate
0,exact_strict,8556,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.613955,0.613955,0.614306,0.985975,0.985975,0.985975,0.744974,0.744974,1.0,1.0
1,exact_token_unique,5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.800000,0.800000,0.800000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0
2,manual_pending,1316,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
3,unmatched,365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

shape: (4, 25)

### split x match_method
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/split_by_match_method_crosstab.csv`

   split  exact_strict  exact_token_unique  manual_pending  unmatched
0   test           996                   0             196          7
1  train          6297                   5             960        267
2    val          1263                   0             160         91

shape: (3, 5)

### major_group_7 x match_method
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/major_group_7_by_match_method_crosstab.csv`

  major_group_7  exact_strict  exact_token_unique  manual_pending  unmatched
0           NaN             0                   0              73         70
1           ART          1258                   1             262         45
2           EDU           687                   0              34          7
3           ENG          2212                   0             338         92
4           HUM          1009                   1              71         27
5           MED           519                   0             102         11
6           NAT          1097                   1             123         37
7           SOC          1774                   2             313         76

shape: (8, 5)

### Structure stratified sample seed=3085
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/samples/structure_match_sample_seed3085.csv`

,outcome_row_id,school_name_raw,campus_name_raw_x,dept_name_raw,campus_name_std_x,dept_norm_strict,dept_norm_suffix_reduced,headcount_row_id,campus_name_raw_y,campus_name_std_y,field_middle_name,field_small_name,candidate_count,match_method,match_status,match_score,match_evidence,candidate_preview,admission_capacity_n,recruitment_n,applicants_n,admits_n,enrolled_students_n,graduates_n
0,OC2024_03902,동덕여자대학교,NaN,미술학부 디지털공예전공,unknown,미술학부디지털공예전공,미술학부디지털공예,HC2_2024_13537,본교(제1캠퍼스),본교_제1캠퍼스,응용예술,공예,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,미술학부 디지털공예전공,0.0,35.0,920.0,35.0,61.0,0.0
1,OC2024_06496,신라대학교,NaN,전기전자공학과,unknown,전기전자공학과,전기전자공,HC2_2024_18218,본교(제1캠퍼스),본교_제1캠퍼스,전기ㆍ전자,전자공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,전기전자공학과,20.0,22.0,129.0,11.0,56.0,0.0
2,OC2024_08182,제주국제대학교,NaN,건축학과,unknown,건축학과,건축,HC2_2024_26140,본교(제1캠퍼스),본교_제1캠퍼스,건축,건축학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,건축학과,0.0,0.0,0.0,0.0,37.0,23.0
3,OC2024_02892,극동대학교,NaN,호텔경영학과,unknown,호텔경영학과,호텔경영,HC2_2024_11314,본교(제1캠퍼스),본교_제1캠퍼스,경영ㆍ경제,경영학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,호텔경영학과,106.0,154.0,446.0,134.0,161.0,0.0
4,OC2024_06623,아주대학교,NaN,물리학과,unknown,물리학과,물리,HC2_2024_18446,본교(제1캠퍼스),본교_제1캠퍼스,수학ㆍ물리ㆍ천문ㆍ지리,물리ㆍ과학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,물리학과,33.0,35.0,274.0,35.0,215.0,30.0
5,OC2024_04452,동의대학교,NaN,환경공학과,unknown,환경공학과,환경공,HC2_2024_14384,본교(제1캠퍼스),본교_제1캠퍼스,생물ㆍ화학ㆍ환경,환경학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,환경공학과,35.0,36.0,113.0,34.0,35.0,0.0
6,OC2024_08436,중부대학교,NaN,전자출판인쇄공학전공,unknown,전자출판인쇄공학전공,전자출판인쇄공학,HC2_2024_21507,본교(제2캠퍼스),본교_제2캠퍼스,기타,응용공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,전자출판인쇄공학전공,0.0,0.0,0.0,0.0,22.0,12.0
7,OC2024_07326,원광대학교,NaN,스포츠과학부,unknown,스포츠과학부,스포츠과,HC2_2024_20008,본교(제1캠퍼스),본교_제1캠퍼스,무용ㆍ체육,체육,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,스포츠과학부,120.0,120.0,456.0,119.0,749.0,107.0
8,OC2024_06965,영산대학교(양산)_제2캠퍼스,제2캠퍼스|양산,건축공학과,제2캠퍼스,건축공학과,건축공,HC2_2024_25422,본교(제2캠퍼스),본교_제2캠퍼스,건축,건축ㆍ설비공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,건축공학과,0.0,0.0,0.0,0.0,48.0,10.0
9,OC2024_09423,한국항공대학교,NaN,항공전자정보공학부,unknown,항공전자정보공학부,항공전자정보공,HC2_2024_22807,본교(제1캠퍼스),본교_제1캠퍼스,컴퓨터ㆍ통신,정보ㆍ통신공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,항공전자정보공학부,0.0,0.0,0.0,0.0,1087.0,207.0
10,OC2024_04958,부산외국어대학교,NaN,태국어과,unknown,태국어과,태국어,HC2_2024_15165,본교(제1캠퍼스),본교_제1캠퍼스,언어ㆍ문학,기타아시아어ㆍ문학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,태국어과,0.0,0.0,0.0,0.0,39.0,0.0
11,OC2024_00815,경남대학교,NaN,문화콘텐츠학과,unknown,문화콘텐츠학과,문화콘텐츠,HC2_2024_08285,본교(제1캠퍼스),본교_제1캠퍼스,인문과학,문화ㆍ민속ㆍ미술사학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,문화콘텐츠학과,40.0,41.0,134.0,24.0,256.0,82.0
12,OC2024_03773,동국대학교,NaN,정치행정학부 정치외교학 전공,unknown,정치행정학부정치외교학전공,정치행정학부정치외교학,HC2_2024_13100,본교(제1캠퍼스),본교_제1캠퍼스,사회과학,정치외교학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,정치행정학부 정치외교학 전공,40.0,46.0,789.0,47.0,256.0,36.0
13,OC2024_01437,경희대학교,NaN,사회기반시스템공학과,unknown,사회기반시스템공학과,사회기반시스템공,HC2_2024_09443,본교(제2캠퍼스),본교_제2캠퍼스,산업,산업공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,사회기반시스템공학과,68.0,71.0,708.0,70.0,363.0,46.0
14,OC2024_05697,성결대학교,NaN,기독교교육상담학과,unknown,기독교교육상담학과,기독교교육상담,HC2_2024_16555,본교(제1캠퍼스),본교_제1캠퍼스,인문과학,종교학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,기독교교육상담학과,40.0,40.0,173.0,40.0,134.0,0.0
15,OC2024_05012,상명대학교,NaN,경제금융학부,unknown,경제금융학부,경제금융,HC2_2024_15441,본교(제1캠퍼스),본교_제1캠퍼스,경영ㆍ경제,경제학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,경제금융학부,64.0,64.0,454.0,68.0,436.0,71.0
16,OC2024_03184,대구가톨릭대학교,NaN,반도체전자공학과,unknown,반도체전자공학과,반도체전자공,HC2_2024_12336,본교(제1캠퍼스),본교_제1캠퍼스,소재ㆍ재료,반도체ㆍ세라믹공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,반도체전자공학과,26.0,28.0,124.0,27.0,161.0,20.0
17,OC2024_09812,한양대학교,NaN,교육학과,unknown,교육학과,교육,HC2_2024_23749,본교(제1캠퍼스),본교_제1캠퍼스,교육일반,교육학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,교육학과,20.0,20.0,290.0,20.0,97.0,16.0
18,OC2024_03571,대전대학교,NaN,패션디자인・비즈니스학과,unknown,패션디자인비즈니스학과,패션디자인비즈니스,HC2_2024_12721,본교(제1캠퍼스),본교_제1캠퍼스,디자인,패션디자인,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,패션디자인?비즈니스학과,50.0,49.0,296.0,56.0,240.0,44.0
19,OC2024_00725,경기대학교,NaN,체육학과,unknown,체육학과,체육,HC2_2024_08091,본교(제1캠퍼스),본교_제1캠퍼스,무용ㆍ체육,체육,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,체육학과,28.0,28.0,115.0,29.0,165.0,26.0
20,OC2024_06709,연세대학교,NaN,국제통상전공,unknown,국제통상전공,국제통상,HC2_2024_18675,본교(제1캠퍼스),본교_제1캠퍼스,경영ㆍ경제,무역ㆍ유통학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,국제통상전공,0.0,0.0,0.0,0.0,316.0,64.0
21,OC2024_06487,신라대학교,NaN,일본어일본학과,unknown,일본어일본학과,일본어일본,HC2_2024_18114,본교(제1캠퍼스),본교_제1캠퍼스,언어ㆍ문학,일본어ㆍ문학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,일본어일본학과,25.0,25.0,167.0,17.0,87.0,0.0
22,OC2024_03126,단국대학교_제2캠퍼스,제2캠퍼스,의생명과학부 의생명시스템학전공,제2캠퍼스,의생명과학부의생명시스템학전공,의생명과학부의생명시스템학,HC2_2024_11694,본교(제2캠퍼스),본교_제2캠퍼스,생물ㆍ화학ㆍ환경,생명과학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,의생명과학부 의생명시스템학전공,40.0,43.0,204.0,43.0,46.0,0.0
23,OC2024_09495,한남대학교,NaN,화공신소재공학과,unknown,화공신소재공학과,화공신소재공,HC2_2024_22950,본교(제2캠퍼스),본교_제2캠퍼스,화공,화학공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,화공신소재공학과,0.0,0.0,0.0,0.0,23.0,12.0
24,OC2024_07235,울산대학교,NaN,나노에너지화학전공,unknown,나노에너지화학전공,나노에너지화학,HC2_2024_19794,본교(제1캠퍼스),본교_제1캠퍼스,생물ㆍ화학ㆍ환경,화학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,나노에너지화학전공,0.0,47.0,153.0,38.0,132.0,0.0
25,OC2024_01895,광주대학교,NaN,응급구조학과,unknown,응급구조학과,응급구조,HC2_2024_25051,본교(제1캠퍼스),본교_제1캠퍼스,치료ㆍ보건,의료공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,응급구조학과,0.0,37.0,161.0,32.0,32.0,0.0
26,OC2024_09151,한국과학기술원,NaN,기술경영학부,unknown,기술경영학부,기술경영,HC2_2024_34418,본교(제1캠퍼스),본교_제1캠퍼스,경영ㆍ경제,경영학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,기술경영학부,0.0,0.0,0.0,0.0,63.0,12.0
27,OC2024_07565,이화여자대학교,NaN,지능형반도체공학전공,unknown,지능형반도체공학전공,지능형반도체공학,HC2_2024_20308,본교(제1캠퍼스),본교_제1캠퍼스,소재ㆍ재료,반도체ㆍ세라믹공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,지능형반도체공학전공,60.0,60.0,464.0,60.0,60.0,0.0
28,OC2024_06343,숭실대학교,NaN,정치외교학과,unknown,정치외교학과,정치외교,HC2_2024_17967,본교(제1캠퍼스),본교_제1캠퍼스,사회과학,정치외교학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,정치외교학과,35.0,41.0,458.0,38.0,226.0,35.0
29,OC2024_08263,제주대학교,NaN,융합디자인학과,unknown,융합디자인학과,융합디자인,HC2_2024_04896,본교(제1캠퍼스),본교_제1캠퍼스,디자인,기타디자인,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,융합디자인학과,44.0,44.0,150.0,44.0,117.0,0.0
30,OC2024_05344,서울대학교,NaN,경제학부,unknown,경제학부,경제,HC2_2024_03333,본교(제1캠퍼스),본교_제1캠퍼스,경영ㆍ경제,경제학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,경제학부,154.0,166.0,668.0,166.0,1107.0,171.0
31,OC2024_02753,국립한밭대학교,NaN,전자·제어공학과,unknown,전자제어공학과,전자제어공,HC2_2024_06709,본교(제1캠퍼스),본교_제1캠퍼스,전기ㆍ전자,제어계측공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,전자·제어공학과,0.0,0.0,0.0,0.0,255.0,135.0
32,OC2024_07070,용인대학교,NaN,산업환경보건학과,unknown,산업환경보건학과,산업환경보건,HC2_2024_19496,본교(제1캠퍼스),본교_제1캠퍼스,생물ㆍ화학ㆍ환경,환경학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,산업환경보건학과,40.0,40.0,263.0,42.0,205.0,15.0
33,OC2024_05408,서울대학교,NaN,자유전공학부,unknown,자유전공학부,자유전공,HC2_2024_03329,본교(제1캠퍼스),본교_제1캠퍼스,인문과학,교양인문학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,자유전공학부,123.0,131.0,818.0,131.0,935.0,118.0
34,OC2024_05358,서울대학교,NaN,독어교육과,unknown,독어교육과,독어교육,HC2_2024_03344,본교(제1캠퍼스),본교_제1캠퍼스,중등교육,언어교육,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,독어교육과,15.0,15.0,95.0,15.0,103.0,9.0
35,OC2024_07434,유원대학교,NaN,스마트팜학과,unknown,스마트팜학과,스마트팜,HC2_2024_19426,본교(제1캠퍼스),본교_제1캠퍼스,농림ㆍ수산,농업학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,스마트팜학과,20.0,20.0,20.0,20.0,20.0,0.0
36,OC2024_01831,광주과학기술원,NaN,물리・광과학과,unknown,물리광과학과,물리광과,HC2_2024_34507,본교(제1캠퍼스),본교_제1캠퍼스,수학ㆍ물리ㆍ천문ㆍ지리,물리ㆍ과학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,물리?광과학과,0.0,0.0,0.0,0.0,58.0,21.0
37,OC2024_02168,국립공주대학교,NaN,전기공학전공,unknown,전기공학전공,전기공학,HC2_2024_01794,본교(제2캠퍼스),본교_제2캠퍼스,전기ㆍ전자,전기공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,전기공학전공,0.0,0.0,0.0,0.0,258.0,65.0
38,OC2024_08219,제주대학교,NaN,국어국문학과,unknown,국어국문학과,국어국문,HC2_2024_04798,본교(제1캠퍼스),본교_제1캠퍼스,언어ㆍ문학,국어ㆍ국문학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,국어국문학과,30.0,33.0,115.0,32.0,183.0,26.0
39,OC2024_02411,국립부경대학교,NaN,디지털금융학과,unknown,디지털금융학과,디지털금융,HC2_2024_02623,본교(제1캠퍼스),본교_제1캠퍼스,경영ㆍ경제,금융ㆍ회계ㆍ세무학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,디지털금융학과,20.0,21.0,147.0,21.0,21.0,0.0
40,OC2024_05830,성신여자대학교,NaN,국어국문학과,unknown,국어국문학과,국어국문,HC2_2024_16974,본교(제1캠퍼스),본교_제1캠퍼스,언어ㆍ문학,국어ㆍ국문학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,국어국문학과,22.0,22.0,288.0,25.0,165.0,30.0
41,OC2024_08330,조선대학교,NaN,법학과,unknown,법학과,법학,HC2_2024_21186,본교(제1캠퍼스),본교_제1캠퍼스,법률,법학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,법학과,99.0,110.0,406.0,108.0,708.0,138.0
42,OC2024_00587,건국대학교(글로컬)_분교,분교|글로컬,소방방재융합학과,분교,소방방재융합학과,소방방재융합,HC2_2024_07580,분교(제1캠퍼스),분교_제1캠퍼스,기타,응용공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,소방방재융합학과,35.0,38.0,299.0,38.0,166.0,0.0
43,OC2024_02462,국립부경대학교,NaN,전기공학전공,unknown,전기공학전공,전기공학,HC2_2024_02682,본교(제1캠퍼스),본교_제1캠퍼스,전기ㆍ전자,전기공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,전기공학전공,0.0,0.0,0.0,0.0,363.0,71.0
44,OC2024_06382,신경주대학교,NaN,외식조리학과,unknown,외식조리학과,외식조리,HC2_2024_09288,본교(제1캠퍼스),본교_제1캠퍼스,생활과학,식품영양학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,외식조리학과,40.0,40.0,57.0,26.0,33.0,0.0
45,OC2024_05277,서경대학교,NaN,화학생명공학과,unknown,화학생명공학과,화학생명공,HC2_2024_16051,본교(제1캠퍼스),본교_제1캠퍼스,생물ㆍ화학ㆍ환경,생명과학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,화학생명공학과,0.0,0.0,0.0,0.0,31.0,41.0
46,OC2024_09113,한경국립대학교,NaN,전자전기공학부,unknown,전자전기공학부,전자전기공,HC2_2024_06565,본교(제1캠퍼스),본교_제1캠퍼스,전기ㆍ전자,전자공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,전자전기공학부,80.0,84.0,554.0,86.0,101.0,0.0
47,OC2024_02542,국립순천대학교,NaN,전자공학과,unknown,전자공학과,전자공,HC2_2024_03666,본교(제1캠퍼스),본교_제1캠퍼스,전기ㆍ전자,전자공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,전자공학과,30.0,32.0,95.0,32.0,183.0,33.0
48,OC2024_06541,신라대학교,NaN,회계세무학과,unknown,회계세무학과,회계세무,HC2_2024_18154,본교(제1캠퍼스),본교_제1캠퍼스,경영ㆍ경제,금융ㆍ회계ㆍ세무학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,회계세무학과,0.0,0.0,0.0,0.0,56.0,29.0
49,OC2024_05725,성공회대학교,NaN,글로컬IT학과,unknown,글로컬it학과,글로컬it,HC2_2024_16649,본교(제1캠퍼스),본교_제1캠퍼스,컴퓨터ㆍ통신,정보ㆍ통신공학,1,exact_strict,auto_high_confidence,1.0,school+campus+department strict exact unique,글로컬IT학과,0.0,0.0,0.0,0.0,2.0,4.0
50,OC2024_03355,대구대학교,NaN,지역사회개발・복지학과,unknown,지역사회개발복지학과,지역사회개발복지,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,지역사회개발?복지학과,NaN,NaN,NaN,NaN,NaN,NaN
51,OC2024_09637,한서대학교,NaN,항공보안학과,unknown,항공보안학과,항공보안,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,항공보안학과,NaN,NaN,NaN,NaN,NaN,NaN
52,OC2024_04136,동신대학교,NaN,산림조경학과,unknown,산림조경학과,산림조경,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,산림조경학과,NaN,NaN,NaN,NaN,NaN,NaN
53,OC2024_08413,중부대학교,NaN,미디어커뮤니케이션학전공,unknown,미디어커뮤니케이션학전공,미디어커뮤니케이션학,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,미디어커뮤니케이션학전공,NaN,NaN,NaN,NaN,NaN,NaN
54,OC2024_03750,동국대학교,NaN,생명과학과,unknown,생명과학과,생명과,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,생명과학과 | 생명과학과,NaN,NaN,NaN,NaN,NaN,NaN
55,OC2024_06602,아신대학교,NaN,사회복지선교학과,unknown,사회복지선교학과,사회복지선교,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,사회복지선교학과,NaN,NaN,NaN,NaN,NaN,NaN
56,OC2024_04198,동아대학교,NaN,미디어커뮤니케이션학과,unknown,미디어커뮤니케이션학과,미디어커뮤니케이션,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,미디어커뮤니케이션학과,NaN,NaN,NaN,NaN,NaN,NaN
57,OC2024_07039,예원예술대학교,NaN,애니메이션전공 | 애니메이션학과 | 애니메이션전공,unknown,애니메이션전공애니메이션학과애니메이션전공,애니메이션전공애니메이션학과애니메이션,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,애니메이션전공 | 애니메이션학과,NaN,NaN,NaN,NaN,NaN,NaN
58,OC2024_04591,목원대학교,NaN,소방안전관리학과,unknown,소방안전관리학과,소방안전관리,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,소방안전관리학과,NaN,NaN,NaN,NaN,NaN,NaN
59,OC2024_03816,동국대학교(WISE)_분교,분교|WISE,소방방재전공,분교,소방방재전공,소방방재,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,소방방재전공,NaN,NaN,NaN,NaN,NaN,NaN
60,OC2024_00039,가천대학교,NaN,미술·디자인학부(디자인) | 미술·디자인학부(패션디자인) | 미술·디자인학부(회화·조소),unknown,미술디자인학부디자인미술디자인학부패션디자인미술디자인학부회화조소,미술디자인학부디자인미술디자인학부패션디자인미술디자인학부회화조소,NaN,NaN,NaN,NaN,NaN,3,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,미술·디자인학부(디자인) | 미술·디자인학부(패션디자인) | 미술·디자인학부(회화·조소),NaN,NaN,NaN,NaN,NaN,NaN
61,OC2024_00486,건국대학교,NaN,건축학과 | 건축학부,unknown,건축학과건축학부,건축학과건축,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,건축학과 | 건축학부,NaN,NaN,NaN,NaN,NaN,NaN
62,OC2024_00408,강원대학교,NaN,토목공학전공,unknown,토목공학전공,토목공학,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,토목공학전공 | 토목공학전공,NaN,NaN,NaN,NaN,NaN,NaN
63,OC2024_06371,신경주대학교,NaN,문화유산학과 | 문화유산학부,unknown,문화유산학과문화유산학부,문화유산학과문화유산,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,문화유산학과 | 문화유산학부,NaN,NaN,NaN,NaN,NaN,NaN
64,OC2024_04921,부산외국어대학교,NaN,사회복지전공 | 사회복지학과,unknown,사회복지전공사회복지학과,사회복지전공사회복지,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,사회복지전공 | 사회복지학과,NaN,NaN,NaN,NaN,NaN,NaN
65,OC2024_08357,조선대학교,NaN,유럽언어문화학부 | 유럽언어문화학부(독일어문화학전공) | 유럽언어문화학부(러시아어전...,unknown,유럽언어문화학부유럽언어문화학부독일어문화학전공유럽언어문화학부러시아어전공유럽언어문화학부...,유럽언어문화학부유럽언어문화학부독일어문화학전공유럽언어문화학부러시아어전공유럽언어문화학부...,NaN,NaN,NaN,NaN,NaN,4,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,유럽언어문화학부(독일어문화학전공) | 유럽언어문화학부(러시아어전공) | 유럽언어문화...,NaN,NaN,NaN,NaN,NaN,NaN
66,OC2024_05128,상지대학교,NaN,빅데이터사이언스학과,unknown,빅데이터사이언스학과,빅데이터사이언스,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,빅데이터사이언스학과,NaN,NaN,NaN,NaN,NaN,NaN
67,OC2024_08490,중앙대학교,NaN,의학부(의예) | 의학부(의학),unknown,의학부의예의학부의학,의학부의예의학부의학,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,의학부(의예) | 의학부(의학),NaN,NaN,NaN,NaN,NaN,NaN
68,OC2024_01420,경희대학교,NaN,글로벌커뮤니케이션학부,unknown,글로벌커뮤니케이션학부,글로벌커뮤니케이션,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,글로벌커뮤니케이션학부 | 글로벌커뮤니케이션학부,NaN,NaN,NaN,NaN,NaN,NaN
69,OC2024_06048,세한대학교,NaN,스포츠레저산업학과,unknown,스포츠레저산업학과,스포츠레저산업,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,스포츠레저산업학과 | 스포츠레저산업학과,NaN,NaN,NaN,NaN,NaN,NaN
70,OC2024_08328,조선대학교,NaN,미디어커뮤니케이션학과,unknown,미디어커뮤니케이션학과,미디어커뮤니케이션,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,미디어커뮤니케이션학과,NaN,NaN,NaN,NaN,NaN,NaN
71,OC2024_03376,대구예술대학교,NaN,경호보안전공,unknown,경호보안전공,경호보안,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,경호보안전공,NaN,NaN,NaN,NaN,NaN,NaN
72,OC2024_01130,경상국립대학교,NaN,수의예과,unknown,수의예과,수의예,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,수의예과,NaN,NaN,NaN,NaN,NaN,NaN
73,OC2024_01962,국립강릉원주대학교(폐교),NaN,수학물리학부 | 수학물리학부(물리・에너지전공) | 수학물리학부(수학전공),unknown,수학물리학부수학물리학부물리에너지전공수학물리학부수학전공,수학물리학부수학물리학부물리에너지전공수학물리학부수학,NaN,NaN,NaN,NaN,NaN,3,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,수학물리학부 | 수학물리학부(수학전공) | 수학물리학부(물리?에너지전공),NaN,NaN,NaN,NaN,NaN,NaN
74,OC2024_09342,한국외국어대학교,NaN,일본언어문화전공 | 일본언어문화학부,unknown,일본언어문화전공일본언어문화학부,일본언어문화전공일본언어문화,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,일본언어문화전공 | 일본언어문화학부,NaN,NaN,NaN,NaN,NaN,NaN
75,OC2024_08233,제주대학교,NaN,바이오소재전공,unknown,바이오소재전공,바이오소재,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,바이오소재전공,NaN,NaN,NaN,NaN,NaN,NaN
76,OC2024_06499,신라대학교,NaN,제약공학전공,unknown,제약공학전공,제약공학,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,제약공학전공,NaN,NaN,NaN,NaN,NaN,NaN
77,OC2024_00164,가톨릭관동대학교,NaN,항공교통물류학과 | 항공교통물류전공,unknown,항공교통물류학과항공교통물류전공,항공교통물류학과항공교통물류,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,항공교통물류전공 | 항공교통물류학과,NaN,NaN,NaN,NaN,NaN,NaN
78,OC2024_00015,가천대학교,NaN,AI・소프트웨어학부(소프트웨어전공) | AI・소프트웨어학부(인공지능전공),unknown,ai소프트웨어학부소프트웨어전공ai소프트웨어학부인공지능전공,ai소프트웨어학부소프트웨어전공ai소프트웨어학부인공지능,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,AI?소프트웨어학부(인공지능전공) | AI?소프트웨어학부(소프트웨어전공),NaN,NaN,NaN,NaN,NaN,NaN
79,OC2024_03953,동명대학교,NaN,건축학과 | 건축학과(5년제),unknown,건축학과건축학과5년제,건축학과건축학과5년제,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,건축학과 | 건축학과(5년제),NaN,NaN,NaN,NaN,NaN,NaN
80,OC2024_08507,중앙대학교_제2캠퍼스,제2캠퍼스,미술학부(서양화전공) | 미술학부(조소전공) | 미술학부(한국화전공),제2캠퍼스,미술학부서양화전공미술학부조소전공미술학부한국화전공,미술학부서양화전공미술학부조소전공미술학부한국화,NaN,NaN,NaN,NaN,NaN,4,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,미술학부 | 미술학부(한국화전공) | 미술학부(서양화전공) | 미술학부(조소전공),NaN,NaN,NaN,NaN,NaN,NaN
81,OC2024_00077,가천대학교,NaN,전자공학과 | 전자공학부(시스템반도체전공) | 전자공학부(전자공학전공) | 전자공학...,unknown,전자공학과전자공학부시스템반도체전공전자공학부전자공학전공전자공학부차세대반도체전공,전자공학과전자공학부시스템반도체전공전자공학부전자공학전공전자공학부차세대반도체,NaN,NaN,NaN,NaN,NaN,4,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,전자공학과 | 전자공학부(전자공학전공) | 전자공학부(차세대반도체전공) | 전자공학...,NaN,NaN,NaN,NaN,NaN,NaN
82,OC2024_08313,조선대학교,NaN,국어국문학과 | 국어국문학부 | 국어국문학부(고전번역전공) | 국어국문학부(국어국문...,unknown,국어국문학과국어국문학부국어국문학부고전번역전공국어국문학부국어국문학전공,국어국문학과국어국문학부국어국문학부고전번역전공국어국문학부국어국문학,NaN,NaN,NaN,NaN,NaN,4,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,국어국문학과 | 국어국문학부 | 국어국문학부(국어국문학전공) | 국어국문학부(고전번...,NaN,NaN,NaN,NaN,NaN,NaN
83,OC2024_03975,동명대학교,NaN,디지털콘텐츠전공 | 디지털콘텐츠학과,unknown,디지털콘텐츠전공디지털콘텐츠학과,디지털콘텐츠전공디지털콘텐츠,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,디지털콘텐츠학과 | 디지털콘텐츠전공,NaN,NaN,NaN,NaN,NaN,NaN
84,OC2024_08128,전주대학교,NaN,산업디자인전공 | 산업디자인학과,unknown,산업디자인전공산업디자인학과,산업디자인전공산업디자인,NaN,NaN,NaN,NaN,NaN,2,manual_pending,manual_pending,1.0,school+campus+department strict exact unique; ...,산업디자인전공 | 산업디자인학과,NaN,NaN,NaN,NaN,NaN,NaN
85,OC2024_00162,가톨릭관동대학교,NaN,통합치유학과,unknown,통합치유학과,통합치유,NaN,NaN,NaN,NaN,NaN,1,manual_pending,manual_pending,1.0,fuzzy candidates need manual review,통합치유학과,NaN,NaN,NaN,NaN,NaN,NaN

shape: (205, 24)

         match_method  sample_rows
0      manual_pending          100
1        exact_strict           50
2           unmatched           50
3  exact_token_unique            5

## Gate 4 - major_group_7 Verification

In [ ]:
gate_summary("Gate 4", summary["gate4"])
show_csv("Major mapping integrity", QA / "major7_mapping_integrity.csv")
show_csv("major7 mapping method distribution", PROFILES / "major7_mapping_method_distribution.csv")
show_csv("major_group_7 distribution", PROFILES / "major_group_7_distribution.csv")
show_csv("split x major_group_7", PROFILES / "split_by_major_group_7_crosstab.csv")
show_csv("mapping_method x major_group_7", PROFILES / "major_mapping_method_by_major_group_7_crosstab.csv")
show_csv("mapping confidence by method", PROFILES / "major_mapping_confidence_by_method.csv")
special = show_csv("Special major term search", QA / "major7_special_term_search.csv", n=200)
display(special.groupby(["search_term", "major7_mapping_method", "major_group_7"], dropna=False).size().reset_index(name="rows"))
major_sample = show_csv("major7 stratified sample", SAMPLES / "major7_mapping_sample.csv", n=160)
display(major_sample["major7_mapping_method"].value_counts(dropna=False).rename_axis("major7_mapping_method").reset_index(name="sample_rows"))

## Gate 4 Summary

,major_method_distribution,major_group_distribution,major_high_medium_n,major_high_medium_rate,ambiguous_unknown_n,ambiguous_unknown_rate,major_allowed_code_violation_n,inherited_major_mismatch_n
0,"{'inherited_headcount': 8561, 'keyword_rule': ...","{'ENG': 2642, 'SOC': 2165, 'ART': 1566, 'NAT':...",10099,0.986038,143,0.013962,0,0

### Major mapping integrity
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/major7_mapping_integrity.csv`

                                              check    actual expected status
0             allowed major_group_7 code violations  0.000000        0   PASS
1                      major high/medium rate >=97%  0.986038   >=0.97   PASS
2                            ambiguous+unknown <=3%  0.013962   <=0.03   PASS
3                      inherited D01 major mismatch  0.000000        0   PASS
4           major_context_eligible formula mismatch  0.000000        0   PASS
5  ambiguous/unknown rows included in major samples  0.000000        0   PASS

shape: (6, 4)

### major7 mapping method distribution
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/major7_mapping_method_distribution.csv`

  major7_mapping_method  rows
0   inherited_headcount  8561
1          keyword_rule   859
2      exact_dictionary   679
3             ambiguous    85
4               unknown    58

shape: (5, 2)

### major_group_7 distribution
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/major_group_7_distribution.csv`

  major_group_7  rows
0           ENG  2642
1           SOC  2165
2           ART  1566
3           NAT  1258
4           HUM  1108
5           EDU   728
6           MED   632
7           NaN   143

shape: (8, 2)

### split x major_group_7
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/split_by_major_group_7_crosstab.csv`

   split  <NA>   ART  EDU   ENG  HUM  MED  NAT   SOC
0   test    21   226   80   297   96   91  108   280
1  train   112  1092  543  1957  864  424  964  1573
2    val    10   248  105   388  148  117  186   312

shape: (3, 9)

### mapping_method x major_group_7
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/major_mapping_method_by_major_group_7_crosstab.csv`

  major7_mapping_method  <NA>   ART  EDU   ENG   HUM  MED   NAT   SOC
0             ambiguous    85     0    0     0     0    0     0     0
1      exact_dictionary     0   136   31   186    70   39    57   160
2   inherited_headcount     0  1259  687  2212  1010  519  1098  1776
3          keyword_rule     0   171   10   244    28   74   103   229
4               unknown    58     0    0     0     0    0     0     0

shape: (5, 9)

### mapping confidence by method
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/major_mapping_confidence_by_method.csv`

  major7_mapping_method major7_mapping_confidence  rows
0             ambiguous                       low    85
1      exact_dictionary                    medium   679
2   inherited_headcount                      high  8561
3          keyword_rule                    medium   859
4               unknown                   unknown    58

shape: (5, 3)

### Special major term search
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/major7_special_term_search.csv`

    search_term outcome_row_id school_name_raw                                      dept_name_raw major_group_7 major7_mapping_method major7_mapping_confidence                                    major7_evidence
0          자유전공   OC2024_00380           강원대학교  자유전공학부(학생설계전공 인문사회계열) | 자유전공학부(학생설계전공 자연과학계열) ...           HUM      exact_dictionary                    medium  unique dictionary inherited from matched rows:...
1          자유전공   OC2024_00846           경남대학교                                             자유전공학부           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
2          자유전공   OC2024_02540         국립순천대학교                                    자유전공학부(인문사회・자연)           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
3          자유전공   OC2024_03048           단국대학교                                 국제자유전공학부 영상연기&제작전공           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
4          자유전공   OC2024_03345           대구대학교                                             자유전공학부           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
5          자유전공   OC2024_04206           동아대학교                                            분자유전공학과           NAT   inherited_headcount                      high              D01 v2 high-confidence match 대계열=자연계열
6          자유전공   OC2024_05159           상지대학교                                             자유전공학부           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
7          자유전공   OC2024_05408           서울대학교                                             자유전공학부           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
8          자유전공   OC2024_06053           세한대학교                                             자유전공학과           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
9          자유전공   OC2024_06147           수원대학교                                             자유전공학부           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
10         자유전공   OC2024_06244          순천향대학교                                          글로벌자유전공학과           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
11         자유전공   OC2024_06334           숭실대학교                                        융합특성화자유전공학부           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
12         자유전공   OC2024_07557         이화여자대학교                                               자유전공           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
13         자유전공   OC2024_07594           인제대학교                                          글로벌자유전공학과           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
14         자유전공   OC2024_07633           인제대학교                                             자유전공학부           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
15           융합   OC2024_00053           가천대학교                                          스마트시티융합학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
16           융합   OC2024_00115        가톨릭관동대학교                                           바이오융합공학과           NAT   inherited_headcount                      high              D01 v2 high-confidence match 대계열=자연계열
17           융합   OC2024_00227           강남대학교                                           ICT융합공학부           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
18           융합   OC2024_00236           강남대학교                                  복지융합인재학부 미술문화복지전공           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
19           융합   OC2024_00237           강남대학교                                   복지융합인재학부 스포츠복지전공           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
20           융합   OC2024_00238           강남대학교                              복지융합인재학부 유니버설비주얼디자인전공           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
21           융합   OC2024_00250           강남대학교                                           융합자율전공학부           SOC   inherited_headcount                      high              D01 v2 high-confidence match 대계열=사회계열
22           융합   OC2024_00252           강남대학교                                          인공지능융합공학부           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
23           융합   OC2024_00268           강원대학교                                             AI융합학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
24           융합   OC2024_00288           강원대학교                                            글로벌융합학부           SOC   inherited_headcount                      high              D01 v2 high-confidence match 대계열=사회계열
25           융합   OC2024_00299           강원대학교                                           동물산업융합학과           NAT   inherited_headcount                      high              D01 v2 high-confidence match 대계열=자연계열
26           융합   OC2024_00319           강원대학교                                           배터리융합공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
27           융합   OC2024_00425     강원대학교_제2캠퍼스                                             건설융합학부           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
28           융합   OC2024_00426     강원대학교_제2캠퍼스                                      건설융합학부 건축공학전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
29           융합   OC2024_00427     강원대학교_제2캠퍼스                                       건설융합학부 건축학전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
30           융합   OC2024_00428     강원대학교_제2캠퍼스                                      건설융합학부 토목공학전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
31           융합   OC2024_00452     강원대학교_제2캠퍼스                                       소프트웨어미디어융합전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
32           융합   OC2024_00458     강원대학교_제2캠퍼스                                        에너지자원융합공학전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
33           융합   OC2024_00485           건국대학교                                          K뷰티산업융합학과           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
34           융합   OC2024_00519           건국대학교                                        스마트ICT융합공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
35           융합   OC2024_00524           건국대학교                                            신산업융합학과           SOC   inherited_headcount                      high              D01 v2 high-confidence match 대계열=사회계열
36           융합   OC2024_00529           건국대학교                                            융합생명공학과           NAT   inherited_headcount                      high              D01 v2 high-confidence match 대계열=자연계열
37           융합   OC2024_00530           건국대학교                                             융합인재학과           SOC   inherited_headcount                      high              D01 v2 high-confidence match 대계열=사회계열
38           융합   OC2024_00568   건국대학교(글로컬)_분교                                           녹색기술융합학과           NAT   inherited_headcount                      high              D01 v2 high-confidence match 대계열=자연계열
39           융합   OC2024_00587   건국대학교(글로컬)_분교                                           소방방재융합학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
40           융합   OC2024_00653           건양대학교                                             융합IT학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
41           융합   OC2024_00654           건양대학교                                            융합기계공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
42           융합   OC2024_00655           건양대학교                                            융합디자인학과           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
43           융합   OC2024_00700           경기대학교                                            바이오융합학부           NAT   inherited_headcount                      high              D01 v2 high-confidence match 대계열=자연계열
44           융합   OC2024_00717           경기대학교                                             융합보안학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
45           융합   OC2024_00718           경기대학교                                        융합에너지시스템공학부           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
46           융합   OC2024_00751   경남과학기술대학교(폐교)                                         IoT융합시스템전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
47           융합   OC2024_00810           경남대학교                                  기계융합공학과(중소기업계약학과)           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
48           융합   OC2024_00830           경남대학교                                        스마트기계융합공학전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
49           융합   OC2024_01018           경북대학교                                 융합학부 로봇및스마트시스템공학전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
50           융합   OC2024_01019           경북대학교                                 융합학부 수소 및 신재생에너지전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
51           융합   OC2024_01020           경북대학교                                     융합학부 의생명융합공학전공           MED   inherited_headcount                      high              D01 v2 high-confidence match 대계열=의약계열
52           융합   OC2024_01060           경북대학교   컴퓨터학부(글로벌소프트웨어융합전공) | 컴퓨터학부(플랫폼소프트웨어전공, 데이터과학전공)           ENG      exact_dictionary                    medium  unique dictionary inherited from matched rows:...
53           융합   OC2024_01092         경상국립대학교                                            기계융합공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
54           융합   OC2024_01099         경상국립대학교                                           동물생명융합학부           NAT   inherited_headcount                      high              D01 v2 high-confidence match 대계열=자연계열
55           융합   OC2024_01156         경상국립대학교                                           융합전자공학전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
56           융합   OC2024_01312           경운대학교                                          소프트웨어융합계열           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
57           융합   OC2024_01371           경일대학교                                          기계자동화융합학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
58           융합   OC2024_01387           경일대학교                                            스포츠융합학부           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
59           융합   OC2024_01393           경일대학교                                           전기전자융합학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
60           융합   OC2024_01396           경일대학교                               조기취업형계약학부 스마트팩토리융합학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
61           융합   OC2024_01419           경희대학교                                        글로벌문화기술융합전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
62           융합   OC2024_01444           경희대학교                                          소프트웨어융합학과           ENG      exact_dictionary                    medium  unique dictionary inherited from matched rows:...
63           융합   OC2024_01609           고려대학교                                          글로벌한국융합학부           HUM   inherited_headcount                      high              D01 v2 high-confidence match 대계열=인문계열
64           융합   OC2024_01622           고려대학교                                          보건환경융합과학부           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
65           융합   OC2024_01644           고려대학교                                           융합에너지공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
66           융합   OC2024_01683    고려대학교(세종)_분교                                          디스플레이융합전공           NaN               unknown                   unknown  no inherited, dictionary, or strict keyword ev...
67           융합   OC2024_01685    고려대학교(세종)_분교                                          문화ICT융합전공           NaN             ambiguous                       low   hits=ENG; evidence=ENG:ict; ambiguous_token=True
68           융합   OC2024_01686    고려대학교(세종)_분교                                           문화유산융합학부           NaN               unknown                   unknown  no inherited, dictionary, or strict keyword ev...
69           융합   OC2024_01707    고려대학교(세종)_분교                                             융합경영학부           SOC      exact_dictionary                    medium  unique dictionary inherited from matched rows:...
70           융합   OC2024_01711    고려대학교(세종)_분교                                         전자·기계융합공학과           NaN             ambiguous                       low  hits=ENG; evidence=ENG:기계/전자/공학; ambiguous_tok...
71           융합   OC2024_01718    고려대학교(세종)_분교                                       컴퓨터융합소프트웨어학과           NaN             ambiguous                       low  hits=ENG; evidence=ENG:컴퓨터/소프트웨어; ambiguous_to...
72           융합   OC2024_01767           광신대학교                                           복지상담융합학부           SOC   inherited_headcount                      high              D01 v2 high-confidence match 대계열=사회계열
73           융합   OC2024_01800           광운대학교                                           스포츠융합과학과           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
74           융합   OC2024_01810           광운대학교                                            전자융합공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
75           융합   OC2024_01814           광운대학교                                             정보융합학부           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
76           융합   OC2024_01892           광주대학교                                            융합기계공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
77           융합   OC2024_01893           광주대학교                                            융합디자인학부           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
78           융합   OC2024_01894           광주대학교                                          융합소프트웨어학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
79           융합   OC2024_01910         광주여자대학교                                             AI융합학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
80           융합   OC2024_01918         광주여자대학교  미래융합학부(뷰티산업학과) | 미래융합학부(사회복지상담전공) | 미래융합학부(사회복...           NaN             ambiguous                       low  hits=MED,ART,SOC,HUM; evidence=MED:재활 | ART:뷰티...
81           융합   OC2024_01985   국립강릉원주대학교(폐교)                                 해양바이오식품학과 해양식품융합전공           NAT   inherited_headcount                      high              D01 v2 high-confidence match 대계열=자연계열
82           융합   OC2024_02045         국립경국대학교                                          원예・생약융합학부           NaN             ambiguous                       low    hits=NAT; evidence=NAT:원예; ambiguous_token=True
83           융합   OC2024_02064         국립경국대학교                      창의융합학부(이공계열) | 창의융합학부(인문사회계열)           NaN             ambiguous                       low  hits=SOC,HUM; evidence=SOC:회계 | HUM:인문; ambigu...
84           융합   OC2024_02108         국립공주대학교                                        도자문화융합디자인학과           ART   inherited_headcount                      high             D01 v2 high-confidence match 대계열=예체능계열
85           융합   OC2024_02112         국립공주대학교                                         디지털융합금형공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
86           융합   OC2024_02204         국립군산대학교                                          IT융합통신공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
87           융합   OC2024_02209         국립군산대학교  공간디자인융합기술학부(공간디자인융합기술학전공) | 공간디자인융합기술학부 | 공간디자...           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
88           융합   OC2024_02239         국립군산대학교                                           인공지능융합학과           ENG      exact_dictionary                    medium  unique dictionary inherited from matched rows:...
89           융합   OC2024_02250         국립군산대학교  컴퓨터소프트웨어학부 | 컴퓨터소프트웨어학부(소프트웨어학전공) | 컴퓨터소프트웨어학부...           ENG      exact_dictionary                    medium  unique dictionary inherited from matched rows:...
90           융합   OC2024_02266       국립금오공과대학교                                             IT융합학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
91           융합   OC2024_02276       국립금오공과대학교                                         메디컬IT융합공학과           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열
92           융합   OC2024_02283       국립금오공과대학교                                           전자IT융합전공           ENG   inherited_headcount                      high              D01 v2 high-confidence match 대계열=공학계열

shape: (1817, 8)

    search_term major7_mapping_method major_group_7  rows
0            AI             ambiguous           NaN     1
1            AI      exact_dictionary           ENG     8
2            AI   inherited_headcount           ART     4
3            AI   inherited_headcount           ENG   109
4            AI   inherited_headcount           NAT     2
5            AI   inherited_headcount           SOC     5
6            AI          keyword_rule           ART     1
7            AI          keyword_rule           ENG     3
8            AI          keyword_rule           MED     2
9            AI          keyword_rule           SOC     1
10           AI               unknown           NaN     1
11           건축             ambiguous           NaN     1
12           건축      exact_dictionary           ART     2
13           건축      exact_dictionary           ENG    29
14           건축   inherited_headcount           ART    10
15           건축   inherited_headcount           ENG   186
16           건축          keyword_rule           ART     5
17           건축          keyword_rule           ENG     1
18           건축          keyword_rule           SOC     2
19           건축               unknown           NaN     1
20         교육공학      exact_dictionary           EDU     1
21         교육공학   inherited_headcount           EDU     3
22      데이터사이언스             ambiguous           NaN     2
23      데이터사이언스      exact_dictionary           ENG     2
24      데이터사이언스      exact_dictionary           SOC     1
25      데이터사이언스   inherited_headcount           ENG    21
26      데이터사이언스   inherited_headcount           NAT     4
27      데이터사이언스          keyword_rule           ENG     4
28        문화콘텐츠             ambiguous           NaN     2
29        문화콘텐츠      exact_dictionary           HUM     4
30        문화콘텐츠   inherited_headcount           ART     1
31        문화콘텐츠   inherited_headcount           ENG     1
32        문화콘텐츠   inherited_headcount           HUM    38
33        문화콘텐츠   inherited_headcount           SOC     1
34          미디어             ambiguous           NaN     4
35          미디어      exact_dictionary           ART     7
36          미디어      exact_dictionary           ENG     1
37          미디어      exact_dictionary           HUM     1
38          미디어   inherited_headcount           ART    35
39          미디어   inherited_headcount           ENG    19
40          미디어   inherited_headcount           HUM     4
41          미디어   inherited_headcount           SOC    16
42          미디어          keyword_rule           ART    75
43          바이오             ambiguous           NaN     5
44          바이오      exact_dictionary           ENG     2
45          바이오      exact_dictionary           NAT     5
46          바이오   inherited_headcount           ENG    15
47          바이오   inherited_headcount           MED     6
48          바이오   inherited_headcount           NAT    87
49          바이오          keyword_rule           NAT    13
50          반도체             ambiguous           NaN     5
51          반도체      exact_dictionary           ENG     6
52          반도체      exact_dictionary           NAT     1
53          반도체   inherited_headcount           ENG    63
54          반도체   inherited_headcount           NAT     4
55          반도체          keyword_rule           ENG     2
56           보건             ambiguous           NaN     1
57           보건      exact_dictionary           MED     5
58           보건      exact_dictionary           SOC     2
59           보건   inherited_headcount           ART     1
60           보건   inherited_headcount           ENG     3
61           보건   inherited_headcount           MED    27
62           보건   inherited_headcount           NAT    16
63           보건   inherited_headcount           SOC    20
64           보건          keyword_rule           MED    15
65        산업디자인             ambiguous           NaN     1
66        산업디자인      exact_dictionary           ART    12
67        산업디자인   inherited_headcount           ART    37
68        산업디자인   inherited_headcount           ENG     2
69           상담             ambiguous           NaN     3
70           상담      exact_dictionary           SOC     7
71           상담   inherited_headcount           ART     1
72           상담   inherited_headcount           EDU     5
73           상담   inherited_headcount           HUM     6
74           상담   inherited_headcount           MED     2
75           상담   inherited_headcount           NAT     1
76           상담   inherited_headcount           SOC    49
77           상담          keyword_rule           SOC    50
78        스포츠과학      exact_dictionary           ART     5
79        스포츠과학   inherited_headcount           ART    33
80         식품영양      exact_dictionary           NAT     8
81         식품영양   inherited_headcount           NAT    89
82           심리             ambiguous           NaN     2
83           심리      exact_dictionary           SOC     2
84           심리   inherited_headcount           EDU     1
85           심리   inherited_headcount           HUM     2
86           심리   inherited_headcount           MED     3
87           심리   inherited_headcount           NAT     1
88           심리   inherited_headcount           SOC    18
89           심리          keyword_rule           SOC    78
90           융합             ambiguous           NaN    33
91           융합      exact_dictionary           ART     3
92           융합      exact_dictionary           ENG    11
93           융합      exact_dictionary           NAT     1
94           융합      exact_dictionary           SOC     3
95           융합   inherited_headcount           ART    33
96           융합   inherited_headcount           ENG   209
97           융합   inherited_headcount           HUM    24
98           융합   inherited_headcount           MED     8
99           융합   inherited_headcount           NAT    38
100          융합   inherited_headcount           SOC    50
101          융합               unknown           NaN     5
102         의공학      exact_dictionary           ENG     1
103         의공학   inherited_headcount           ENG     2
104         의공학   inherited_headcount           MED     2
105         의공학          keyword_rule           ENG     8
106        자유전공      exact_dictionary           HUM     1
107        자유전공   inherited_headcount           ART     1
108        자유전공   inherited_headcount           ENG     1
109        자유전공   inherited_headcount           HUM    11
110        자유전공   inherited_headcount           NAT     1
111        호텔관광      exact_dictionary           SOC     2
112        호텔관광   inherited_headcount           SOC    26

### major7 stratified sample
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/samples/major7_mapping_sample.csv`

    outcome_row_id major7_mapping_method major7_mapping_confidence                                      dept_name_raw                         major7_evidence  split  major_group_7
0     OC2024_05252   inherited_headcount                      high                                             미용예술학과  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
1     OC2024_05081   inherited_headcount                      high                                        인더스트리얼디자인전공  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
2     OC2024_01405   inherited_headcount                      high                                     PostModern음악학과  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
3     OC2024_00243   inherited_headcount                      high                                            스포츠복지학과  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
4     OC2024_09660   inherited_headcount                      high                                              동양화전공  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
5     OC2024_08409   inherited_headcount                      high                                           레저스포츠학전공  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
6     OC2024_03876   inherited_headcount                      high                                               관현악과  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
7     OC2024_09214   inherited_headcount                      high                                            미디어영상학과  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
8     OC2024_05577   inherited_headcount                      high                                               뷰티학과  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
9     OC2024_07047   inherited_headcount                      high                                               음악전공  D01 v2 high-confidence match 대계열=예체능계열  train            NaN
10    OC2024_05594   inherited_headcount                      high                                              영어교육과   D01 v2 high-confidence match 대계열=교육계열  train            NaN
11    OC2024_09469   inherited_headcount                      high                                              역사교육과   D01 v2 high-confidence match 대계열=교육계열  train            NaN
12    OC2024_00464   inherited_headcount                      high                                              유아교육과   D01 v2 high-confidence match 대계열=교육계열  train            NaN
13    OC2024_02103   inherited_headcount                      high                                           기술・가정교육과   D01 v2 high-confidence match 대계열=교육계열  train            NaN
14    OC2024_07744   inherited_headcount                      high                                               교육학과   D01 v2 high-confidence match 대계열=교육계열  train            NaN
15    OC2024_08072   inherited_headcount                      high                                        윤리교육과(심화전공)   D01 v2 high-confidence match 대계열=교육계열  train            NaN
16    OC2024_00281   inherited_headcount                      high                                              국어교육과   D01 v2 high-confidence match 대계열=교육계열  train            NaN
17    OC2024_08029   inherited_headcount                      high                                            일반사회교육과   D01 v2 high-confidence match 대계열=교육계열  train            NaN
18    OC2024_08785   inherited_headcount                      high                                      초등수학교육과(심화과정)   D01 v2 high-confidence match 대계열=교육계열    val            NaN
19    OC2024_04774   inherited_headcount                      high                                              과학교육과   D01 v2 high-confidence match 대계열=교육계열  train            NaN
20    OC2024_02200   inherited_headcount                      high                                             화학공학전공   D01 v2 high-confidence match 대계열=공학계열  train            NaN
21    OC2024_02440   inherited_headcount                      high                                         신소재시스템공학전공   D01 v2 high-confidence match 대계열=공학계열  train            NaN
22    OC2024_10142   inherited_headcount                      high                                           자동차기계공학과   D01 v2 high-confidence match 대계열=공학계열  train            NaN
23    OC2024_05164   inherited_headcount                      high                                    전자・보안공학부 전자공학전공   D01 v2 high-confidence match 대계열=공학계열  train            NaN
24    OC2024_02552   inherited_headcount                      high                                              토목공학과   D01 v2 high-confidence match 대계열=공학계열  train            NaN
25    OC2024_05654   inherited_headcount                      high                                          스마트자동차공학부   D01 v2 high-confidence match 대계열=공학계열  train            NaN
26    OC2024_07505   inherited_headcount                      high                                      기후·에너지시스템공학전공   D01 v2 high-confidence match 대계열=공학계열  train            NaN
27    OC2024_06153   inherited_headcount                      high                                             전자재료공학   D01 v2 high-confidence match 대계열=공학계열  train            NaN
28    OC2024_02001   inherited_headcount                      high                                            정보통신공학과   D01 v2 high-confidence match 대계열=공학계열  train            NaN
29    OC2024_01810   inherited_headcount                      high                                            전자융합공학과   D01 v2 high-confidence match 대계열=공학계열  train            NaN
30    OC2024_08363   inherited_headcount                      high                                               일본어과   D01 v2 high-confidence match 대계열=인문계열  train            NaN
31    OC2024_01237   inherited_headcount                      high                                             문헌정보학과   D01 v2 high-confidence match 대계열=인문계열  train            NaN
32    OC2024_00698   inherited_headcount                      high                                             문예창작학과   D01 v2 high-confidence match 대계열=인문계열  train            NaN
33    OC2024_00400   inherited_headcount                      high                                               철학전공   D01 v2 high-confidence match 대계열=인문계열  train            NaN
34    OC2024_09326   inherited_headcount                      high                                           영미문학번역전공   D01 v2 high-confidence match 대계열=인문계열  train            NaN
35    OC2024_04918   inherited_headcount                      high                                              베트남어과   D01 v2 high-confidence match 대계열=인문계열  train            NaN
36    OC2024_07549   inherited_headcount                      high                                            영어영문학전공   D01 v2 high-confidence match 대계열=인문계열  train            NaN
37    OC2024_02126   inherited_headcount                      high                                             불어불문학과   D01 v2 high-confidence match 대계열=인문계열  train            NaN
38    OC2024_01114   inherited_headcount                      high                                                사학과   D01 v2 high-confidence match 대계열=인문계열  train            NaN
39    OC2024_03968   inherited_headcount                      high                                         글로벌문화콘텐츠학과   D01 v2 high-confidence match 대계열=인문계열  train            NaN
40    OC2024_03470   inherited_headcount                      high                                            재활의료공학과   D01 v2 high-confidence match 대계열=의약계열  train            NaN
41    OC2024_07632   inherited_headcount                      high                                             임상병리학과   D01 v2 high-confidence match 대계열=의약계열  train            NaN
42    OC2024_04861   inherited_headcount                      high                                                의예과   D01 v2 high-confidence match 대계열=의약계열   test            NaN
43    OC2024_09609   inherited_headcount                      high                                             물리치료학과   D01 v2 high-confidence match 대계열=의약계열   test            NaN
44    OC2024_01568   inherited_headcount                      high                                                의학과   D01 v2 high-confidence match 대계열=의약계열    val            NaN
45    OC2024_03128   inherited_headcount                      high                                             임상병리학과   D01 v2 high-confidence match 대계열=의약계열  train            NaN
46    OC2024_08862   inherited_headcount                      high                                                의예과   D01 v2 high-confidence match 대계열=의약계열  train            NaN
47    OC2024_02161   inherited_headcount                      high                                             응급구조학과   D01 v2 high-confidence match 대계열=의약계열  train            NaN
48    OC2024_01406   inherited_headcount                      high                                               간호학과   D01 v2 high-confidence match 대계열=의약계열  train            NaN
49    OC2024_04236   inherited_headcount                      high                                                의학과   D01 v2 high-confidence match 대계열=의약계열  train            NaN
50    OC2024_06637   inherited_headcount                      high                                          응용화학생명공학과   D01 v2 high-confidence match 대계열=자연계열   test            NaN
51    OC2024_05139   inherited_headcount                      high                                             스마트팜학과   D01 v2 high-confidence match 대계열=자연계열  train            NaN
52    OC2024_01454   inherited_headcount                      high                                             아동가족학과   D01 v2 high-confidence match 대계열=자연계열  train            NaN
53    OC2024_05387   inherited_headcount                      high                                             식품영양학과   D01 v2 high-confidence match 대계열=자연계열  train            NaN
54    OC2024_07897   inherited_headcount                      high                                               통계학과   D01 v2 high-confidence match 대계열=자연계열  train            NaN
55    OC2024_07434   inherited_headcount                      high                                             스마트팜학과   D01 v2 high-confidence match 대계열=자연계열  train            NaN
56    OC2024_06906   inherited_headcount                      high                                             식품영양학과   D01 v2 high-confidence match 대계열=자연계열  train            NaN
57    OC2024_07439   inherited_headcount                      high                                            와인식음료학과   D01 v2 high-confidence match 대계열=자연계열  train            NaN
58    OC2024_02490   inherited_headcount                      high                                           환경대기과학전공   D01 v2 high-confidence match 대계열=자연계열  train            NaN
59    OC2024_05543   inherited_headcount                      high                                                화학과   D01 v2 high-confidence match 대계열=자연계열  train            NaN
60    OC2024_03316   inherited_headcount                      high                                             사회복지학과   D01 v2 high-confidence match 대계열=사회계열  train            NaN
61    OC2024_00244   inherited_headcount                      high                                             실버산업학과   D01 v2 high-confidence match 대계열=사회계열  train            NaN
62    OC2024_08399   inherited_headcount                      high                                          경찰탐정수사학전공   D01 v2 high-confidence match 대계열=사회계열  train            NaN
63    OC2024_09430   inherited_headcount                      high                                             경영정보학과   D01 v2 high-confidence match 대계열=사회계열  train            NaN
64    OC2024_05227   inherited_headcount                      high                                             경찰행정전공   D01 v2 high-confidence match 대계열=사회계열  train            NaN
65    OC2024_08612   inherited_headcount                      high                                               경영학과   D01 v2 high-confidence match 대계열=사회계열   test            NaN
66    OC2024_02803   inherited_headcount                      high                                              사법학전공   D01 v2 high-confidence match 대계열=사회계열   test            NaN
67    OC2024_09810   inherited_headcount                      high                                               관광학부   D01 v2 high-confidence match 대계열=사회계열    val            NaN
68    OC2024_04051   inherited_headcount                      high                                            관광경영학전공   D01 v2 high-confidence match 대계열=사회계열  train            NaN
69    OC2024_10032   inherited_headcount                      high                                             호텔경영학과   D01 v2 high-confidence match 대계열=사회계열    val            NaN
70    OC2024_06332          keyword_rule                    medium                                      예술창작학부 문예창작전공                                  ART:예술  train            NaN
71    OC2024_07726          keyword_rule                    medium                                             패션산업학과                                  ART:패션  train            NaN
72    OC2024_07600          keyword_rule                    medium                                        미디어커뮤니케이션학과                                 ART:미디어  train            NaN
73    OC2024_06309          keyword_rule                    medium                                           글로벌미디어학부                                 ART:미디어  train            NaN
74    OC2024_00573          keyword_rule                    medium                                         동화미디어콘텐츠전공                             ART:콘텐츠/미디어  train            NaN
75    OC2024_06679          keyword_rule                    medium                                            게임콘텐츠학과                                 ART:콘텐츠  train            NaN
76    OC2024_09561          keyword_rule                    medium                                              미디어스쿨                                 ART:미디어  train            NaN
77    OC2024_00454          keyword_rule                    medium                                           스포츠웰니스전공                                 ART:스포츠  train            NaN
78    OC2024_04471          keyword_rule                    medium                                      디자인학부 영상디자인전공                              ART:디자인/영상    val            NaN
79    OC2024_07569          keyword_rule                    medium                                       커뮤니케이션·미디어학부                                 ART:미디어  train            NaN
80    OC2024_09027          keyword_rule                    medium                                스마트콘텐츠전공 | 스마트콘텐츠학과                                 ART:콘텐츠   test            NaN
81    OC2024_03417          keyword_rule                    medium                                            미술치료학전공                                  ART:미술  train            NaN
82    OC2024_04505          keyword_rule                    medium                                          만화애니콘텐츠학과                              ART:만화/콘텐츠    val            NaN
83    OC2024_00286          keyword_rule                    medium                                     글로벌미디어커뮤니케이션전공                                 ART:미디어  train            NaN
84    OC2024_09305          keyword_rule                    medium                                        미디어커뮤니케이션학부                                 ART:미디어  train            NaN
85    OC2024_07429          keyword_rule                    medium                                            뷰티화장품학과                                  ART:뷰티  train            NaN
86    OC2024_04365          keyword_rule                    medium                                        미디어커뮤니케이션학과                                 ART:미디어  train            NaN
87    OC2024_00505          keyword_rule                    medium                                        미디어커뮤니케이션학과                                 ART:미디어  train            NaN
88    OC2024_08134          keyword_rule                    medium                                           스마트미디어학과                                 ART:미디어  train            NaN
89    OC2024_08462          keyword_rule                    medium  공연영상창작학부(공간연출전공) | 공연영상창작학부(연극전공) | 공연영상창작학부(영...                            ART:연극/영화/영상   test            NaN
90    OC2024_01245          keyword_rule                    medium                                           미디어콘텐츠학과                             ART:콘텐츠/미디어  train            NaN
91    OC2024_03482          keyword_rule                    medium                                             토탈뷰티전공                                  ART:뷰티  train            NaN
92    OC2024_08444          keyword_rule                    medium                                           토탈패션산업학과                                  ART:패션  train            NaN
93    OC2024_08429          keyword_rule                    medium                                          엔터테인먼트학전공                              ART:엔터테인먼트  train            NaN
94    OC2024_04503          keyword_rule                    medium                                           디지털미디어학과                                 ART:미디어    val            NaN
95    OC2024_05571          keyword_rule                    medium                                            멀티미디어전공                                 ART:미디어  train            NaN
96    OC2024_01482          keyword_rule                    medium                                         조리&푸드디자인학과                                 ART:디자인  train            NaN
97    OC2024_08618          keyword_rule                    medium                                            멀티미디어학과                                 ART:미디어   test            NaN
98    OC2024_00582          keyword_rule                    medium                                  뷰티화장품전공 | 뷰티화장품학과                                  ART:뷰티  train            NaN
99    OC2024_03847          keyword_rule                    medium                                            정원디자인전공                                 ART:디자인  train            NaN
100   OC2024_04933          keyword_rule                    medium                                           시민영어교육학과                             EDU:교육/영어교육  train            NaN
101   OC2024_06587          keyword_rule                    medium                                           유아통합교육학과                                  EDU:교육  train            NaN
102   OC2024_01928          keyword_rule                    medium                                          어린이영어교육학과                             EDU:교육/영어교육  train            NaN
103   OC2024_03484          keyword_rule                    medium                                           평생교육복지전공                                  EDU:교육  train            NaN
104   OC2024_02948          keyword_rule                    medium                                           수어통역교육전공                                  EDU:교육   test            NaN
105   OC2024_04630          keyword_rule                    medium                                      피아노학부 피아노교육전공                                  EDU:교육    val            NaN
106   OC2024_06271          keyword_rule                    medium                                    외국어로서의 한국어교육학전공                             EDU:교육/국어교육  train            NaN
107   OC2024_09331          keyword_rule                    medium                                      외국어로서의한국어교육전공                             EDU:교육/국어교육  train            NaN
108   OC2024_06710          keyword_rule                    medium                                          글로벌기초교육학부                                  EDU:교육  train            NaN
109   OC2024_08170          keyword_rule                    medium                                             평생교육계열                                  EDU:교육  train            NaN

shape: (541, 7)

  major7_mapping_method  sample_rows
0          keyword_rule          188
1      exact_dictionary          140
2             ambiguous           85
3   inherited_headcount           70
4               unknown           58

## Gate 5 - Local 2 GOMS Context Lineage

In [ ]:
gate_summary("Gate 5", summary["gate5"])
show_csv("Local2 context lineage integrity", QA / "local2_context_lineage_integrity.csv")
show_csv("GOMS D07->D08 exact comparison", QA / "goms_d07_d08_exact_comparison.csv")
show_csv("GOMS context unique values by major", PROFILES / "goms_context_unique_by_major.csv")

## Gate 5 Summary

                                            d07_path                                           d07_hash d07_shape  d07_ready_for_local1  d07_key_duplicate_n  d07_d08_goms_mismatch_n
0  /home/sieg/projects-wsl/SBS_dataScience/workbo...  f44c6f9e7a7539361dce301686144780e0ce588deb929b...   [7, 29]                  True                    0                        0

### Local2 context lineage integrity
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/local2_context_lineage_integrity.csv`

                                          check                                             actual                                           expected status
0                       Local2 ready_for_local1                                               True                                               True   PASS
1               manifest D07 hash equals actual  f44c6f9e7a7539361dce301686144780e0ce588deb929b...  f44c6f9e7a7539361dce301686144780e0ce588deb929b...   PASS
2  actual D07 hash equals Local1 manifest input  f44c6f9e7a7539361dce301686144780e0ce588deb929b...  f44c6f9e7a7539361dce301686144780e0ce588deb929b...   PASS
3                                 D07 row count                                                  7                                                  7   PASS
4                       D07 major key duplicate                                                  0                                                  0   PASS
5          D07 to D08 goms exact mismatch cells                                                  0                                                  0   PASS

shape: (6, 4)

### GOMS D07->D08 exact comparison
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/goms_d07_d08_exact_comparison.csv`

                                    column                                 d08_unique_preview                                 d07_unique_preview  mismatch_count
0                  goms_profile_start_year                                          2017|<NA>                                          2017|<NA>               0
1                    goms_profile_end_year                                          2019|<NA>                                          2019|<NA>               0
2                     goms_profile_years_n                                             3|<NA>                                             3|<NA>               0
3                  goms_aggregation_method                       mixed_weighted_2017_2019|nan                       mixed_weighted_2017_2019|nan               0
4          goms_recent_employment_rate_pct  83.63194274902344|69.60953521728516|70.6443328...  83.63194274902344|69.60953521728516|70.6443328...               0
5             goms_recent_firm_300plus_pct  34.586936950683594|20.332578659057617|8.162267...  34.586936950683594|20.332578659057617|8.162267...               0
6         goms_recent_public_nonprofit_pct  42.84096908569336|31.614683151245117|16.418355...  42.84096908569336|31.614683151245117|16.418355...               0
7                goms_recent_permanent_pct  88.36591339111328|79.11846160888672|63.2879600...  88.36591339111328|79.11846160888672|63.2879600...               0
8                 goms_recent_unstable_pct  10.131061553955078|16.2655029296875|26.0556640...  10.131061553955078|16.2655029296875|26.0556640...               0
9            goms_recent_self_employed_pct  1.1710143089294434|4.286320209503174|10.322768...  1.1710143089294434|4.286320209503174|10.322768...               0
10                goms_recent_industry_hhi  0.6168563365936279|0.08301936089992523|0.10221...  0.6168563365936279|0.08301936089992523|0.10221...               0
11           goms_recent_industry_top3_pct  85.75497436523438|33.00703811645508|40.6763076...  85.75497436523438|33.00703811645508|40.6763076...               0
12  goms_recent_professional_highskill_pct  88.55696868896484|23.923974990844727|54.354106...  88.55696868896484|23.923974990844727|54.354106...               0
13          goms_recent_mean_income_10kkrw  261.694091796875|235.4596710205078|189.7611236...  261.694091796875|235.4596710205078|189.7611236...               0
14           goms_recent_weekly_work_hours  44.96006774902344|42.231544494628906|39.008335...  44.96006774902344|42.231544494628906|39.008335...               0
15         goms_recent_hourly_income_proxy  1.3403993844985962|1.2835510969161987|1.120741...  1.3403993844985962|1.2835510969161987|1.120741...               0
16              goms_income_trend_per_year  5.240109443664551|3.1109890937805176|3.2362635...  5.240109443664551|3.1109890937805176|3.2362635...               0
17               goms_hours_trend_per_year  -0.40384626388549805|-0.4010988473892212|-0.54...  -0.40384626388549805|-0.4010988473892212|-0.54...               0
18        goms_firm_300plus_trend_per_year  -0.10659337043762207|0.21868132054805756|-0.19...  -0.10659337043762207|0.21868132054805756|-0.19...               0
19           goms_permanent_trend_per_year  -0.19505485892295837|-0.37142863869667053|-0.6...  -0.19505485892295837|-0.37142863869667053|-0.6...               0
20     goms_latest_2019_mean_income_10kkrw  271.79998779296875|234.60000610351562|192.6999...  271.79998779296875|234.60000610351562|192.6999...               0
21      goms_latest_2019_weekly_work_hours  44.79999923706055|41.900001525878906|37.599998...  44.79999923706055|41.900001525878906|37.599998...               0
22       goms_latest_2019_firm_300plus_pct  37.20000076293945|22.700000762939453|9.3999996...  37.20000076293945|22.700000762939453|9.3999996...               0
23          goms_latest_2019_permanent_pct  89.69999694824219|78.5|63.099998474121094|73.8...  89.69999694824219|78.5|63.099998474121094|73.8...               0
24              goms_source_years_observed                                             3|<NA>                                             3|<NA>               0
25         goms_year_over_year_review_flag                                    False|True|<NA>                                    False|True|<NA>               0
26                 goms_mapping_confidence                                medium_reviewed|nan                                medium_reviewed|nan               0
27                      goms_row_qa_status                                           PASS|nan                                           PASS|nan               0

shape: (28, 4)

### GOMS context unique values by major
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/goms_context_unique_by_major.csv`

,major_group_7,d08_rows,goms_profile_start_year_d08_unique_n,goms_profile_end_year_d08_unique_n,goms_profile_years_n_d08_unique_n,goms_aggregation_method_d08_unique_n,goms_recent_employment_rate_pct_d08_unique_n,goms_recent_firm_300plus_pct_d08_unique_n,goms_recent_public_nonprofit_pct_d08_unique_n,goms_recent_permanent_pct_d08_unique_n,goms_recent_unstable_pct_d08_unique_n,goms_recent_self_employed_pct_d08_unique_n,goms_recent_industry_hhi_d08_unique_n,goms_recent_industry_top3_pct_d08_unique_n,goms_recent_professional_highskill_pct_d08_unique_n,goms_recent_mean_income_10kkrw_d08_unique_n,goms_recent_weekly_work_hours_d08_unique_n,goms_recent_hourly_income_proxy_d08_unique_n,goms_income_trend_per_year_d08_unique_n,goms_hours_trend_per_year_d08_unique_n,goms_firm_300plus_trend_per_year_d08_unique_n,goms_permanent_trend_per_year_d08_unique_n,goms_latest_2019_mean_income_10kkrw_d08_unique_n,goms_latest_2019_weekly_work_hours_d08_unique_n,goms_latest_2019_firm_300plus_pct_d08_unique_n,goms_latest_2019_permanent_pct_d08_unique_n,goms_source_years_observed_d08_unique_n,goms_year_over_year_review_flag_d08_unique_n,goms_mapping_confidence_d08_unique_n,goms_row_qa_status_d08_unique_n
0,ART,1566,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,EDU,728,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,ENG,2642,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,HUM,1108,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,MED,632,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
5,NAT,1258,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
6,SOC,2165,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
7,NaN,143,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

shape: (8, 30)

,major_group_7,d08_rows,goms_profile_start_year_d08_unique_n,goms_profile_end_year_d08_unique_n,goms_profile_years_n_d08_unique_n,goms_aggregation_method_d08_unique_n,goms_recent_employment_rate_pct_d08_unique_n,goms_recent_firm_300plus_pct_d08_unique_n,goms_recent_public_nonprofit_pct_d08_unique_n,goms_recent_permanent_pct_d08_unique_n,goms_recent_unstable_pct_d08_unique_n,goms_recent_self_employed_pct_d08_unique_n,goms_recent_industry_hhi_d08_unique_n,goms_recent_industry_top3_pct_d08_unique_n,goms_recent_professional_highskill_pct_d08_unique_n,goms_recent_mean_income_10kkrw_d08_unique_n,goms_recent_weekly_work_hours_d08_unique_n,goms_recent_hourly_income_proxy_d08_unique_n,goms_income_trend_per_year_d08_unique_n,goms_hours_trend_per_year_d08_unique_n,goms_firm_300plus_trend_per_year_d08_unique_n,goms_permanent_trend_per_year_d08_unique_n,goms_latest_2019_mean_income_10kkrw_d08_unique_n,goms_latest_2019_weekly_work_hours_d08_unique_n,goms_latest_2019_firm_300plus_pct_d08_unique_n,goms_latest_2019_permanent_pct_d08_unique_n,goms_source_years_observed_d08_unique_n,goms_year_over_year_review_flag_d08_unique_n,goms_mapping_confidence_d08_unique_n,goms_row_qa_status_d08_unique_n
0,ART,1566,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,EDU,728,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,ENG,2642,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,HUM,1108,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,MED,632,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
5,NAT,1258,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
6,SOC,2165,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
7,NaN,143,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

## Gate 6 - Split And Sample Registry

In [ ]:
gate_summary("Gate 6", summary["gate6"])
show_csv("Split/sample integrity", QA / "split_sample_integrity.csv")
show_csv("Split row/school summary", PROFILES / "split_row_school_summary.csv")
show_csv("Sample registry actual check", QA / "sample_registry_actual_check.csv")
target_missing = show_csv("Target missing by split and major", PROFILES / "target_missing_by_split_major.csv", n=120)
feature_missing = show_csv("Feature missing by sample", PROFILES / "feature_missing_by_sample.csv", n=120)
display(feature_missing.groupby("sample_id", dropna=False).agg(feature_columns=("feature_column", "nunique"), mean_missing_rate=("missing_rate", "mean")).reset_index())

## Gate 6 Summary

   split_leakage_n                                      split_summary  sample_registry_mismatch_rows                                      sample_actual
0                0  [{'split': 'test', 'rows': 1199, 'schools': 30...                              0  [{'sample_id': 'GRADE_ALL', 'registry_usable_r...

### Split/sample integrity
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/split_sample_integrity.csv`

                                  check  actual  expected status
0                  school split leakage       0         0   PASS
1                  membership row count   10242     10242   PASS
2   membership outcome_row_id duplicate       0         0   PASS
3  sample registry actual mismatch rows       0         0   PASS

shape: (4, 4)

### Split row/school summary
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/split_row_school_summary.csv`

   split  rows  schools
0   test  1199       30
1  train  7529      140
2    val  1514       30

shape: (3, 3)

### Sample registry actual check
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/sample_registry_actual_check.csv`

,sample_id,registry_usable_rows_n,actual_usable_rows_n,registry_with_structure_n,actual_with_structure_n,registry_train_n,actual_train_n,registry_val_n,actual_val_n,registry_test_n,actual_test_n,registry_actual_mismatch_n,status
0,GRADE_ALL,10099,10099,8561,8561,7417,7417,1504,1504,1178,1178,0,PASS
1,GRADE_SELECTIVITY,3707,3707,3198,3198,2760,2760,585,585,362,362,0,PASS
2,EMPLOYMENT_HEALTH,7389,7389,6270,6270,5428,5428,1121,1121,840,840,0,PASS
3,PROGRESSION_GRADSCHOOL,7498,7498,6366,6366,5499,5499,1141,1141,858,858,0,PASS
4,JOINT_EMP_PROG,7389,7389,6270,6270,5428,5428,1121,1121,840,840,0,PASS

shape: (5, 13)

### Target missing by split and major
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/target_missing_by_split_major.csv`

                           target_column  split major_group_7  rows  missing_n  non_null_n  missing_rate
0                             a_rate_pct   test           ART   226          0         226      0.000000
1                             a_rate_pct   test           EDU    80          0          80      0.000000
2                             a_rate_pct   test           ENG   297          0         297      0.000000
3                             a_rate_pct   test           HUM    96          0          96      0.000000
4                             a_rate_pct   test           MED    91          0          91      0.000000
5                             a_rate_pct   test           NAT   108          0         108      0.000000
6                             a_rate_pct   test           SOC   280          0         280      0.000000
7                             a_rate_pct   test           NaN    21          0          21      0.000000
8                             a_rate_pct  train           ART  1092          0        1092      0.000000
9                             a_rate_pct  train           EDU   543          0         543      0.000000
10                            a_rate_pct  train           ENG  1957          0        1957      0.000000
11                            a_rate_pct  train           HUM   864          0         864      0.000000
12                            a_rate_pct  train           MED   424          0         424      0.000000
13                            a_rate_pct  train           NAT   964          0         964      0.000000
14                            a_rate_pct  train           SOC  1573          0        1573      0.000000
15                            a_rate_pct  train           NaN   112          0         112      0.000000
16                            a_rate_pct    val           ART   248          0         248      0.000000
17                            a_rate_pct    val           EDU   105          0         105      0.000000
18                            a_rate_pct    val           ENG   388          0         388      0.000000
19                            a_rate_pct    val           HUM   148          0         148      0.000000
20                            a_rate_pct    val           MED   117          0         117      0.000000
21                            a_rate_pct    val           NAT   186          0         186      0.000000
22                            a_rate_pct    val           SOC   312          0         312      0.000000
23                            a_rate_pct    val           NaN    10          0          10      0.000000
24                 selectivity_proxy_pct   test           ART   226        168          58      0.743363
25                 selectivity_proxy_pct   test           EDU    80         51          29      0.637500
26                 selectivity_proxy_pct   test           ENG   297        205          92      0.690236
27                 selectivity_proxy_pct   test           HUM    96         56          40      0.583333
28                 selectivity_proxy_pct   test           MED    91         61          30      0.670330
29                 selectivity_proxy_pct   test           NAT   108         68          40      0.629630
30                 selectivity_proxy_pct   test           SOC   280        207          73      0.739286
31                 selectivity_proxy_pct   test           NaN    21         19           2      0.904762
32                 selectivity_proxy_pct  train           ART  1092        844         248      0.772894
33                 selectivity_proxy_pct  train           EDU   543        245         298      0.451197
34                 selectivity_proxy_pct  train           ENG  1957       1208         749      0.617271
35                 selectivity_proxy_pct  train           HUM   864        565         299      0.653935
36                 selectivity_proxy_pct  train           MED   424        198         226      0.466981
37                 selectivity_proxy_pct  train           NAT   964        547         417      0.567427
38                 selectivity_proxy_pct  train           SOC  1573       1050         523      0.667514
39                 selectivity_proxy_pct  train           NaN   112         85          27      0.758929
40                 selectivity_proxy_pct    val           ART   248        203          45      0.818548
41                 selectivity_proxy_pct    val           EDU   105         53          52      0.504762
42                 selectivity_proxy_pct    val           ENG   388        229         159      0.590206
43                 selectivity_proxy_pct    val           HUM   148         81          67      0.547297
44                 selectivity_proxy_pct    val           MED   117         64          53      0.547009
45                 selectivity_proxy_pct    val           NAT   186        114          72      0.612903
46                 selectivity_proxy_pct    val           SOC   312        175         137      0.560897
47                 selectivity_proxy_pct    val           NaN    10          9           1      0.900000
48            health_employment_rate_pct   test           ART   226         61         165      0.269912
49            health_employment_rate_pct   test           EDU    80         21          59      0.262500
50            health_employment_rate_pct   test           ENG   297         97         200      0.326599
51            health_employment_rate_pct   test           HUM    96         30          66      0.312500
52            health_employment_rate_pct   test           MED    91         14          77      0.153846
53            health_employment_rate_pct   test           NAT   108         29          79      0.268519
54            health_employment_rate_pct   test           SOC   280         86         194      0.307143
55            health_employment_rate_pct   test           NaN    21          5          16      0.238095
56            health_employment_rate_pct  train           ART  1092        321         771      0.293956
57            health_employment_rate_pct  train           EDU   543         26         517      0.047882
58            health_employment_rate_pct  train           ENG  1957        633        1324      0.323454
59            health_employment_rate_pct  train           HUM   864        209         655      0.241898
60            health_employment_rate_pct  train           MED   424        103         321      0.242925
61            health_employment_rate_pct  train           NAT   964        244         720      0.253112
62            health_employment_rate_pct  train           SOC  1573        453        1120      0.287985
63            health_employment_rate_pct  train           NaN   112         46          66      0.410714
64            health_employment_rate_pct    val           ART   248         62         186      0.250000
65            health_employment_rate_pct    val           EDU   105         10          95      0.095238
66            health_employment_rate_pct    val           ENG   388        128         260      0.329897
67            health_employment_rate_pct    val           HUM   148         30         118      0.202703
68            health_employment_rate_pct    val           MED   117         29          88      0.247863
69            health_employment_rate_pct    val           NAT   186         47         139      0.252688
70            health_employment_rate_pct    val           SOC   312         77         235      0.246795
71            health_employment_rate_pct    val           NaN    10          4           6      0.400000
72  graduate_school_progression_rate_pct   test           ART   226         59         167      0.261062
73  graduate_school_progression_rate_pct   test           EDU    80         18          62      0.225000
74  graduate_school_progression_rate_pct   test           ENG   297         97         200      0.326599
75  graduate_school_progression_rate_pct   test           HUM    96         19          77      0.197917
76  graduate_school_progression_rate_pct   test           MED    91         14          77      0.153846
77  graduate_school_progression_rate_pct   test           NAT   108         29          79      0.268519
78  graduate_school_progression_rate_pct   test           SOC   280         84         196      0.300000
79  graduate_school_progression_rate_pct   test           NaN    21          5          16      0.238095
80  graduate_school_progression_rate_pct  train           ART  1092        316         776      0.289377
81  graduate_school_progression_rate_pct  train           EDU   543         21         522      0.038674
82  graduate_school_progression_rate_pct  train           ENG  1957        631        1326      0.322432
83  graduate_school_progression_rate_pct  train           HUM   864        166         698      0.192130
84  graduate_school_progression_rate_pct  train           MED   424        103         321      0.242925
85  graduate_school_progression_rate_pct  train           NAT   964        241         723      0.250000
86  graduate_school_progression_rate_pct  train           SOC  1573        440        1133      0.279720
87  graduate_school_progression_rate_pct  train           NaN   112         45          67      0.401786
88  graduate_school_progression_rate_pct    val           ART   248         62         186      0.250000
89  graduate_school_progression_rate_pct    val           EDU   105          7          98      0.066667
90  graduate_school_progression_rate_pct    val           ENG   388        125         263      0.322165
91  graduate_school_progression_rate_pct    val           HUM   148         19         129      0.128378
92  graduate_school_progression_rate_pct    val           MED   117         29          88      0.247863
93  graduate_school_progression_rate_pct    val           NAT   186         46         140      0.247312
94  graduate_school_progression_rate_pct    val           SOC   312         75         237      0.240385
95  graduate_school_progression_rate_pct    val           NaN    10          4           6      0.400000

shape: (96, 7)

### Feature missing by sample
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/feature_missing_by_sample.csv`

             sample_id                          feature_column   rows  missing_n  missing_rate
0            GRADE_ALL                ctx24_reference_sample_n  10099          0      0.000000
1            GRADE_ALL                ctx24_mean_income_10kkrw  10099          0      0.000000
2            GRADE_ALL              ctx24_median_income_10kkrw  10099          0      0.000000
3            GRADE_ALL                ctx24_income_300plus_pct  10099          0      0.000000
4            GRADE_ALL                ctx24_income_400plus_pct  10099          0      0.000000
5            GRADE_ALL                 ctx24_large_company_pct  10099          0      0.000000
6            GRADE_ALL                   ctx24_mid_company_pct  10099          0      0.000000
7            GRADE_ALL                 ctx24_small_company_pct  10099          0      0.000000
8            GRADE_ALL             ctx24_large_mid_company_pct  10099          0      0.000000
9            GRADE_ALL              ctx24_public_nonprofit_pct  10099          0      0.000000
10           GRADE_ALL                     ctx24_cert_rate_pct  10099          0      0.000000
11           GRADE_ALL                   ctx24_cert_per_person  10099          0      0.000000
12           GRADE_ALL                 ctx24_log10_mean_income  10099          0      0.000000
13           GRADE_ALL                 ctx24_industry_top3_pct  10099      10099      1.000000
14           GRADE_ALL                      ctx24_industry_hhi  10099      10099      1.000000
15           GRADE_ALL                 goms_profile_start_year  10099          0      0.000000
16           GRADE_ALL                   goms_profile_end_year  10099          0      0.000000
17           GRADE_ALL                    goms_profile_years_n  10099          0      0.000000
18           GRADE_ALL                 goms_aggregation_method  10099          0      0.000000
19           GRADE_ALL         goms_recent_employment_rate_pct  10099          0      0.000000
20           GRADE_ALL            goms_recent_firm_300plus_pct  10099          0      0.000000
21           GRADE_ALL        goms_recent_public_nonprofit_pct  10099          0      0.000000
22           GRADE_ALL               goms_recent_permanent_pct  10099          0      0.000000
23           GRADE_ALL                goms_recent_unstable_pct  10099          0      0.000000
24           GRADE_ALL           goms_recent_self_employed_pct  10099          0      0.000000
25           GRADE_ALL                goms_recent_industry_hhi  10099          0      0.000000
26           GRADE_ALL           goms_recent_industry_top3_pct  10099          0      0.000000
27           GRADE_ALL  goms_recent_professional_highskill_pct  10099          0      0.000000
28           GRADE_ALL          goms_recent_mean_income_10kkrw  10099          0      0.000000
29           GRADE_ALL           goms_recent_weekly_work_hours  10099          0      0.000000
30           GRADE_ALL         goms_recent_hourly_income_proxy  10099          0      0.000000
31           GRADE_ALL              goms_income_trend_per_year  10099          0      0.000000
32           GRADE_ALL               goms_hours_trend_per_year  10099          0      0.000000
33           GRADE_ALL        goms_firm_300plus_trend_per_year  10099          0      0.000000
34           GRADE_ALL           goms_permanent_trend_per_year  10099          0      0.000000
35           GRADE_ALL     goms_latest_2019_mean_income_10kkrw  10099          0      0.000000
36           GRADE_ALL      goms_latest_2019_weekly_work_hours  10099          0      0.000000
37           GRADE_ALL       goms_latest_2019_firm_300plus_pct  10099          0      0.000000
38           GRADE_ALL          goms_latest_2019_permanent_pct  10099          0      0.000000
39           GRADE_ALL              goms_source_years_observed  10099          0      0.000000
40           GRADE_ALL         goms_year_over_year_review_flag  10099          0      0.000000
41           GRADE_ALL                 goms_mapping_confidence  10099          0      0.000000
42           GRADE_ALL                      goms_row_qa_status  10099          0      0.000000
43           GRADE_ALL                    admission_capacity_n  10099       1538      0.152292
44           GRADE_ALL                           recruitment_n  10099       1538      0.152292
45           GRADE_ALL                            applicants_n  10099       1538      0.152292
46           GRADE_ALL                                admits_n  10099       1538      0.152292
47           GRADE_ALL                     enrolled_students_n  10099       1538      0.152292
48           GRADE_ALL                        leave_students_n  10099       1538      0.152292
49           GRADE_ALL                             graduates_n  10099       1538      0.152292
50           GRADE_ALL                      fulltime_faculty_n  10099       1538      0.152292
51           GRADE_ALL                   nonfulltime_faculty_n  10099       1538      0.152292
52           GRADE_ALL                international_students_n  10099       1538      0.152292
53           GRADE_ALL                       female_students_n  10099       1538      0.152292
54           GRADE_ALL                      masters_students_n  10099       1538      0.152292
55           GRADE_ALL                     doctoral_students_n  10099       1538      0.152292
56           GRADE_ALL                       competition_ratio  10099       4842      0.479453
57           GRADE_ALL                   admission_yield_ratio  10099       4842      0.479453
58           GRADE_ALL               admit_per_applicant_ratio  10099       4839      0.479156
59           GRADE_ALL                          leave_rate_pct  10099       1658      0.164175
60           GRADE_ALL                female_student_share_pct  10099       1658      0.164175
61           GRADE_ALL         international_student_share_pct  10099       1658      0.164175
62           GRADE_ALL                   student_faculty_ratio  10099       3720      0.368353
63           GRADE_ALL              fulltime_faculty_share_pct  10099       3720      0.368353
64           GRADE_ALL                   log_enrolled_students  10099       1538      0.152292
65           GRADE_ALL                           log_graduates  10099       1538      0.152292
66   GRADE_SELECTIVITY                ctx24_reference_sample_n   3707          0      0.000000
67   GRADE_SELECTIVITY                ctx24_mean_income_10kkrw   3707          0      0.000000
68   GRADE_SELECTIVITY              ctx24_median_income_10kkrw   3707          0      0.000000
69   GRADE_SELECTIVITY                ctx24_income_300plus_pct   3707          0      0.000000
70   GRADE_SELECTIVITY                ctx24_income_400plus_pct   3707          0      0.000000
71   GRADE_SELECTIVITY                 ctx24_large_company_pct   3707          0      0.000000
72   GRADE_SELECTIVITY                   ctx24_mid_company_pct   3707          0      0.000000
73   GRADE_SELECTIVITY                 ctx24_small_company_pct   3707          0      0.000000
74   GRADE_SELECTIVITY             ctx24_large_mid_company_pct   3707          0      0.000000
75   GRADE_SELECTIVITY              ctx24_public_nonprofit_pct   3707          0      0.000000
76   GRADE_SELECTIVITY                     ctx24_cert_rate_pct   3707          0      0.000000
77   GRADE_SELECTIVITY                   ctx24_cert_per_person   3707          0      0.000000
78   GRADE_SELECTIVITY                 ctx24_log10_mean_income   3707          0      0.000000
79   GRADE_SELECTIVITY                 ctx24_industry_top3_pct   3707       3707      1.000000
80   GRADE_SELECTIVITY                      ctx24_industry_hhi   3707       3707      1.000000
81   GRADE_SELECTIVITY                 goms_profile_start_year   3707          0      0.000000
82   GRADE_SELECTIVITY                   goms_profile_end_year   3707          0      0.000000
83   GRADE_SELECTIVITY                    goms_profile_years_n   3707          0      0.000000
84   GRADE_SELECTIVITY                 goms_aggregation_method   3707          0      0.000000
85   GRADE_SELECTIVITY         goms_recent_employment_rate_pct   3707          0      0.000000
86   GRADE_SELECTIVITY            goms_recent_firm_300plus_pct   3707          0      0.000000
87   GRADE_SELECTIVITY        goms_recent_public_nonprofit_pct   3707          0      0.000000
88   GRADE_SELECTIVITY               goms_recent_permanent_pct   3707          0      0.000000
89   GRADE_SELECTIVITY                goms_recent_unstable_pct   3707          0      0.000000
90   GRADE_SELECTIVITY           goms_recent_self_employed_pct   3707          0      0.000000
91   GRADE_SELECTIVITY                goms_recent_industry_hhi   3707          0      0.000000
92   GRADE_SELECTIVITY           goms_recent_industry_top3_pct   3707          0      0.000000
93   GRADE_SELECTIVITY  goms_recent_professional_highskill_pct   3707          0      0.000000
94   GRADE_SELECTIVITY          goms_recent_mean_income_10kkrw   3707          0      0.000000
95   GRADE_SELECTIVITY           goms_recent_weekly_work_hours   3707          0      0.000000
96   GRADE_SELECTIVITY         goms_recent_hourly_income_proxy   3707          0      0.000000
97   GRADE_SELECTIVITY              goms_income_trend_per_year   3707          0      0.000000
98   GRADE_SELECTIVITY               goms_hours_trend_per_year   3707          0      0.000000
99   GRADE_SELECTIVITY        goms_firm_300plus_trend_per_year   3707          0      0.000000
100  GRADE_SELECTIVITY           goms_permanent_trend_per_year   3707          0      0.000000
101  GRADE_SELECTIVITY     goms_latest_2019_mean_income_10kkrw   3707          0      0.000000
102  GRADE_SELECTIVITY      goms_latest_2019_weekly_work_hours   3707          0      0.000000
103  GRADE_SELECTIVITY       goms_latest_2019_firm_300plus_pct   3707          0      0.000000
104  GRADE_SELECTIVITY          goms_latest_2019_permanent_pct   3707          0      0.000000
105  GRADE_SELECTIVITY              goms_source_years_observed   3707          0      0.000000
106  GRADE_SELECTIVITY         goms_year_over_year_review_flag   3707          0      0.000000
107  GRADE_SELECTIVITY                 goms_mapping_confidence   3707          0      0.000000
108  GRADE_SELECTIVITY                      goms_row_qa_status   3707          0      0.000000
109  GRADE_SELECTIVITY                    admission_capacity_n   3707        509      0.137308
110  GRADE_SELECTIVITY                           recruitment_n   3707        509      0.137308
111  GRADE_SELECTIVITY                            applicants_n   3707        509      0.137308
112  GRADE_SELECTIVITY                                admits_n   3707        509      0.137308
113  GRADE_SELECTIVITY                     enrolled_students_n   3707        509      0.137308
114  GRADE_SELECTIVITY                        leave_students_n   3707        509      0.137308
115  GRADE_SELECTIVITY                             graduates_n   3707        509      0.137308
116  GRADE_SELECTIVITY                      fulltime_faculty_n   3707        509      0.137308
117  GRADE_SELECTIVITY                   nonfulltime_faculty_n   3707        509      0.137308
118  GRADE_SELECTIVITY                international_students_n   3707        509      0.137308
119  GRADE_SELECTIVITY                       female_students_n   3707        509      0.137308

shape: (330, 5)

                sample_id  feature_columns  mean_missing_rate
0       EMPLOYMENT_HEALTH               66           0.105530
1               GRADE_ALL               66           0.105328
2       GRADE_SELECTIVITY               66           0.079685
3          JOINT_EMP_PROG               66           0.105530
4  PROGRESSION_GRADSCHOOL               66           0.105372

## Gate 7 - Registry And Feature Set Contract

In [ ]:
gate_summary("Gate 7", summary["gate7"])
show_csv("Registry integrity", QA / "registry_integrity.csv")
show_csv("All-null feature audit", QA / "all_null_feature_audit.csv")
show_csv("P4 feature set registry", ROOT / "workbook" / "p2" / "p2_3" / "p4_handoff_candidate" / "shared" / "p4_feature_set_registry.csv")
show_csv("P4 target candidate registry", ROOT / "workbook" / "p2" / "p2_3" / "p4_handoff_candidate" / "shared" / "p4_target_candidate_registry.csv")
show_csv("D08 column registry dtype profile", PROFILES / "d08_v2_dtype_profile.csv")
show_csv("D08 top missing columns", PROFILES / "d08_v2_missing_top200.csv", n=80)

## Gate 7 Summary

   registry_missing_n  all_null_active_feature_set_n  p4_use_column_n  target_candidate_n  feature_set_n
0                   0                              0              120                   6              4

### Registry integrity
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/registry_integrity.csv`

                                      check  actual  expected status
0  D08 columns missing from column registry       0         0   PASS
1  p4_use registry columns missing from D08       0         0   PASS
2  target registry columns missing from D08       0         0   PASS
3                        unknown sample ids       0         0   PASS
4              all-null active feature sets       0         0   PASS

shape: (5, 4)

### All-null feature audit
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/all_null_feature_audit.csv`

                 feature_set_id                   column  p4_use  exists_in_d08  d08_all_null
0  CTX24_WAGE_DISABLED_ALL_NULL  ctx24_industry_top3_pct   False           True          True
1  CTX24_WAGE_DISABLED_ALL_NULL       ctx24_industry_hhi   False           True          True

shape: (2, 5)

### P4 feature set registry
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/p4_feature_set_registry.csv`

                 feature_set_id context_block  feature_count  all_null_count                            all_null_columns  p4_use                                     exclusion_rule
0                     STRUCTURE     structure             31               0                                         NaN    True  use only rows where required context is observ...
1                    CTX24_WAGE    ctx24_wage             13               0                                         NaN    True  use only rows where required context is observ...
2  CTX24_WAGE_DISABLED_ALL_NULL    ctx24_wage              2               2  ctx24_industry_top3_pct|ctx24_industry_hhi   False  disabled because source D04 has no industry di...
3                   GOMS_RECENT   goms_recent             28               0                                         NaN    True  use only rows where required context is observ...

shape: (4, 7)

### P4 target candidate registry
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/p4_target_candidate_registry.csv`

                       target_candidate  non_null_n                          role                                          p3_policy
0                            a_rate_pct       10242  candidate_target_or_exposure  candidate only; P4 chooses target within decla...
1                           cd_rate_pct       10242  candidate_target_or_exposure  candidate only; P4 chooses target within decla...
2                            f_rate_pct       10242  candidate_target_or_exposure  candidate only; P4 chooses target within decla...
3                 selectivity_proxy_pct        3737  candidate_target_or_exposure  candidate only; P4 chooses target within decla...
4            health_employment_rate_pct        7477  candidate_target_or_exposure  candidate only; P4 chooses target within decla...
5  graduate_school_progression_rate_pct        7587  candidate_target_or_exposure  candidate only; P4 chooses target within decla...

shape: (6, 4)

### D08 column registry dtype profile
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/d08_v2_dtype_profile.csv`

  dataset     dtype  column_count   rows  columns  key_columns  key_duplicate_rows  full_duplicate_rows  missing_cells
0  D08_v2   Float32            57  10242      151          NaN                 NaN                    0         141736
1  D08_v2    string            34  10242      151          NaN                 NaN                    0         141736
2  D08_v2       str            20  10242      151          NaN                 NaN                    0         141736
3  D08_v2     Int32            13  10242      151          NaN                 NaN                    0         141736
4  D08_v2   boolean             9  10242      151          NaN                 NaN                    0         141736
5  D08_v2     Int16             6  10242      151          NaN                 NaN                    0         141736
6  D08_v2      bool             6  10242      151          NaN                 NaN                    0         141736
7  D08_v2  category             4  10242      151          NaN                 NaN                    0         141736
8  D08_v2   float64             1  10242      151          NaN                 NaN                    0         141736
9  D08_v2     int64             1  10242      151          NaN                 NaN                    0         141736

shape: (10, 9)

### D08 top missing columns
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/profiles/d08_v2_missing_top200.csv`

   dataset                                   column  missing_n  missing_rate     dtype
0   D08_v2                  ctx24_industry_top3_pct      10242      1.000000   Float32
1   D08_v2                       ctx24_industry_hhi      10242      1.000000   Float32
2   D08_v2                    selectivity_proxy_pct       6505      0.635130   Float32
3   D08_v2                        competition_ratio       4985      0.486721   Float32
4   D08_v2                    admission_yield_ratio       4985      0.486721   Float32
5   D08_v2                admit_per_applicant_ratio       4982      0.486428   Float32
6   D08_v2                    student_faculty_ratio       3863      0.377172   Float32
7   D08_v2               fulltime_faculty_share_pct       3863      0.377172   Float32
8   D08_v2                      employment_rate_pct       2765      0.269967   Float32
9   D08_v2               health_employment_rate_pct       2765      0.269967   Float32
10  D08_v2                     progression_rate_pct       2655      0.259227   Float32
11  D08_v2  vocational_college_progression_rate_pct       2655      0.259227   Float32
12  D08_v2          university_progression_rate_pct       2655      0.259227   Float32
13  D08_v2     graduate_school_progression_rate_pct       2655      0.259227   Float32
14  D08_v2            domestic_progression_rate_pct       2655      0.259227   Float32
15  D08_v2            overseas_progression_rate_pct       2655      0.259227   Float32
16  D08_v2                           leave_rate_pct       1801      0.175845   Float32
17  D08_v2                 female_student_share_pct       1801      0.175845   Float32
18  D08_v2          international_student_share_pct       1801      0.175845   Float32
19  D08_v2                         headcount_row_id       1681      0.164128       str
20  D08_v2                  headcount_grain_version       1681      0.164128       str
21  D08_v2                      headcount_grain_uid       1681      0.164128    string
22  D08_v2                  grain_resolution_method       1681      0.164128       str
23  D08_v2                      grain_review_needed       1681      0.164128   boolean
24  D08_v2                          raw_row_lineage       1681      0.164128    string
25  D08_v2                             school_uid_y       1681      0.164128    string
26  D08_v2                           kedi_dept_code       1681      0.164128    string
27  D08_v2                              school_type       1681      0.164128    string
28  D08_v2                            degree_course       1681      0.164128    string
29  D08_v2                        school_status_raw       1681      0.164128    string
30  D08_v2                          day_evening_raw       1681      0.164128    string
31  D08_v2                        campus_name_raw_y       1681      0.164128    string
32  D08_v2                        campus_name_std_y       1681      0.164128    string
33  D08_v2                              region_sido       1681      0.164128    string
34  D08_v2                           region_sigungu       1681      0.164128    string
35  D08_v2                       hc_major_group_raw       1681      0.164128    string
36  D08_v2                         hc_major_group_7       1681      0.164128    string
37  D08_v2                        field_middle_name       1681      0.164128    string
38  D08_v2                         field_small_name       1681      0.164128    string
39  D08_v2                     admission_capacity_n       1681      0.164128     Int32
40  D08_v2                            recruitment_n       1681      0.164128     Int32
41  D08_v2                             applicants_n       1681      0.164128     Int32
42  D08_v2                                 admits_n       1681      0.164128     Int32
43  D08_v2                      enrolled_students_n       1681      0.164128     Int32
44  D08_v2                         leave_students_n       1681      0.164128     Int32
45  D08_v2                              graduates_n       1681      0.164128     Int32
46  D08_v2                       fulltime_faculty_n       1681      0.164128     Int32
47  D08_v2                    nonfulltime_faculty_n       1681      0.164128     Int32
48  D08_v2                 international_students_n       1681      0.164128     Int32
49  D08_v2                        female_students_n       1681      0.164128     Int32
50  D08_v2                       masters_students_n       1681      0.164128     Int32
51  D08_v2                      doctoral_students_n       1681      0.164128     Int32
52  D08_v2                    log_enrolled_students       1681      0.164128   Float32
53  D08_v2                            log_graduates       1681      0.164128   Float32
54  D08_v2                              match_score        365      0.035638   float64
55  D08_v2                            major_group_7        143      0.013962       str
56  D08_v2                 ctx24_reference_sample_n        143      0.013962   Float32
57  D08_v2                 ctx24_mean_income_10kkrw        143      0.013962   Float32
58  D08_v2               ctx24_median_income_10kkrw        143      0.013962   Float32
59  D08_v2                 ctx24_income_300plus_pct        143      0.013962   Float32
60  D08_v2                 ctx24_income_400plus_pct        143      0.013962   Float32
61  D08_v2                  ctx24_large_company_pct        143      0.013962   Float32
62  D08_v2                    ctx24_mid_company_pct        143      0.013962   Float32
63  D08_v2                  ctx24_small_company_pct        143      0.013962   Float32
64  D08_v2              ctx24_large_mid_company_pct        143      0.013962   Float32
65  D08_v2               ctx24_public_nonprofit_pct        143      0.013962   Float32
66  D08_v2                      ctx24_cert_rate_pct        143      0.013962   Float32
67  D08_v2                    ctx24_cert_per_person        143      0.013962   Float32
68  D08_v2                  ctx24_log10_mean_income        143      0.013962   Float32
69  D08_v2                  goms_profile_start_year        143      0.013962     Int16
70  D08_v2                    goms_profile_end_year        143      0.013962     Int16
71  D08_v2                     goms_profile_years_n        143      0.013962     Int16
72  D08_v2                  goms_aggregation_method        143      0.013962  category
73  D08_v2          goms_recent_employment_rate_pct        143      0.013962   Float32
74  D08_v2             goms_recent_firm_300plus_pct        143      0.013962   Float32
75  D08_v2         goms_recent_public_nonprofit_pct        143      0.013962   Float32
76  D08_v2                goms_recent_permanent_pct        143      0.013962   Float32
77  D08_v2                 goms_recent_unstable_pct        143      0.013962   Float32
78  D08_v2            goms_recent_self_employed_pct        143      0.013962   Float32
79  D08_v2                 goms_recent_industry_hhi        143      0.013962   Float32

shape: (151, 5)

    dataset                                   column  missing_n  missing_rate     dtype
0    D08_v2                  ctx24_industry_top3_pct      10242      1.000000   Float32
1    D08_v2                       ctx24_industry_hhi      10242      1.000000   Float32
2    D08_v2                    selectivity_proxy_pct       6505      0.635130   Float32
3    D08_v2                        competition_ratio       4985      0.486721   Float32
4    D08_v2                    admission_yield_ratio       4985      0.486721   Float32
5    D08_v2                admit_per_applicant_ratio       4982      0.486428   Float32
6    D08_v2                    student_faculty_ratio       3863      0.377172   Float32
7    D08_v2               fulltime_faculty_share_pct       3863      0.377172   Float32
8    D08_v2                      employment_rate_pct       2765      0.269967   Float32
9    D08_v2               health_employment_rate_pct       2765      0.269967   Float32
10   D08_v2                     progression_rate_pct       2655      0.259227   Float32
11   D08_v2  vocational_college_progression_rate_pct       2655      0.259227   Float32
12   D08_v2          university_progression_rate_pct       2655      0.259227   Float32
13   D08_v2     graduate_school_progression_rate_pct       2655      0.259227   Float32
14   D08_v2            domestic_progression_rate_pct       2655      0.259227   Float32
15   D08_v2            overseas_progression_rate_pct       2655      0.259227   Float32
16   D08_v2                           leave_rate_pct       1801      0.175845   Float32
17   D08_v2                 female_student_share_pct       1801      0.175845   Float32
18   D08_v2          international_student_share_pct       1801      0.175845   Float32
19   D08_v2                         headcount_row_id       1681      0.164128       str
20   D08_v2                  headcount_grain_version       1681      0.164128       str
21   D08_v2                      headcount_grain_uid       1681      0.164128    string
22   D08_v2                  grain_resolution_method       1681      0.164128       str
23   D08_v2                      grain_review_needed       1681      0.164128   boolean
24   D08_v2                          raw_row_lineage       1681      0.164128    string
25   D08_v2                             school_uid_y       1681      0.164128    string
26   D08_v2                           kedi_dept_code       1681      0.164128    string
27   D08_v2                              school_type       1681      0.164128    string
28   D08_v2                            degree_course       1681      0.164128    string
29   D08_v2                        school_status_raw       1681      0.164128    string
30   D08_v2                          day_evening_raw       1681      0.164128    string
31   D08_v2                        campus_name_raw_y       1681      0.164128    string
32   D08_v2                        campus_name_std_y       1681      0.164128    string
33   D08_v2                              region_sido       1681      0.164128    string
34   D08_v2                           region_sigungu       1681      0.164128    string
35   D08_v2                       hc_major_group_raw       1681      0.164128    string
36   D08_v2                         hc_major_group_7       1681      0.164128    string
37   D08_v2                        field_middle_name       1681      0.164128    string
38   D08_v2                         field_small_name       1681      0.164128    string
39   D08_v2                     admission_capacity_n       1681      0.164128     Int32
40   D08_v2                            recruitment_n       1681      0.164128     Int32
41   D08_v2                             applicants_n       1681      0.164128     Int32
42   D08_v2                                 admits_n       1681      0.164128     Int32
43   D08_v2                      enrolled_students_n       1681      0.164128     Int32
44   D08_v2                         leave_students_n       1681      0.164128     Int32
45   D08_v2                              graduates_n       1681      0.164128     Int32
46   D08_v2                       fulltime_faculty_n       1681      0.164128     Int32
47   D08_v2                    nonfulltime_faculty_n       1681      0.164128     Int32
48   D08_v2                 international_students_n       1681      0.164128     Int32
49   D08_v2                        female_students_n       1681      0.164128     Int32
50   D08_v2                       masters_students_n       1681      0.164128     Int32
51   D08_v2                      doctoral_students_n       1681      0.164128     Int32
52   D08_v2                    log_enrolled_students       1681      0.164128   Float32
53   D08_v2                            log_graduates       1681      0.164128   Float32
54   D08_v2                              match_score        365      0.035638   float64
55   D08_v2                            major_group_7        143      0.013962       str
56   D08_v2                 ctx24_reference_sample_n        143      0.013962   Float32
57   D08_v2                 ctx24_mean_income_10kkrw        143      0.013962   Float32
58   D08_v2               ctx24_median_income_10kkrw        143      0.013962   Float32
59   D08_v2                 ctx24_income_300plus_pct        143      0.013962   Float32
60   D08_v2                 ctx24_income_400plus_pct        143      0.013962   Float32
61   D08_v2                  ctx24_large_company_pct        143      0.013962   Float32
62   D08_v2                    ctx24_mid_company_pct        143      0.013962   Float32
63   D08_v2                  ctx24_small_company_pct        143      0.013962   Float32
64   D08_v2              ctx24_large_mid_company_pct        143      0.013962   Float32
65   D08_v2               ctx24_public_nonprofit_pct        143      0.013962   Float32
66   D08_v2                      ctx24_cert_rate_pct        143      0.013962   Float32
67   D08_v2                    ctx24_cert_per_person        143      0.013962   Float32
68   D08_v2                  ctx24_log10_mean_income        143      0.013962   Float32
69   D08_v2                  goms_profile_start_year        143      0.013962     Int16
70   D08_v2                    goms_profile_end_year        143      0.013962     Int16
71   D08_v2                     goms_profile_years_n        143      0.013962     Int16
72   D08_v2                  goms_aggregation_method        143      0.013962  category
73   D08_v2          goms_recent_employment_rate_pct        143      0.013962   Float32
74   D08_v2             goms_recent_firm_300plus_pct        143      0.013962   Float32
75   D08_v2         goms_recent_public_nonprofit_pct        143      0.013962   Float32
76   D08_v2                goms_recent_permanent_pct        143      0.013962   Float32
77   D08_v2                 goms_recent_unstable_pct        143      0.013962   Float32
78   D08_v2            goms_recent_self_employed_pct        143      0.013962   Float32
79   D08_v2                 goms_recent_industry_hhi        143      0.013962   Float32
80   D08_v2            goms_recent_industry_top3_pct        143      0.013962   Float32
81   D08_v2   goms_recent_professional_highskill_pct        143      0.013962   Float32
82   D08_v2           goms_recent_mean_income_10kkrw        143      0.013962   Float32
83   D08_v2            goms_recent_weekly_work_hours        143      0.013962   Float32
84   D08_v2          goms_recent_hourly_income_proxy        143      0.013962   Float32
85   D08_v2               goms_income_trend_per_year        143      0.013962   Float32
86   D08_v2                goms_hours_trend_per_year        143      0.013962   Float32
87   D08_v2         goms_firm_300plus_trend_per_year        143      0.013962   Float32
88   D08_v2            goms_permanent_trend_per_year        143      0.013962   Float32
89   D08_v2      goms_latest_2019_mean_income_10kkrw        143      0.013962   Float32
90   D08_v2       goms_latest_2019_weekly_work_hours        143      0.013962   Float32
91   D08_v2        goms_latest_2019_firm_300plus_pct        143      0.013962   Float32
92   D08_v2           goms_latest_2019_permanent_pct        143      0.013962   Float32
93   D08_v2               goms_source_years_observed        143      0.013962     Int16
94   D08_v2          goms_year_over_year_review_flag        143      0.013962   boolean
95   D08_v2                  goms_mapping_confidence        143      0.013962  category
96   D08_v2                       goms_row_qa_status        143      0.013962  category
97   D08_v2                            analysis_year          0      0.000000     Int16
98   D08_v2                           outcome_row_id          0      0.000000       str
99   D08_v2                          school_name_raw          0      0.000000    string
100  D08_v2                     school_name_base_raw          0      0.000000    string
101  D08_v2                          school_name_std          0      0.000000    string
102  D08_v2                        campus_name_raw_x          0      0.000000    string
103  D08_v2                               campus_seq          0      0.000000    string
104  D08_v2                            campus_branch          0      0.000000    string
105  D08_v2                        campus_name_std_x          0      0.000000    string
106  D08_v2                            dept_name_raw          0      0.000000    string
107  D08_v2                            dept_name_std          0      0.000000    string
108  D08_v2                           dept_field_raw          0      0.000000    string
109  D08_v2                           dept_field_std          0      0.000000    string
110  D08_v2                      credit_forfeit_flag          0      0.000000   boolean
111  D08_v2                               a_rate_pct          0      0.000000   Float32
112  D08_v2                              cd_rate_pct          0      0.000000   Float32
113  D08_v2                               f_rate_pct          0      0.000000   Float32
114  D08_v2                          has_selectivity          0      0.000000   boolean
115  D08_v2                           has_employment          0      0.000000   boolean
116  D08_v2                          has_progression          0      0.000000   boolean
117  D08_v2                            rate_range_qa          0      0.000000  category
118  D08_v2                              source_file          0      0.000000       str
119  D08_v2                            source_sha256          0      0.000000       str
120  D08_v2                        campus_region_raw          0      0.000000    string
121  D08_v2                         dept_norm_strict          0      0.000000    string
122  D08_v2                 dept_norm_suffix_reduced          0      0.000000    string
123  D08_v2                     dept_token_signature          0      0.000000    string
124  D08_v2                             school_uid_x          0      0.000000    string
125  D08_v2                              match_stage          0      0.000000       str
126  D08_v2                             match_method          0      0.000000       str
127  D08_v2                             match_status          0      0.000000       str
128  D08_v2                          candidate_count          0      0.000000     Int16
129  D08_v2                            review_needed          0      0.000000   boolean
130  D08_v2                         unmatched_reason          0      0.000000       str
131  D08_v2                           match_evidence          0      0.000000       str
132  D08_v2              candidate_headcount_row_ids          0      0.000000       str
133  D08_v2                        candidate_preview          0      0.000000       str
134  D08_v2                     campus_conflict_flag          0      0.000000      bool
135  D08_v2              degree_course_conflict_flag          0      0.000000      bool
136  D08_v2                      major_conflict_flag          0      0.000000      bool
137  D08_v2         forbidden_modifier_conflict_flag          0      0.000000      bool
138  D08_v2                     headcount_match_flag          0      0.000000      bool
139  D08_v2                               campus_uid          0      0.000000    string
140  D08_v2                                 dept_uid          0      0.000000    string
141  D08_v2                               school_uid          0      0.000000       str
142  D08_v2                    major7_mapping_method          0      0.000000       str
143  D08_v2                major7_mapping_confidence          0      0.000000       str
144  D08_v2                   major7_candidate_count          0      0.000000     int64
145  D08_v2                     major7_review_needed          0      0.000000      bool
146  D08_v2                          major7_evidence          0      0.000000       str
147  D08_v2             major7_sample_exclusion_rule          0      0.000000       str
148  D08_v2                    has_structure_context          0      0.000000   boolean
149  D08_v2            has_major_group_7_high_medium          0      0.000000   boolean
150  D08_v2                            row_qa_status          0      0.000000       str

## Reports And Execution Evidence

In [ ]:
show_md("P4 D08 data card", REPORTS / "P4_D08_DATA_CARD.md")
show_md("P4 data integrity report", REPORTS / "P4_DATA_INTEGRITY_REPORT.md")
show_csv("All gate QA summary", QA / "all_gate_qa_summary.csv")
show_csv("Failed checks", QA / "failed_checks.csv")
show_csv("Warn checks", QA / "warn_checks.csv")
show_csv("Code line trace", LOGS / "code_line_trace.csv")
run_manifest = json.loads((LOGS / "run_manifest.json").read_text(encoding="utf-8"))
display(pd.DataFrame([run_manifest]))

### P4 D08 data card
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/reports/P4_D08_DATA_CARD.md`

# P4 D08 Data Card

## Status
- final_status: **P4_DATA_CONTRACT_READY**
- D08 shape: `[10242, 151]`
- D08 hash: `598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962`

## Grain And Keys
- Grain: 2024년 × outcome 학교 × outcome 캠퍼스 × outcome 학과
- Frozen P4 key: `analysis_year`, `p4_school_uid`, `p4_campus_uid`, `p4_dept_uid`, with `outcome_row_id` as stable row identity.
- P4 composite duplicate rows: `0`
- Carried headcount UID composite duplicate rows: `18`. This is tracked as WARN because `dept_uid` is a matched D01 identifier, not the outcome spine key.

## Coverage
- structure high-confidence: `8561/10242 = 83.59%`
- major high/medium: `10099/10242 = 98.60%`
- Local2 D07 hash: `f44c6f9e7a7539361dce301686144780e0ce588deb929b625ebe811674bb621f`
- D07 to D08 GOMS mismatch cells: `0`

## P4 Restrictions
- Do not treat `manual_pending` or `unmatched` rows as having observed structure context.
- Do not use ambiguous/unknown `major_group_7` rows in major/context/GOMS samples.
- Do not activate all-null D04 industry features (`ctx24_industry_hhi`, `ctx24_industry_top3_pct`).
- Do not impute, scale, one-hot encode, train models, or recalculate ratios in this contract notebook.

### P4 data integrity report
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/reports/P4_DATA_INTEGRITY_REPORT.md`

# P4 Data Integrity Report

## Final Status
**P4_DATA_CONTRACT_READY**

## Core Hashes
- D01 v2: `2f187b5af44c828d4107af12368029caf6b83b6254af75b9653b6402b8f1b0ce` shape `[34969, 186]`
- D03 v2: `c6fd569052684502e5bab5758510d3cd945f68ddeaa47fdfb3e9bab803889dca` shape `[10242, 108]`
- D08 v2: `598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962` shape `[10242, 151]`

## Gate Summary
- Manifest hash mismatch: `0`
- Manifest shape mismatch: `0`
- Manifest missing files: `0`
- D01 canonical grain duplicate: `0`
- D01 unexplained raw count delta: `0`
- D08 P4 composite duplicate: `0`
- Outcome mismatch cells D03->D08: `0`
- Structure high-confidence rate: `83.59%`
- Major high/medium rate: `98.60%`
- D07->D08 GOMS mismatch: `0`
- Split leakage: `0`
- Registry missing count: `0`
- All-null active feature sets: `0`
- FAIL checks: `0`

## Evidence Paths
- Manifest audit: `qa/manifest_integrity_audit.csv`
- D01 explanation: `reports/D01_GRAIN_EXPLANATION.md`
- Spine comparison: `qa/d03_d08_spine_comparison.csv`
- Structure matching: `qa/structure_match_integrity.csv`
- Major mapping: `qa/major7_mapping_integrity.csv`
- Local2 lineage: `qa/local2_context_lineage_integrity.csv`
- Split/sample: `qa/split_sample_integrity.csv`
- Registry: `qa/registry_integrity.csv`

### All gate QA summary
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/all_gate_qa_summary.csv`

,check,actual,expected,status,audit_item,key,duplicate_rows
0,manifest hash mismatch,0,0,PASS,NaN,NaN,NaN
1,manifest shape mismatch,0,0,PASS,NaN,NaN,NaN
2,manifest missing files,0,0,PASS,NaN,NaN,NaN
3,NaN,NaN,NaN,PASS,canonical_grain_duplicate_rows,analysis_year|school_name_std|campus_name_std|...,0.0
4,NaN,NaN,NaN,PASS,exact_duplicate_rows_raw_columns,all restored raw Excel columns excluding sourc...,0.0
5,NaN,NaN,NaN,INFO,legacy_grain_duplicate_rows_without_day_degree,analysis_year|school_name_std|campus_name_std|...,1.0
6,NaN,NaN,NaN,PASS,lineage_missing_rows,source_excel_row/raw_row_lineage,0.0
7,D03 row count,10242,10242,PASS,NaN,NaN,NaN
8,D08 row count,10242,10242,PASS,NaN,NaN,NaN
9,D03 outcome_row_id duplicate,0,0,PASS,NaN,NaN,NaN
10,D08 outcome_row_id duplicate,0,0,PASS,NaN,NaN,NaN
11,P4 raw outcome composite key duplicate,0,0,PASS,NaN,NaN,NaN
12,D08 carried headcount UID composite duplicate,18,tracked as WARN only,WARN,NaN,NaN,NaN
13,D03 to D08 lost rows,0,0,PASS,NaN,NaN,NaN
14,D08 extra rows over D03,0,0,PASS,NaN,NaN,NaN
15,D03-D08 order changed,False,False,PASS,NaN,NaN,NaN
16,D03-D08 outcome value mismatch cells,0,0,PASS,NaN,NaN,NaN
17,P4 key null cells,0,0,PASS,NaN,NaN,NaN
18,D08 inf/-inf cells,0,0,PASS,NaN,NaN,NaN
19,bridge row count,10242,10242,PASS,NaN,NaN,NaN
20,bridge outcome_row_id duplicate,0,0,PASS,NaN,NaN,NaN
21,candidate_count>=2 auto-confirmed,0,0,PASS,NaN,NaN,NaN
22,campus conflict auto-confirmed,0,0,PASS,NaN,NaN,NaN
23,manual_pending included in high confidence,0,0,PASS,NaN,NaN,NaN
24,unmatched rows deleted from D08,0,0,PASS,NaN,NaN,NaN
25,structural_match_eligible formula mismatch,0,0,PASS,NaN,NaN,NaN
26,allowed major_group_7 code violations,0.0,0,PASS,NaN,NaN,NaN
27,major high/medium rate >=97%,0.9860378832259324,>=0.97,PASS,NaN,NaN,NaN
28,ambiguous+unknown <=3%,0.0139621167740675,<=0.03,PASS,NaN,NaN,NaN
29,inherited D01 major mismatch,0.0,0,PASS,NaN,NaN,NaN
30,major_context_eligible formula mismatch,0.0,0,PASS,NaN,NaN,NaN
31,ambiguous/unknown rows included in major samples,0.0,0,PASS,NaN,NaN,NaN
32,Local2 ready_for_local1,True,True,PASS,NaN,NaN,NaN
33,manifest D07 hash equals actual,f44c6f9e7a7539361dce301686144780e0ce588deb929b...,f44c6f9e7a7539361dce301686144780e0ce588deb929b...,PASS,NaN,NaN,NaN
34,actual D07 hash equals Local1 manifest input,f44c6f9e7a7539361dce301686144780e0ce588deb929b...,f44c6f9e7a7539361dce301686144780e0ce588deb929b...,PASS,NaN,NaN,NaN
35,D07 row count,7,7,PASS,NaN,NaN,NaN
36,D07 major key duplicate,0,0,PASS,NaN,NaN,NaN
37,D07 to D08 goms exact mismatch cells,0,0,PASS,NaN,NaN,NaN
38,school split leakage,0,0,PASS,NaN,NaN,NaN
39,membership row count,10242,10242,PASS,NaN,NaN,NaN
40,membership outcome_row_id duplicate,0,0,PASS,NaN,NaN,NaN
41,sample registry actual mismatch rows,0,0,PASS,NaN,NaN,NaN
42,D08 columns missing from column registry,0,0,PASS,NaN,NaN,NaN
43,p4_use registry columns missing from D08,0,0,PASS,NaN,NaN,NaN
44,target registry columns missing from D08,0,0,PASS,NaN,NaN,NaN
45,unknown sample ids,0,0,PASS,NaN,NaN,NaN
46,all-null active feature sets,0,0,PASS,NaN,NaN,NaN

shape: (47, 7)

### Failed checks
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/failed_checks.csv`

Empty DataFrame
Columns: [check, actual, expected, status, audit_item, key, duplicate_rows]
Index: []

shape: (0, 7)

### Warn checks
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/qa/warn_checks.csv`

                                           check  actual              expected status  audit_item  key  duplicate_rows
0  D08 carried headcount UID composite duplicate      18  tracked as WARN only   WARN         NaN  NaN             NaN

shape: (1, 7)

### Code line trace
`/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_1_data_contract/logs/code_line_trace.csv`

                  agent                                   script            function_or_cell  script_line_start  script_line_end
0   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py  collect_manifest_artifacts                296              364
1   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py       load_candidate_tables                367              386
2   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py           gate1_d01_profile                397              509
3   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py                 gate2_spine                534              657
4   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py    gate3_structure_matching                660              748
5   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py         gate4_major_mapping                751              831
6   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py        gate5_local2_lineage                834              900
7   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py        gate6_splits_samples                918             1017
8   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py            gate7_registries               1020             1075
9   P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py                final_status               1279             1300
10  P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py            write_data_cards               1078             1154
11  P2-G4 Local Agent 1  scripts/p2_g4_1_data_contract_local1.py                  write_logs               1157             1276

shape: (12, 5)

,created_at,agent,script,python,platform,runtime_seconds,input_manifest,input_manifest_hash,output_root,final_status,fail_count,warn_count,metrics_path
0,2026-07-12T22:32:49,P2-G4 Local Agent 1,/home/sieg/projects-wsl/SBS_dataScience/script...,"3.12.3 (main, Jun 19 2026, 12:46:00) [GCC 13.3.0]",Linux-6.18.33.2-microsoft-standard-WSL2-x86_64...,25.722,/home/sieg/projects-wsl/SBS_dataScience/workbo...,b9ea9528b24630f15be8913012b40df81692d16e849120...,/home/sieg/projects-wsl/SBS_dataScience/workbo...,P4_DATA_CONTRACT_READY,0,1,/home/sieg/projects-wsl/SBS_dataScience/workbo...

## Final Contract Status

In [ ]:
final = json.loads((REPORTS / "final_status.json").read_text(encoding="utf-8"))
display(pd.DataFrame([
    {
        "final_status": final["final_status"],
        "manifest_hash_mismatch": final["gate0"]["hash_mismatch_n"],
        "manifest_shape_mismatch": final["gate0"]["shape_mismatch_n"],
        "d01_grain_duplicate": final["gate1"]["d01_key_duplicate_n"],
        "d08_p4_composite_duplicate": final["gate2"]["p4_composite_key_duplicate_n"],
        "structure_high_conf_rate": final["gate3"]["high_conf_match_rate"],
        "major_high_medium_rate": final["gate4"]["major_high_medium_rate"],
        "d07_d08_goms_mismatch": final["gate5"]["d07_d08_goms_mismatch_n"],
        "split_leakage": final["gate6"]["split_leakage_n"],
        "registry_missing": final["gate7"]["registry_missing_n"],
        "fail_count": final["fail_count"],
        "warn_count": final["warn_count"],
    }
]))

,final_status,manifest_hash_mismatch,manifest_shape_mismatch,d01_grain_duplicate,d08_p4_composite_duplicate,structure_high_conf_rate,major_high_medium_rate,d07_d08_goms_mismatch,split_leakage,registry_missing,fail_count,warn_count
0,P4_DATA_CONTRACT_READY,0,0,0,0,0.835872,0.986038,0,0,0,0,1