# P2-G4 Dataset-by-Dataset Inspection

- 실행 목적: P2-G4 모델링 착수 전 핵심 데이터셋을 파일별 독립 셀에서 read-only로 검사한다.
- 실행 시각: `2026-07-13T02:54:03.539862+00:00`
- read-only 원칙: 원본 데이터와 readiness 산출물은 수정하지 않고, inspection 프로파일만 `dataset_inspection/`에 저장한다.
- random seed = `3085`
- active D08 hash = `598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962`

In [ ]:

from __future__ import annotations

import hashlib
import io
import json
import os
import platform
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow
from IPython.display import Markdown, display

RANDOM_STATE = 3085
HEAD_N = 5
TAIL_N = 5
RANDOM_N = 10
TOP_MISSING_N = 30
TOP_CARDINALITY_N = 30

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 300)
pd.set_option("display.max_colwidth", 120)
pd.set_option("display.width", 240)
pd.set_option("display.float_format", lambda x: f"{x:,.6f}")

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "workbook").exists():
    for parent in Path.cwd().resolve().parents:
        if (parent / "workbook").exists():
            PROJECT_ROOT = parent
            break

OUT_ROOT = PROJECT_ROOT / "workbook" / "p2" / "p2_4" / "p4_modeling_readiness_v4"
INSPECTION_ROOT = OUT_ROOT / "dataset_inspection"
PROFILE_DIR = INSPECTION_ROOT / "profiles"
QA_DIR = INSPECTION_ROOT / "qa"
LOG_DIR = INSPECTION_ROOT / "logs"
REPORT_DIR = INSPECTION_ROOT / "reports"
for _path in [PROFILE_DIR, QA_DIR, LOG_DIR, REPORT_DIR]:
    _path.mkdir(parents=True, exist_ok=True)

RUN_STARTED_AT = datetime.now(timezone.utc).isoformat()

try:
    GIT_COMMIT = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=PROJECT_ROOT, text=True).strip()
except Exception as exc:
    GIT_COMMIT = f"unknown ({type(exc).__name__})"

print("working directory:", PROJECT_ROOT)
print("Python version:", platform.python_version())
print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)
print("pyarrow version:", pyarrow.__version__)
print("platform:", platform.platform())
print("execution time:", RUN_STARTED_AT)
print("Git commit:", GIT_COMMIT)
print("inspection root:", INSPECTION_ROOT)

DATASET_RESULTS = []
ANOMALY_ROWS = []
PROFILE_PATHS = []

working directory: /home/sieg/projects-wsl/SBS_dataScience
Python version: 3.12.3
pandas version: 3.0.3
numpy version: 2.5.0
pyarrow version: 24.0.0
platform: Linux-6.18.33.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
execution time: 2026-07-13T02:54:15.479923+00:00
Git commit: 5b1a3d5
inspection root: /home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/dataset_inspection

In [ ]:

def rel(path: Path | str) -> str:
    path = Path(path)
    try:
        return path.resolve().relative_to(PROJECT_ROOT).as_posix()
    except Exception:
        return path.as_posix()


def safe_label(label: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in label)


def sha256_file(path: Path | str) -> str | None:
    path = Path(path)
    if not path.exists():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def summarize_json_structure(obj, depth=0, max_depth=4):
    if depth >= max_depth:
        return type(obj).__name__
    if isinstance(obj, dict):
        return {str(k): summarize_json_structure(v, depth + 1, max_depth) for k, v in obj.items()}
    if isinstance(obj, list):
        return {
            "type": "list",
            "length": len(obj),
            "item_structure": summarize_json_structure(obj[0], depth + 1, max_depth) if obj else None,
        }
    return type(obj).__name__


def load_dataset(path: Path | str):
    path = Path(path)
    ext = path.suffix.lower()
    meta = {"encoding": None, "loader": None, "json_raw_type": None, "json_top_level_keys": None, "json_structure": None, "json_raw_preview": None}
    if ext == ".parquet":
        meta["loader"] = "pd.read_parquet"
        return pd.read_parquet(path), meta
    if ext == ".csv":
        errors = []
        for enc in ["utf-8-sig", "cp949", "euc-kr"]:
            try:
                df = pd.read_csv(path, low_memory=False, encoding=enc)
                meta["encoding"] = enc
                meta["loader"] = "pd.read_csv(low_memory=False)"
                return df, meta
            except UnicodeDecodeError as exc:
                errors.append(f"{enc}: {exc}")
        raise UnicodeDecodeError("csv", b"", 0, 1, " / ".join(errors))
    if ext == ".json":
        obj = json.loads(path.read_text(encoding="utf-8"))
        meta["loader"] = "json.load + pd.json_normalize"
        meta["json_raw_type"] = type(obj).__name__
        meta["json_structure"] = summarize_json_structure(obj)
        meta["json_raw_preview"] = json.dumps(obj, ensure_ascii=False, indent=2, default=str)[:12000]
        if isinstance(obj, dict):
            meta["json_top_level_keys"] = list(obj.keys())
            if "files" in obj and isinstance(obj["files"], list):
                df = pd.json_normalize(obj["files"])
            else:
                df = pd.DataFrame({"key": list(obj.keys()), "value": [json.dumps(v, ensure_ascii=False) if isinstance(v, (dict, list)) else v for v in obj.values()]})
        elif isinstance(obj, list):
            df = pd.json_normalize(obj)
        else:
            df = pd.DataFrame({"value": [obj]})
        return df, meta
    raise ValueError(f"Unsupported file extension: {ext}")


def capture_df_info(df: pd.DataFrame) -> str:
    buf = io.StringIO()
    df.info(buf=buf, verbose=True, show_counts=True, memory_usage=True)
    return buf.getvalue()


def identifier_candidate(column: str) -> bool:
    text = str(column).lower()
    return any(token in text for token in ["id", "uid", "key", "name", "raw", "label", "sha", "path", "file"])


UNHASHABLE_TYPES = (list, dict, tuple, set, np.ndarray)


def hashable_value(value):
    if isinstance(value, UNHASHABLE_TYPES):
        return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
    return value


def hashable_series(s: pd.Series) -> pd.Series:
    obj = s.astype("object")
    has_unhashable = bool(obj.map(lambda x: isinstance(x, UNHASHABLE_TYPES)).to_numpy(dtype=bool).any())
    if has_unhashable:
        return obj.map(hashable_value)
    return s


def make_hashable_frame(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    for col in out.columns:
        out[col] = hashable_series(out[col])
    return out


def build_column_profile(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    n = len(df)
    for pos, col in enumerate(df.columns, start=1):
        s = df[col]
        hs = hashable_series(s)
        non_null = int(s.notna().sum())
        missing = int(s.isna().sum())
        nunique = int(hs.nunique(dropna=True))
        vc_all = hs.value_counts(dropna=False, normalize=True)
        rows.append({
            "position": pos,
            "column": col,
            "dtype": str(s.dtype),
            "non_null_n": non_null,
            "missing_n": missing,
            "missing_pct": (missing / n * 100) if n else np.nan,
            "nunique": nunique,
            "unique_ratio": (nunique / non_null) if non_null else np.nan,
            "is_all_null": non_null == 0,
            "is_constant": nunique <= 1,
            "is_identifier_candidate": identifier_candidate(col),
            "top_value_share": float(vc_all.iloc[0]) if n and len(vc_all) else np.nan,
        })
    return pd.DataFrame(rows)


def build_numeric_describe(df: pd.DataFrame) -> pd.DataFrame:
    numeric_cols = [c for c in df.select_dtypes(include=[np.number]).columns]
    if not numeric_cols:
        return pd.DataFrame()
    numeric_df = df[numeric_cols].apply(pd.to_numeric, errors="coerce").astype("float64")
    desc = numeric_df.describe(percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]).T.reset_index().rename(columns={"index": "column"})
    rows = []
    n = len(df)
    for col in numeric_cols:
        s = pd.to_numeric(df[col], errors="coerce").astype("float64")
        rows.append({
            "column": col,
            "missing_n": int(s.isna().sum()),
            "missing_pct": float(s.isna().mean() * 100) if n else np.nan,
            "zero_n": int((s == 0).sum()),
            "zero_pct": float((s == 0).mean() * 100) if n else np.nan,
            "negative_n": int((s < 0).sum()),
            "inf_n": int(np.isinf(s).sum()),
            "nunique": int(s.nunique(dropna=True)),
        })
    return desc.merge(pd.DataFrame(rows), on="column", how="left")


def build_categorical_describe(df: pd.DataFrame) -> pd.DataFrame:
    cols = [c for c in df.columns if c not in df.select_dtypes(include=[np.number]).columns]
    rows = []
    n = len(df)
    for col in cols:
        s = df[col]
        hs = hashable_series(s)
        vc = hs.value_counts(dropna=True)
        top = vc.index[0] if len(vc) else np.nan
        freq = int(vc.iloc[0]) if len(vc) else 0
        sample_values = [str(x) for x in hs.dropna().drop_duplicates().head(5).tolist()]
        rows.append({
            "column": col,
            "dtype": str(s.dtype),
            "count": int(s.notna().sum()),
            "missing_n": int(s.isna().sum()),
            "missing_pct": float(s.isna().mean() * 100) if n else np.nan,
            "nunique": int(hs.nunique(dropna=True)),
            "top": top,
            "freq": freq,
            "top_pct": float(freq / n * 100) if n else np.nan,
            "sample_values": " | ".join(sample_values),
        })
    return pd.DataFrame(rows)


def build_datetime_describe(df: pd.DataFrame) -> pd.DataFrame:
    cols = list(df.select_dtypes(include=["datetime64[ns]", "datetimetz"]).columns)
    rows = []
    for col in cols:
        s = df[col]
        rows.append({"column": col, "min": s.min(), "max": s.max(), "missing_n": int(s.isna().sum()), "nunique": int(s.nunique(dropna=True))})
    return pd.DataFrame(rows)


def save_profile_outputs(label, column_profile, numeric_desc, categorical_desc, top_missing, duplicates):
    base = safe_label(label)
    paths = []
    for suffix, df in [
        ("column_profile", column_profile),
        ("numeric_describe", numeric_desc),
        ("categorical_describe", categorical_desc),
        ("top_missing", top_missing),
        ("duplicates", duplicates),
    ]:
        path = PROFILE_DIR / f"{base}__{suffix}.csv"
        df.to_csv(path, index=False, encoding="utf-8-sig")
        paths.append(path)
    PROFILE_PATHS.extend(paths)
    return paths


def resolve_candidate_key(df: pd.DataFrame, key_cols):
    alias = {"p4_school_uid": "school_uid", "p4_campus_uid": "campus_uid", "p4_dept_uid": "dept_uid"}
    actual = [alias.get(c, c) for c in key_cols]
    exists = all(c in df.columns for c in actual)
    return actual, exists


def range_audit(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for col in df.columns:
        s = df[col]
        text = str(col).lower()
        if pd.api.types.is_numeric_dtype(s):
            num = pd.to_numeric(s, errors="coerce").astype("float64")
            rows.append({
                "column": col, "check": "numeric_basic", "nan_n": int(num.isna().sum()),
                "pos_inf_n": int(np.isposinf(num).sum()), "neg_inf_n": int(np.isneginf(num).sum()),
                "negative_n": int((num < 0).sum()), "zero_n": int((num == 0).sum()), "violation_n": 0,
            })
            if text.endswith("_pct"):
                bad = int(((num < 0) | (num > 100)).sum())
                rows.append({"column": col, "check": "pct_0_100", "violation_n": bad})
            if text.endswith("_prop"):
                bad = int(((num < 0) | (num > 1)).sum())
                rows.append({"column": col, "check": "prop_0_1", "violation_n": bad})
            if text.endswith("_n") or text.endswith("count"):
                bad = int((num < 0).sum())
                rows.append({"column": col, "check": "count_nonnegative", "violation_n": bad})
            if "year" in text:
                bad = int(((num < 1900) | (num > 2100)).sum())
                rows.append({"column": col, "check": "year_reasonable_1900_2100", "violation_n": bad})
        elif text.endswith("_flag"):
            allowed = {True, False, 0, 1, "0", "1", "True", "False", "true", "false", np.nan, None, pd.NA}
            non_na = s.dropna().astype(str).str.lower()
            bad = int((~non_na.isin(["true", "false", "0", "1"])).sum())
            rows.append({"column": col, "check": "flag_boolean_or_01", "violation_n": bad})
    return pd.DataFrame(rows)


def inspect_dataset(label, path, expected_shape=None, expected_sha256=None, candidate_keys=None):
    candidate_keys = candidate_keys or []
    abs_path = (PROJECT_ROOT / path).resolve() if not Path(path).is_absolute() else Path(path).resolve()
    warnings = []
    status = "PASS"
    display(Markdown(f"### 5.1 File Identification - `{label}`"))
    exists = abs_path.exists()
    actual_sha = sha256_file(abs_path) if exists else None
    hash_match = (actual_sha == expected_sha256) if expected_sha256 else None
    file_info = pd.DataFrame([{
        "label": label,
        "absolute_path": str(abs_path),
        "relative_path": rel(abs_path),
        "exists": exists,
        "file_extension": abs_path.suffix.lower(),
        "file_size": abs_path.stat().st_size if exists else np.nan,
        "mtime": datetime.fromtimestamp(abs_path.stat().st_mtime).isoformat() if exists else np.nan,
        "actual_SHA256": actual_sha,
        "expected_SHA256": expected_sha256,
        "hash_match": hash_match,
    }])
    display(file_info)
    if not exists:
        status = "FAIL_LOAD"
        warnings.append("file does not exist")
        result = {"label": label, "path": rel(abs_path), "actual_shape": None, "expected_shape": expected_shape, "shape_match": False, "actual_sha256": actual_sha, "expected_sha256": expected_sha256, "hash_match": hash_match, "status": status, "warning_n": len(warnings), "warnings": warnings}
        DATASET_RESULTS.append(result)
        return result
    if expected_sha256 and not hash_match:
        status = "FAIL_HASH"
        warnings.append("SHA256 mismatch")

    try:
        df, load_meta = load_dataset(abs_path)
    except Exception as exc:
        status = "FAIL_LOAD"
        warnings.append(f"load error: {type(exc).__name__}: {exc}")
        result = {"label": label, "path": rel(abs_path), "actual_shape": None, "expected_shape": expected_shape, "shape_match": False, "actual_sha256": actual_sha, "expected_sha256": expected_sha256, "hash_match": hash_match, "status": status, "warning_n": len(warnings), "warnings": warnings}
        DATASET_RESULTS.append(result)
        raise

    if abs_path.suffix.lower() == ".json":
        display(Markdown("### JSON raw structure and flattened table"))
        display(Markdown("JSON structure summary"))
        print(json.dumps(load_meta.get("json_structure"), ensure_ascii=False, indent=2, default=str))
        display(Markdown("JSON raw preview"))
        print(load_meta.get("json_raw_preview"))
        display(Markdown("Flattened table preview"))
        display(df.head(30))

    actual_shape = tuple(df.shape)
    shape_match = (actual_shape == tuple(expected_shape)) if expected_shape else None
    if expected_shape and not shape_match and status == "PASS":
        status = "FAIL_SHAPE"
        warnings.append("shape mismatch")

    display(Markdown("### 5.2 Basic Structure"))
    dup_df_for_basic = make_hashable_frame(df)
    basic_rows = [{
        "shape": actual_shape,
        "expected_shape": expected_shape,
        "shape_match": shape_match,
        "row_count": len(df),
        "column_count": df.shape[1],
        "memory_usage_bytes": int(df.memory_usage(deep=True).sum()),
        "index_dtype": str(df.index.dtype),
        "index_unique": bool(df.index.is_unique),
        "exact_duplicate_row_count": int(dup_df_for_basic.duplicated().sum()),
        "loader": load_meta.get("loader"),
        "encoding": load_meta.get("encoding"),
        "json_raw_type": load_meta.get("json_raw_type"),
        "json_top_level_keys": load_meta.get("json_top_level_keys"),
    }]
    display(pd.DataFrame(basic_rows))

    key_summary_rows = []
    key_dup_frames = []
    for key_cols in candidate_keys:
        actual_key, exists_key = resolve_candidate_key(df, key_cols)
        if exists_key:
            null_key_n = int(df[actual_key].isna().any(axis=1).sum())
            key_frame = make_hashable_frame(df[actual_key])
            dup_mask = key_frame.duplicated(keep=False)
            dup_row_n = int(dup_mask.sum())
            dup_group_n = int(key_frame.loc[dup_mask].drop_duplicates().shape[0]) if dup_row_n else 0
            unique_key_n = int(key_frame.drop_duplicates().shape[0])
            if dup_row_n:
                key_dup_frames.append(df.loc[dup_mask].head(30).copy())
        else:
            null_key_n = dup_row_n = dup_group_n = unique_key_n = np.nan
        key_summary_rows.append({
            "candidate_key_requested": " + ".join(key_cols),
            "candidate_key_actual": " + ".join(actual_key),
            "exists": exists_key,
            "null_key_rows": null_key_n,
            "duplicate_key_rows": dup_row_n,
            "duplicate_key_groups": dup_group_n,
            "unique_key_count": unique_key_n,
        })
        if exists_key and (null_key_n or dup_row_n):
            if status == "PASS":
                status = "PASS_WITH_WARNINGS"
            warnings.append(f"key issue {actual_key}: null={null_key_n}, duplicate_rows={dup_row_n}")
    key_summary = pd.DataFrame(key_summary_rows)
    if not key_summary.empty:
        display(Markdown("#### Candidate Key Check"))
        display(key_summary)

    display(Markdown("### 5.3 Full Column List"))
    column_profile = build_column_profile(df)
    display(column_profile)

    display(Markdown("### 5.4 df.info()"))
    print(capture_df_info(df))

    display(Markdown("### 5.5 Head"))
    display(df.head(HEAD_N))

    display(Markdown("### 5.6 Tail"))
    display(df.tail(TAIL_N))

    display(Markdown("### 5.7 Random Sample"))
    if len(df):
        display(df.sample(n=min(RANDOM_N, len(df)), random_state=RANDOM_STATE))
    else:
        display(Markdown("Empty dataset; no random sample."))

    display(Markdown("### 5.8 Numeric Describe"))
    numeric_desc = build_numeric_describe(df)
    display(numeric_desc if not numeric_desc.empty else pd.DataFrame({"message": ["No numeric columns"]}))

    display(Markdown("### 5.8 Categorical/String/Boolean Describe"))
    categorical_desc = build_categorical_describe(df)
    display(categorical_desc if not categorical_desc.empty else pd.DataFrame({"message": ["No categorical/string/boolean columns"]}))

    display(Markdown("### 5.8 Datetime Describe"))
    datetime_desc = build_datetime_describe(df)
    display(datetime_desc if not datetime_desc.empty else pd.DataFrame({"message": ["No datetime columns"]}))

    display(Markdown("### 5.9 Top Missing Columns"))
    top_missing = column_profile[column_profile["missing_n"] > 0].sort_values(["missing_pct", "missing_n"], ascending=False).head(TOP_MISSING_N).copy()
    top_missing.insert(0, "rank", range(1, len(top_missing) + 1))
    if top_missing.empty:
        display(Markdown("No missing values"))
    else:
        display(top_missing[["rank", "column", "dtype", "missing_n", "missing_pct", "non_null_n", "nunique"]])

    display(Markdown("### 5.10 Top Cardinality Columns"))
    display(column_profile.sort_values(["nunique", "unique_ratio"], ascending=False).head(TOP_CARDINALITY_N)[["column", "dtype", "nunique", "unique_ratio"]])

    display(Markdown("### 5.11 All-null / Constant / Near-constant Columns"))
    all_null = column_profile[column_profile["is_all_null"]].copy()
    constant = column_profile[column_profile["is_constant"]].copy()
    near_constant = column_profile[(column_profile["top_value_share"] >= 0.99) & (~column_profile["is_constant"])].copy()
    display(Markdown("All-null columns"))
    display(all_null[["column", "dtype", "missing_n", "missing_pct"]] if not all_null.empty else pd.DataFrame({"message": ["None"]}))
    display(Markdown("Constant columns"))
    display(constant[["column", "dtype", "nunique", "top_value_share"]] if not constant.empty else pd.DataFrame({"message": ["None"]}))
    display(Markdown("Near-constant columns"))
    display(near_constant[["column", "dtype", "nunique", "top_value_share"]] if not near_constant.empty else pd.DataFrame({"message": ["None"]}))
    if not all_null.empty:
        warnings.append(f"all-null columns: {len(all_null)}")
    if not constant.empty:
        warnings.append(f"constant columns: {len(constant)}")
    if not near_constant.empty:
        warnings.append(f"near-constant columns: {len(near_constant)}")

    display(Markdown("### 5.12 Duplicate Check"))
    dup_df = make_hashable_frame(df)
    exact_dup_mask = dup_df.duplicated(keep=False)
    exact_dup_count = int(dup_df.duplicated().sum())
    exact_dup_group_count = int(dup_df.loc[exact_dup_mask].drop_duplicates().shape[0]) if exact_dup_mask.any() else 0
    key_dup_count = int(pd.to_numeric(key_summary.get("duplicate_key_rows", pd.Series(dtype=float)), errors="coerce").fillna(0).sum()) if not key_summary.empty else 0
    key_dup_group_count = int(pd.to_numeric(key_summary.get("duplicate_key_groups", pd.Series(dtype=float)), errors="coerce").fillna(0).sum()) if not key_summary.empty else 0
    duplicate_summary = pd.DataFrame([{
        "exact_duplicate_row_count": exact_dup_count,
        "exact_duplicate_group_count": exact_dup_group_count,
        "candidate_key_duplicate_row_count": key_dup_count,
        "candidate_key_duplicate_group_count": key_dup_group_count,
    }])
    display(duplicate_summary)
    duplicate_rows = pd.concat(([df.loc[exact_dup_mask].head(30)] if exact_dup_mask.any() else []) + key_dup_frames, ignore_index=True) if (exact_dup_mask.any() or key_dup_frames) else pd.DataFrame()
    display(duplicate_rows if not duplicate_rows.empty else pd.DataFrame({"message": ["No duplicate rows to display"]}))
    if exact_dup_count or key_dup_count:
        warnings.append(f"duplicates: exact={exact_dup_count}, key={key_dup_count}")

    display(Markdown("### 5.13 Range and Basic Outlier Checks"))
    range_df = range_audit(df)
    display(range_df if not range_df.empty else pd.DataFrame({"message": ["No numeric/range checks applicable"]}))
    violations = range_df[pd.to_numeric(range_df.get("violation_n", 0), errors="coerce").fillna(0) > 0].copy() if not range_df.empty else pd.DataFrame()
    display(Markdown("Range violations"))
    display(violations if not violations.empty else pd.DataFrame({"message": ["No range violations"]}))
    if not violations.empty:
        warnings.append(f"range violations: {len(violations)}")

    duplicate_save = duplicate_rows.copy()
    save_profile_outputs(label, column_profile, numeric_desc, categorical_desc, top_missing, duplicate_save)

    for _, row in all_null.iterrows():
        ANOMALY_ROWS.append({"dataset": label, "anomaly_type": "all-null", "column": row["column"], "detail": f"missing_n={row['missing_n']}"})
    for _, row in constant.iterrows():
        ANOMALY_ROWS.append({"dataset": label, "anomaly_type": "constant", "column": row["column"], "detail": f"nunique={row['nunique']}"})
    for _, row in near_constant.iterrows():
        ANOMALY_ROWS.append({"dataset": label, "anomaly_type": "near-constant", "column": row["column"], "detail": f"top_value_share={row['top_value_share']:.6f}"})
    for _, row in violations.iterrows():
        ANOMALY_ROWS.append({"dataset": label, "anomaly_type": "range violation", "column": row["column"], "detail": f"{row['check']} violations={row['violation_n']}"})
    if key_dup_count:
        ANOMALY_ROWS.append({"dataset": label, "anomaly_type": "duplicate key", "column": "", "detail": f"duplicate_key_rows={key_dup_count}"})
    if expected_sha256 and not hash_match:
        ANOMALY_ROWS.append({"dataset": label, "anomaly_type": "hash mismatch", "column": "", "detail": f"actual={actual_sha} expected={expected_sha256}"})
    if expected_shape and not shape_match:
        ANOMALY_ROWS.append({"dataset": label, "anomaly_type": "shape mismatch", "column": "", "detail": f"actual={actual_shape} expected={expected_shape}"})

    if status == "PASS" and warnings:
        status = "PASS_WITH_WARNINGS"
    result = {
        "label": label,
        "path": rel(abs_path),
        "actual_shape": actual_shape,
        "expected_shape": expected_shape,
        "shape_match": shape_match,
        "actual_sha256": actual_sha,
        "expected_sha256": expected_sha256,
        "hash_match": hash_match,
        "status": status,
        "warning_n": len(warnings),
        "warnings": warnings,
        "column_profile_path": rel(PROFILE_DIR / f"{safe_label(label)}__column_profile.csv"),
    }
    DATASET_RESULTS.append(result)
    display(Markdown("### 5.14 Cell Final Status"))
    print("DATASET_STATUS:")
    print(status)
    print("WARNINGS:")
    for warning in warnings:
        print("-", warning)
    if not warnings:
        print("- none")
    return result


def load_by_rel(path: str):
    return load_dataset(PROJECT_ROOT / path)[0]


def extra_d08():
    df = pd.read_parquet(PROJECT_ROOT / "workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet")
    membership = pd.read_parquet(OUT_ROOT / "data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet")
    display(Markdown("### 6.1 D08 Additional Checks"))
    display(Markdown("analysis_year distribution"))
    display(df["analysis_year"].value_counts(dropna=False).rename_axis("analysis_year").reset_index(name="rows"))
    display(Markdown("split distribution via final membership merge"))
    split = df[["outcome_row_id"]].merge(membership[["outcome_row_id", "split"]], on="outcome_row_id", how="left", validate="one_to_one")
    display(split["split"].value_counts(dropna=False).rename_axis("split").reset_index(name="rows"))
    display(Markdown("major_group_7 distribution"))
    display(df["major_group_7"].value_counts(dropna=False).rename_axis("major_group_7").reset_index(name="rows"))
    display(pd.DataFrame([{"school_n": df["school_uid"].nunique(), "campus_n": df["campus_uid"].nunique(), "outcome_row_id_unique_n": df["outcome_row_id"].nunique()}]))
    target_cols = ["a_rate_pct", "health_employment_rate_pct", "graduate_school_progression_rate_pct"]
    display(Markdown("Target describe"))
    display(df[target_cols].describe(percentiles=[.01,.05,.1,.25,.5,.75,.9,.95,.99]).T)
    display(Markdown("Structure match status distribution"))
    for col in ["match_status", "match_method", "row_qa_status"]:
        if col in df:
            display(Markdown(col))
            display(df[col].value_counts(dropna=False).rename_axis(col).reset_index(name="rows"))
    display(Markdown("major7 mapping status distribution"))
    for col in ["major7_mapping_method", "major7_mapping_confidence", "has_major_group_7_high_medium"]:
        if col in df:
            display(Markdown(col))
            display(df[col].value_counts(dropna=False).rename_axis(col).reset_index(name="rows"))
    display(Markdown("Target missing"))
    missing_cols = ["a_rate_pct", "health_employment_rate_pct", "graduate_school_progression_rate_pct", "selectivity_proxy_pct"]
    display(pd.DataFrame([{"column": c, "missing_n": int(df[c].isna().sum()), "missing_pct": float(df[c].isna().mean()*100)} for c in missing_cols]))


def extra_membership():
    df = pd.read_parquet(OUT_ROOT / "data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet")
    d08 = pd.read_parquet(PROJECT_ROOT / "workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet")
    display(Markdown("### 6.2 Sample Membership Additional Checks"))
    rows = []
    for col in [c for c in df.columns if c.startswith("sample_")]:
        s = df[col]
        rows.append({"flag": col, "true_n": int((s == True).sum()), "false_n": int((s == False).sum()), "na_n": int(s.isna().sum())})
    display(pd.DataFrame(rows))
    merged = d08[["outcome_row_id"]].merge(df[["outcome_row_id"]], on="outcome_row_id", how="outer", indicator=True, validate="one_to_one")
    display(merged["_merge"].value_counts(dropna=False).rename_axis("merge_status").reset_index(name="rows"))


def extra_sample_registry():
    reg = pd.read_csv(OUT_ROOT / "artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv", low_memory=False)
    mem = pd.read_parquet(OUT_ROOT / "data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet")
    display(Markdown("### 6.3 Sample Registry Recalculation"))
    rows = []
    for _, r in reg.iterrows():
        sample_id = r["sample_id"]
        col = f"sample_{sample_id}"
        mask = mem[col].fillna(False).astype(bool)
        sub = mem[mask]
        rows.append({
            "sample_id": sample_id,
            "registry_row_n": r["row_n"], "actual_row_n": int(mask.sum()), "diff_row_n": int(mask.sum()) - int(r["row_n"]),
            "registry_school_n": r["school_n"], "actual_school_n": int(sub["school_uid"].nunique()), "diff_school_n": int(sub["school_uid"].nunique()) - int(r["school_n"]),
            "registry_train_n": r["train_n"], "actual_train_n": int(sub["split"].eq("train").sum()),
            "registry_validation_n": r["validation_n"], "actual_validation_n": int(sub["split"].eq("val").sum()),
            "registry_test_n": r["test_n"], "actual_test_n": int(sub["split"].eq("test").sum()),
        })
    display(pd.DataFrame(rows))


def extra_column_registry():
    df = pd.read_csv(OUT_ROOT / "artifacts/department_model_column_registry_v4.csv", low_memory=False)
    display(Markdown("### 6.4 Column Registry Additional Checks"))
    for col in ["semantic_role", "feature_block", "measurement_level", "dtype_actual", "model_default_active", "review_required"]:
        display(Markdown(col))
        display(df[col].value_counts(dropna=False).rename_axis(col).reset_index(name="rows"))
    checks = pd.DataFrame([{
        "OTHER_count": int(df["feature_block"].eq("OTHER").sum()),
        "feature_block_missing": int(df["feature_block"].isna().sum()),
        "dtype_missing": int(df["dtype_actual"].isna().sum()),
        "source_missing": int(df["source_dataset"].isna().sum()),
        "duplicate_column_rows": int(df.duplicated(["column"]).sum()),
    }])
    display(checks)


def extra_feature_set():
    df = pd.read_csv(OUT_ROOT / "artifacts/P4_PHASE_FEATURE_SET_FINAL.csv", low_memory=False)
    colreg = pd.read_csv(OUT_ROOT / "artifacts/department_model_column_registry_v4.csv", low_memory=False)
    display(Markdown("### 6.5 Feature Set Additional Checks"))
    display(df.groupby(["model_id", "target"], dropna=False).agg(feature_count=("feature", "nunique"), allowed_count=("included_in_contract", "sum")).reset_index())
    display(Markdown("Block count by model"))
    display(df.groupby(["model_id", "feature_block"], dropna=False).size().reset_index(name="feature_n"))
    merged = df.merge(colreg[["column", "feature_block", "is_identifier", "is_quality_metadata"]], left_on="feature", right_on="column", how="left", suffixes=("", "_registry"))
    bad = merged[(merged["is_identifier"].fillna(False)) | (merged["is_quality_metadata"].fillna(False)) | merged["feature"].astype(str).str.contains("name|raw|uid|row_id", case=False, regex=True)]
    display(Markdown("Active feature ID/name/QUALITY leakage check"))
    display(bad if not bad.empty else pd.DataFrame({"message": ["No ID/name/QUALITY feature in active feature set"]}))


def extra_model_spec():
    df = pd.read_csv(OUT_ROOT / "artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv", low_memory=False)
    display(Markdown("### 6.6 Model Specification Additional Checks"))
    display(df[["model_id", "sample_id", "target", "allowed_blocks", "feature_count", "status"]])
    display(pd.pivot_table(df, index=["phase", "target"], columns="status", values="model_id", aggfunc="count", fill_value=0).reset_index())


def extra_rank():
    df = pd.read_csv(OUT_ROOT / "qa/P4_PHASE_DESIGN_MATRIX_RANK.csv", low_memory=False)
    display(Markdown("### 6.7 Rank Additional Checks"))
    display(Markdown("rank_deficiency > 0"))
    display(df[pd.to_numeric(df["rank_deficiency"], errors="coerce").fillna(0) > 0])
    display(Markdown("condition_number > 30"))
    display(df[pd.to_numeric(df["condition_number"], errors="coerce").fillna(0) > 30])
    display(Markdown("condition_number > 100"))
    display(df[pd.to_numeric(df["condition_number"], errors="coerce").fillna(0) > 100])


def extra_alias():
    df = pd.read_csv(OUT_ROOT / "qa/P4_LINEAR_ALIAS_GROUPS.csv", low_memory=False)
    display(Markdown("### 6.7 Alias Additional Checks"))
    display(df.groupby(["model_id", "coding", "alias_type"], dropna=False).size().reset_index(name="alias_group_n"))
    display(df[["model_id", "coding", "group_id", "encoded_features", "recommended_exclusion"]].head(80))


def extra_vif():
    df = pd.read_csv(OUT_ROOT / "qa/P4_VIF_TOP30_BY_PHASE.csv", low_memory=False)
    display(Markdown("### 6.7 VIF Additional Checks"))
    bins = []
    for v in df["vif"]:
        if np.isinf(v):
            bins.append("inf")
        elif v < 5:
            bins.append("VIF < 5")
        elif v < 10:
            bins.append("5 <= VIF < 10")
        else:
            bins.append("VIF >= 10")
    df = df.assign(vif_bucket=bins)
    display(df.groupby(["model_id", "vif_bucket"], dropna=False).size().reset_index(name="feature_n"))
    display(df.sort_values(["model_id", "rank"]).groupby("model_id").head(5))


def extra_target_profile():
    df = pd.read_csv(OUT_ROOT / "profiles/P4_TARGET_PROFILE_BY_PHASE.csv", low_memory=False)
    display(Markdown("### 6.8 Target Profile Additional Checks"))
    overall = df[df["row_type"].eq("overall")].copy()
    display(overall[["sample_id", "target", "N", "zero_ratio", "hundred_ratio", "skewness", "school_icc"]])
    display(Markdown("High zero_ratio"))
    display(overall.sort_values("zero_ratio", ascending=False).head(20))
    display(Markdown("High hundred_ratio"))
    display(overall.sort_values("hundred_ratio", ascending=False).head(20))
    display(Markdown("High absolute skewness"))
    display(overall.assign(abs_skewness=overall["skewness"].abs()).sort_values("abs_skewness", ascending=False).head(20))


def extra_nested():
    df = pd.read_csv(OUT_ROOT / "qa/P3_NESTED_CROSSFIT_SMOKE.csv", low_memory=False)
    mem = pd.read_parquet(OUT_ROOT / "data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet")
    total = int(mem["sample_P3_STRUCTURE_READY"].fillna(False).astype(bool).sum())
    display(Markdown("### 6.9 Nested Crossfit Smoke Additional Checks"))
    row = df.iloc[0].to_dict()
    table = pd.DataFrame([{
        "outer_train_N": total - int(row["prediction_n"]),
        "outer_validation_N": int(row["prediction_n"]),
        "train_school_N": int(row["outer_train_schools"]),
        "validation_school_N": int(row["outer_validation_schools"]),
        "selected_alpha": row["selected_alpha"],
        "alpha_grid": "0.1|1.0|10.0|100.0",
        "selected_alpha_is_grid_max": float(row["selected_alpha"]) == 100.0,
        "prediction_N": int(row["prediction_n"]),
        "NaN_prediction_N": int(row["nan_prediction_n"]),
        "encoded_feature_N": int(row["encoded_dimensions"]),
    }])
    display(table)


def extra_bootstrap():
    df = pd.read_csv(OUT_ROOT / "qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv", low_memory=False)
    display(Markdown("### 6.10 Bootstrap Smoke Additional Checks"))
    out = df.assign(
        P3_success=df["p3_crossfit_nan_n"].eq(0),
        P4_E_success=df["p4_e_fit_n"].gt(0),
        P4_P_success=df["p4_p_fit_n"].gt(0),
        stored_metric=df["p4_e_rmse_in_boot_smoke"].astype(str) + " | " + df["p4_p_rmse_in_boot_smoke"].astype(str),
    )
    display(out[["iteration", "school_resample_n", "P3_success", "P4_E_success", "P4_P_success", "stored_metric"]])


def extra_final_json():
    path = OUT_ROOT / "reports/P4_FINAL_MODELING_READINESS.json"
    obj = json.loads(path.read_text(encoding="utf-8"))
    display(Markdown("### 6.11 Final Readiness JSON Key-Value Table"))
    display(pd.DataFrame({"key": list(obj.keys()), "value": [json.dumps(v, ensure_ascii=False) if isinstance(v, (list, dict)) else v for v in obj.values()]}))


def extra_bundle_manifest():
    path = OUT_ROOT / "P4_MODELING_REVIEW_BUNDLE_MANIFEST.json"
    obj = json.loads(path.read_text(encoding="utf-8"))
    display(Markdown("### 6.12 Review Bundle Manifest Files"))
    files = pd.json_normalize(obj.get("files", []))
    cols = [c for c in ["label", "relative_path", "shape", "size_bytes", "sha256", "mtime"] if c in files.columns]
    display(files[cols])

## Dataset: `mart_department_model_base_2024`

- 역할: 2024 modeling single source of truth D08
- 경로: `workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet`
- 예상 shape: `(10242, 151)`
- 예상 SHA256: `598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962`

In [ ]:
result = inspect_dataset(
    label='mart_department_model_base_2024',
    path='workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet',
    expected_shape=(10242, 151),
    expected_sha256='598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962',
    candidate_keys=[['outcome_row_id'], ['analysis_year', 'p4_school_uid', 'p4_campus_uid', 'p4_dept_uid', 'outcome_row_id']],
)

extra_d08()

### 5.1 File Identification - `mart_department_model_base_2024`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,mart_department_model_base_2024,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024...,workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet,True,.parquet,2103297,2026-07-12T21:47:51.507501,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962,True

### 5.2 Basic Structure

          shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count           loader encoding json_raw_type json_top_level_keys
0  (10242, 151)   (10242, 151)         True      10242           151            16773447       int64          True                          0  pd.read_parquet     None          None                None

#### Candidate Key Check

                                                        candidate_key_requested                                                 candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0                                                                outcome_row_id                                                       outcome_row_id    True              0                   0                     0             10242
1  analysis_year + p4_school_uid + p4_campus_uid + p4_dept_uid + outcome_row_id  analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id    True              0                   0                     0             10242

### 5.3 Full Column List

     position                                   column     dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0           1                            analysis_year     Int16       10242          0     0.000000        1      0.000098        False         True                    False         1.000000
1           2                           outcome_row_id       str       10242          0     0.000000    10242      1.000000        False        False                     True         0.000098
2           3                          school_name_raw    string       10242          0     0.000000      227      0.022164        False        False                     True         0.015427
3           4                     school_name_base_raw    string       10242          0     0.000000      200      0.019527        False        False                     True         0.021187
4           5                          school_name_std    string       10242          0     0.000000      200      0.019527        False        False                     True         0.021187
5           6                        campus_name_raw_x    string       10242          0     0.000000       12      0.001172        False        False                     True         0.913201
6           7                               campus_seq    string       10242          0     0.000000        4      0.000391        False        False                    False         0.949912
7           8                            campus_branch    string       10242          0     0.000000        2      0.000195        False        False                    False         0.968658
8           9                        campus_name_std_x    string       10242          0     0.000000        5      0.000488        False        False                     True         0.918571
9          10                            dept_name_raw    string       10242          0     0.000000     4946      0.482913        False        False                     True         0.010350
10         11                            dept_name_std    string       10242          0     0.000000     4890      0.477446        False        False                     True         0.010350
11         12                           dept_field_raw    string       10242          0     0.000000     4195      0.409588        False        False                     True         0.011716
12         13                           dept_field_std    string       10242          0     0.000000     4119      0.402168        False        False                    False         0.011716
13         14                      credit_forfeit_flag   boolean       10242          0     0.000000        2      0.000195        False        False                    False         0.887815
14         15                    selectivity_proxy_pct   Float32        3737       6505    63.512986     1609      0.430559        False        False                    False         0.635130
15         16                               a_rate_pct   Float32       10242          0     0.000000     9203      0.898555        False        False                    False         0.031146
16         17                              cd_rate_pct   Float32       10242          0     0.000000     8975      0.876294        False        False                    False         0.046378
17         18                               f_rate_pct   Float32       10242          0     0.000000     7453      0.727690        False        False                    False         0.176528
18         19                      employment_rate_pct   Float32        7477       2765    26.996680     1135      0.151799        False        False                    False         0.269967
19         20               health_employment_rate_pct   Float32        7477       2765    26.996680     1196      0.159957        False        False                    False         0.269967
20         21                     progression_rate_pct   Float32        7587       2655    25.922671      971      0.127982        False        False                    False         0.302480
21         22  vocational_college_progression_rate_pct   Float32        7587       2655    25.922671      120      0.015817        False        False                    False         0.716559
22         23          university_progression_rate_pct   Float32        7587       2655    25.922671      182      0.023988        False        False                    False         0.690978
23         24     graduate_school_progression_rate_pct   Float32        7587       2655    25.922671      946      0.124687        False        False                    False         0.326401
24         25            domestic_progression_rate_pct   Float32        7587       2655    25.922671      965      0.127191        False        False                    False         0.304530
25         26            overseas_progression_rate_pct   Float32        7587       2655    25.922671      107      0.014103        False        False                    False         0.723101
26         27                          has_selectivity   boolean       10242          0     0.000000        2      0.000195        False        False                    False         0.635130
27         28                           has_employment   boolean       10242          0     0.000000        2      0.000195        False        False                    False         0.730033
28         29                          has_progression   boolean       10242          0     0.000000        2      0.000195        False        False                    False         0.740773
29         30                            rate_range_qa  category       10242          0     0.000000        1      0.000098        False         True                    False         1.000000
30         31                              source_file       str       10242          0     0.000000        1      0.000098        False         True                     True         1.000000
31         32                            source_sha256       str       10242          0     0.000000        1      0.000098        False         True                     True         1.000000
32         33                        campus_region_raw    string       10242          0     0.000000        9      0.000879        False        False                     True         0.961140
33         34                         dept_norm_strict    string       10242          0     0.000000     4890      0.477446        False        False                    False         0.010350
34         35                 dept_norm_suffix_reduced    string       10242          0     0.000000     4391      0.428725        False        False                    False         0.010545
35         36                     dept_token_signature    string       10242          0     0.000000     4391      0.428725        False        False                    False         0.010545
36         37                             school_uid_x    string       10242          0     0.000000      200      0.019527        False        False                     True         0.021187
37         38                         headcount_row_id       str        8561       1681    16.412810     8547      0.998365        False        False                     True         0.164128
38         39                              match_stage       str       10242          0     0.000000        4      0.000391        False        False                    False         0.835384
39         40                             match_method       str       10242          0     0.000000        4      0.000391        False        False                    False         0.835384
40         41                             match_status       str       10242          0     0.000000        3      0.000293        False        False                    False         0.835872
41         42                              match_score   float64        9877        365     3.563757        1      0.000101        False         True                    False         0.964362
42         43                          candidate_count     Int16       10242          0     0.000000       42      0.004101        False        False                     True         0.901484
43         44                            review_needed   boolean       10242          0     0.000000        2      0.000195        False        False                    False         0.835872
44         45                         unmatched_reason       str       10242          0     0.000000        6      0.000586        False        False                    False         0.835872
45         46                           match_evidence       str       10242          0     0.000000        8      0.000781        False        False                     True         0.835384
46         47              candidate_headcount_row_ids       str       10242          0     0.000000     9899      0.966510        False        False                     True         0.017184
47         48                        candidate_preview       str       10242          0     0.000000     4907      0.479106        False        False                     True         0.017184
48         49                     campus_conflict_flag      bool       10242          0     0.000000        2      0.000195        False        False                    False         0.976958
49         50              degree_course_conflict_flag      bool       10242          0     0.000000        1      0.000098        False         True                    False         1.000000
50         51                      major_conflict_flag      bool       10242          0     0.000000        1      0.000098        False         True                    False         1.000000
51         52         forbidden_modifier_conflict_flag      bool       10242          0     0.000000        1      0.000098        False         True                     True         1.000000
52         53                     headcount_match_flag      bool       10242          0     0.000000        2      0.000195        False        False                    False         0.835872
53         54                  headcount_grain_version       str        8561       1681    16.412810        1      0.000117        False         True                    False         0.835872
54         55                      headcount_grain_uid    string        8561       1681    16.412810     8547      0.998365        False        False                     True         0.164128
55         56                  grain_resolution_method       str        8561       1681    16.412810        1      0.000117        False         True                    False         0.835872
56         57                      grain_review_needed   boolean        8561       1681    16.412810        1      0.000117        False         True                    False         0.835872
57         58                          raw_row_lineage    string        8561       1681    16.412810     8547      0.998365        False        False                     True         0.164128
58         59                             school_uid_y    string        8561       1681    16.412810      198      0.023128        False        False                     True         0.164128
59         60                               campus_uid    string       10242          0     0.000000      452      0.044132        False        False                     True         0.012790
60         61                                 dept_uid    string       10242          0     0.000000    10222      0.998047        False        False                     True         0.000195
61         62                           kedi_dept_code    string        8561       1681    16.412810     3929      0.458942        False        False                    False         0.164128
62         63                              school_type    string        8561       1681    16.412810        5      0.000584        False        False                    False         0.812732
63         64                            degree_course    string        8561       1681    16.412810        1      0.000117        False         True                    False         0.835872
64         65                        school_status_raw    string        8561       1681    16.412810        3      0.000350        False        False                     True         0.814782
65         66                          day_evening_raw    string        8561       1681    16.412810        4      0.000467        False        False                     True         0.427065
66         67                        campus_name_raw_y    string        8561       1681    16.412810        5      0.000584        False        False                     True         0.734915
67         68                        campus_name_std_y    string        8561       1681    16.412810        5      0.000584        False        False                     True         0.734915
68         69                              region_sido    string        8561       1681    16.412810       17      0.001986        False        False                     True         0.164128
69         70                           region_sigungu    string        8561       1681    16.412810      120      0.014017        False        False                    False         0.164128
70         71                       hc_major_group_raw    string        8561       1681    16.412810        7      0.000818        False        False                     True         0.215973
71         72                         hc_major_group_7    string        8561       1681    16.412810        7      0.000818        False        False                    False         0.215973
72         73                        field_middle_name    string        8561       1681    16.412810       35      0.004088        False        False                     True         0.164128
73         74                         field_small_name    string        8561       1681    16.412810      121      0.014134        False        False                     True         0.164128
74         75                     admission_capacity_n     Int32        8561       1681    16.412810      228      0.026632        False        False                    False         0.359012
75         76                            recruitment_n     Int32        8561       1681    16.412810      256      0.029903        False        False                    False         0.322593
76         77                             applicants_n     Int32        8561       1681    16.412810     1250      0.146011        False        False                    False         0.322300
77         78                                 admits_n     Int32        8561       1681    16.412810      243      0.028385        False        False                    False         0.304042
78         79                      enrolled_students_n     Int32        8561       1681    16.412810      836      0.097652        False        False                    False         0.164128
79         80                         leave_students_n     Int32        8561       1681    16.412810      354      0.041350        False        False                    False         0.164128
80         81                              graduates_n     Int32        8561       1681    16.412810      246      0.028735        False        False                    False         0.207967
81         82                       fulltime_faculty_n     Int32        8561       1681    16.412810       95      0.011097        False        False                    False         0.264987
82         83                    nonfulltime_faculty_n     Int32        8561       1681    16.412810      108      0.012615        False        False                    False         0.255126
83         84                 international_students_n     Int32        8561       1681    16.412810      184      0.021493        False        False                    False         0.499414
84         85                        female_students_n     Int32        8561       1681    16.412810      488      0.057003        False        False                    False         0.164128
85         86                       masters_students_n     Int32        8561       1681    16.412810        1      0.000117        False         True                    False         0.835872
86         87                      doctoral_students_n     Int32        8561       1681    16.412810        1      0.000117        False         True                    False         0.835872
87         88                        competition_ratio   Float32        5257       4985    48.672134     3947      0.750808        False        False                    False         0.486721
88         89                    admission_yield_ratio   Float32        5257       4985    48.672134      842      0.160167        False        False                    False         0.486721
89         90                admit_per_applicant_ratio   Float32        5260       4982    48.642843     3926      0.746388        False        False                    False         0.486428
90         91                           leave_rate_pct   Float32        8441       1801    17.584456     4284      0.507523        False        False                    False         0.175845
91         92                 female_student_share_pct   Float32        8441       1801    17.584456     4857      0.575406        False        False                     True         0.175845
92         93          international_student_share_pct   Float32        8441       1801    17.584456     1927      0.228290        False        False                     True         0.487698
93         94                    student_faculty_ratio   Float32        6379       3863    37.717243     3288      0.515441        False        False                    False         0.377172
94         95               fulltime_faculty_share_pct   Float32        6379       3863    37.717243      613      0.096097        False        False                     True         0.377172
95         96                    log_enrolled_students   Float32        8561       1681    16.412810      836      0.097652        False        False                    False         0.164128
96         97                            log_graduates   Float32        8561       1681    16.412810      246      0.028735        False        False                    False         0.207967
97         98                               school_uid       str       10242          0     0.000000      200      0.019527        False        False                     True         0.021187
98         99                            major_group_7       str       10099        143     1.396212        7      0.000693        False        False                    False         0.257957
99        100                    major7_mapping_method       str       10242          0     0.000000        5      0.000488        False        False                    False         0.835872
100       101                major7_mapping_confidence       str       10242          0     0.000000        4      0.000391        False        False                     True         0.835872
101       102                   major7_candidate_count     int64       10242          0     0.000000        5      0.000488        False        False                     True         0.988186
102       103                     major7_review_needed      bool       10242          0     0.000000        2      0.000195        False        False                    False         0.986038

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10242 entries, 0 to 10241
Data columns (total 151 columns):
 #    Column                                   Non-Null Count  Dtype
---   ------                                   --------------  -----
 0    analysis_year                            10242 non-null  Int16
 1    outcome_row_id                           10242 non-null  str
 2    school_name_raw                          10242 non-null  string
 3    school_name_base_raw                     10242 non-null  string
 4    school_name_std                          10242 non-null  string
 5    campus_name_raw_x                        10242 non-null  string
 6    campus_seq                               10242 non-null  string
 7    campus_branch                            10242 non-null  string
 8    campus_name_std_x                        10242 non-null  string
 9    dept_name_raw                            10242 non-null  string
 10   dept_name_std                            10242 non-null  string
 11   dept_field_raw                           10242 non-null  string
 12   dept_field_std                           10242 non-null  string
 13   credit_forfeit_flag                      10242 non-null  boolean
 14   selectivity_proxy_pct                    3737 non-null   Float32
 15   a_rate_pct                               10242 non-null  Float32
 16   cd_rate_pct                              10242 non-null  Float32
 17   f_rate_pct                               10242 non-null  Float32
 18   employment_rate_pct                      7477 non-null   Float32
 19   health_employment_rate_pct               7477 non-null   Float32
 20   progression_rate_pct                     7587 non-null   Float32
 21   vocational_college_progression_rate_pct  7587 non-null   Float32
 22   university_progression_rate_pct          7587 non-null   Float32
 23   graduate_school_progression_rate_pct     7587 non-null   Float32
 24   domestic_progression_rate_pct            7587 non-null   Float32
 25   overseas_progression_rate_pct            7587 non-null   Float32
 26   has_selectivity                          10242 non-null  boolean
 27   has_employment                           10242 non-null  boolean
 28   has_progression                          10242 non-null  boolean
 29   rate_range_qa                            10242 non-null  category
 30   source_file                              10242 non-null  str
 31   source_sha256                            10242 non-null  str
 32   campus_region_raw                        10242 non-null  string
 33   dept_norm_strict                         10242 non-null  string
 34   dept_norm_suffix_reduced                 10242 non-null  string
 35   dept_token_signature                     10242 non-null  string
 36   school_uid_x                             10242 non-null  string
 37   headcount_row_id                         8561 non-null   str
 38   match_stage                              10242 non-null  str
 39   match_method                             10242 non-null  str
 40   match_status                             10242 non-null  str
 41   match_score                              9877 non-null   float64
 42   candidate_count                          10242 non-null  Int16
 43   review_needed                            10242 non-null  boolean
 44   unmatched_reason                         10242 non-null  str
 45   match_evidence                           10242 non-null  str
 46   candidate_headcount_row_ids              10242 non-null  str
 47   candidate_preview                        10242 non-null  str
 48   campus_conflict_flag                     10242 non-null  bool
 49   degree_course_conflict_flag              10242 non-null  bool
 50   major_conflict_flag                      10242 non-null  bool
 51   forbidden_modifier_conflict_flag         10242 non-null  bool
 52   headcount_match_flag                     10242 non-null  bool
 53   headcount_grain_version                  8561 non-null   str
 54   headcount_grain_uid                      8561 non-null   string
 55   grain_resolution_method                  8561 non-null   str
 56   grain_review_needed                      8561 non-null   boolean
 57   raw_row_lineage                          8561 non-null   string
 58   school_uid_y                             8561 non-null   string
 59   campus_uid                               10242 non-null  string
 60   dept_uid                                 10242 non-null  string
 61   kedi_dept_code                           8561 non-null   string
 62   school_type                              8561 non-null   string
 63   degree_course                            8561 non-null   string
 64   school_status_raw                        8561 non-null   string
 65   day_evening_raw                          8561 non-null   string
 66   campus_name_raw_y                        8561 non-null   string
 67   campus_name_std_y                        8561 non-null   string
 68   region_sido                              8561 non-null   string
 69   region_sigungu                           8561 non-null   string
 70   hc_major_group_raw                       8561 non-null   string
 71   hc_major_group_7                         8561 non-null   string
 72   field_middle_name                        8561 non-null   string
 73   field_small_name                         8561 non-null   string
 74   admission_capacity_n                     8561 non-null   Int32
 75   recruitment_n                            8561 non-null   Int32
 76   applicants_n                             8561 non-null   Int32
 77   admits_n                                 8561 non-null   Int32
 78   enrolled_students_n                      8561 non-null   Int32
 79   leave_students_n                         8561 non-null   Int32
 80   graduates_n                              8561 non-null   Int32
 81   fulltime_faculty_n                       8561 non-null   Int32
 82   nonfulltime_faculty_n                    8561 non-null   Int32
 83   international_students_n                 8561 non-null   Int32
 84   female_students_n                        8561 non-null   Int32
 85   masters_students_n                       8561 non-null   Int32
 86   doctoral_students_n                      8561 non-null   Int32
 87   competition_ratio                        5257 non-null   Float32
 88   admission_yield_ratio                    5257 non-null   Float32
 89   admit_per_applicant_ratio                5260 non-null   Float32
 90   leave_rate_pct                           8441 non-null   Float32
 91   female_student_share_pct                 8441 non-null   Float32
 92   international_student_share_pct          8441 non-null   Float32
 93   student_faculty_ratio                    6379 non-null   Float32
 94   fulltime_faculty_share_pct               6379 non-null   Float32
 95   log_enrolled_students                    8561 non-null   Float32
 96   log_graduates                            8561 non-null   Float32
 97   school_uid                               10242 non-null  str
 98   major_group_7                            10099 non-null  str
 99   major7_mapping_method                    10242 non-null  str
 100  major7_mapping_confidence                10242 non-null  str
 101  major7_candidate_count                   10242 non-null  int64
 102  major7_review_needed                     10242 non-null  bool
 103  major7_evidence                          10242 non-null  str
 104  major7_sample_exclusion_rule             10242 non-null  str
 105  has_structure_context                    10242 non-null  boolean
 106  has_major_group_7_high_medium            10242 non-null  boolean
 107  row_qa_status                            10242 non-null  str
 108  ctx24_reference_sample_n                 10099 non-null  Float32
 109  ctx24_mean_income_10kkrw                 10099 non-null  Float32
 110  ctx24_median_income_10kkrw               10099 non-null  Float32
 111  ctx24_income_300plus_pct                 10099 non-null  Float32
 112  ctx24_income_400plus_pct                 10099 non-null  Float32
 113  ctx24_large_company_pct                  10099 non-null  Float32
 114  ctx24_mid_company_pct                    10099 non-null  Float32
 115  ctx24_small_company_pct                  10099 non-null  Float32
 116  ctx24_large_mid_company_pct              10099 non-null  Float32
 117  ctx24_public_nonprofit_pct               10099 non-null  Float32
 118  ctx24_cert_rate_pct                      10099 non-null  Float32
 119  ctx24_cert_per_person                    10099 non-null  Float32
 120  ctx24_log10_mean_income                  10099 non-null  Float32
 121  ctx24_industry_top3_pct                  0 non-null      Float32
 122  ctx24_industry_hhi                       0 non-null      Float32
 123  goms_profile_start_year                  10099 non-null  Int16
 124  goms_profile_end_year                    10099 non-null  Int16
 125  goms_profile_years_n                     10099 non-null  Int16
 126  goms_aggregation_method                  10099 non-null  category
 127  goms_recent_employment_rate_pct          10099 non-null  Float32
 128  goms_recent_firm_300plus_pct             10099 non-null  Float32
 129  goms_recent_public_nonprofit_pct         10099 non-null  Float32
 130  goms_recent_permanent_pct                10099 non-null  Float32
 131  goms_recent_unstable_pct                 10099 non-null  Float32
 132  goms_recent_self_employed_pct            10099 non-null  Float32
 133  goms_recent_industry_hhi                 10099 non-null  Float32
 134  goms_recent_industry_top3_pct            10099 non-null  Float32
 135  goms_recent_professional_highskill_pct   10099 non-null  Float32
 136  goms_recent_mean_income_10kkrw           10099 non-null  Float32
 137  goms_recent_weekly_work_hours            10099 non-null  Float32
 138  goms_recent_hourly_income_proxy          10099 non-null  Float32
 139  goms_income_trend_per_year               10099 non-null  Float32
 140  goms_hours_trend_per_year                10099 non-null  Float32
 141  goms_firm_300plus_trend_per_year         10099 non-null  Float32
 142  goms_permanent_trend_per_year            10099 non-null  Float32
 143  goms_latest_2019_mean_income_10kkrw      10099 non-null  Float32
 144  goms_latest_2019_weekly_work_hours       10099 non-null  Float32
 145  goms_latest_2019_firm_300plus_pct        10099 non-null  Float32
 146  goms_latest_2019_permanent_pct           10099 non-null  Float32
 147  goms_source_years_observed               10099 non-null  Int16
 148  goms_year_over_year_review_flag          10099 non-null  boolean
 149  goms_mapping_confidence                  10099 non-null  category
 150  goms_row_qa_status                       10099 non-null  category
dtypes: Float32(57), Int16(6), Int32(13), bool(6), boolean(9), category(4), float64(1), int64(1), str(20), string(34)
memory usage: 16.0 MB

### 5.5 Head

,analysis_year,outcome_row_id,school_name_raw,school_name_base_raw,school_name_std,campus_name_raw_x,campus_seq,campus_branch,campus_name_std_x,dept_name_raw,dept_name_std,dept_field_raw,dept_field_std,credit_forfeit_flag,selectivity_proxy_pct,a_rate_pct,cd_rate_pct,f_rate_pct,employment_rate_pct,health_employment_rate_pct,progression_rate_pct,vocational_college_progression_rate_pct,university_progression_rate_pct,graduate_school_progression_rate_pct,domestic_progression_rate_pct,overseas_progression_rate_pct,has_selectivity,has_employment,has_progression,rate_range_qa,source_file,source_sha256,campus_region_raw,dept_norm_strict,dept_norm_suffix_reduced,dept_token_signature,school_uid_x,headcount_row_id,match_stage,match_method,match_status,match_score,candidate_count,review_needed,unmatched_reason,match_evidence,candidate_headcount_row_ids,candidate_preview,campus_conflict_flag,degree_course_conflict_flag,major_conflict_flag,forbidden_modifier_conflict_flag,headcount_match_flag,headcount_grain_version,headcount_grain_uid,grain_resolution_method,grain_review_needed,raw_row_lineage,school_uid_y,campus_uid,dept_uid,kedi_dept_code,school_type,degree_course,school_status_raw,day_evening_raw,campus_name_raw_y,campus_name_std_y,region_sido,region_sigungu,hc_major_group_raw,hc_major_group_7,field_middle_name,field_small_name,admission_capacity_n,recruitment_n,applicants_n,admits_n,enrolled_students_n,leave_students_n,graduates_n,fulltime_faculty_n,nonfulltime_faculty_n,international_students_n,female_students_n,masters_students_n,doctoral_students_n,competition_ratio,admission_yield_ratio,admit_per_applicant_ratio,leave_rate_pct,female_student_share_pct,international_student_share_pct,student_faculty_ratio,fulltime_faculty_share_pct,log_enrolled_students,log_graduates,school_uid,major_group_7,major7_mapping_method,major7_mapping_confidence,major7_candidate_count,major7_review_needed,major7_evidence,major7_sample_exclusion_rule,has_structure_context,has_major_group_7_high_medium,row_qa_status,ctx24_reference_sample_n,ctx24_mean_income_10kkrw,ctx24_median_income_10kkrw,ctx24_income_300plus_pct,ctx24_income_400plus_pct,ctx24_large_company_pct,ctx24_mid_company_pct,ctx24_small_company_pct,ctx24_large_mid_company_pct,ctx24_public_nonprofit_pct,ctx24_cert_rate_pct,ctx24_cert_per_person,ctx24_log10_mean_income,ctx24_industry_top3_pct,ctx24_industry_hhi,goms_profile_start_year,goms_profile_end_year,goms_profile_years_n,goms_aggregation_method,goms_recent_employment_rate_pct,goms_recent_firm_300plus_pct,goms_recent_public_nonprofit_pct,goms_recent_permanent_pct,goms_recent_unstable_pct,goms_recent_self_employed_pct,goms_recent_industry_hhi,goms_recent_industry_top3_pct,goms_recent_professional_highskill_pct,goms_recent_mean_income_10kkrw,goms_recent_weekly_work_hours,goms_recent_hourly_income_proxy,goms_income_trend_per_year,goms_hours_trend_per_year,goms_firm_300plus_trend_per_year,goms_permanent_trend_per_year,goms_latest_2019_mean_income_10kkrw,goms_latest_2019_weekly_work_hours,goms_latest_2019_firm_300plus_pct,goms_latest_2019_permanent_pct,goms_source_years_observed,goms_year_over_year_review_flag,goms_mapping_confidence,goms_row_qa_status
0,2024,OC2024_00001,가야대학교(김해),가야대학교,가야대학교,김해,,,unknown,간호학과,간호학과,간호,간호,False,4.000000,35.114052,25.497461,1.185804,74.074074,74.074074,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,김해,간호학과,간호,간호,SCH_4fcb5ca730cd,HC2_2024_07159,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_07159,간호학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_fca851c614e1,semantic_distinct_key_expansion,False,7243,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_c02dd4a5678d,U06020100004,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,경남,경남 김해시,의약계열,MED,간호,간호학,166,186,1410,184,822,103,162,20,39,0,557,0,0,7.580645,0.989247,0.130496,12.530414,67.761559,0.000000,13.932203,33.898304,6.712956,5.093750,SCH_4fcb5ca730cd,MED,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=의약계열,,True,True,ok,"41,094.000000",314.299988,282.399994,43.334793,13.206307,1.603640,0.992846,48.612938,2.596486,48.325790,25.200001,0.413953,2.497344,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,83.631943,34.586937,42.840969,88.365913,10.131062,1.171014,0.616856,85.754974,88.556969,261.694092,44.960068,1.340399,5.240109,-0.403846,-0.106593,-0.195055,271.799988,44.799999,37.200001,89.699997,3,False,medium_reviewed,PASS
1,2024,OC2024_00002,가야대학교(김해),가야대학교,가야대학교,김해,,,unknown,경영물류학과,경영물류학과,경영물류,경영물류,False,<NA>,34.833332,13.333333,12.166667,69.230766,61.538460,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,김해,경영물류학과,경영물류,경영물류,SCH_4fcb5ca730cd,HC2_2024_07147,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_07147,경영물류학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_1e1b0e646a52,semantic_distinct_key_expansion,False,7231,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_e99f4ff43785,U02010600249,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,경남,경남 김해시,사회계열,SOC,경영ㆍ경제,무역ㆍ유통학,0,0,0,0,25,5,14,4,0,10,3,0,0,<NA>,<NA>,<NA>,20.000000,12.000000,40.000000,6.250000,100.000000,3.258096,2.708050,SCH_4fcb5ca730cd,SOC,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=사회계열,,True,True,ok,"65,600.000000",300.299988,250.500000,32.472561,16.076220,11.987804,6.647866,42.675304,18.635672,32.722561,44.500000,0.796006,2.477555,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,69.609535,20.332579,31.614683,79.118462,16.265503,4.286320,0.083019,33.007038,23.923975,235.459671,42.231544,1.283551,3.110989,-0.401099,0.218681,-0.371429,234.600006,41.900002,22.700001,78.500000,3,False,medium_reviewed,PASS
2,2024,OC2024_00003,가야대학교(김해),가야대학교,가야대학교,김해,,,unknown,경찰소방학과,경찰소방학과,경찰소방,경찰소방,False,<NA>,39.507271,21.864212,1.239669,61.111111,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,김해,경찰소방학과,경찰소방,경찰소방,SCH_4fcb5ca730cd,HC2_2024_07154,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_07154,경찰소방학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_3f01aaaf0b11,semantic_distinct_key_expansion,False,7238,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_fca11c7fd249,U02030700344,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,경남,경남 김해시,사회계열,SOC,사회과학,행정학,0,0,0,0,48,12,18,3,2,0,6,0,0,<NA>,<NA>,<NA>,25.000000,12.500000,0.000000,9.600000,60.000000,3.891820,2.944439,SCH_4fcb5ca730cd,SOC,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=사회계열,,True,True,ok,"65,600.000000",300.299988,250.500000,32.472561,16.076220,11.987804,6.647866,42.675304,18.635672,32.722561,44.500000,0.796006,2.477555,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,69.609535,20.332579,31.614683,79.118462,16.265503,4.286320,0.083019,33.007038,23.923975,235.459671,42.231544,1.283551,3.110989,-0.401099,0.218681,-0.371429,234.600006,41.900002,22.700001,78.500000,3,False,medium_reviewed,PASS
3,2024,OC2024_00004,가야대학교(김해),가야대학교,가야대학교,김해,,,unknown,귀금속주얼리학과,귀금속주얼리학과,귀금속주얼리,귀금속주얼리,False,<NA>,51.785713,1.428571,5.000000,36.363636,36.363636,8.333333,0.000000,0.000000,8.333333,8.333333,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,김해,귀금속주얼리학과,귀금속주얼리,귀금속주얼리,SCH_4fcb5ca730cd,HC2_2024_07165,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_07165,귀금속주얼리학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_c66b81ecad49,semantic_distinct_key_expansion,False,7249,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_4746d0bda0b9,U07020100065,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,경남,경남 김해시,예체능계열,ART,응용예술,공예,0,0,0,0,10,0,12,3,3,0,3,0,0,<NA>,<NA>,<NA>,0.000000,30.000000,0.000000,1.666667,50.000000,2.397895,2.564949,SCH_4fcb5ca730cd,ART,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=예체능계열,,True,True,ok,"22,813.000000",234.699997,217.500000,13.426555,4.891948,8.214615,4.633323,70.788582,12.847938,15.434182,32.500000,0.523035,2.370513,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,70.644333,8.162268,16.418356,63.287960,26.055664,10.322768,0.102211,40.676308,54.354107,189.761124,39.008335,1.120742,3.236264,-0.545604,-0.190110,-0.673077,192.699997,37.599998,9.400000,63.099998,3,False,medium_reviewed,PASS
4,2024,OC2024_00005,가야대학교(김해),가야대학교,가야대학교,김해,,,unknown,물리치료학과,물리치료학과,물리치료,물리치료,False,<NA>,27.349869,32.314045,5.576489,91.071426,91.071426,1.754386,0.000000,0.000000,1.754386,1.754386,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,김해,물리치료학과,물리치료,물리치료,SCH_4fcb5ca730cd,HC2_2024_07161,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_07161,물리치료학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_abcbe1bd0237,semantic_distinct_key_expansion,False,7245,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_90eb7f613e75,U06040200001,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,경남,경남 김해시,의약계열,MED,치료ㆍ보건,재활학,53,57,492,55,315,75,57,7,2,0,75,0,0,8.631579,0.964912,0.111789,23.809525,23.809525,0.000000,35.000000,77.777779,5.755742,4.060443,SCH_4fcb5ca730cd,MED,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=의약계열,,True,True,ok,"41,094.000000",314.299988,282.399994,43.334793,13.206307,1.603640,0.992846,48.612938,2.596486,48.325790,25.200001,0.413953,2.497344,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,83.631943,34.586937,42.840969,88.365913,10.131062,1.171014,0.616856,85.754974,88.556969,261.694092,44.960068,1.340399,5.240109,-0.403846,-0.106593,-0.195055,271.799988,44.799999,37.200001,89.699997,3,False,medium_reviewed,PASS

### 5.6 Tail

,analysis_year,outcome_row_id,school_name_raw,school_name_base_raw,school_name_std,campus_name_raw_x,campus_seq,campus_branch,campus_name_std_x,dept_name_raw,dept_name_std,dept_field_raw,dept_field_std,credit_forfeit_flag,selectivity_proxy_pct,a_rate_pct,cd_rate_pct,f_rate_pct,employment_rate_pct,health_employment_rate_pct,progression_rate_pct,vocational_college_progression_rate_pct,university_progression_rate_pct,graduate_school_progression_rate_pct,domestic_progression_rate_pct,overseas_progression_rate_pct,has_selectivity,has_employment,has_progression,rate_range_qa,source_file,source_sha256,campus_region_raw,dept_norm_strict,dept_norm_suffix_reduced,dept_token_signature,school_uid_x,headcount_row_id,match_stage,match_method,match_status,match_score,candidate_count,review_needed,unmatched_reason,match_evidence,candidate_headcount_row_ids,candidate_preview,campus_conflict_flag,degree_course_conflict_flag,major_conflict_flag,forbidden_modifier_conflict_flag,headcount_match_flag,headcount_grain_version,headcount_grain_uid,grain_resolution_method,grain_review_needed,raw_row_lineage,school_uid_y,campus_uid,dept_uid,kedi_dept_code,school_type,degree_course,school_status_raw,day_evening_raw,campus_name_raw_y,campus_name_std_y,region_sido,region_sigungu,hc_major_group_raw,hc_major_group_7,field_middle_name,field_small_name,admission_capacity_n,recruitment_n,applicants_n,admits_n,enrolled_students_n,leave_students_n,graduates_n,fulltime_faculty_n,nonfulltime_faculty_n,international_students_n,female_students_n,masters_students_n,doctoral_students_n,competition_ratio,admission_yield_ratio,admit_per_applicant_ratio,leave_rate_pct,female_student_share_pct,international_student_share_pct,student_faculty_ratio,fulltime_faculty_share_pct,log_enrolled_students,log_graduates,school_uid,major_group_7,major7_mapping_method,major7_mapping_confidence,major7_candidate_count,major7_review_needed,major7_evidence,major7_sample_exclusion_rule,has_structure_context,has_major_group_7_high_medium,row_qa_status,ctx24_reference_sample_n,ctx24_mean_income_10kkrw,ctx24_median_income_10kkrw,ctx24_income_300plus_pct,ctx24_income_400plus_pct,ctx24_large_company_pct,ctx24_mid_company_pct,ctx24_small_company_pct,ctx24_large_mid_company_pct,ctx24_public_nonprofit_pct,ctx24_cert_rate_pct,ctx24_cert_per_person,ctx24_log10_mean_income,ctx24_industry_top3_pct,ctx24_industry_hhi,goms_profile_start_year,goms_profile_end_year,goms_profile_years_n,goms_aggregation_method,goms_recent_employment_rate_pct,goms_recent_firm_300plus_pct,goms_recent_public_nonprofit_pct,goms_recent_permanent_pct,goms_recent_unstable_pct,goms_recent_self_employed_pct,goms_recent_industry_hhi,goms_recent_industry_top3_pct,goms_recent_professional_highskill_pct,goms_recent_mean_income_10kkrw,goms_recent_weekly_work_hours,goms_recent_hourly_income_proxy,goms_income_trend_per_year,goms_hours_trend_per_year,goms_firm_300plus_trend_per_year,goms_permanent_trend_per_year,goms_latest_2019_mean_income_10kkrw,goms_latest_2019_weekly_work_hours,goms_latest_2019_firm_300plus_pct,goms_latest_2019_permanent_pct,goms_source_years_observed,goms_year_over_year_review_flag,goms_mapping_confidence,goms_row_qa_status
10237,2024,OC2024_10238,화성의과학대학교,화성의과학대학교,화성의과학대학교,,,,unknown,의료복지학과,의료복지학과,의료복지,의료복지,False,26.500000,27.525253,27.525253,10.101010,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,의료복지학과,의료복지,의료복지,SCH_35d77d3b6c8e,NaN,L7,manual_pending,manual_pending,1.000000,1,True,multiple_fuzzy_or_conflict,fuzzy candidates need manual review,HC2_2024_25116,의료복지학과,False,False,False,False,False,NaN,<NA>,NaN,<NA>,<NA>,<NA>,CAM_2fbc8e4c3911,DEP_0843ff8846b4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,SCH_35d77d3b6c8e,MED,keyword_rule,medium,1,False,MED:의료,,False,True,manual_match_pending,"41,094.000000",314.299988,282.399994,43.334793,13.206307,1.603640,0.992846,48.612938,2.596486,48.325790,25.200001,0.413953,2.497344,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,83.631943,34.586937,42.840969,88.365913,10.131062,1.171014,0.616856,85.754974,88.556969,261.694092,44.960068,1.340399,5.240109,-0.403846,-0.106593,-0.195055,271.799988,44.799999,37.200001,89.699997,3,False,medium_reviewed,PASS
10238,2024,OC2024_10239,화성의과학대학교,화성의과학대학교,화성의과학대학교,,,,unknown,의료심리학과,의료심리학과,의료심리,의료심리,False,49.500000,33.759468,26.231060,7.670455,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,의료심리학과,의료심리,의료심리,SCH_35d77d3b6c8e,HC2_2024_25111,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_25111,의료심리학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_f97013719617,semantic_distinct_key_expansion,False,25365,SCH_35d77d3b6c8e,CAM_f83c793bedfd,DEP_0628482f77c4,U01020300084,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,경기,경기 화성시,인문계열,HUM,인문과학,심리학,20,20,67,17,16,0,0,1,1,0,14,0,0,3.350000,0.850000,0.253731,0.000000,87.500000,0.000000,8.000000,50.000000,2.833213,0.000000,SCH_35d77d3b6c8e,HUM,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=인문계열,,True,True,ok,"18,844.000000",303.899994,250.000000,32.482487,16.769264,12.815750,6.474209,45.552959,19.289959,31.845680,41.599998,0.713118,2.482731,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,64.400627,21.097418,28.517433,73.155090,22.966125,3.649978,0.092309,40.299431,27.957674,225.948471,39.975986,1.301203,4.529670,-0.317582,0.020879,-0.471978,269.799988,39.900002,23.700001,71.599998,3,True,medium_reviewed,PASS
10239,2024,OC2024_10240,화성의과학대학교,화성의과학대학교,화성의과학대학교,,,,unknown,의생명과학과,의생명과학과,의생명과,의생명과,False,53.680000,30.047096,21.224489,10.753532,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,의생명과학과,의생명과,의생명과,SCH_35d77d3b6c8e,HC2_2024_25125,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_25125,의생명과학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_94d2abec42f4,semantic_distinct_key_expansion,False,25379,SCH_35d77d3b6c8e,CAM_f83c793bedfd,DEP_a06d4e12b67e,U05020100184,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,경기,경기 화성시,자연계열,NAT,생물ㆍ화학ㆍ환경,생명과학,30,31,142,24,36,6,0,2,1,1,26,0,0,4.580645,0.774194,0.169014,16.666666,72.222221,2.777778,12.000000,66.666664,3.610918,0.000000,SCH_35d77d3b6c8e,NAT,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=자연계열,,True,True,ok,"22,406.000000",281.799988,248.899994,27.327501,11.394269,14.424707,7.556012,53.940910,21.980719,22.244041,58.900002,1.263635,2.449941,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,66.616158,20.634125,30.696854,74.289322,20.130655,5.349733,0.120147,51.656002,45.124050,224.645950,43.161877,1.198174,3.625274,-0.358791,0.058242,-0.736263,225.199997,42.500000,19.900000,73.800003,3,False,medium_reviewed,PASS
10240,2024,OC2024_10241,화성의과학대학교,화성의과학대학교,화성의과학대학교,,,,unknown,컴퓨터학과,컴퓨터학과,컴퓨터,컴퓨터,False,<NA>,26.556992,26.263220,6.227967,33.333332,33.333332,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,컴퓨터학과,컴퓨터,컴퓨터,SCH_35d77d3b6c8e,HC2_2024_25119,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_25119,컴퓨터학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_c4df18e1cbea,semantic_distinct_key_expansion,False,25373,SCH_35d77d3b6c8e,CAM_f83c793bedfd,DEP_94ace6bdfef1,U04080100092,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,경기,경기 화성시,공학계열,ENG,컴퓨터ㆍ통신,전산학ㆍ컴퓨터공학,0,0,0,0,18,7,3,1,1,0,1,0,0,<NA>,<NA>,<NA>,38.888889,5.555555,0.000000,9.000000,50.000000,2.944439,1.386294,SCH_35d77d3b6c8e,ENG,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=공학계열,,True,True,ok,"72,776.000000",328.100006,290.000000,46.695339,23.572332,21.148455,11.050346,53.189240,32.198803,13.894691,60.900002,1.425704,2.516006,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,73.065971,29.134941,21.277163,84.834541,12.588641,2.276821,0.146353,55.035660,55.704208,255.028931,44.322861,1.325061,4.251100,-0.441209,0.080220,-0.399450,260.600006,43.700001,30.000000,84.800003,3,False,medium_reviewed,PASS
10241,2024,OC2024_10242,화성의과학대학교,화성의과학대학교,화성의과학대학교,,,,unknown,컴퓨터사이언스학과,컴퓨터사이언스학과,컴퓨터사이언스,컴퓨터사이언스,False,<NA>,47.500000,10.500000,0.000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,False,False,False,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,컴퓨터사이언스학과,컴퓨터사이언스,컴퓨터사이언스,SCH_35d77d3b6c8e,HC2_2024_25122,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_25122,컴퓨터사이언스학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_317a8c6b50c9,semantic_distinct_key_expansion,False,25376,SCH_35d77d3b6c8e,CAM_f83c793bedfd,DEP_553cedacbfaa,U04080200285,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,경기,경기 화성시,공학계열,ENG,컴퓨터ㆍ통신,응용소프트웨어공학,0,0,0,0,15,5,0,0,0,0,1,0,0,<NA>,<NA>,<NA>,33.333332,6.666667,0.000000,<NA>,<NA>,2.772589,0.000000,SCH_35d77d3b6c8e,ENG,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=공학계열,,True,True,ok,"72,776.000000",328.100006,290.000000,46.695339,23.572332,21.148455,11.050346,53.189240,32.198803,13.894691,60.900002,1.425704,2.516006,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,73.065971,29.134941,21.277163,84.834541,12.588641,2.276821,0.146353,55.035660,55.704208,255.028931,44.322861,1.325061,4.251100,-0.441209,0.080220,-0.399450,260.600006,43.700001,30.000000,84.800003,3,False,medium_reviewed,PASS

### 5.7 Random Sample

,analysis_year,outcome_row_id,school_name_raw,school_name_base_raw,school_name_std,campus_name_raw_x,campus_seq,campus_branch,campus_name_std_x,dept_name_raw,dept_name_std,dept_field_raw,dept_field_std,credit_forfeit_flag,selectivity_proxy_pct,a_rate_pct,cd_rate_pct,f_rate_pct,employment_rate_pct,health_employment_rate_pct,progression_rate_pct,vocational_college_progression_rate_pct,university_progression_rate_pct,graduate_school_progression_rate_pct,domestic_progression_rate_pct,overseas_progression_rate_pct,has_selectivity,has_employment,has_progression,rate_range_qa,source_file,source_sha256,campus_region_raw,dept_norm_strict,dept_norm_suffix_reduced,dept_token_signature,school_uid_x,headcount_row_id,match_stage,match_method,match_status,match_score,candidate_count,review_needed,unmatched_reason,match_evidence,candidate_headcount_row_ids,candidate_preview,campus_conflict_flag,degree_course_conflict_flag,major_conflict_flag,forbidden_modifier_conflict_flag,headcount_match_flag,headcount_grain_version,headcount_grain_uid,grain_resolution_method,grain_review_needed,raw_row_lineage,school_uid_y,campus_uid,dept_uid,kedi_dept_code,school_type,degree_course,school_status_raw,day_evening_raw,campus_name_raw_y,campus_name_std_y,region_sido,region_sigungu,hc_major_group_raw,hc_major_group_7,field_middle_name,field_small_name,admission_capacity_n,recruitment_n,applicants_n,admits_n,enrolled_students_n,leave_students_n,graduates_n,fulltime_faculty_n,nonfulltime_faculty_n,international_students_n,female_students_n,masters_students_n,doctoral_students_n,competition_ratio,admission_yield_ratio,admit_per_applicant_ratio,leave_rate_pct,female_student_share_pct,international_student_share_pct,student_faculty_ratio,fulltime_faculty_share_pct,log_enrolled_students,log_graduates,school_uid,major_group_7,major7_mapping_method,major7_mapping_confidence,major7_candidate_count,major7_review_needed,major7_evidence,major7_sample_exclusion_rule,has_structure_context,has_major_group_7_high_medium,row_qa_status,ctx24_reference_sample_n,ctx24_mean_income_10kkrw,ctx24_median_income_10kkrw,ctx24_income_300plus_pct,ctx24_income_400plus_pct,ctx24_large_company_pct,ctx24_mid_company_pct,ctx24_small_company_pct,ctx24_large_mid_company_pct,ctx24_public_nonprofit_pct,ctx24_cert_rate_pct,ctx24_cert_per_person,ctx24_log10_mean_income,ctx24_industry_top3_pct,ctx24_industry_hhi,goms_profile_start_year,goms_profile_end_year,goms_profile_years_n,goms_aggregation_method,goms_recent_employment_rate_pct,goms_recent_firm_300plus_pct,goms_recent_public_nonprofit_pct,goms_recent_permanent_pct,goms_recent_unstable_pct,goms_recent_self_employed_pct,goms_recent_industry_hhi,goms_recent_industry_top3_pct,goms_recent_professional_highskill_pct,goms_recent_mean_income_10kkrw,goms_recent_weekly_work_hours,goms_recent_hourly_income_proxy,goms_income_trend_per_year,goms_hours_trend_per_year,goms_firm_300plus_trend_per_year,goms_permanent_trend_per_year,goms_latest_2019_mean_income_10kkrw,goms_latest_2019_weekly_work_hours,goms_latest_2019_firm_300plus_pct,goms_latest_2019_permanent_pct,goms_source_years_observed,goms_year_over_year_review_flag,goms_mapping_confidence,goms_row_qa_status
1867,2024,OC2024_01868,광주대학교,광주대학교,광주대학교,,,,unknown,문예창작과,문예창작과,문예창작과,문예창작과,False,<NA>,36.733154,23.870983,0.694411,84.210526,47.368420,9.523809,0.000000,0.000000,9.523809,9.523809,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,문예창작과,문예창작,문예창작,SCH_6a3a99a48782,HC2_2024_24990,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_24990,문예창작과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_e4adc167409c,semantic_distinct_key_expansion,False,25242,SCH_6a3a99a48782,CAM_da41d915b48f,DEP_6dbe7995ac9b,U01010200013,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,광주,광주 남구,인문계열,HUM,언어ㆍ문학,국어ㆍ국문학,0,31,105,25,173,61,21,4,3,0,67,0,0,3.387097,0.806452,0.238095,35.260117,38.728325,0.000000,24.714285,57.142857,5.159055,3.091043,SCH_6a3a99a48782,HUM,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=인문계열,,True,True,ok,"18,844.000000",303.899994,250.000000,32.482487,16.769264,12.815750,6.474209,45.552959,19.289959,31.845680,41.599998,0.713118,2.482731,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,64.400627,21.097418,28.517433,73.155090,22.966125,3.649978,0.092309,40.299431,27.957674,225.948471,39.975986,1.301203,4.529670,-0.317582,0.020879,-0.471978,269.799988,39.900002,23.700001,71.599998,3,True,medium_reviewed,PASS
1158,2024,OC2024_01159,경상국립대학교,경상국립대학교,경상국립대학교,,,,unknown,의류학과,의류학과,의류,의류,False,66.830002,41.034794,18.622355,4.105611,56.250000,53.125000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,의류학과,의류,의류,SCH_bd24ab6964ce,HC2_2024_01455,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_01455,의류학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_7170aa2ab989,semantic_distinct_key_expansion,False,1478,SCH_bd24ab6964ce,CAM_61ef2ce04720,DEP_8603fa45094a,U05030300008,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,경남,경남 진주시,자연계열,NAT,생활과학,의류ㆍ의상학,31,33,272,33,179,41,32,6,14,2,125,0,0,8.242424,1.000000,0.121324,22.905027,69.832405,1.117318,8.950000,30.000000,5.192957,3.496508,SCH_bd24ab6964ce,NAT,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=자연계열,,True,True,ok,"22,406.000000",281.799988,248.899994,27.327501,11.394269,14.424707,7.556012,53.940910,21.980719,22.244041,58.900002,1.263635,2.449941,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,66.616158,20.634125,30.696854,74.289322,20.130655,5.349733,0.120147,51.656002,45.124050,224.645950,43.161877,1.198174,3.625274,-0.358791,0.058242,-0.736263,225.199997,42.500000,19.900000,73.800003,3,False,medium_reviewed,PASS
6704,2024,OC2024_06705,연세대학교,연세대학교,연세대학교,,,,unknown,관현악과,관현악과,관현악과,관현악과,False,21.000000,68.313606,8.369531,2.314846,52.941177,26.470589,2.857143,0.000000,0.000000,2.857143,2.857143,0.000000,True,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,관현악과,관현악,관현악,SCH_8c0fe037a811,HC2_2024_18733,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_18733,관현악과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_a2d7f97aa137,semantic_distinct_key_expansion,False,18912,SCH_8c0fe037a811,CAM_cd6488ffd347,DEP_5676050ae761,U07060300002,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,서울,서울 서대문구,예체능계열,ART,음악,기악,40,41,281,41,210,30,35,6,74,0,123,0,0,6.853659,1.000000,0.145907,14.285714,58.571430,0.000000,2.625000,7.500000,5.351858,3.583519,SCH_8c0fe037a811,ART,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=예체능계열,,True,True,ok,"22,813.000000",234.699997,217.500000,13.426555,4.891948,8.214615,4.633323,70.788582,12.847938,15.434182,32.500000,0.523035,2.370513,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,70.644333,8.162268,16.418356,63.287960,26.055664,10.322768,0.102211,40.676308,54.354107,189.761124,39.008335,1.120742,3.236264,-0.545604,-0.190110,-0.673077,192.699997,37.599998,9.400000,63.099998,3,False,medium_reviewed,PASS
8954,2024,OC2024_08955,충북대학교,충북대학교,충북대학교,,,,unknown,안전공학과,안전공학과,안,안,False,68.330002,31.175568,29.245140,0.705549,78.571426,71.428574,9.677420,0.000000,0.000000,9.677420,6.451613,3.225806,True,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,안전공학과,안전공,안전공,SCH_8eaffeb1f469,HC2_2024_05573,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_05573,안전공학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_b38562a2f30c,semantic_distinct_key_expansion,False,5633,SCH_8eaffeb1f469,CAM_deb9b8555416,DEP_802c18fec5aa,U04110200022,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,충북,충북 청주시,공학계열,ENG,기타,응용공학,34,40,284,39,226,60,31,6,9,2,41,0,0,7.100000,0.975000,0.137324,26.548672,18.141592,0.884956,15.066667,40.000000,5.424950,3.465736,SCH_8eaffeb1f469,ENG,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=공학계열,,True,True,ok,"72,776.000000",328.100006,290.000000,46.695339,23.572332,21.148455,11.050346,53.189240,32.198803,13.894691,60.900002,1.425704,2.516006,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,73.065971,29.134941,21.277163,84.834541,12.588641,2.276821,0.146353,55.035660,55.704208,255.028931,44.322861,1.325061,4.251100,-0.441209,0.080220,-0.399450,260.600006,43.700001,30.000000,84.800003,3,False,medium_reviewed,PASS
2915,2024,OC2024_02916,김천대학교,김천대학교,김천대학교,,,,unknown,식품영양학과,식품영양학과,식품영양,식품영양,False,<NA>,24.624624,23.310810,2.702703,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,False,False,False,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,식품영양학과,식품영양,식품영양,SCH_b3c5162386a0,HC2_2024_25710,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_25710,식품영양학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_ad4252ed28d2,semantic_distinct_key_expansion,False,25970,SCH_b3c5162386a0,CAM_d737a74d7150,DEP_92790e042348,U05030200045,대학교,대학과정,기존,주간,본교(제1캠퍼스),본교_제1캠퍼스,경북,경북 김천시,자연계열,NAT,생활과학,식품영양학,0,0,0,0,16,7,0,0,0,4,4,0,0,<NA>,<NA>,<NA>,43.750000,25.000000,25.000000,<NA>,<NA>,2.833213,0.000000,SCH_b3c5162386a0,NAT,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=자연계열,,True,True,ok,"22,406.000000",281.799988,248.899994,27.327501,11.394269,14.424707,7.556012,53.940910,21.980719,22.244041,58.900002,1.263635,2.449941,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,66.616158,20.634125,30.696854,74.289322,20.130655,5.349733,0.120147,51.656002,45.124050,224.645950,43.161877,1.198174,3.625274,-0.358791,0.058242,-0.736263,225.199997,42.500000,19.900000,73.800003,3,False,medium_reviewed,PASS
1091,2024,OC2024_01092,경상국립대학교,경상국립대학교,경상국립대학교,,,,unknown,기계융합공학과,기계융합공학과,기계융합공,기계융합공,False,63.830002,51.993244,10.541759,0.322255,71.428574,61.904762,4.545455,0.000000,0.000000,4.545455,4.545455,0.000000,True,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,기계융합공학과,기계융합공,기계융합공,SCH_bd24ab6964ce,HC2_2024_01490,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_01490,기계융합공학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_45f8152033e4,semantic_distinct_key_expansion,False,1515,SCH_bd24ab6964ce,CAM_e9c41a32b5a4,DEP_97ba9fdc7b8f,U04040100177,대학교,대학과정,기존,주간,본교(제3캠퍼스),본교_제3캠퍼스,경남,경남 창원시,공학계열,ENG,기계ㆍ금속,기계공학,30,30,145,30,164,47,22,7,1,0,16,0,0,4.833333,1.000000,0.206897,28.658537,9.756098,0.000000,20.500000,87.500000,5.105946,3.135494,SCH_bd24ab6964ce,ENG,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=공학계열,,True,True,ok,"72,776.000000",328.100006,290.000000,46.695339,23.572332,21.148455,11.050346,53.189240,32.198803,13.894691,60.900002,1.425704,2.516006,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,73.065971,29.134941,21.277163,84.834541,12.588641,2.276821,0.146353,55.035660,55.704208,255.028931,44.322861,1.325061,4.251100,-0.441209,0.080220,-0.399450,260.600006,43.700001,30.000000,84.800003,3,False,medium_reviewed,PASS
1457,2024,OC2024_01458,경희대학교,경희대학교,경희대학교,,,,unknown,영어학부,영어학부,영어,영어,True,<NA>,36.370369,17.555555,2.000000,57.894737,52.631580,4.761905,0.000000,0.000000,4.761905,4.761905,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,영어학부,영어,영어,SCH_c82adbe73aeb,HC2_2024_09332,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_09332,영어학부,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_3fe3dbc7ba84,semantic_distinct_key_expansion,False,9430,SCH_c82adbe73aeb,CAM_153004ff9506,DEP_c67eb52f5b0a,U01010600027,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,서울,서울 동대문구,인문계열,HUM,언어ㆍ문학,영미어ㆍ문학,0,0,0,0,18,5,21,0,0,0,3,0,0,<NA>,<NA>,<NA>,27.777779,16.666666,0.000000,<NA>,<NA>,2.944439,3.091043,SCH_c82adbe73aeb,HUM,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=인문계열,,True,True,ok,"18,844.000000",303.899994,250.000000,32.482487,16.769264,12.815750,6.474209,45.552959,19.289959,31.845680,41.599998,0.713118,2.482731,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,64.400627,21.097418,28.517433,73.155090,22.966125,3.649978,0.092309,40.299431,27.957674,225.948471,39.975986,1.301203,4.529670,-0.317582,0.020879,-0.471978,269.799988,39.900002,23.700001,71.599998,3,True,medium_reviewed,PASS
626,2024,OC2024_00627,건양대학교,건양대학교,건양대학교,,,,unknown,경영학부,경영학부,경영,경영,False,2.304147,28.915606,15.141592,3.358907,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,경영학부,경영,경영,SCH_708f797d9c02,HC2_2024_07868,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_07868,경영학부,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_1687eeffdd73,semantic_distinct_key_expansion,False,7957,SCH_708f797d9c02,CAM_bb779fca2250,DEP_054cf8c8437e,U02010100038,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,충남,충남 논산시,사회계열,SOC,경영ㆍ경제,경영학,30,32,182,28,80,29,0,6,6,2,32,0,0,5.687500,0.875000,0.153846,36.250000,40.000000,2.500000,6.666667,50.000000,4.394449,0.000000,SCH_708f797d9c02,SOC,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=사회계열,,True,True,ok,"65,600.000000",300.299988,250.500000,32.472561,16.076220,11.987804,6.647866,42.675304,18.635672,32.722561,44.500000,0.796006,2.477555,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,69.609535,20.332579,31.614683,79.118462,16.265503,4.286320,0.083019,33.007038,23.923975,235.459671,42.231544,1.283551,3.110989,-0.401099,0.218681,-0.371429,234.600006,41.900002,22.700001,78.500000,3,False,medium_reviewed,PASS
7393,2024,OC2024_07394,위덕대학교,위덕대학교,위덕대학교,,,,unknown,유아교육과,유아교육과,유아교육과,유아교육과,False,<NA>,31.666666,14.696970,4.264069,96.296295,92.592590,3.571429,0.000000,0.000000,3.571429,3.571429,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,유아교육과,유아교육,유아교육,SCH_38a7fe8ddf6c,HC2_2024_20125,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_20125,유아교육과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_9813590fd244,semantic_distinct_key_expansion,False,20313,SCH_38a7fe8ddf6c,CAM_3a3327adcafd,DEP_d72a895b79e5,U03020100007,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,경북,경북 경주시,교육계열,EDU,유아교육,유아교육학,28,28,66,20,80,4,28,5,2,0,69,0,0,2.357143,0.714286,0.303030,5.000000,86.250000,0.000000,11.428572,71.428574,4.394449,3.367296,SCH_38a7fe8ddf6c,EDU,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=교육계열,,True,True,ok,"15,498.000000",260.200012,235.300003,27.184153,5.142599,2.406762,1.142083,15.931087,3.548845,48.722416,25.100000,0.453671,2.415307,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,69.202415,4.769505,62.423748,79.453407,18.015871,2.265895,0.438346,86.049698,82.351410,217.437210,39.498657,1.267081,4.053847,-0.457143,-0.036813,-0.153297,221.800003,39.599998,4.700000,80.800003,3,True,medium_reviewed,PASS
6069,2024,OC2024_06070,송원대학교,송원대학교,송원대학교,,,,unknown,국방경찰학과,국방경찰학과,국방경찰,국방경찰,False,<NA>,40.761272,12.453806,2.629958,66.666664,61.111111,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,True,True,ok,P2_G2_정시입결.csv,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,,국방경찰학과,국방경찰,국방경찰,SCH_406e2951a18f,HC2_2024_25753,L1,exact_strict,auto_high_confidence,1.000000,1,False,,school+campus+department strict exact unique,HC2_2024_25753,국방경찰학과,False,False,False,False,True,v2_year_school_campus_day_degree_deptcode,HCG_ed0342585707,semantic_distinct_key_expansion,False,26014,SCH_406e2951a18f,CAM_56ae2e962361,DEP_7ba417c7081d,U02030700272,대학교,대학과정,기존,주야간,본교(제1캠퍼스),본교_제1캠퍼스,광주,광주 남구,사회계열,SOC,사회과학,행정학,0,0,0,0,76,16,18,0,0,0,16,0,0,<NA>,<NA>,<NA>,21.052631,21.052631,0.000000,<NA>,<NA>,4.343805,2.944439,SCH_406e2951a18f,SOC,inherited_headcount,high,1,False,D01 v2 high-confidence match 대계열=사회계열,,True,True,ok,"65,600.000000",300.299988,250.500000,32.472561,16.076220,11.987804,6.647866,42.675304,18.635672,32.722561,44.500000,0.796006,2.477555,<NA>,<NA>,2017,2019,3,mixed_weighted_2017_2019,69.609535,20.332579,31.614683,79.118462,16.265503,4.286320,0.083019,33.007038,23.923975,235.459671,42.231544,1.283551,3.110989,-0.401099,0.218681,-0.371429,234.600006,41.900002,22.700001,78.500000,3,False,medium_reviewed,PASS

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,analysis_year,"10,242.000000","2,024.000000",0.000000,"2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000",0,0.000000,0,0.000000,0,0,1
1,selectivity_proxy_pct,"3,737.000000",69.656123,19.072921,0.100000,3.773400,30.764000,43.688000,61.400002,72.500000,82.870003,91.169998,94.169998,97.782002,100.000000,6505,63.512986,0,0.000000,0,0,1609
2,a_rate_pct,"10,242.000000",41.726427,17.010999,0.000000,0.000000,14.643038,25.731864,32.476539,39.791552,49.940473,63.412966,73.036091,92.857140,100.000000,0,0.000000,319,3.114626,0,0,9203
3,cd_rate_pct,"10,242.000000",18.606950,12.729525,0.000000,0.000000,0.833552,4.436793,10.412399,17.967908,24.792164,30.355446,35.551011,66.666664,100.000000,0,0.000000,475,4.637766,0,0,8975
4,f_rate_pct,"10,242.000000",3.937010,9.650919,0.000000,0.000000,0.000000,0.000000,0.513097,1.695090,3.510926,7.183361,12.752200,50.737500,100.000000,0,0.000000,1808,17.652802,0,0,7453
5,employment_rate_pct,"7,477.000000",61.586545,17.444647,0.000000,0.000000,33.333332,40.740742,50.000000,62.068966,72.000000,82.758621,91.666664,100.000000,100.000000,2765,26.996680,78,0.761570,0,0,1135
6,health_employment_rate_pct,"7,477.000000",52.675705,19.217385,0.000000,0.000000,20.000000,28.998303,41.176472,52.941177,64.000000,75.757576,86.206894,100.000000,100.000000,2765,26.996680,136,1.327866,0,0,1196
7,progression_rate_pct,"7,587.000000",8.373070,13.086164,0.000000,0.000000,0.000000,0.000000,0.000000,2.941176,11.111111,25.000000,35.897434,57.526923,100.000000,2655,25.922671,3098,30.247998,0,0,971
8,vocational_college_progression_rate_pct,"7,587.000000",0.109347,0.945585,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.448276,50.000000,2655,25.922671,7339,71.655927,0,0,120
9,university_progression_rate_pct,"7,587.000000",0.201633,0.987264,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.470588,4.761905,25.000000,2655,25.922671,7077,69.097832,0,0,182
10,graduate_school_progression_rate_pct,"7,587.000000",8.062090,13.011694,0.000000,0.000000,0.000000,0.000000,0.000000,2.380952,10.841195,25.000000,35.483871,57.192857,100.000000,2655,25.922671,3343,32.640109,0,0,946
11,domestic_progression_rate_pct,"7,587.000000",8.297621,13.025195,0.000000,0.000000,0.000000,0.000000,0.000000,2.857143,11.111111,25.000000,35.714287,57.192857,100.000000,2655,25.922671,3119,30.453037,0,0,965
12,overseas_progression_rate_pct,"7,587.000000",0.075449,0.657507,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.745053,18.181818,2655,25.922671,7406,72.310096,0,0,107
13,match_score,"9,877.000000",1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,365,3.563757,0,0.000000,0,0,1
14,candidate_count,"10,242.000000",2.850225,13.771810,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,81.000000,180.000000,0,0.000000,176,1.718414,0,0,42
15,admission_capacity_n,"8,561.000000",32.218432,135.003132,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,40.000000,63.000000,88.000000,179.000000,"4,500.000000",1681,16.412810,3677,35.901191,0,0,228
16,recruitment_n,"8,561.000000",36.855274,144.584568,0.000000,0.000000,0.000000,0.000000,0.000000,26.000000,43.000000,71.000000,100.000000,204.200000,"4,815.000000",1681,16.412810,3304,32.259324,0,0,256
17,applicants_n,"8,561.000000",260.552389,500.680506,0.000000,0.000000,0.000000,0.000000,0.000000,114.000000,329.000000,667.000000,996.000000,"2,135.400000","14,788.000000",1681,16.412810,3301,32.230033,0,0,1250
18,admits_n,"8,561.000000",31.527158,45.645147,0.000000,0.000000,0.000000,0.000000,0.000000,26.000000,43.000000,71.000000,100.000000,198.000000,"1,069.000000",1681,16.412810,3114,30.404218,0,0,243
19,enrolled_students_n,"8,561.000000",189.344820,356.206272,0.000000,0.000000,5.000000,16.000000,55.000000,132.000000,225.000000,368.000000,516.000000,"1,081.000000","13,106.000000",1681,16.412810,120,1.171646,0,0,836
20,leave_students_n,"8,561.000000",45.825488,93.376362,0.000000,0.000000,0.000000,1.000000,7.000000,28.000000,56.000000,96.000000,142.000000,305.800000,"3,191.000000",1681,16.412810,724,7.068932,0,0,354
21,graduates_n,"8,561.000000",32.004088,74.145018,0.000000,0.000000,0.000000,0.000000,1.000000,23.000000,40.000000,66.000000,93.000000,183.400000,"3,259.000000",1681,16.412810,2130,20.796719,0,0,246
22,fulltime_faculty_n,"8,561.000000",6.042518,22.989627,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,6.000000,11.000000,17.000000,37.000000,903.000000,1681,16.412810,2714,26.498731,0,0,95
23,nonfulltime_faculty_n,"8,561.000000",7.921738,21.040475,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,10.000000,19.000000,28.000000,59.000000,854.000000,1681,16.412810,2613,25.512595,0,0,108
24,international_students_n,"8,561.000000",6.676790,29.539920,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,11.000000,29.000000,133.800000,712.000000,1681,16.412810,5115,49.941418,0,0,184
25,female_students_n,"8,561.000000",84.537437,223.321909,0.000000,0.000000,0.000000,3.000000,15.000000,50.000000,102.000000,172.000000,246.000000,503.000000,"10,211.000000",1681,16.412810,437,4.266745,0,0,488
26,masters_students_n,"8,561.000000",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1681,16.412810,8561,83.587190,0,0,1
27,doctoral_students_n,"8,561.000000",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1681,16.412810,8561,83.587190,0,0,1
28,competition_ratio,"5,257.000000",8.082261,7.091869,0.000000,0.483077,1.760000,2.739683,4.187500,6.354839,10.067568,14.558974,19.137778,34.445728,139.027023,4985,48.672134,20,0.195274,0,0,3947
29,admission_yield_ratio,"5,257.000000",0.968216,0.271644,0.000000,0.200000,0.687255,0.878247,0.976190,1.000000,1.000000,1.030769,1.075000,1.198303,14.400000,4985,48.672134,16,0.156219,0,0,842
30,admit_per_applicant_ratio,"5,260.000000",0.185854,0.144183,0.000000,0.025590,0.051610,0.068284,0.098099,0.153407,0.223049,0.311673,0.457575,0.816010,1.309524,4982,48.642843,21,0.205038,0,0,3926
31,leave_rate_pct,"8,441.000000",23.139003,15.048066,0.000000,0.000000,0.000000,2.950820,13.580247,23.188406,30.630630,38.461540,46.530613,76.742084,100.000000,1801,17.584456,604,5.897286,0,0,4284
32,female_student_share_pct,"8,441.000000",42.936171,26.357262,0.000000,0.000000,3.448276,9.150327,21.568628,41.263439,61.025642,78.651688,96.969696,100.000000,100.000000,1801,17.584456,317,3.095099,0,0,4857
33,international_student_share_pct,"8,441.000000",3.541700,12.679773,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.388889,6.693712,16.274090,96.288516,100.000000,1801,17.584456,4995,48.769772,0,0,1927
34,student_faculty_ratio,"6,379.000000",19.294945,40.578520,0.000000,0.243889,2.193610,3.500000,7.157895,13.454545,21.788889,32.714287,42.557145,123.000000,"1,613.500000",3863,37.717243,54,0.527241,0,0,3288
35,fulltime_faculty_share_pct,"6,379.000000",45.062133,26.832951,0.000000,0.000000,0.000000,9.646698,26.315790,42.857143,62.500000,83.333336,100.000000,100.000000,100.000000,3863,37.717243,532,5.194298,0,0,613
36,log_enrolled_students,"8,561.000000",4.599217,1.325461,0.000000,0.000000,1.791759,2.833213,4.025352,4.890349,5.420535,5.910797,6.248043,6.986556,9.480902,1681,16.412810,120,1.171646,0,0,836
37,log_graduates,"8,561.000000",2.544819,1.645445,0.000000,0.000000,0.000000,0.000000,0.693147,3.178054,3.713572,4.204693,4.543295,5.217104,8.089482,1681,16.412810,2130,20.796719,0,0,246
38,major7_candidate_count,"10,242.000000",1.001172,0.119395,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,0,0.000000,58,0.566296,0,0,5
39,ctx24_reference_sample_n,"10,099.000000","45,186.969205","23,906.212681","15,498.000000","15,498.000000","15,498.000000","18,844.000000","22,406.000000","41,094.000000","72,776.000000","72,776.000000","72,776.000000","72,776.000000","72,776.000000",143,1.396212,0,0.000000,0,0,7
40,ctx24_mean_income_10kkrw,"10,099.000000",293.476450,31.547689,234.699997,234.699997,234.699997,234.699997,281.799988,300.299988,328.100006,328.100006,328.100006,328.100006,328.100006,143,1.396212,0,0.000000,0,0,7
41,ctx24_median_income_10kkrw,"10,099.000000",256.362896,24.968270,217.500000,217.500000,217.500000,217.500000,248.899994,250.500000,290.000000,290.000000,290.000000,290.000000,290.000000,143,1.396212,0,0.000000,0,0,7
42,ctx24_income_300plus_pct,"10,099.000000",32.898743,11.031681,13.426555,13.426555,13.426555,13.426555,27.327501,32.472561,46.695339,46.695339,46.695339,46.695339,46.695339,143,1.396212,0,0.000000,0,0,7
43,ctx24_income_400plus_pct,"10,099.000000",14.828046,6.667814,4.891948,4.891948,4.891948,4.891948,11.394269,16.076220,23.572332,23.572332,23.572332,23.572332,23.572332,143,1.396212,0,0.000000,0,0,7
44,ctx24_large_company_pct,"10,099.000000",12.853120,6.131606,1.603640,1.603640,1.603640,2.406762,8.214615,11.987804,21.148455,21.148455,21.148455,21.148455,21.148455,143,1.396212,0,0.000000,0,0,7
45,ctx24_mid_company_pct,"10,099.000000",6.830501,3.155938,0.992846,0.992846,0.992846,1.142083,4.633323,6.647866,11.050346,11.050346,11.050346,11.050346,11.050346,143,1.396212,0,0.000000,0,0,7
46,ctx24_small_company_pct,"10,099.000000",49.947963,13.003264,15.931087,15.931087,15.931087,42.675304,42.675304,53.189240,53.940910,70.788582,70.788582,70.788582,70.788582,143,1.396212,0,0.000000,0,0,7
47,ctx24_large_mid_company_pct,"10,099.000000",19.683622,9.283198,2.596486,2.596486,2.596486,3.548845,12.847938,18.635672,32.198803,32.198803,32.198803,32.198803,32.198803,143,1.396212,0,0.000000,0,0,7
48,ctx24_public_nonprofit_pct,"10,099.000000",25.844527,11.800113,13.894691,13.894691,13.894691,13.894691,13.894691,22.244041,32.722561,48.325790,48.722416,48.722416,48.722416,143,1.396212,0,0.000000,0,0,7
49,ctx24_cert_rate_pct,"10,099.000000",45.798941,12.969783,25.100000,25.100000,25.100000,25.200001,32.500000,44.500000,60.900002,60.900002,60.900002,60.900002,60.900002,143,1.396212,0,0.000000,0,0,7
50,ctx24_cert_per_person,"10,099.000000",0.918983,0.381779,0.413953,0.413953,0.413953,0.453671,0.523035,0.796006,1.425704,1.425704,1.425704,1.425704,1.425704,143,1.396212,0,0.000000,0,0,7
51,ctx24_log10_mean_income,"10,099.000000",2.464895,0.049043,2.370513,2.370513,2.370513,2.370513,2.449941,2.477555,2.516006,2.516006,2.516006,2.516006,2.516006,143,1.396212,0,0.000000,0,0,7
52,ctx24_industry_top3_pct,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10242,100.000000,0,0.000000,0,0,0
53,ctx24_industry_hhi,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10242,100.000000,0,0.000000,0,0,0
54,goms_profile_start_year,"10,099.000000","2,017.000000",0.000000,"2,017.000000","2,017.000000","2,017.000000","2,017.000000","2,017.000000","2,017.000000","2,017.000000","2,017.000000","2,017.000000","2,017.000000","2,017.000000",143,1.396212,0,0.000000,0,0,1
55,goms_profile_end_year,"10,099.000000","2,019.000000",0.000000,"2,019.000000","2,019.000000","2,019.000000","2,019.000000","2,019.000000","2,019.000000","2,019.000000","2,019.000000","2,019.000000","2,019.000000","2,019.000000",143,1.396212,0,0.000000,0,0,1
56,goms_profile_years_n,"10,099.000000",3.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,143,1.396212,0,0.000000,0,0,1
57,goms_recent_employment_rate_pct,"10,099.000000",70.578051,4.331896,64.400627,64.400627,64.400627,64.400627,69.202415,69.609535,73.065971,73.065971,83.631943,83.631943,83.631943,143,1.396212,0,0.000000,0,0,7
58,goms_recent_firm_300plus_pct,"10,099.000000",20.639813,8.567468,4.769505,4.769505,4.769505,8.162268,20.332579,20.634125,29.134941,29.134941,34.586937,34.586937,34.586937,143,1.396212,0,0.000000,0,0,7
59,goms_recent_public_nonprofit_pct,"10,099.000000",29.023184,11.598783,16.418356,16.418356,16.418356,16.418356,21.277163,28.517433,31.614683,42.840969,62.423748,62.423748,62.423748,143,1.396212,0,0.000000,0,0,7
60,goms_recent_permanent_pct,"10,099.000000",77.506131,7.548512,63.287960,63.287960,63.287960,63.287960,73.155090,79.118462,84.834541,84.834541,88.365913,88.365913,88.365913,143,1.396212,0,0.000000,0,0,7
61,goms_recent_unstable_pct,"10,099.000000",17.780611,5.046689,10.131062,10.131062,10.131062,12.588641,12.588641,16.265503,22.966125,26.055664,26.055664,26.055664,26.055664,143,1.396212,0,0.000000,0,0,7
62,goms_recent_self_employed_pct,"10,099.000000",4.418704,2.788713,1.171014,1.171014,1.171014,2.265895,2.276821,3.649978,5.349733,10.322768,10.322768,10.322768,10.322768,143,1.396212,0,0.000000,0,0,7
63,goms_recent_industry_hhi,"10,099.000000",0.167230,0.145375,0.083019,0.083019,0.083019,0.083019,0.092309,0.120147,0.146353,0.438346,0.616856,0.616856,0.616856,143,1.396212,0,0.000000,0,0,7
64,goms_recent_industry_top3_pct,"10,099.000000",50.206941,16.320327,33.007038,33.007038,33.007038,33.007038,40.299431,51.656002,55.035660,85.754974,86.049698,86.049698,86.049698,143,1.396212,0,0.000000,0,0,7
65,goms_recent_professional_highskill_pct,"10,099.000000",48.296608,19.470613,23.923975,23.923975,23.923975,23.923975,27.957674,54.354107,55.704208,82.351410,88.556969,88.556969,88.556969,143,1.396212,0,0.000000,0,0,7
66,goms_recent_mean_income_10kkrw,"10,099.000000",231.444995,22.336610,189.761124,189.761124,189.761124,189.761124,224.645950,235.459671,255.028931,255.028931,261.694092,261.694092,261.694092,143,1.396212,0,0.000000,0,0,7
67,goms_recent_weekly_work_hours,"10,099.000000",42.121018,2.100871,39.008335,39.008335,39.008335,39.008335,39.975986,42.231544,44.322861,44.322861,44.960068,44.960068,44.960068,143,1.396212,0,0.000000,0,0,7
68,goms_recent_hourly_income_proxy,"10,099.000000",1.262836,0.072777,1.120742,1.120742,1.120742,1.120742,1.198174,1.283551,1.325061,1.325061,1.340399,1.340399,1.340399,143,1.396212,0,0.000000,0,0,7
69,goms_income_trend_per_year,"10,099.000000",3.849599,0.631281,3.110989,3.110989,3.110989,3.110989,3.236264,4.053847,4.251100,4.529670,5.240109,5.240109,5.240109,143,1.396212,0,0.000000,0,0,7
70,goms_hours_trend_per_year,"10,099.000000",-0.423779,0.066031,-0.545604,-0.545604,-0.545604,-0.545604,-0.441209,-0.403846,-0.401099,-0.317582,-0.317582,-0.317582,-0.317582,143,1.396212,0,0.000000,10099,0,7
71,goms_firm_300plus_trend_per_year,"10,099.000000",0.038609,0.131643,-0.190110,-0.190110,-0.190110,-0.190110,-0.036813,0.058242,0.080220,0.218681,0.218681,0.218681,0.218681,143,1.396212,0,0.000000,2926,0,7
72,goms_permanent_trend_per_year,"10,099.000000",-0.455251,0.174236,-0.736263,-0.736263,-0.736263,-0.736263,-0.673077,-0.399450,-0.371429,-0.195055,-0.153297,-0.153297,-0.153297,143,1.396212,0,0.000000,10099,0,7
73,goms_latest_2019_mean_income_10kkrw,"10,099.000000",239.000931,25.983436,192.699997,192.699997,192.699997,192.699997,225.199997,234.600006,260.600006,269.799988,271.799988,271.799988,271.799988,143,1.396212,0,0.000000,0,0,7
74,goms_latest_2019_weekly_work_hours,"10,099.000000",41.575117,2.236303,37.599998,37.599998,37.599998,37.599998,39.900002,41.900002,43.700001,43.700001,44.799999,44.799999,44.799999,143,1.396212,0,0.000000,0,0,7
75,goms_latest_2019_firm_300plus_pct,"10,099.000000",21.918180,8.852513,4.700000,4.700000,4.700000,9.400000,19.900000,22.700001,30.000000,30.000000,37.200001,37.200001,37.200001,143,1.396212,0,0.000000,0,0,7
76,goms_latest_2019_permanent_pct,"10,099.000000",77.284356,7.867237,63.099998,63.099998,63.099998,63.099998,71.599998,78.500000,84.800003,84.800003,89.699997,89.699997,89.699997,143,1.396212,0,0.000000,0,0,7
77,goms_source_years_observed,"10,099.000000",3.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,143,1.396212,0,0.000000,0,0,1

### 5.8 Categorical/String/Boolean Describe

,column,dtype,count,missing_n,missing_pct,nunique,top,freq,top_pct,sample_values
0,outcome_row_id,str,10242,0,0.000000,10242,OC2024_00001,1,0.009764,OC2024_00001 | OC2024_00002 | OC2024_00003 | OC2024_00004 | OC2024_00005
1,school_name_raw,string,10242,0,0.000000,227,경북대학교,158,1.542667,가야대학교(김해) | 가천대학교 | 가톨릭관동대학교 | 가톨릭꽃동네대학교 | 가톨릭대학교
2,school_name_base_raw,string,10242,0,0.000000,200,강원대학교,217,2.118727,가야대학교 | 가천대학교 | 가톨릭관동대학교 | 가톨릭꽃동네대학교 | 가톨릭대학교
3,school_name_std,string,10242,0,0.000000,200,강원대학교,217,2.118727,가야대학교 | 가천대학교 | 가톨릭관동대학교 | 가톨릭꽃동네대학교 | 가톨릭대학교
4,campus_name_raw_x,string,10242,0,0.000000,12,,9353,91.320055,김해 | | 제2캠퍼스 | 제3캠퍼스 | 분교|글로컬
5,campus_seq,string,10242,0,0.000000,4,,9729,94.991213,| 제2캠퍼스 | 제3캠퍼스 | 제4캠퍼스
6,campus_branch,string,10242,0,0.000000,2,,9921,96.865847,| 분교
7,campus_name_std_x,string,10242,0,0.000000,5,unknown,9408,91.857059,unknown | 제2캠퍼스 | 제3캠퍼스 | 분교 | 제4캠퍼스
8,dept_name_raw,string,10242,0,0.000000,4946,간호학과,106,1.034954,간호학과 | 경영물류학과 | 경찰소방학과 | 귀금속주얼리학과 | 물리치료학과
9,dept_name_std,string,10242,0,0.000000,4890,간호학과,106,1.034954,간호학과 | 경영물류학과 | 경찰소방학과 | 귀금속주얼리학과 | 물리치료학과
10,dept_field_raw,string,10242,0,0.000000,4195,경영,120,1.171646,간호 | 경영물류 | 경찰소방 | 귀금속주얼리 | 물리치료
11,dept_field_std,string,10242,0,0.000000,4119,경영,120,1.171646,간호 | 경영물류 | 경찰소방 | 귀금속주얼리 | 물리치료
12,credit_forfeit_flag,boolean,10242,0,0.000000,2,False,9093,88.781488,False | True
13,has_selectivity,boolean,10242,0,0.000000,2,False,6505,63.512986,True | False
14,has_employment,boolean,10242,0,0.000000,2,True,7477,73.003320,True | False
15,has_progression,boolean,10242,0,0.000000,2,True,7587,74.077329,True | False
16,rate_range_qa,category,10242,0,0.000000,1,ok,10242,100.000000,ok
17,source_file,str,10242,0,0.000000,1,P2_G2_정시입결.csv,10242,100.000000,P2_G2_정시입결.csv
18,source_sha256,str,10242,0,0.000000,1,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04,10242,100.000000,2530f88a0d923edf11c83e5884d2bb47d1811679cc9b6198b0d3384c50950b04
19,campus_region_raw,string,10242,0,0.000000,9,,9844,96.114040,김해 | | 글로컬 | 세종 | WISE
20,dept_norm_strict,string,10242,0,0.000000,4890,간호학과,106,1.034954,간호학과 | 경영물류학과 | 경찰소방학과 | 귀금속주얼리학과 | 물리치료학과
21,dept_norm_suffix_reduced,string,10242,0,0.000000,4391,간호,108,1.054482,간호 | 경영물류 | 경찰소방 | 귀금속주얼리 | 물리치료
22,dept_token_signature,string,10242,0,0.000000,4391,간호,108,1.054482,간호 | 경영물류 | 경찰소방 | 귀금속주얼리 | 물리치료
23,school_uid_x,string,10242,0,0.000000,200,SCH_193517d15ce2,217,2.118727,SCH_4fcb5ca730cd | SCH_e46f0f22fdd7 | SCH_f0a7062f14b7 | SCH_11568cc95743 | SCH_f11056a7ff4e
24,headcount_row_id,str,8561,1681,16.412810,8547,HC2_2024_10023,2,0.019527,HC2_2024_07159 | HC2_2024_07147 | HC2_2024_07154 | HC2_2024_07165 | HC2_2024_07161
25,match_stage,str,10242,0,0.000000,4,L1,8556,83.538371,L1 | L7 | L8 | L3
26,match_method,str,10242,0,0.000000,4,exact_strict,8556,83.538371,exact_strict | manual_pending | unmatched | exact_token_unique
27,match_status,str,10242,0,0.000000,3,auto_high_confidence,8561,83.587190,auto_high_confidence | manual_pending | unmatched
28,review_needed,boolean,10242,0,0.000000,2,False,8561,83.587190,False | True
29,unmatched_reason,str,10242,0,0.000000,6,,8561,83.587190,| multiple_candidates | multiple_fuzzy_or_conflict | department_formatting_or_source_coverage_mismatch | no_candidate
30,match_evidence,str,10242,0,0.000000,8,school+campus+department strict exact unique,8556,83.538371,school+campus+department strict exact unique | school+campus+department strict exact unique; multiple D01 rows remai...
31,candidate_headcount_row_ids,str,10242,0,0.000000,9899,,176,1.718414,HC2_2024_07159 | HC2_2024_07147 | HC2_2024_07154 | HC2_2024_07165 | HC2_2024_07161
32,candidate_preview,str,10242,0,0.000000,4907,,176,1.718414,간호학과 | 경영물류학과 | 경찰소방학과 | 귀금속주얼리학과 | 물리치료학과
33,campus_conflict_flag,bool,10242,0,0.000000,2,False,10006,97.695763,False | True
34,degree_course_conflict_flag,bool,10242,0,0.000000,1,False,10242,100.000000,False
35,major_conflict_flag,bool,10242,0,0.000000,1,False,10242,100.000000,False
36,forbidden_modifier_conflict_flag,bool,10242,0,0.000000,1,False,10242,100.000000,False
37,headcount_match_flag,bool,10242,0,0.000000,2,True,8561,83.587190,True | False
38,headcount_grain_version,str,8561,1681,16.412810,1,v2_year_school_campus_day_degree_deptcode,8561,83.587190,v2_year_school_campus_day_degree_deptcode
39,headcount_grain_uid,string,8561,1681,16.412810,8547,HCG_8eb2aae466a7,2,0.019527,HCG_fca851c614e1 | HCG_1e1b0e646a52 | HCG_3f01aaaf0b11 | HCG_c66b81ecad49 | HCG_abcbe1bd0237
40,grain_resolution_method,str,8561,1681,16.412810,1,semantic_distinct_key_expansion,8561,83.587190,semantic_distinct_key_expansion
41,grain_review_needed,boolean,8561,1681,16.412810,1,False,8561,83.587190,False
42,raw_row_lineage,string,8561,1681,16.412810,8547,10126,2,0.019527,7243 | 7231 | 7238 | 7249 | 7245
43,school_uid_y,string,8561,1681,16.412810,198,SCH_193517d15ce2,179,1.747706,SCH_4fcb5ca730cd | SCH_e46f0f22fdd7 | SCH_f0a7062f14b7 | SCH_11568cc95743 | SCH_f11056a7ff4e
44,campus_uid,string,10242,0,0.000000,452,CAM_f6396906ee8f,131,1.279047,CAM_60c4060f5f80 | CAM_40d7469e00a5 | CAM_aac084de6912 | CAM_6f177c7e5a77 | CAM_2ed1e6c2a9e7
45,dept_uid,string,10242,0,0.000000,10222,DEP_608b06fc070c,2,0.019527,DEP_c02dd4a5678d | DEP_e99f4ff43785 | DEP_fca11c7fd249 | DEP_4746d0bda0b9 | DEP_90eb7f613e75
46,kedi_dept_code,string,8561,1681,16.412810,3929,U06020100004,104,1.015427,U06020100004 | U02010600249 | U02030700344 | U07020100065 | U06040200001
47,school_type,string,8561,1681,16.412810,5,대학교,8324,81.273189,대학교 | 교육대학 | 각종대학(대학) | 산업대학 | 방송통신대학교
48,degree_course,string,8561,1681,16.412810,1,대학과정,8561,83.587190,대학과정
49,school_status_raw,string,8561,1681,16.412810,3,기존,8345,81.478227,기존 | 폐교 | 학교명변경
50,day_evening_raw,string,8561,1681,16.412810,4,주간,4374,42.706503,주야간 | 주간 | 주간+원격 | 주야간+원격
51,campus_name_raw_y,string,8561,1681,16.412810,5,본교(제1캠퍼스),7527,73.491506,본교(제1캠퍼스) | 본교(제2캠퍼스) | 본교(제3캠퍼스) | 분교(제1캠퍼스) | 본교(제4캠퍼스)
52,campus_name_std_y,string,8561,1681,16.412810,5,본교_제1캠퍼스,7527,73.491506,본교_제1캠퍼스 | 본교_제2캠퍼스 | 본교_제3캠퍼스 | 분교_제1캠퍼스 | 본교_제4캠퍼스
53,region_sido,string,8561,1681,16.412810,17,서울,1629,15.905097,경남 | 인천 | 경기 | 강원 | 충북
54,region_sigungu,string,8561,1681,16.412810,120,경북 경산시,385,3.759031,경남 김해시 | 인천 연수구 | 경기 성남시 | 강원 강릉시 | 충북 청주시
55,hc_major_group_raw,string,8561,1681,16.412810,7,공학계열,2212,21.597344,의약계열 | 사회계열 | 예체능계열 | 자연계열 | 교육계열
56,hc_major_group_7,string,8561,1681,16.412810,7,ENG,2212,21.597344,MED | SOC | ART | NAT | EDU
57,field_middle_name,string,8561,1681,16.412810,35,경영ㆍ경제,934,9.119313,간호 | 경영ㆍ경제 | 사회과학 | 응용예술 | 치료ㆍ보건
58,field_small_name,string,8561,1681,16.412810,121,경영학,476,4.647530,간호학 | 무역ㆍ유통학 | 행정학 | 공예 | 재활학
59,school_uid,str,10242,0,0.000000,200,SCH_193517d15ce2,217,2.118727,SCH_4fcb5ca730cd | SCH_e46f0f22fdd7 | SCH_f0a7062f14b7 | SCH_11568cc95743 | SCH_f11056a7ff4e
60,major_group_7,str,10099,143,1.396212,7,ENG,2642,25.795743,MED | SOC | ART | NAT | EDU
61,major7_mapping_method,str,10242,0,0.000000,5,inherited_headcount,8561,83.587190,inherited_headcount | exact_dictionary | keyword_rule | unknown | ambiguous
62,major7_mapping_confidence,str,10242,0,0.000000,4,high,8561,83.587190,high | medium | unknown | low
63,major7_review_needed,bool,10242,0,0.000000,2,False,10099,98.603788,False | True
64,major7_evidence,str,10242,0,0.000000,596,D01 v2 high-confidence match 대계열=공학계열,2212,21.597344,D01 v2 high-confidence match 대계열=의약계열 | D01 v2 high-confidence match 대계열=사회계열 | D01 v2 high-confidence match 대계열=예체능...
65,major7_sample_exclusion_rule,str,10242,0,0.000000,2,,10099,98.603788,| exclude from samples requiring major/context/GOMS until manual approved
66,has_structure_context,boolean,10242,0,0.000000,2,True,8561,83.587190,True | False
67,has_major_group_7_high_medium,boolean,10242,0,0.000000,2,True,10099,98.603788,True | False
68,row_qa_status,str,10242,0,0.000000,3,ok,8561,83.587190,ok | manual_match_pending | review_unmatched
69,goms_aggregation_method,category,10099,143,1.396212,1,mixed_weighted_2017_2019,10099,98.603788,mixed_weighted_2017_2019
70,goms_year_over_year_review_flag,boolean,10099,143,1.396212,2,False,8263,80.677602,False | True
71,goms_mapping_confidence,category,10099,143,1.396212,1,medium_reviewed,10099,98.603788,medium_reviewed
72,goms_row_qa_status,category,10099,143,1.396212,1,PASS,10099,98.603788,PASS

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

     rank                                   column    dtype  missing_n  missing_pct  non_null_n  nunique
121     1                  ctx24_industry_top3_pct  Float32      10242   100.000000           0        0
122     2                       ctx24_industry_hhi  Float32      10242   100.000000           0        0
14      3                    selectivity_proxy_pct  Float32       6505    63.512986        3737     1609
87      4                        competition_ratio  Float32       4985    48.672134        5257     3947
88      5                    admission_yield_ratio  Float32       4985    48.672134        5257      842
89      6                admit_per_applicant_ratio  Float32       4982    48.642843        5260     3926
93      7                    student_faculty_ratio  Float32       3863    37.717243        6379     3288
94      8               fulltime_faculty_share_pct  Float32       3863    37.717243        6379      613
18      9                      employment_rate_pct  Float32       2765    26.996680        7477     1135
19     10               health_employment_rate_pct  Float32       2765    26.996680        7477     1196
20     11                     progression_rate_pct  Float32       2655    25.922671        7587      971
21     12  vocational_college_progression_rate_pct  Float32       2655    25.922671        7587      120
22     13          university_progression_rate_pct  Float32       2655    25.922671        7587      182
23     14     graduate_school_progression_rate_pct  Float32       2655    25.922671        7587      946
24     15            domestic_progression_rate_pct  Float32       2655    25.922671        7587      965
25     16            overseas_progression_rate_pct  Float32       2655    25.922671        7587      107
90     17                           leave_rate_pct  Float32       1801    17.584456        8441     4284
91     18                 female_student_share_pct  Float32       1801    17.584456        8441     4857
92     19          international_student_share_pct  Float32       1801    17.584456        8441     1927
37     20                         headcount_row_id      str       1681    16.412810        8561     8547
53     21                  headcount_grain_version      str       1681    16.412810        8561        1
54     22                      headcount_grain_uid   string       1681    16.412810        8561     8547
55     23                  grain_resolution_method      str       1681    16.412810        8561        1
56     24                      grain_review_needed  boolean       1681    16.412810        8561        1
57     25                          raw_row_lineage   string       1681    16.412810        8561     8547
58     26                             school_uid_y   string       1681    16.412810        8561      198
61     27                           kedi_dept_code   string       1681    16.412810        8561     3929
62     28                              school_type   string       1681    16.412810        8561        5
63     29                            degree_course   string       1681    16.412810        8561        1
64     30                        school_status_raw   string       1681    16.412810        8561        3

### 5.10 Top Cardinality Columns

                             column    dtype  nunique  unique_ratio
1                    outcome_row_id      str    10242      1.000000
60                         dept_uid   string    10222      0.998047
46      candidate_headcount_row_ids      str     9899      0.966510
15                       a_rate_pct  Float32     9203      0.898555
16                      cd_rate_pct  Float32     8975      0.876294
37                 headcount_row_id      str     8547      0.998365
54              headcount_grain_uid   string     8547      0.998365
57                  raw_row_lineage   string     8547      0.998365
17                       f_rate_pct  Float32     7453      0.727690
9                     dept_name_raw   string     4946      0.482913
47                candidate_preview      str     4907      0.479106
10                    dept_name_std   string     4890      0.477446
33                 dept_norm_strict   string     4890      0.477446
91         female_student_share_pct  Float32     4857      0.575406
34         dept_norm_suffix_reduced   string     4391      0.428725
35             dept_token_signature   string     4391      0.428725
90                   leave_rate_pct  Float32     4284      0.507523
11                   dept_field_raw   string     4195      0.409588
12                   dept_field_std   string     4119      0.402168
87                competition_ratio  Float32     3947      0.750808
61                   kedi_dept_code   string     3929      0.458942
89        admit_per_applicant_ratio  Float32     3926      0.746388
93            student_faculty_ratio  Float32     3288      0.515441
92  international_student_share_pct  Float32     1927      0.228290
14            selectivity_proxy_pct  Float32     1609      0.430559
76                     applicants_n    Int32     1250      0.146011
19       health_employment_rate_pct  Float32     1196      0.159957
18              employment_rate_pct  Float32     1135      0.151799
20             progression_rate_pct  Float32      971      0.127982
24    domestic_progression_rate_pct  Float32      965      0.127191

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

                      column    dtype  missing_n  missing_pct
121  ctx24_industry_top3_pct  Float32      10242   100.000000
122       ctx24_industry_hhi  Float32      10242   100.000000

Constant columns

                               column     dtype  nunique  top_value_share
0                       analysis_year     Int16        1         1.000000
29                      rate_range_qa  category        1         1.000000
30                        source_file       str        1         1.000000
31                      source_sha256       str        1         1.000000
41                        match_score   float64        1         0.964362
49        degree_course_conflict_flag      bool        1         1.000000
50                major_conflict_flag      bool        1         1.000000
51   forbidden_modifier_conflict_flag      bool        1         1.000000
53            headcount_grain_version       str        1         0.835872
55            grain_resolution_method       str        1         0.835872
56                grain_review_needed   boolean        1         0.835872
63                      degree_course    string        1         0.835872
85                 masters_students_n     Int32        1         0.835872
86                doctoral_students_n     Int32        1         0.835872
121           ctx24_industry_top3_pct   Float32        0         1.000000
122                ctx24_industry_hhi   Float32        0         1.000000
123           goms_profile_start_year     Int16        1         0.986038
124             goms_profile_end_year     Int16        1         0.986038
125              goms_profile_years_n     Int16        1         0.986038
126           goms_aggregation_method  category        1         0.986038
147        goms_source_years_observed     Int16        1         0.986038
149           goms_mapping_confidence  category        1         0.986038
150                goms_row_qa_status  category        1         0.986038

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                                      column                      check         nan_n  pos_inf_n  neg_inf_n    negative_n        zero_n  violation_n
0                              analysis_year              numeric_basic      0.000000   0.000000   0.000000      0.000000      0.000000            0
1                              analysis_year  year_reasonable_1900_2100           NaN        NaN        NaN           NaN           NaN            0
2                        credit_forfeit_flag              numeric_basic      0.000000   0.000000   0.000000      0.000000  9,093.000000            0
3                      selectivity_proxy_pct              numeric_basic  6,505.000000   0.000000   0.000000      0.000000      0.000000            0
4                      selectivity_proxy_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
5                                 a_rate_pct              numeric_basic      0.000000   0.000000   0.000000      0.000000    319.000000            0
6                                 a_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
7                                cd_rate_pct              numeric_basic      0.000000   0.000000   0.000000      0.000000    475.000000            0
8                                cd_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
9                                 f_rate_pct              numeric_basic      0.000000   0.000000   0.000000      0.000000  1,808.000000            0
10                                f_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
11                       employment_rate_pct              numeric_basic  2,765.000000   0.000000   0.000000      0.000000     78.000000            0
12                       employment_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
13                health_employment_rate_pct              numeric_basic  2,765.000000   0.000000   0.000000      0.000000    136.000000            0
14                health_employment_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
15                      progression_rate_pct              numeric_basic  2,655.000000   0.000000   0.000000      0.000000  3,098.000000            0
16                      progression_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
17   vocational_college_progression_rate_pct              numeric_basic  2,655.000000   0.000000   0.000000      0.000000  7,339.000000            0
18   vocational_college_progression_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
19           university_progression_rate_pct              numeric_basic  2,655.000000   0.000000   0.000000      0.000000  7,077.000000            0
20           university_progression_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
21      graduate_school_progression_rate_pct              numeric_basic  2,655.000000   0.000000   0.000000      0.000000  3,343.000000            0
22      graduate_school_progression_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
23             domestic_progression_rate_pct              numeric_basic  2,655.000000   0.000000   0.000000      0.000000  3,119.000000            0
24             domestic_progression_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
25             overseas_progression_rate_pct              numeric_basic  2,655.000000   0.000000   0.000000      0.000000  7,406.000000            0
26             overseas_progression_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
27                           has_selectivity              numeric_basic      0.000000   0.000000   0.000000      0.000000  6,505.000000            0
28                            has_employment              numeric_basic      0.000000   0.000000   0.000000      0.000000  2,765.000000            0
29                           has_progression              numeric_basic      0.000000   0.000000   0.000000      0.000000  2,655.000000            0
30                               match_score              numeric_basic    365.000000   0.000000   0.000000      0.000000      0.000000            0
31                           candidate_count              numeric_basic      0.000000   0.000000   0.000000      0.000000    176.000000            0
32                           candidate_count          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
33                             review_needed              numeric_basic      0.000000   0.000000   0.000000      0.000000  8,561.000000            0
34                      campus_conflict_flag              numeric_basic      0.000000   0.000000   0.000000      0.000000 10,006.000000            0
35               degree_course_conflict_flag              numeric_basic      0.000000   0.000000   0.000000      0.000000 10,242.000000            0
36                       major_conflict_flag              numeric_basic      0.000000   0.000000   0.000000      0.000000 10,242.000000            0
37          forbidden_modifier_conflict_flag              numeric_basic      0.000000   0.000000   0.000000      0.000000 10,242.000000            0
38                      headcount_match_flag              numeric_basic      0.000000   0.000000   0.000000      0.000000  1,681.000000            0
39                       grain_review_needed              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  8,561.000000            0
40                      admission_capacity_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  3,677.000000            0
41                      admission_capacity_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
42                             recruitment_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  3,304.000000            0
43                             recruitment_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
44                              applicants_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  3,301.000000            0
45                              applicants_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
46                                  admits_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  3,114.000000            0
47                                  admits_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
48                       enrolled_students_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000    120.000000            0
49                       enrolled_students_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
50                          leave_students_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000    724.000000            0
51                          leave_students_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
52                               graduates_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  2,130.000000            0
53                               graduates_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
54                        fulltime_faculty_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  2,714.000000            0
55                        fulltime_faculty_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
56                     nonfulltime_faculty_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  2,613.000000            0
57                     nonfulltime_faculty_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
58                  international_students_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  5,115.000000            0
59                  international_students_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
60                         female_students_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000    437.000000            0
61                         female_students_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
62                        masters_students_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  8,561.000000            0
63                        masters_students_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
64                       doctoral_students_n              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  8,561.000000            0
65                       doctoral_students_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
66                         competition_ratio              numeric_basic  4,985.000000   0.000000   0.000000      0.000000     20.000000            0
67                     admission_yield_ratio              numeric_basic  4,985.000000   0.000000   0.000000      0.000000     16.000000            0
68                 admit_per_applicant_ratio              numeric_basic  4,982.000000   0.000000   0.000000      0.000000     21.000000            0
69                            leave_rate_pct              numeric_basic  1,801.000000   0.000000   0.000000      0.000000    604.000000            0
70                            leave_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
71                  female_student_share_pct              numeric_basic  1,801.000000   0.000000   0.000000      0.000000    317.000000            0
72                  female_student_share_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
73           international_student_share_pct              numeric_basic  1,801.000000   0.000000   0.000000      0.000000  4,995.000000            0
74           international_student_share_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
75                     student_faculty_ratio              numeric_basic  3,863.000000   0.000000   0.000000      0.000000     54.000000            0
76                fulltime_faculty_share_pct              numeric_basic  3,863.000000   0.000000   0.000000      0.000000    532.000000            0
77                fulltime_faculty_share_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
78                     log_enrolled_students              numeric_basic  1,681.000000   0.000000   0.000000      0.000000    120.000000            0
79                             log_graduates              numeric_basic  1,681.000000   0.000000   0.000000      0.000000  2,130.000000            0
80                    major7_candidate_count              numeric_basic      0.000000   0.000000   0.000000      0.000000     58.000000            0
81                    major7_candidate_count          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
82                      major7_review_needed              numeric_basic      0.000000   0.000000   0.000000      0.000000 10,099.000000            0
83                     has_structure_context              numeric_basic      0.000000   0.000000   0.000000      0.000000  1,681.000000            0
84             has_major_group_7_high_medium              numeric_basic      0.000000   0.000000   0.000000      0.000000    143.000000            0
85                  ctx24_reference_sample_n              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
86                  ctx24_reference_sample_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
87                  ctx24_mean_income_10kkrw              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
88                ctx24_median_income_10kkrw              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
89                  ctx24_income_300plus_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
90                  ctx24_income_300plus_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
91                  ctx24_income_400plus_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
92                  ctx24_income_400plus_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
93                   ctx24_large_company_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
94                   ctx24_large_company_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
95                     ctx24_mid_company_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
96                     ctx24_mid_company_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
97                   ctx24_small_company_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
98                   ctx24_small_company_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
99               ctx24_large_mid_company_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
100              ctx24_large_mid_company_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
101               ctx24_public_nonprofit_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
102               ctx24_public_nonprofit_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
103                      ctx24_cert_rate_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
104                      ctx24_cert_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
105                    ctx24_cert_per_person              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
106                  ctx24_log10_mean_income              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
107                  ctx24_industry_top3_pct              numeric_basic 10,242.000000   0.000000   0.000000      0.000000      0.000000            0
108                  ctx24_industry_top3_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
109                       ctx24_industry_hhi              numeric_basic 10,242.000000   0.000000   0.000000      0.000000      0.000000            0
110                  goms_profile_start_year              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
111                  goms_profile_start_year  year_reasonable_1900_2100           NaN        NaN        NaN           NaN           NaN            0
112                    goms_profile_end_year              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
113                    goms_profile_end_year  year_reasonable_1900_2100           NaN        NaN        NaN           NaN           NaN            0
114                     goms_profile_years_n              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
115                     goms_profile_years_n          count_nonnegative           NaN        NaN        NaN           NaN           NaN            0
116                     goms_profile_years_n  year_reasonable_1900_2100           NaN        NaN        NaN           NaN           NaN        10099
117          goms_recent_employment_rate_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
118          goms_recent_employment_rate_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
119             goms_recent_firm_300plus_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
120             goms_recent_firm_300plus_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
121         goms_recent_public_nonprofit_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
122         goms_recent_public_nonprofit_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
123                goms_recent_permanent_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
124                goms_recent_permanent_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
125                 goms_recent_unstable_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
126                 goms_recent_unstable_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
127            goms_recent_self_employed_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
128            goms_recent_self_employed_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
129                 goms_recent_industry_hhi              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
130            goms_recent_industry_top3_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0
131            goms_recent_industry_top3_pct                  pct_0_100           NaN        NaN        NaN           NaN           NaN            0
132   goms_recent_professional_highskill_pct              numeric_basic    143.000000   0.000000   0.000000      0.000000      0.000000            0

Range violations

                               column                      check  nan_n  pos_inf_n  neg_inf_n  negative_n  zero_n  violation_n
116              goms_profile_years_n  year_reasonable_1900_2100    NaN        NaN        NaN         NaN     NaN        10099
138        goms_income_trend_per_year  year_reasonable_1900_2100    NaN        NaN        NaN         NaN     NaN        10099
140         goms_hours_trend_per_year  year_reasonable_1900_2100    NaN        NaN        NaN         NaN     NaN        10099
142  goms_firm_300plus_trend_per_year  year_reasonable_1900_2100    NaN        NaN        NaN         NaN     NaN        10099
144     goms_permanent_trend_per_year  year_reasonable_1900_2100    NaN        NaN        NaN         NaN     NaN        10099
152        goms_source_years_observed  year_reasonable_1900_2100    NaN        NaN        NaN         NaN     NaN        10099
154   goms_year_over_year_review_flag  year_reasonable_1900_2100    NaN        NaN        NaN         NaN     NaN        10099

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- all-null columns: 2
- constant columns: 23
- range violations: 7

### 6.1 D08 Additional Checks

analysis_year distribution

   analysis_year   rows
0           2024  10242

split distribution via final membership merge

   split  rows
0  train  7529
1    val  1514
2   test  1199

major_group_7 distribution

  major_group_7  rows
0           ENG  2642
1           SOC  2165
2           ART  1566
3           NAT  1258
4           HUM  1108
5           EDU   728
6           MED   632
7           NaN   143

   school_n  campus_n  outcome_row_id_unique_n
0       200       452                    10242

Target describe

                                             count      mean       std      min       1%        5%       10%       25%       50%       75%       90%       95%        99%        max
a_rate_pct                           10,242.000000 41.726425 17.011000 0.000000 0.000000 14.643038 25.731864 32.476539 39.791552 49.940473 63.412966 73.036091  92.857140 100.000000
health_employment_rate_pct            7,477.000000 52.675671 19.217381 0.000000 0.000000 20.000000 28.998302 41.176472 52.941177 64.000000 75.757576 86.206894 100.000000 100.000000
graduate_school_progression_rate_pct  7,587.000000  8.062091 13.011699 0.000000 0.000000  0.000000  0.000000  0.000000  2.380952 10.841194 25.000000 35.483871  57.192856 100.000000

Structure match status distribution

match_status

           match_status  rows
0  auto_high_confidence  8561
1        manual_pending  1316
2             unmatched   365

match_method

         match_method  rows
0        exact_strict  8556
1      manual_pending  1316
2           unmatched   365
3  exact_token_unique     5

row_qa_status

          row_qa_status  rows
0                    ok  8561
1  manual_match_pending  1316
2      review_unmatched   365

major7 mapping status distribution

major7_mapping_method

  major7_mapping_method  rows
0   inherited_headcount  8561
1          keyword_rule   859
2      exact_dictionary   679
3             ambiguous    85
4               unknown    58

major7_mapping_confidence

  major7_mapping_confidence  rows
0                      high  8561
1                    medium  1538
2                       low    85
3                   unknown    58

has_major_group_7_high_medium

   has_major_group_7_high_medium   rows
0                           True  10099
1                          False    143

Target missing

                                 column  missing_n  missing_pct
0                            a_rate_pct          0     0.000000
1            health_employment_rate_pct       2765    26.996680
2  graduate_school_progression_rate_pct       2655    25.922671
3                 selectivity_proxy_pct       6505    63.512986

## Dataset: `P4_PHASE_SAMPLE_MEMBERSHIP_FINAL`

- 역할: Final phase-specific sample membership flags
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet`
- 예상 shape: `(10242, 21)`
- 예상 SHA256: `58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6`

In [ ]:
result = inspect_dataset(
    label='P4_PHASE_SAMPLE_MEMBERSHIP_FINAL',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet',
    expected_shape=(10242, 21),
    expected_sha256='58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6',
    candidate_keys=[['outcome_row_id']],
)

extra_membership()

### 5.1 File Identification - `P4_PHASE_SAMPLE_MEMBERSHIP_FINAL`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_PHASE_SAMPLE_MEMBERSHIP_FINAL,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FI...,workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,True,.parquet,273814,2026-07-13T11:12:50.209943,58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6,58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6,True

### 5.2 Basic Structure

         shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count           loader encoding json_raw_type json_top_level_keys
0  (10242, 21)    (10242, 21)         True      10242            21             1634494       int64          True                          0  pd.read_parquet     None          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0          outcome_row_id       outcome_row_id    True              0                   0                     0             10242

### 5.3 Full Column List

    position                             column   dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1                     outcome_row_id     str       10242          0     0.000000    10242      1.000000        False        False                     True         0.000098
1          2                      analysis_year   Int16       10242          0     0.000000        1      0.000098        False         True                    False         1.000000
2          3                         school_uid     str       10242          0     0.000000      200      0.019527        False        False                     True         0.021187
3          4                         campus_uid  string       10242          0     0.000000      452      0.044132        False        False                     True         0.012790
4          5                           dept_uid  string       10242          0     0.000000    10222      0.998047        False        False                     True         0.000195
5          6                      major_group_7     str       10099        143     1.396212        7      0.000693        False        False                    False         0.257957
6          7                        school_type  string        8561       1681    16.412810        5      0.000584        False        False                    False         0.812732
7          8                        region_sido  string        8561       1681    16.412810       17      0.001986        False        False                     True         0.164128
8          9                              split     str       10242          0     0.000000        3      0.000293        False        False                    False         0.735110
9         10          sample_P1_STRUCTURE_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.612185
10        11        sample_P1_SELECTIVITY_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.764109
11        12          sample_P2_STRUCTURE_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.835872
12        13        sample_P2_SELECTIVITY_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.687756
13        14          sample_P3_STRUCTURE_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.835872
14        15        sample_P3_SELECTIVITY_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.687756
15        16        sample_P4_E_STRUCTURE_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.612185
16        17        sample_P4_P_STRUCTURE_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.621558
17        18    sample_P4_JOINT_STRUCTURE_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.612185
18        19      sample_P4_E_SELECTIVITY_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.764109
19        20      sample_P4_P_SELECTIVITY_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.761863
20        21  sample_P4_JOINT_SELECTIVITY_READY    bool       10242          0     0.000000        2      0.000195        False        False                    False         0.764109

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10242 entries, 0 to 10241
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   outcome_row_id                     10242 non-null  str
 1   analysis_year                      10242 non-null  Int16
 2   school_uid                         10242 non-null  str
 3   campus_uid                         10242 non-null  string
 4   dept_uid                           10242 non-null  string
 5   major_group_7                      10099 non-null  str
 6   school_type                        8561 non-null   string
 7   region_sido                        8561 non-null   string
 8   split                              10242 non-null  str
 9   sample_P1_STRUCTURE_READY          10242 non-null  bool
 10  sample_P1_SELECTIVITY_READY        10242 non-null  bool
 11  sample_P2_STRUCTURE_READY          10242 non-null  bool
 12  sample_P2_SELECTIVITY_READY        10242 non-null  bool
 13  sample_P3_STRUCTURE_READY          10242 non-null  bool
 14  sample_P3_SELECTIVITY_READY        10242 non-null  bool
 15  sample_P4_E_STRUCTURE_READY        10242 non-null  bool
 16  sample_P4_P_STRUCTURE_READY        10242 non-null  bool
 17  sample_P4_JOINT_STRUCTURE_READY    10242 non-null  bool
 18  sample_P4_E_SELECTIVITY_READY      10242 non-null  bool
 19  sample_P4_P_SELECTIVITY_READY      10242 non-null  bool
 20  sample_P4_JOINT_SELECTIVITY_READY  10242 non-null  bool
dtypes: Int16(1), bool(12), str(4), string(4)
memory usage: 1.6 MB

### 5.5 Head

,outcome_row_id,analysis_year,school_uid,campus_uid,dept_uid,major_group_7,school_type,region_sido,split,sample_P1_STRUCTURE_READY,sample_P1_SELECTIVITY_READY,sample_P2_STRUCTURE_READY,sample_P2_SELECTIVITY_READY,sample_P3_STRUCTURE_READY,sample_P3_SELECTIVITY_READY,sample_P4_E_STRUCTURE_READY,sample_P4_P_STRUCTURE_READY,sample_P4_JOINT_STRUCTURE_READY,sample_P4_E_SELECTIVITY_READY,sample_P4_P_SELECTIVITY_READY,sample_P4_JOINT_SELECTIVITY_READY
0,OC2024_00001,2024,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_c02dd4a5678d,MED,대학교,경남,train,True,True,True,True,True,True,True,True,True,True,True,True
1,OC2024_00002,2024,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_e99f4ff43785,SOC,대학교,경남,train,True,False,True,False,True,False,True,True,True,False,False,False
2,OC2024_00003,2024,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_fca11c7fd249,SOC,대학교,경남,train,True,False,True,False,True,False,True,True,True,False,False,False
3,OC2024_00004,2024,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_4746d0bda0b9,ART,대학교,경남,train,True,False,True,False,True,False,True,True,True,False,False,False
4,OC2024_00005,2024,SCH_4fcb5ca730cd,CAM_60c4060f5f80,DEP_90eb7f613e75,MED,대학교,경남,train,True,False,True,False,True,False,True,True,True,False,False,False

### 5.6 Tail

,outcome_row_id,analysis_year,school_uid,campus_uid,dept_uid,major_group_7,school_type,region_sido,split,sample_P1_STRUCTURE_READY,sample_P1_SELECTIVITY_READY,sample_P2_STRUCTURE_READY,sample_P2_SELECTIVITY_READY,sample_P3_STRUCTURE_READY,sample_P3_SELECTIVITY_READY,sample_P4_E_STRUCTURE_READY,sample_P4_P_STRUCTURE_READY,sample_P4_JOINT_STRUCTURE_READY,sample_P4_E_SELECTIVITY_READY,sample_P4_P_SELECTIVITY_READY,sample_P4_JOINT_SELECTIVITY_READY
10237,OC2024_10238,2024,SCH_35d77d3b6c8e,CAM_2fbc8e4c3911,DEP_0843ff8846b4,MED,<NA>,<NA>,train,False,False,False,False,False,False,False,False,False,False,False,False
10238,OC2024_10239,2024,SCH_35d77d3b6c8e,CAM_f83c793bedfd,DEP_0628482f77c4,HUM,대학교,경기,train,False,False,True,True,True,True,False,False,False,False,False,False
10239,OC2024_10240,2024,SCH_35d77d3b6c8e,CAM_f83c793bedfd,DEP_a06d4e12b67e,NAT,대학교,경기,train,False,False,True,True,True,True,False,False,False,False,False,False
10240,OC2024_10241,2024,SCH_35d77d3b6c8e,CAM_f83c793bedfd,DEP_94ace6bdfef1,ENG,대학교,경기,train,True,False,True,False,True,False,True,True,True,False,False,False
10241,OC2024_10242,2024,SCH_35d77d3b6c8e,CAM_f83c793bedfd,DEP_553cedacbfaa,ENG,대학교,경기,train,False,False,True,False,True,False,False,False,False,False,False,False

### 5.7 Random Sample

,outcome_row_id,analysis_year,school_uid,campus_uid,dept_uid,major_group_7,school_type,region_sido,split,sample_P1_STRUCTURE_READY,sample_P1_SELECTIVITY_READY,sample_P2_STRUCTURE_READY,sample_P2_SELECTIVITY_READY,sample_P3_STRUCTURE_READY,sample_P3_SELECTIVITY_READY,sample_P4_E_STRUCTURE_READY,sample_P4_P_STRUCTURE_READY,sample_P4_JOINT_STRUCTURE_READY,sample_P4_E_SELECTIVITY_READY,sample_P4_P_SELECTIVITY_READY,sample_P4_JOINT_SELECTIVITY_READY
1867,OC2024_01868,2024,SCH_6a3a99a48782,CAM_da41d915b48f,DEP_6dbe7995ac9b,HUM,대학교,광주,train,True,False,True,False,True,False,True,True,True,False,False,False
1158,OC2024_01159,2024,SCH_bd24ab6964ce,CAM_61ef2ce04720,DEP_8603fa45094a,NAT,대학교,경남,train,True,True,True,True,True,True,True,True,True,True,True,True
6704,OC2024_06705,2024,SCH_8c0fe037a811,CAM_cd6488ffd347,DEP_5676050ae761,ART,대학교,서울,train,True,True,True,True,True,True,True,True,True,True,True,True
8954,OC2024_08955,2024,SCH_8eaffeb1f469,CAM_deb9b8555416,DEP_802c18fec5aa,ENG,대학교,충북,train,True,True,True,True,True,True,True,True,True,True,True,True
2915,OC2024_02916,2024,SCH_b3c5162386a0,CAM_d737a74d7150,DEP_92790e042348,NAT,대학교,경북,test,False,False,True,False,True,False,False,False,False,False,False,False
1091,OC2024_01092,2024,SCH_bd24ab6964ce,CAM_e9c41a32b5a4,DEP_97ba9fdc7b8f,ENG,대학교,경남,train,True,True,True,True,True,True,True,True,True,True,True,True
1457,OC2024_01458,2024,SCH_c82adbe73aeb,CAM_153004ff9506,DEP_c67eb52f5b0a,HUM,대학교,서울,train,True,False,True,False,True,False,True,True,True,False,False,False
626,OC2024_00627,2024,SCH_708f797d9c02,CAM_bb779fca2250,DEP_054cf8c8437e,SOC,대학교,충남,test,False,False,True,True,True,True,False,False,False,False,False,False
7393,OC2024_07394,2024,SCH_38a7fe8ddf6c,CAM_3a3327adcafd,DEP_d72a895b79e5,EDU,대학교,경북,val,True,False,True,False,True,False,True,True,True,False,False,False
6069,OC2024_06070,2024,SCH_406e2951a18f,CAM_56ae2e962361,DEP_7ba417c7081d,SOC,대학교,광주,test,True,False,True,False,True,False,True,True,True,False,False,False

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,analysis_year,"10,242.000000","2,024.000000",0.000000,"2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000","2,024.000000",0,0.000000,0,0.000000,0,0,1

### 5.8 Categorical/String/Boolean Describe

                               column   dtype  count  missing_n  missing_pct  nunique               top  freq   top_pct                                                                                 sample_values
0                      outcome_row_id     str  10242          0     0.000000    10242      OC2024_00001     1  0.009764                      OC2024_00001 | OC2024_00002 | OC2024_00003 | OC2024_00004 | OC2024_00005
1                          school_uid     str  10242          0     0.000000      200  SCH_193517d15ce2   217  2.118727  SCH_4fcb5ca730cd | SCH_e46f0f22fdd7 | SCH_f0a7062f14b7 | SCH_11568cc95743 | SCH_f11056a7ff4e
2                          campus_uid  string  10242          0     0.000000      452  CAM_f6396906ee8f   131  1.279047  CAM_60c4060f5f80 | CAM_40d7469e00a5 | CAM_aac084de6912 | CAM_6f177c7e5a77 | CAM_2ed1e6c2a9e7
3                            dept_uid  string  10242          0     0.000000    10222  DEP_608b06fc070c     2  0.019527  DEP_c02dd4a5678d | DEP_e99f4ff43785 | DEP_fca11c7fd249 | DEP_4746d0bda0b9 | DEP_90eb7f613e75
4                       major_group_7     str  10099        143     1.396212        7               ENG  2642 25.795743                                                                   MED | SOC | ART | NAT | EDU
5                         school_type  string   8561       1681    16.412810        5               대학교  8324 81.273189                                                        대학교 | 교육대학 | 각종대학(대학) | 산업대학 | 방송통신대학교
6                         region_sido  string   8561       1681    16.412810       17                서울  1629 15.905097                                                                        경남 | 인천 | 경기 | 강원 | 충북
7                               split     str  10242          0     0.000000        3             train  7529 73.511033                                                                            train | test | val
8           sample_P1_STRUCTURE_READY    bool  10242          0     0.000000        2              True  6270 61.218512                                                                                  True | False
9         sample_P1_SELECTIVITY_READY    bool  10242          0     0.000000        2             False  7826 76.410857                                                                                  True | False
10          sample_P2_STRUCTURE_READY    bool  10242          0     0.000000        2              True  8561 83.587190                                                                                  True | False
11        sample_P2_SELECTIVITY_READY    bool  10242          0     0.000000        2             False  7044 68.775630                                                                                  True | False
12          sample_P3_STRUCTURE_READY    bool  10242          0     0.000000        2              True  8561 83.587190                                                                                  True | False
13        sample_P3_SELECTIVITY_READY    bool  10242          0     0.000000        2             False  7044 68.775630                                                                                  True | False
14        sample_P4_E_STRUCTURE_READY    bool  10242          0     0.000000        2              True  6270 61.218512                                                                                  True | False
15        sample_P4_P_STRUCTURE_READY    bool  10242          0     0.000000        2              True  6366 62.155829                                                                                  True | False
16    sample_P4_JOINT_STRUCTURE_READY    bool  10242          0     0.000000        2              True  6270 61.218512                                                                                  True | False
17      sample_P4_E_SELECTIVITY_READY    bool  10242          0     0.000000        2             False  7826 76.410857                                                                                  True | False
18      sample_P4_P_SELECTIVITY_READY    bool  10242          0     0.000000        2             False  7803 76.186292                                                                                  True | False
19  sample_P4_JOINT_SELECTIVITY_READY    bool  10242          0     0.000000        2             False  7826 76.410857                                                                                  True | False

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

   rank         column   dtype  missing_n  missing_pct  non_null_n  nunique
6     1    school_type  string       1681    16.412810        8561        5
7     2    region_sido  string       1681    16.412810        8561       17
5     3  major_group_7     str        143     1.396212       10099        7

### 5.10 Top Cardinality Columns

                               column   dtype  nunique  unique_ratio
0                      outcome_row_id     str    10242      1.000000
4                            dept_uid  string    10222      0.998047
3                          campus_uid  string      452      0.044132
2                          school_uid     str      200      0.019527
7                         region_sido  string       17      0.001986
5                       major_group_7     str        7      0.000693
6                         school_type  string        5      0.000584
8                               split     str        3      0.000293
9           sample_P1_STRUCTURE_READY    bool        2      0.000195
10        sample_P1_SELECTIVITY_READY    bool        2      0.000195
11          sample_P2_STRUCTURE_READY    bool        2      0.000195
12        sample_P2_SELECTIVITY_READY    bool        2      0.000195
13          sample_P3_STRUCTURE_READY    bool        2      0.000195
14        sample_P3_SELECTIVITY_READY    bool        2      0.000195
15        sample_P4_E_STRUCTURE_READY    bool        2      0.000195
16        sample_P4_P_STRUCTURE_READY    bool        2      0.000195
17    sample_P4_JOINT_STRUCTURE_READY    bool        2      0.000195
18      sample_P4_E_SELECTIVITY_READY    bool        2      0.000195
19      sample_P4_P_SELECTIVITY_READY    bool        2      0.000195
20  sample_P4_JOINT_SELECTIVITY_READY    bool        2      0.000195
1                       analysis_year   Int16        1      0.000098

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

          column  dtype  nunique  top_value_share
1  analysis_year  Int16        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                               column                      check    nan_n  pos_inf_n  neg_inf_n  negative_n       zero_n  violation_n
0                       analysis_year              numeric_basic 0.000000   0.000000   0.000000    0.000000     0.000000            0
1                       analysis_year  year_reasonable_1900_2100      NaN        NaN        NaN         NaN          NaN            0
2           sample_P1_STRUCTURE_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 3,972.000000            0
3         sample_P1_SELECTIVITY_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 7,826.000000            0
4           sample_P2_STRUCTURE_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 1,681.000000            0
5         sample_P2_SELECTIVITY_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 7,044.000000            0
6           sample_P3_STRUCTURE_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 1,681.000000            0
7         sample_P3_SELECTIVITY_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 7,044.000000            0
8         sample_P4_E_STRUCTURE_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 3,972.000000            0
9         sample_P4_P_STRUCTURE_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 3,876.000000            0
10    sample_P4_JOINT_STRUCTURE_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 3,972.000000            0
11      sample_P4_E_SELECTIVITY_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 7,826.000000            0
12      sample_P4_P_SELECTIVITY_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 7,803.000000            0
13  sample_P4_JOINT_SELECTIVITY_READY              numeric_basic 0.000000   0.000000   0.000000    0.000000 7,826.000000            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 1

### 6.2 Sample Membership Additional Checks

                                 flag  true_n  false_n  na_n
0           sample_P1_STRUCTURE_READY    6270     3972     0
1         sample_P1_SELECTIVITY_READY    2416     7826     0
2           sample_P2_STRUCTURE_READY    8561     1681     0
3         sample_P2_SELECTIVITY_READY    3198     7044     0
4           sample_P3_STRUCTURE_READY    8561     1681     0
5         sample_P3_SELECTIVITY_READY    3198     7044     0
6         sample_P4_E_STRUCTURE_READY    6270     3972     0
7         sample_P4_P_STRUCTURE_READY    6366     3876     0
8     sample_P4_JOINT_STRUCTURE_READY    6270     3972     0
9       sample_P4_E_SELECTIVITY_READY    2416     7826     0
10      sample_P4_P_SELECTIVITY_READY    2439     7803     0
11  sample_P4_JOINT_SELECTIVITY_READY    2416     7826     0

  merge_status   rows
0         both  10242
1    left_only      0
2   right_only      0

## Dataset: `P4_PHASE_SAMPLE_REGISTRY_FINAL`

- 역할: Final phase sample registry
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv`
- 예상 shape: `(12, 11)`
- 예상 SHA256: `6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e`

In [ ]:
result = inspect_dataset(
    label='P4_PHASE_SAMPLE_REGISTRY_FINAL',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv',
    expected_shape=(12, 11),
    expected_sha256='6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e',
    candidate_keys=[['sample_id']],
)

extra_sample_registry()

### 5.1 File Identification - `P4_PHASE_SAMPLE_REGISTRY_FINAL`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_PHASE_SAMPLE_REGISTRY_FINAL,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,True,.csv,1587,2026-07-13T11:12:50.205743,6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e,6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e,True

### 5.2 Basic Structure

      shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (12, 11)       (12, 11)         True         12            11                2264       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0               sample_id            sample_id    True              0                   0                     0                12

### 5.3 Full Column List

    position               column  dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1            sample_id    str          12          0     0.000000       12      1.000000        False        False                     True         0.083333
1          2                row_n  int64          12          0     0.000000        6      0.500000        False        False                    False         0.250000
2          3             school_n  int64          12          0     0.000000        6      0.500000        False        False                    False         0.250000
3          4             campus_n  int64          12          0     0.000000        6      0.500000        False        False                    False         0.250000
4          5             major7_n  int64          12          0     0.000000        1      0.083333        False         True                    False         1.000000
5          6              train_n  int64          12          0     0.000000        6      0.500000        False        False                    False         0.250000
6          7         validation_n  int64          12          0     0.000000        6      0.500000        False        False                     True         0.250000
7          8               test_n  int64          12          0     0.000000        6      0.500000        False        False                    False         0.250000
8          9  excluded_conflict_n  int64          12          0     0.000000        1      0.083333        False         True                    False         1.000000
9         10          row_id_hash    str          12          0     0.000000        6      0.500000        False        False                     True         0.250000
10        11               status    str          12          0     0.000000        1      0.083333        False         True                    False         1.000000

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   sample_id            12 non-null     str
 1   row_n                12 non-null     int64
 2   school_n             12 non-null     int64
 3   campus_n             12 non-null     int64
 4   major7_n             12 non-null     int64
 5   train_n              12 non-null     int64
 6   validation_n         12 non-null     int64
 7   test_n               12 non-null     int64
 8   excluded_conflict_n  12 non-null     int64
 9   row_id_hash          12 non-null     str
 10  status               12 non-null     str
dtypes: int64(8), str(3)
memory usage: 2.2 KB

### 5.5 Head

              sample_id  row_n  school_n  campus_n  major7_n  train_n  validation_n  test_n  excluded_conflict_n                                                       row_id_hash status
0    P1_STRUCTURE_READY   6270       186       243         7     4623           932     715                    0  31b2ad6cfd737f45fcc2428c7354dfb76929bceeb9a3bdfadcf66d4a1b09c9e6  READY
1  P1_SELECTIVITY_READY   2416       130       159         7     1789           367     260                    0  ba507054b4fdbf198835ab9031f2d96fa3ec543b389a9bbc821b9592183e6af1  READY
2    P2_STRUCTURE_READY   8561       198       262         7     6302          1263     996                    0  864a2537e35494e94735bd777a3db0f6d78213fe4bffbabf458f36ed7fb6fb2f  READY
3  P2_SELECTIVITY_READY   3198       146       179         7     2355           522     321                    0  ae80c878bd544fcc721bd6fda90bde287de48a7e7be79565c11b43d60ecbd229  READY
4    P3_STRUCTURE_READY   8561       198       262         7     6302          1263     996                    0  864a2537e35494e94735bd777a3db0f6d78213fe4bffbabf458f36ed7fb6fb2f  READY

### 5.6 Tail

                     sample_id  row_n  school_n  campus_n  major7_n  train_n  validation_n  test_n  excluded_conflict_n                                                       row_id_hash status
7         P4_P_STRUCTURE_READY   6366       195       255         7     4687           949     730                    0  5436cdb1b8b99f325aa93cc6f6f9a47e70c82140a8922022eeb2b7a9d03be3ea  READY
8     P4_JOINT_STRUCTURE_READY   6270       186       243         7     4623           932     715                    0  31b2ad6cfd737f45fcc2428c7354dfb76929bceeb9a3bdfadcf66d4a1b09c9e6  READY
9       P4_E_SELECTIVITY_READY   2416       130       159         7     1789           367     260                    0  ba507054b4fdbf198835ab9031f2d96fa3ec543b389a9bbc821b9592183e6af1  READY
10      P4_P_SELECTIVITY_READY   2439       136       165         7     1805           372     262                    0  aceba0efbdf07723e0a68bd78dd594d0ffee6a4c810afe80ddbc7e60e7bb9c78  READY
11  P4_JOINT_SELECTIVITY_READY   2416       130       159         7     1789           367     260                    0  ba507054b4fdbf198835ab9031f2d96fa3ec543b389a9bbc821b9592183e6af1  READY

### 5.7 Random Sample

                     sample_id  row_n  school_n  campus_n  major7_n  train_n  validation_n  test_n  excluded_conflict_n                                                       row_id_hash status
11  P4_JOINT_SELECTIVITY_READY   2416       130       159         7     1789           367     260                    0  ba507054b4fdbf198835ab9031f2d96fa3ec543b389a9bbc821b9592183e6af1  READY
4           P3_STRUCTURE_READY   8561       198       262         7     6302          1263     996                    0  864a2537e35494e94735bd777a3db0f6d78213fe4bffbabf458f36ed7fb6fb2f  READY
0           P1_STRUCTURE_READY   6270       186       243         7     4623           932     715                    0  31b2ad6cfd737f45fcc2428c7354dfb76929bceeb9a3bdfadcf66d4a1b09c9e6  READY
6         P4_E_STRUCTURE_READY   6270       186       243         7     4623           932     715                    0  31b2ad6cfd737f45fcc2428c7354dfb76929bceeb9a3bdfadcf66d4a1b09c9e6  READY
2           P2_STRUCTURE_READY   8561       198       262         7     6302          1263     996                    0  864a2537e35494e94735bd777a3db0f6d78213fe4bffbabf458f36ed7fb6fb2f  READY
1         P1_SELECTIVITY_READY   2416       130       159         7     1789           367     260                    0  ba507054b4fdbf198835ab9031f2d96fa3ec543b389a9bbc821b9592183e6af1  READY
3         P2_SELECTIVITY_READY   3198       146       179         7     2355           522     321                    0  ae80c878bd544fcc721bd6fda90bde287de48a7e7be79565c11b43d60ecbd229  READY
5         P3_SELECTIVITY_READY   3198       146       179         7     2355           522     321                    0  ae80c878bd544fcc721bd6fda90bde287de48a7e7be79565c11b43d60ecbd229  READY
9       P4_E_SELECTIVITY_READY   2416       130       159         7     1789           367     260                    0  ba507054b4fdbf198835ab9031f2d96fa3ec543b389a9bbc821b9592183e6af1  READY
7         P4_P_STRUCTURE_READY   6366       195       255         7     4687           949     730                    0  5436cdb1b8b99f325aa93cc6f6f9a47e70c82140a8922022eeb2b7a9d03be3ea  READY

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,row_n,12.000000,"4,865.083333","2,429.589657","2,416.000000","2,416.000000","2,416.000000","2,416.000000","2,433.250000","4,734.000000","6,294.000000","8,341.500000","8,561.000000","8,561.000000","8,561.000000",0,0.000000,0,0.000000,0,0,6
1,school_n,12.000000,163.916667,29.580271,130.000000,130.000000,130.000000,130.000000,134.500000,166.000000,188.250000,197.700000,198.000000,198.000000,198.000000,0,0.000000,0,0.000000,0,0,6
2,campus_n,12.000000,209.000000,45.164346,159.000000,159.000000,159.000000,159.000000,163.500000,211.000000,246.000000,261.300000,262.000000,262.000000,262.000000,0,0.000000,0,0.000000,0,0,6
3,major7_n,12.000000,7.000000,0.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,0,0.000000,0,0.000000,0,0,1
4,train_n,12.000000,"3,586.833333","1,785.851507","1,789.000000","1,789.000000","1,789.000000","1,789.000000","1,801.000000","3,489.000000","4,639.000000","6,140.500000","6,302.000000","6,302.000000","6,302.000000",0,0.000000,0,0.000000,0,0,6
5,validation_n,12.000000,732.333333,350.127855,367.000000,367.000000,367.000000,367.000000,370.750000,727.000000,936.250000,"1,231.600000","1,263.000000","1,263.000000","1,263.000000",0,0.000000,0,0.000000,0,0,6
6,test_n,12.000000,545.916667,294.160271,260.000000,260.000000,260.000000,260.000000,261.500000,518.000000,718.750000,969.400000,996.000000,996.000000,996.000000,0,0.000000,0,0.000000,0,0,6
7,excluded_conflict_n,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,12,100.000000,0,0,1

### 5.8 Categorical/String/Boolean Describe

,column,dtype,count,missing_n,missing_pct,nunique,top,freq,top_pct,sample_values
0,sample_id,str,12,0,0.000000,12,P1_STRUCTURE_READY,1,8.333333,P1_STRUCTURE_READY | P1_SELECTIVITY_READY | P2_STRUCTURE_READY | P2_SELECTIVITY_READY | P3_STRUCTURE_READY
1,row_id_hash,str,12,0,0.000000,6,31b2ad6cfd737f45fcc2428c7354dfb76929bceeb9a3bdfadcf66d4a1b09c9e6,3,25.000000,31b2ad6cfd737f45fcc2428c7354dfb76929bceeb9a3bdfadcf66d4a1b09c9e6 | ba507054b4fdbf198835ab9031f2d96fa3ec543b389a9bbc8...
2,status,str,12,0,0.000000,1,READY,12,100.000000,READY

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

No missing values

### 5.10 Top Cardinality Columns

                 column  dtype  nunique  unique_ratio
0             sample_id    str       12      1.000000
1                 row_n  int64        6      0.500000
2              school_n  int64        6      0.500000
3              campus_n  int64        6      0.500000
5               train_n  int64        6      0.500000
6          validation_n  int64        6      0.500000
7                test_n  int64        6      0.500000
9           row_id_hash    str        6      0.500000
4              major7_n  int64        1      0.083333
8   excluded_conflict_n  int64        1      0.083333
10               status    str        1      0.083333

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

                 column  dtype  nunique  top_value_share
4              major7_n  int64        1         1.000000
8   excluded_conflict_n  int64        1         1.000000
10               status    str        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                 column              check    nan_n  pos_inf_n  neg_inf_n  negative_n    zero_n  violation_n
0                 row_n      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
1                 row_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
2              school_n      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
3              school_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
4              campus_n      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
5              campus_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
6              major7_n      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
7              major7_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
8               train_n      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
9               train_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
10         validation_n      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
11         validation_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
12               test_n      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
13               test_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
14  excluded_conflict_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 12.000000            0
15  excluded_conflict_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 3

### 6.3 Sample Registry Recalculation

                     sample_id  registry_row_n  actual_row_n  diff_row_n  registry_school_n  actual_school_n  diff_school_n  registry_train_n  actual_train_n  registry_validation_n  actual_validation_n  registry_test_n  actual_test_n
0           P1_STRUCTURE_READY            6270          6270           0                186              186              0              4623            4623                    932                  932              715            715
1         P1_SELECTIVITY_READY            2416          2416           0                130              130              0              1789            1789                    367                  367              260            260
2           P2_STRUCTURE_READY            8561          8561           0                198              198              0              6302            6302                   1263                 1263              996            996
3         P2_SELECTIVITY_READY            3198          3198           0                146              146              0              2355            2355                    522                  522              321            321
4           P3_STRUCTURE_READY            8561          8561           0                198              198              0              6302            6302                   1263                 1263              996            996
5         P3_SELECTIVITY_READY            3198          3198           0                146              146              0              2355            2355                    522                  522              321            321
6         P4_E_STRUCTURE_READY            6270          6270           0                186              186              0              4623            4623                    932                  932              715            715
7         P4_P_STRUCTURE_READY            6366          6366           0                195              195              0              4687            4687                    949                  949              730            730
8     P4_JOINT_STRUCTURE_READY            6270          6270           0                186              186              0              4623            4623                    932                  932              715            715
9       P4_E_SELECTIVITY_READY            2416          2416           0                130              130              0              1789            1789                    367                  367              260            260
10      P4_P_SELECTIVITY_READY            2439          2439           0                136              136              0              1805            1805                    372                  372              262            262
11  P4_JOINT_SELECTIVITY_READY            2416          2416           0                130              130              0              1789            1789                    367                  367              260            260

## Dataset: `department_model_column_registry_v4`

- 역할: Final column registry with OTHER resolved
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv`
- 예상 shape: `(151, 22)`
- 예상 SHA256: `ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94`

In [ ]:
result = inspect_dataset(
    label='department_model_column_registry_v4',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv',
    expected_shape=(151, 22),
    expected_sha256='ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94',
    candidate_keys=[['column']],
)

extra_column_registry()

### 5.1 File Identification - `department_model_column_registry_v4`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,department_model_column_registry_v4,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv,True,.csv,58300,2026-07-13T11:12:50.014680,ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94,ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94,True

### 5.2 Basic Structure

       shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (151, 22)      (151, 22)         True        151            22               67226       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0                  column               column    True              0                   0                     0               151

### 5.3 Full Column List

    position                column    dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1                column      str         151          0     0.000000      151      1.000000        False        False                    False         0.006623
1          2          dtype_actual      str         151          0     0.000000       10      0.066225        False        False                    False         0.377483
2          3         semantic_role      str         151          0     0.000000       16      0.105960        False        False                    False         0.185430
3          4         feature_block      str         151          0     0.000000       12      0.079470        False        False                    False         0.218543
4          5     measurement_level      str         151          0     0.000000        5      0.033113        False        False                    False         0.291391
5          6                 grain      str         151          0     0.000000        1      0.006623        False         True                    False         1.000000
6          7                  unit      str         151          0     0.000000       10      0.066225        False        False                    False         0.231788
7          8        source_dataset      str         151          0     0.000000        5      0.033113        False        False                    False         0.337748
8          9         source_column      str         151          0     0.000000      150      0.993377        False        False                    False         0.013245
9         10    derivation_formula      str          53         98    64.900662       12      0.226415        False        False                    False         0.649007
10        11           null_policy      str         151          0     0.000000        5      0.033113        False        False                    False         0.350993
11        12           zero_policy      str         151          0     0.000000        4      0.026490        False        False                    False         0.569536
12        13             valid_min  float64          92         59    39.072848       41      0.445652        False        False                     True         0.390728
13        14             valid_max  float64          92         59    39.072848       63      0.684783        False        False                     True         0.390728
14        15         is_identifier     bool         151          0     0.000000        2      0.013245        False        False                     True         0.821192
15        16   is_target_candidate     bool         151          0     0.000000        2      0.013245        False        False                     True         0.920530
16        17        is_denominator     bool         151          0     0.000000        2      0.013245        False        False                    False         0.900662
17        18            is_context     bool         151          0     0.000000        2      0.013245        False        False                    False         0.529801
18        19   is_quality_metadata     bool         151          0     0.000000        2      0.013245        False        False                    False         0.781457
19        20  model_default_active     bool         151          0     0.000000        2      0.013245        False        False                    False         0.516556
20        21       review_required     bool         151          0     0.000000        2      0.013245        False        False                    False         0.913907
21        22                 notes      str         151          0     0.000000       12      0.079470        False        False                    False         0.735099

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   column                151 non-null    str
 1   dtype_actual          151 non-null    str
 2   semantic_role         151 non-null    str
 3   feature_block         151 non-null    str
 4   measurement_level     151 non-null    str
 5   grain                 151 non-null    str
 6   unit                  151 non-null    str
 7   source_dataset        151 non-null    str
 8   source_column         151 non-null    str
 9   derivation_formula    53 non-null     str
 10  null_policy           151 non-null    str
 11  zero_policy           151 non-null    str
 12  valid_min             92 non-null     float64
 13  valid_max             92 non-null     float64
 14  is_identifier         151 non-null    bool
 15  is_target_candidate   151 non-null    bool
 16  is_denominator        151 non-null    bool
 17  is_context            151 non-null    bool
 18  is_quality_metadata   151 non-null    bool
 19  model_default_active  151 non-null    bool
 20  review_required       151 non-null    bool
 21  notes                 151 non-null    str
dtypes: bool(7), float64(2), str(13)
memory usage: 65.7 KB

### 5.5 Head

,column,dtype_actual,semantic_role,feature_block,measurement_level,grain,unit,source_dataset,source_column,derivation_formula,null_policy,zero_policy,valid_min,valid_max,is_identifier,is_target_candidate,is_denominator,is_context,is_quality_metadata,model_default_active,review_required,notes
0,analysis_year,Int16,identifier_or_label,K,department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,id_or_label,D01_v2,analysis_year,NaN,"identifier/metadata; nulls audited, not imputed",not numeric or not applicable,"2,024.000000","2,024.000000",True,False,False,False,False,False,False,candidate_feature_or_context
1,outcome_row_id,str,identifier_or_label,K,department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,id_or_label,D02_v2,outcome_row_id,NaN,"identifier/metadata; nulls audited, not imputed",not numeric or not applicable,NaN,NaN,True,False,False,False,False,False,False,identifier_label_or_qa_metadata
2,school_name_raw,string,identifier_or_label,K,department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,id_or_label,D01_v2,school_name_raw,NaN,"identifier/metadata; nulls audited, not imputed",not numeric or not applicable,NaN,NaN,True,False,False,False,False,False,False,identifier_label_or_qa_metadata
3,school_name_base_raw,string,identifier_or_label,K,department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,category,D02_v2,school_name_base_raw,NaN,feature candidate; impute only inside train-fitted preprocessing,not numeric or not applicable,NaN,NaN,True,False,False,False,False,False,False,Base school-name label; not a model feature.
4,school_name_std,string,identifier_or_label,K,department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,id_or_label,D01_v2,school_name_std,NaN,"identifier/metadata; nulls audited, not imputed",not numeric or not applicable,NaN,NaN,True,False,False,False,False,False,False,identifier_label_or_qa_metadata

### 5.6 Tail

,column,dtype_actual,semantic_role,feature_block,measurement_level,grain,unit,source_dataset,source_column,derivation_formula,null_policy,zero_policy,valid_min,valid_max,is_identifier,is_target_candidate,is_denominator,is_context,is_quality_metadata,model_default_active,review_required,notes
146,goms_latest_2019_permanent_pct,Float32,major7_historical_context,GOMS,major7,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,percent,D07_HANDOFF,latest_2019_permanent_pct,major_group_7 keyed historical GOMS recent profile merge,context; null means major7 context unavailable; no full-data imputation,0 is valid if source definition allows; range audited,63.099998,89.699997,False,False,False,True,False,True,False,candidate_feature_or_context
147,goms_source_years_observed,Int16,major7_historical_context,GOMS,major7,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,numeric,D07_HANDOFF,source_years_observed,major_group_7 keyed historical GOMS recent profile merge,context; null means major7 context unavailable; no full-data imputation,not numeric or not applicable,3.000000,3.000000,False,False,False,True,False,False,False,identifier_label_or_qa_metadata
148,goms_year_over_year_review_flag,boolean,major7_historical_context,GOMS,major7,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,numeric,D07_HANDOFF,year_over_year_review_flag,major_group_7 keyed historical GOMS recent profile merge,context; null means major7 context unavailable; no full-data imputation,not numeric or not applicable,0.000000,1.000000,False,False,False,True,False,False,False,identifier_label_or_qa_metadata
149,goms_mapping_confidence,category,major7_historical_context,GOMS,major7,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,numeric,D07_HANDOFF,mapping_confidence,major_group_7 keyed historical GOMS recent profile merge,context; null means major7 context unavailable; no full-data imputation,not numeric or not applicable,NaN,NaN,False,False,False,True,False,True,False,candidate_feature_or_context
150,goms_row_qa_status,category,major7_historical_context,GOMS,major7,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,numeric,D07_HANDOFF,row_qa_status,major_group_7 keyed historical GOMS recent profile merge,context; null means major7 context unavailable; no full-data imputation,not numeric or not applicable,NaN,NaN,False,False,False,True,False,True,False,candidate_feature_or_context

### 5.7 Random Sample

,column,dtype_actual,semantic_role,feature_block,measurement_level,grain,unit,source_dataset,source_column,derivation_formula,null_policy,zero_policy,valid_min,valid_max,is_identifier,is_target_candidate,is_denominator,is_context,is_quality_metadata,model_default_active,review_required,notes
52,headcount_match_flag,bool,match_or_review_metadata,QUALITY,row_quality,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,metadata,D03_v2,headcount_match_flag,NaN,"identifier/metadata; nulls audited, not imputed",not numeric or not applicable,0.000000,1.000000,False,False,False,False,True,False,False,candidate_feature_or_context
15,a_rate_pct,Float32,target_candidate_or_phase_signal,GRADE,department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,percent,D02_v2,a_rate_pct,NaN,target candidate; null means target not observed for that phase,0 is valid if source definition allows; range audited,0.000000,100.000000,False,True,False,False,False,False,True,Phase-specific target/signal only; exclude unless phase contract explicitly allows.
37,headcount_row_id,str,identifier_or_label,K,department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,id_or_label,D01_v2,headcount_row_id,NaN,"identifier/metadata; nulls audited, not imputed",not numeric or not applicable,NaN,NaN,True,False,False,False,False,False,False,identifier_label_or_qa_metadata
69,region_sigungu,string,stratification_feature,S0,school_department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,category,D01_v2,region_sigungu,NaN,feature candidate; impute only inside train-fitted preprocessing,not numeric or not applicable,NaN,NaN,False,False,False,True,False,True,False,candidate_feature_or_context
109,ctx24_mean_income_10kkrw,Float32,major7_2024_context,C24,major7_year,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,count_or_numeric,D04_v2,mean_income_10kkrw,major_group_7 keyed 2024 wage/job-cert context merge,context; null means major7 context unavailable; no full-data imputation,observed 0 is a true zero; denominator use requires >0 check,234.699997,328.100006,False,False,False,True,False,True,False,candidate_feature_or_context
90,leave_rate_pct,Float32,department_structure_feature,B,school_department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,percent,D01_v2,leave_rate_pct,leave_students_n / enrolled_students_n * 100 where enrolled_students_n > 0,feature candidate; impute only inside train-fitted preprocessing,0 is valid if source definition allows; range audited,0.000000,100.000000,False,False,False,True,False,True,False,candidate_feature_or_context
48,campus_conflict_flag,bool,match_or_review_metadata,QUALITY,row_quality,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,metadata,D03_v2,campus_conflict_flag,NaN,"identifier/metadata; nulls audited, not imputed",not numeric or not applicable,0.000000,1.000000,False,False,False,False,True,False,False,candidate_feature_or_context
114,ctx24_mid_company_pct,Float32,major7_2024_context,C24,major7_year,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,percent,D04_v2,mid_company_pct,major_group_7 keyed 2024 wage/job-cert context merge,context; null means major7 context unavailable; no full-data imputation,0 is valid if source definition allows; range audited,0.992846,11.050346,False,False,False,True,False,True,False,candidate_feature_or_context
30,source_file,str,identifier_or_label,K,department,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,id_or_label,D02_v2,source_file,NaN,"identifier/metadata; nulls audited, not imputed",not numeric or not applicable,NaN,NaN,True,False,False,False,False,False,False,identifier_label_or_qa_metadata
118,ctx24_cert_rate_pct,Float32,major7_2024_context,C24,major7_year,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,percent,D04_v2,cert_rate_pct,major_group_7 keyed 2024 wage/job-cert context merge,context; null means major7 context unavailable; no full-data imputation,0 is valid if source definition allows; range audited,25.100000,60.900002,False,False,False,True,False,True,False,candidate_feature_or_context

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,valid_min,92.000000,248.481994,"1,647.319108",-0.736263,-0.562764,0.000000,0.000000,0.000000,0.000000,4.800116,63.269164,225.239999,"3,236.660000","15,498.000000",59,39.072848,51,33.774834,3,0,41
1,valid_max,92.000000,"1,921.849997","8,618.847036",-0.317582,-0.168082,0.000000,0.655171,1.332680,47.708878,109.756756,"2,023.500000","7,243.200000","38,409.850000","72,776.000000",59,39.072848,6,3.973510,2,0,63

### 5.8 Categorical/String/Boolean Describe

,column,dtype,count,missing_n,missing_pct,nunique,top,freq,top_pct,sample_values
0,column,str,151,0,0.000000,151,analysis_year,1,0.662252,analysis_year | outcome_row_id | school_name_raw | school_name_base_raw | school_name_std
1,dtype_actual,str,151,0,0.000000,10,Float32,57,37.748344,Int16 | str | string | boolean | Float32
2,semantic_role,str,151,0,0.000000,16,major7_historical_context,28,18.543046,identifier_or_label | stratification_feature | policy_feature | selectivity_feature | target_candidate_or_phase_signal
3,feature_block,str,151,0,0.000000,12,QUALITY,33,21.854305,K | S0 | POLICY | Q | GRADE
4,measurement_level,str,151,0,0.000000,5,department,44,29.139073,department | school_department | row_quality | major7_year | major7
5,grain,str,151,0,0.000000,1,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id,151,100.000000,analysis_year + school_uid + campus_uid + dept_uid + outcome_row_id
6,unit,str,151,0,0.000000,10,percent,35,23.178808,id_or_label | category | flag | percent | metadata
7,source_dataset,str,151,0,0.000000,5,D01_v2,51,33.774834,D01_v2 | D02_v2 | D03_v2 | D04_v2 | D07_HANDOFF
8,source_column,str,151,0,0.000000,150,row_qa_status,2,1.324503,analysis_year | outcome_row_id | school_name_raw | school_name_base_raw | school_name_std
9,derivation_formula,str,53,98,64.900662,12,major_group_7 keyed historical GOMS recent profile merge,28,18.543046,applicants_n / recruitment_n where recruitment_n > 0 | admits_n / recruitment_n where recruitment_n > 0 | admits_n /...
10,null_policy,str,151,0,0.000000,5,"identifier/metadata; nulls audited, not imputed",53,35.099338,"identifier/metadata; nulls audited, not imputed | feature candidate; impute only inside train-fitted preprocessing |..."
11,zero_policy,str,151,0,0.000000,4,not numeric or not applicable,86,56.953642,not numeric or not applicable | False/0 is a valid category | 0 is valid if source definition allows; range audited ...
12,is_identifier,bool,151,0,0.000000,2,False,124,82.119205,True | False
13,is_target_candidate,bool,151,0,0.000000,2,False,139,92.052980,False | True
14,is_denominator,bool,151,0,0.000000,2,False,136,90.066225,False | True
15,is_context,bool,151,0,0.000000,2,True,80,52.980132,False | True
16,is_quality_metadata,bool,151,0,0.000000,2,False,118,78.145695,False | True
17,model_default_active,bool,151,0,0.000000,2,False,78,51.655629,False | True
18,review_required,bool,151,0,0.000000,2,False,138,91.390728,False | True
19,notes,str,151,0,0.000000,12,candidate_feature_or_context,111,73.509934,candidate_feature_or_context | identifier_label_or_qa_metadata | Base school-name label; not a model feature. | Raw ...

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

    rank              column    dtype  missing_n  missing_pct  non_null_n  nunique
9      1  derivation_formula      str         98    64.900662          53       12
12     2           valid_min  float64         59    39.072848          92       41
13     3           valid_max  float64         59    39.072848          92       63

### 5.10 Top Cardinality Columns

                  column    dtype  nunique  unique_ratio
0                 column      str      151      1.000000
8          source_column      str      150      0.993377
13             valid_max  float64       63      0.684783
12             valid_min  float64       41      0.445652
2          semantic_role      str       16      0.105960
9     derivation_formula      str       12      0.226415
3          feature_block      str       12      0.079470
21                 notes      str       12      0.079470
1           dtype_actual      str       10      0.066225
6                   unit      str       10      0.066225
4      measurement_level      str        5      0.033113
7         source_dataset      str        5      0.033113
10           null_policy      str        5      0.033113
11           zero_policy      str        4      0.026490
14         is_identifier     bool        2      0.013245
15   is_target_candidate     bool        2      0.013245
16        is_denominator     bool        2      0.013245
17            is_context     bool        2      0.013245
18   is_quality_metadata     bool        2      0.013245
19  model_default_active     bool        2      0.013245
20       review_required     bool        2      0.013245
5                  grain      str        1      0.006623

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

  column dtype  nunique  top_value_share
5  grain   str        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                 column          check  nan_n  pos_inf_n  neg_inf_n  negative_n  zero_n  violation_n
0             valid_min  numeric_basic     59          0          0           3      51            0
1             valid_max  numeric_basic     59          0          0           2       6            0
2         is_identifier  numeric_basic      0          0          0           0     124            0
3   is_target_candidate  numeric_basic      0          0          0           0     139            0
4        is_denominator  numeric_basic      0          0          0           0     136            0
5            is_context  numeric_basic      0          0          0           0      71            0
6   is_quality_metadata  numeric_basic      0          0          0           0     118            0
7  model_default_active  numeric_basic      0          0          0           0      78            0
8       review_required  numeric_basic      0          0          0           0     138            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 1

### 6.4 Column Registry Additional Checks

semantic_role

                       semantic_role  rows
0          major7_historical_context    28
1                identifier_or_label    27
2           match_or_review_metadata    24
3     count_or_denominator_candidate    15
4                major7_2024_context    15
5             stratification_feature    12
6   target_candidate_or_phase_signal    11
7       department_structure_feature     5
8            sample_observation_flag     3
9      admission_selectivity_feature     3
10    target_family_observation_flag     2
11            grain_lineage_metadata     2
12                    policy_feature     1
13               selectivity_feature     1
14    major_mapping_lineage_metadata     1
15         sample_exclusion_metadata     1

feature_block

   feature_block  rows
0        QUALITY    33
1           GOMS    28
2              K    27
3          DENOM    15
4            C24    15
5             S0    12
6           PROG     6
7              B     5
8              Q     4
9          GRADE     3
10           EMP     2
11        POLICY     1

measurement_level

   measurement_level  rows
0         department    44
1  school_department    35
2        row_quality    29
3             major7    28
4        major7_year    15

dtype_actual

  dtype_actual  rows
0      Float32    57
1       string    34
2          str    20
3        Int32    13
4      boolean     9
5        Int16     6
6         bool     6
7     category     4
8      float64     1
9        int64     1

model_default_active

   model_default_active  rows
0                 False    78
1                  True    73

review_required

   review_required  rows
0            False   138
1             True    13

   OTHER_count  feature_block_missing  dtype_missing  source_missing  duplicate_column_rows
0            0                      0              0               0                      0

## Dataset: `P4_PHASE_FEATURE_SET_FINAL`

- 역할: Final phase-model feature set
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv`
- 예상 shape: `(250, 11)`
- 예상 SHA256: `dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320`

In [ ]:
result = inspect_dataset(
    label='P4_PHASE_FEATURE_SET_FINAL',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv',
    expected_shape=(250, 11),
    expected_sha256='dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320',
    candidate_keys=[['model_id', 'feature'], ['phase', 'model_id', 'feature']],
)

extra_feature_set()

### 5.1 File Identification - `P4_PHASE_FEATURE_SET_FINAL`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_PHASE_FEATURE_SET_FINAL,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FIN...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv,True,.csv,39889,2026-07-13T11:12:50.386869,dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320,dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320,True

### 5.2 Basic Structure

       shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (250, 11)      (250, 11)         True        250            11               56448       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

      candidate_key_requested        candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0          model_id + feature          model_id + feature    True              0                   0                     0               250
1  phase + model_id + feature  phase + model_id + feature    True              0                   0                     0               250

### 5.3 Full Column List

    position                  column dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1                model_id   str         250          0     0.000000       18      0.072000        False        False                     True         0.068000
1          2                   phase   str         250          0     0.000000        5      0.020000        False        False                    False         0.336000
2          3               sample_id   str         250          0     0.000000       12      0.048000        False        False                     True         0.128000
3          4                  target   str         250          0     0.000000        3      0.012000        False        False                    False         0.336000
4          5                 feature   str         250          0     0.000000       20      0.080000        False        False                    False         0.072000
5          6           feature_block   str         250          0     0.000000        8      0.032000        False        False                    False         0.360000
6          7            feature_role   str         250          0     0.000000        2      0.008000        False        False                    False         0.936000
7          8    included_in_contract  bool         250          0     0.000000        1      0.004000        False         True                    False         1.000000
8          9                  reason   str         250          0     0.000000        7      0.028000        False        False                    False         0.360000
9         10         source_decision   str         246          4     1.600000        2      0.008130        False        False                    False         0.936000
10        11  source_decision_reason   str         246          4     1.600000        5      0.020325        False        False                    False         0.360000

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   model_id                250 non-null    str
 1   phase                   250 non-null    str
 2   sample_id               250 non-null    str
 3   target                  250 non-null    str
 4   feature                 250 non-null    str
 5   feature_block           250 non-null    str
 6   feature_role            250 non-null    str
 7   included_in_contract    250 non-null    bool
 8   reason                  250 non-null    str
 9   source_decision         246 non-null    str
 10  source_decision_reason  246 non-null    str
dtypes: bool(1), str(10)
memory usage: 55.1 KB

### 5.5 Head

       model_id phase           sample_id      target                     feature feature_block feature_role  included_in_contract                reason source_decision         source_decision_reason
0  P1_STRUCTURE    P1  P1_STRUCTURE_READY  a_rate_pct               campus_branch            S0      control                  True      allowed_block_S0         INCLUDE      allowed_S0_source_feature
1  P1_STRUCTURE    P1  P1_STRUCTURE_READY  a_rate_pct         credit_forfeit_flag        POLICY      control                  True  allowed_block_POLICY         INCLUDE  allowed_POLICY_source_feature
2  P1_STRUCTURE    P1  P1_STRUCTURE_READY  a_rate_pct               degree_course            S0      control                  True      allowed_block_S0         INCLUDE      allowed_S0_source_feature
3  P1_STRUCTURE    P1  P1_STRUCTURE_READY  a_rate_pct    female_student_share_pct             B      control                  True       allowed_block_B         INCLUDE       allowed_B_source_feature
4  P1_STRUCTURE    P1  P1_STRUCTURE_READY  a_rate_pct  fulltime_faculty_share_pct             B      control                  True       allowed_block_B         INCLUDE       allowed_B_source_feature

### 5.6 Tail

,model_id,phase,sample_id,target,feature,feature_block,feature_role,included_in_contract,reason,source_decision,source_decision_reason
245,P4_P_JOINT_SELECTIVITY_A_RATE,P4_P,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,major_group_7,S0,control,True,allowed_block_S0,INCLUDE,allowed_S0_source_feature
246,P4_P_JOINT_SELECTIVITY_A_RATE,P4_P,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,region_sido,S0,control,True,allowed_block_S0,INCLUDE,allowed_S0_source_feature
247,P4_P_JOINT_SELECTIVITY_A_RATE,P4_P,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,school_type,S0,control,True,allowed_block_S0,INCLUDE,allowed_S0_source_feature
248,P4_P_JOINT_SELECTIVITY_A_RATE,P4_P,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,selectivity_proxy_pct,Q,control,True,allowed_block_Q,INCLUDE,allowed_Q_source_feature
249,P4_P_JOINT_SELECTIVITY_A_RATE,P4_P,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,student_faculty_ratio,B,control,True,allowed_block_B,INCLUDE,allowed_B_source_feature

### 5.7 Random Sample

,model_id,phase,sample_id,target,feature,feature_block,feature_role,included_in_contract,reason,source_decision,source_decision_reason
158,P4_P_STRUCTURE_RESIDUAL,P4_P,P4_P_STRUCTURE_READY,graduate_school_progression_rate_pct,major_group_7,S0,control,True,allowed_block_S0,INCLUDE,allowed_S0_source_feature
199,P4_E_JOINT_STRUCTURE_A_RATE,P4_E,P4_JOINT_STRUCTURE_READY,health_employment_rate_pct,fulltime_faculty_share_pct,B,control,True,allowed_block_B,INCLUDE,allowed_B_source_feature
120,P4_E_SELECTIVITY_A_RATE,P4_E,P4_E_SELECTIVITY_READY,health_employment_rate_pct,selectivity_proxy_pct,Q,control,True,allowed_block_Q,INCLUDE,allowed_Q_source_feature
73,P3_Q,P3,P3_SELECTIVITY_READY,a_rate_pct,female_student_share_pct,B,control,True,allowed_block_B,INCLUDE,allowed_B_source_feature
110,P4_E_SELECTIVITY_A_RATE,P4_E,P4_E_SELECTIVITY_READY,health_employment_rate_pct,competition_ratio,Q,control,True,allowed_block_Q,INCLUDE,allowed_Q_source_feature
36,P2_S,P2,P2_STRUCTURE_READY,a_rate_pct,leave_rate_pct,B,control,True,allowed_block_B,INCLUDE,allowed_B_source_feature
68,P3_Q,P3,P3_SELECTIVITY_READY,a_rate_pct,admit_per_applicant_ratio,Q,control,True,allowed_block_Q,INCLUDE,allowed_Q_source_feature
228,P4_E_JOINT_SELECTIVITY_A_RATE,P4_E,P4_JOINT_SELECTIVITY_READY,health_employment_rate_pct,leave_rate_pct,B,control,True,allowed_block_B,INCLUDE,allowed_B_source_feature
219,P4_E_JOINT_SELECTIVITY_A_RATE,P4_E,P4_JOINT_SELECTIVITY_READY,health_employment_rate_pct,admission_yield_ratio,Q,control,True,allowed_block_Q,INCLUDE,allowed_Q_source_feature
14,P1_SELECTIVITY,P1,P1_SELECTIVITY_READY,a_rate_pct,admit_per_applicant_ratio,Q,control,True,allowed_block_Q,INCLUDE,allowed_Q_source_feature

### 5.8 Numeric Describe

              message
0  No numeric columns

### 5.8 Categorical/String/Boolean Describe

                    column dtype  count  missing_n  missing_pct  nunique                         top  freq    top_pct                                                                                                            sample_values
0                 model_id   str    250          0     0.000000       18              P1_SELECTIVITY    17   6.800000                                                                       P1_STRUCTURE | P1_SELECTIVITY | P2_S | P2_Q | P3_S
1                    phase   str    250          0     0.000000        5                        P4_E    84  33.600000                                                                                               P1 | P2 | P3 | P4_E | P4_P
2                sample_id   str    250          0     0.000000       12      P4_E_SELECTIVITY_READY    32  12.800000               P1_STRUCTURE_READY | P1_SELECTIVITY_READY | P2_STRUCTURE_READY | P2_SELECTIVITY_READY | P3_STRUCTURE_READY
3                   target   str    250          0     0.000000        3  health_employment_rate_pct    84  33.600000                                           a_rate_pct | health_employment_rate_pct | graduate_school_progression_rate_pct
4                  feature   str    250          0     0.000000       20               campus_branch    18   7.200000              campus_branch | credit_forfeit_flag | degree_course | female_student_share_pct | fulltime_faculty_share_pct
5            feature_block   str    250          0     0.000000        8                          S0    90  36.000000                                                                                             S0 | POLICY | B | PROG | EMP
6             feature_role   str    250          0     0.000000        2                     control   234  93.600000                                                                                                   control | grade_signal
7     included_in_contract  bool    250          0     0.000000        1                        True   250 100.000000                                                                                                                     True
8                   reason   str    250          0     0.000000        7            allowed_block_S0    90  36.000000              allowed_block_S0 | allowed_block_POLICY | allowed_block_B | same_time_alignment_noncausal | allowed_block_Q
9          source_decision   str    246          4     1.600000        2                     INCLUDE   234  93.600000                                                                                                        INCLUDE | EXCLUDE
10  source_decision_reason   str    246          4     1.600000        5   allowed_S0_source_feature    90  36.000000  allowed_S0_source_feature | allowed_POLICY_source_feature | allowed_B_source_feature | target_or_outcome_signal_only...

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

    rank                  column dtype  missing_n  missing_pct  non_null_n  nunique
9      1         source_decision   str          4     1.600000         246        2
10     2  source_decision_reason   str          4     1.600000         246        5

### 5.10 Top Cardinality Columns

                    column dtype  nunique  unique_ratio
4                  feature   str       20      0.080000
0                 model_id   str       18      0.072000
2                sample_id   str       12      0.048000
5            feature_block   str        8      0.032000
8                   reason   str        7      0.028000
10  source_decision_reason   str        5      0.020325
1                    phase   str        5      0.020000
3                   target   str        3      0.012000
9          source_decision   str        2      0.008130
6             feature_role   str        2      0.008000
7     included_in_contract  bool        1      0.004000

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

                 column dtype  nunique  top_value_share
7  included_in_contract  bool        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                 column          check  nan_n  pos_inf_n  neg_inf_n  negative_n  zero_n  violation_n
0  included_in_contract  numeric_basic      0          0          0           0       0            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 1

### 6.5 Feature Set Additional Checks

                         model_id                                target  feature_count  allowed_count
0                  P1_SELECTIVITY                            a_rate_pct             17             17
1                    P1_STRUCTURE                            a_rate_pct             13             13
2                            P2_Q                            a_rate_pct             15             15
3                            P2_S                            a_rate_pct             11             11
4                            P3_Q                            a_rate_pct             15             15
5                            P3_S                            a_rate_pct             11             11
6   P4_E_JOINT_SELECTIVITY_A_RATE            health_employment_rate_pct             16             16
7     P4_E_JOINT_STRUCTURE_A_RATE            health_employment_rate_pct             12             12
8         P4_E_SELECTIVITY_A_RATE            health_employment_rate_pct             16             16
9       P4_E_SELECTIVITY_RESIDUAL            health_employment_rate_pct             16             16
10          P4_E_STRUCTURE_A_RATE            health_employment_rate_pct             12             12
11        P4_E_STRUCTURE_RESIDUAL            health_employment_rate_pct             12             12
12  P4_P_JOINT_SELECTIVITY_A_RATE  graduate_school_progression_rate_pct             16             16
13    P4_P_JOINT_STRUCTURE_A_RATE  graduate_school_progression_rate_pct             12             12
14        P4_P_SELECTIVITY_A_RATE  graduate_school_progression_rate_pct             16             16
15      P4_P_SELECTIVITY_RESIDUAL  graduate_school_progression_rate_pct             16             16
16          P4_P_STRUCTURE_A_RATE  graduate_school_progression_rate_pct             12             12
17        P4_P_STRUCTURE_RESIDUAL  graduate_school_progression_rate_pct             12             12

Block count by model

                         model_id feature_block  feature_n
0                  P1_SELECTIVITY             B          5
1                  P1_SELECTIVITY           EMP          1
2                  P1_SELECTIVITY        POLICY          1
3                  P1_SELECTIVITY          PROG          1
4                  P1_SELECTIVITY             Q          4
5                  P1_SELECTIVITY            S0          5
6                    P1_STRUCTURE             B          5
7                    P1_STRUCTURE           EMP          1
8                    P1_STRUCTURE        POLICY          1
9                    P1_STRUCTURE          PROG          1
10                   P1_STRUCTURE            S0          5
11                           P2_Q             B          5
12                           P2_Q        POLICY          1
13                           P2_Q             Q          4
14                           P2_Q            S0          5
15                           P2_S             B          5
16                           P2_S        POLICY          1
17                           P2_S            S0          5
18                           P3_Q             B          5
19                           P3_Q        POLICY          1
20                           P3_Q             Q          4
21                           P3_Q            S0          5
22                           P3_S             B          5
23                           P3_S        POLICY          1
24                           P3_S            S0          5
25  P4_E_JOINT_SELECTIVITY_A_RATE             B          5
26  P4_E_JOINT_SELECTIVITY_A_RATE         GRADE          1
27  P4_E_JOINT_SELECTIVITY_A_RATE        POLICY          1
28  P4_E_JOINT_SELECTIVITY_A_RATE             Q          4
29  P4_E_JOINT_SELECTIVITY_A_RATE            S0          5
30    P4_E_JOINT_STRUCTURE_A_RATE             B          5
31    P4_E_JOINT_STRUCTURE_A_RATE         GRADE          1
32    P4_E_JOINT_STRUCTURE_A_RATE        POLICY          1
33    P4_E_JOINT_STRUCTURE_A_RATE            S0          5
34        P4_E_SELECTIVITY_A_RATE             B          5
35        P4_E_SELECTIVITY_A_RATE         GRADE          1
36        P4_E_SELECTIVITY_A_RATE        POLICY          1
37        P4_E_SELECTIVITY_A_RATE             Q          4
38        P4_E_SELECTIVITY_A_RATE            S0          5
39      P4_E_SELECTIVITY_RESIDUAL             B          5
40      P4_E_SELECTIVITY_RESIDUAL       DERIVED          1
41      P4_E_SELECTIVITY_RESIDUAL        POLICY          1
42      P4_E_SELECTIVITY_RESIDUAL             Q          4
43      P4_E_SELECTIVITY_RESIDUAL            S0          5
44          P4_E_STRUCTURE_A_RATE             B          5
45          P4_E_STRUCTURE_A_RATE         GRADE          1
46          P4_E_STRUCTURE_A_RATE        POLICY          1
47          P4_E_STRUCTURE_A_RATE            S0          5
48        P4_E_STRUCTURE_RESIDUAL             B          5
49        P4_E_STRUCTURE_RESIDUAL       DERIVED          1
50        P4_E_STRUCTURE_RESIDUAL        POLICY          1
51        P4_E_STRUCTURE_RESIDUAL            S0          5
52  P4_P_JOINT_SELECTIVITY_A_RATE             B          5
53  P4_P_JOINT_SELECTIVITY_A_RATE         GRADE          1
54  P4_P_JOINT_SELECTIVITY_A_RATE        POLICY          1
55  P4_P_JOINT_SELECTIVITY_A_RATE             Q          4
56  P4_P_JOINT_SELECTIVITY_A_RATE            S0          5
57    P4_P_JOINT_STRUCTURE_A_RATE             B          5
58    P4_P_JOINT_STRUCTURE_A_RATE         GRADE          1
59    P4_P_JOINT_STRUCTURE_A_RATE        POLICY          1
60    P4_P_JOINT_STRUCTURE_A_RATE            S0          5
61        P4_P_SELECTIVITY_A_RATE             B          5
62        P4_P_SELECTIVITY_A_RATE         GRADE          1
63        P4_P_SELECTIVITY_A_RATE        POLICY          1
64        P4_P_SELECTIVITY_A_RATE             Q          4
65        P4_P_SELECTIVITY_A_RATE            S0          5
66      P4_P_SELECTIVITY_RESIDUAL             B          5
67      P4_P_SELECTIVITY_RESIDUAL       DERIVED          1
68      P4_P_SELECTIVITY_RESIDUAL        POLICY          1
69      P4_P_SELECTIVITY_RESIDUAL             Q          4
70      P4_P_SELECTIVITY_RESIDUAL            S0          5
71          P4_P_STRUCTURE_A_RATE             B          5
72          P4_P_STRUCTURE_A_RATE         GRADE          1
73          P4_P_STRUCTURE_A_RATE        POLICY          1
74          P4_P_STRUCTURE_A_RATE            S0          5
75        P4_P_STRUCTURE_RESIDUAL             B          5
76        P4_P_STRUCTURE_RESIDUAL       DERIVED          1
77        P4_P_STRUCTURE_RESIDUAL        POLICY          1
78        P4_P_STRUCTURE_RESIDUAL            S0          5

Active feature ID/name/QUALITY leakage check

                                            message
0  No ID/name/QUALITY feature in active feature set

## Dataset: `P4_PHASE_MODEL_SPEC_FINAL`

- 역할: Final phase model specification registry
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv`
- 예상 shape: `(18, 10)`
- 예상 SHA256: `d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48`

In [ ]:
result = inspect_dataset(
    label='P4_PHASE_MODEL_SPEC_FINAL',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv',
    expected_shape=(18, 10),
    expected_sha256='d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48',
    candidate_keys=[['model_id']],
)

extra_model_spec()

### 5.1 File Identification - `P4_PHASE_MODEL_SPEC_FINAL`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_PHASE_MODEL_SPEC_FINAL,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINA...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv,True,.csv,2618,2026-07-13T11:12:50.388366,d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48,d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48,True

### 5.2 Basic Structure

      shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (18, 10)       (18, 10)         True         18            10                3849       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0                model_id             model_id    True              0                   0                     0                18

### 5.3 Full Column List

   position                     column  dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0         1                   model_id    str          18          0     0.000000       18      1.000000        False        False                     True         0.055556
1         2                      phase    str          18          0     0.000000        5      0.277778        False        False                    False         0.333333
2         3                  sample_id    str          18          0     0.000000       12      0.666667        False        False                     True         0.111111
3         4                     target    str          18          0     0.000000        3      0.166667        False        False                    False         0.333333
4         5             allowed_blocks    str          18          0     0.000000        2      0.111111        False        False                    False         0.500000
5         6          grade_signal_role    str          18          0     0.000000        4      0.222222        False        False                    False         0.444444
6         7              feature_count  int64          18          0     0.000000        6      0.333333        False        False                    False         0.333333
7         8               availability    str          18          0     0.000000        2      0.111111        False        False                    False         0.777778
8         9  missing_required_features    str           4         14    77.777778        2      0.500000        False        False                    False         0.777778
9        10                     status    str          18          0     0.000000        2      0.111111        False        False                    False         0.777778

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   model_id                   18 non-null     str
 1   phase                      18 non-null     str
 2   sample_id                  18 non-null     str
 3   target                     18 non-null     str
 4   allowed_blocks             18 non-null     str
 5   grade_signal_role          18 non-null     str
 6   feature_count              18 non-null     int64
 7   availability               18 non-null     str
 8   missing_required_features  4 non-null      str
 9   status                     18 non-null     str
dtypes: int64(1), str(9)
memory usage: 3.8 KB

### 5.5 Head

         model_id phase             sample_id      target allowed_blocks              grade_signal_role  feature_count availability missing_required_features status
0    P1_STRUCTURE    P1    P1_STRUCTURE_READY  a_rate_pct    B+POLICY+S0  same_time_alignment_noncausal             13    available                       NaN  READY
1  P1_SELECTIVITY    P1  P1_SELECTIVITY_READY  a_rate_pct  B+POLICY+Q+S0  same_time_alignment_noncausal             17    available                       NaN  READY
2            P2_S    P2    P2_STRUCTURE_READY  a_rate_pct    B+POLICY+S0             same_time_controls             11    available                       NaN  READY
3            P2_Q    P2  P2_SELECTIVITY_READY  a_rate_pct  B+POLICY+Q+S0             same_time_controls             15    available                       NaN  READY
4            P3_S    P3    P3_STRUCTURE_READY  a_rate_pct    B+POLICY+S0             same_time_controls             11    available                       NaN  READY

### 5.6 Tail

                         model_id phase                   sample_id                                target allowed_blocks       grade_signal_role  feature_count      availability       missing_required_features                     status
13      P4_P_SELECTIVITY_RESIDUAL  P4_P      P4_P_SELECTIVITY_READY  graduate_school_progression_rate_pct  B+POLICY+Q+S0        oof_grade_signal             16  pending_residual  grade_residual_selectivity_oof  PENDING_UPSTREAM_RESIDUAL
14    P4_E_JOINT_STRUCTURE_A_RATE  P4_E    P4_JOINT_STRUCTURE_READY            health_employment_rate_pct    B+POLICY+S0  same_time_grade_signal             12         available                             NaN                      READY
15    P4_P_JOINT_STRUCTURE_A_RATE  P4_P    P4_JOINT_STRUCTURE_READY  graduate_school_progression_rate_pct    B+POLICY+S0  same_time_grade_signal             12         available                             NaN                      READY
16  P4_E_JOINT_SELECTIVITY_A_RATE  P4_E  P4_JOINT_SELECTIVITY_READY            health_employment_rate_pct  B+POLICY+Q+S0  same_time_grade_signal             16         available                             NaN                      READY
17  P4_P_JOINT_SELECTIVITY_A_RATE  P4_P  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct  B+POLICY+Q+S0  same_time_grade_signal             16         available                             NaN                      READY

### 5.7 Random Sample

                         model_id phase                   sample_id                                target allowed_blocks       grade_signal_role  feature_count      availability       missing_required_features                     status
9       P4_E_SELECTIVITY_RESIDUAL  P4_E      P4_E_SELECTIVITY_READY            health_employment_rate_pct  B+POLICY+Q+S0        oof_grade_signal             16  pending_residual  grade_residual_selectivity_oof  PENDING_UPSTREAM_RESIDUAL
15    P4_P_JOINT_STRUCTURE_A_RATE  P4_P    P4_JOINT_STRUCTURE_READY  graduate_school_progression_rate_pct    B+POLICY+S0  same_time_grade_signal             12         available                             NaN                      READY
6           P4_E_STRUCTURE_A_RATE  P4_E        P4_E_STRUCTURE_READY            health_employment_rate_pct    B+POLICY+S0  same_time_grade_signal             12         available                             NaN                      READY
11        P4_P_STRUCTURE_RESIDUAL  P4_P        P4_P_STRUCTURE_READY  graduate_school_progression_rate_pct    B+POLICY+S0        oof_grade_signal             12  pending_residual    grade_residual_structure_oof  PENDING_UPSTREAM_RESIDUAL
13      P4_P_SELECTIVITY_RESIDUAL  P4_P      P4_P_SELECTIVITY_READY  graduate_school_progression_rate_pct  B+POLICY+Q+S0        oof_grade_signal             16  pending_residual  grade_residual_selectivity_oof  PENDING_UPSTREAM_RESIDUAL
16  P4_E_JOINT_SELECTIVITY_A_RATE  P4_E  P4_JOINT_SELECTIVITY_READY            health_employment_rate_pct  B+POLICY+Q+S0  same_time_grade_signal             16         available                             NaN                      READY
4                            P3_S    P3          P3_STRUCTURE_READY                            a_rate_pct    B+POLICY+S0      same_time_controls             11         available                             NaN                      READY
8         P4_E_SELECTIVITY_A_RATE  P4_E      P4_E_SELECTIVITY_READY            health_employment_rate_pct  B+POLICY+Q+S0  same_time_grade_signal             16         available                             NaN                      READY
12        P4_P_SELECTIVITY_A_RATE  P4_P      P4_P_SELECTIVITY_READY  graduate_school_progression_rate_pct  B+POLICY+Q+S0  same_time_grade_signal             16         available                             NaN                      READY
17  P4_P_JOINT_SELECTIVITY_A_RATE  P4_P  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct  B+POLICY+Q+S0  same_time_grade_signal             16         available                             NaN                      READY

### 5.8 Numeric Describe

          column     count      mean      std       min        1%        5%       10%       25%       50%       75%       90%       95%       99%       max  missing_n  missing_pct  zero_n  zero_pct  negative_n  inf_n  nunique
0  feature_count 18.000000 13.888889 2.138963 11.000000 11.000000 11.000000 11.700000 12.000000 14.000000 16.000000 16.000000 16.150000 16.830000 17.000000          0     0.000000       0  0.000000           0      0        6

### 5.8 Categorical/String/Boolean Describe

                      column dtype  count  missing_n  missing_pct  nunique                           top  freq   top_pct                                                                                               sample_values
0                   model_id   str     18          0     0.000000       18                  P1_STRUCTURE     1  5.555556                                                          P1_STRUCTURE | P1_SELECTIVITY | P2_S | P2_Q | P3_S
1                      phase   str     18          0     0.000000        5                          P4_E     6 33.333333                                                                                  P1 | P2 | P3 | P4_E | P4_P
2                  sample_id   str     18          0     0.000000       12          P4_E_STRUCTURE_READY     2 11.111111  P1_STRUCTURE_READY | P1_SELECTIVITY_READY | P2_STRUCTURE_READY | P2_SELECTIVITY_READY | P3_STRUCTURE_READY
3                     target   str     18          0     0.000000        3                    a_rate_pct     6 33.333333                              a_rate_pct | health_employment_rate_pct | graduate_school_progression_rate_pct
4             allowed_blocks   str     18          0     0.000000        2                   B+POLICY+S0     9 50.000000                                                                                 B+POLICY+S0 | B+POLICY+Q+S0
5          grade_signal_role   str     18          0     0.000000        4        same_time_grade_signal     8 44.444444              same_time_alignment_noncausal | same_time_controls | same_time_grade_signal | oof_grade_signal
6               availability   str     18          0     0.000000        2                     available    14 77.777778                                                                                available | pending_residual
7  missing_required_features   str      4         14    77.777778        2  grade_residual_structure_oof     2 11.111111                                               grade_residual_structure_oof | grade_residual_selectivity_oof
8                     status   str     18          0     0.000000        2                         READY    14 77.777778                                                                           READY | PENDING_UPSTREAM_RESIDUAL

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

   rank                     column dtype  missing_n  missing_pct  non_null_n  nunique
8     1  missing_required_features   str         14    77.777778           4        2

### 5.10 Top Cardinality Columns

                      column  dtype  nunique  unique_ratio
0                   model_id    str       18      1.000000
2                  sample_id    str       12      0.666667
6              feature_count  int64        6      0.333333
1                      phase    str        5      0.277778
5          grade_signal_role    str        4      0.222222
3                     target    str        3      0.166667
8  missing_required_features    str        2      0.500000
4             allowed_blocks    str        2      0.111111
7               availability    str        2      0.111111
9                     status    str        2      0.111111

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

  message
0    None

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

          column              check    nan_n  pos_inf_n  neg_inf_n  negative_n   zero_n  violation_n
0  feature_count      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
1  feature_count  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS
WARNINGS:
- none

### 6.6 Model Specification Additional Checks

                         model_id                   sample_id                                target allowed_blocks  feature_count                     status
0                    P1_STRUCTURE          P1_STRUCTURE_READY                            a_rate_pct    B+POLICY+S0             13                      READY
1                  P1_SELECTIVITY        P1_SELECTIVITY_READY                            a_rate_pct  B+POLICY+Q+S0             17                      READY
2                            P2_S          P2_STRUCTURE_READY                            a_rate_pct    B+POLICY+S0             11                      READY
3                            P2_Q        P2_SELECTIVITY_READY                            a_rate_pct  B+POLICY+Q+S0             15                      READY
4                            P3_S          P3_STRUCTURE_READY                            a_rate_pct    B+POLICY+S0             11                      READY
5                            P3_Q        P3_SELECTIVITY_READY                            a_rate_pct  B+POLICY+Q+S0             15                      READY
6           P4_E_STRUCTURE_A_RATE        P4_E_STRUCTURE_READY            health_employment_rate_pct    B+POLICY+S0             12                      READY
7         P4_E_STRUCTURE_RESIDUAL        P4_E_STRUCTURE_READY            health_employment_rate_pct    B+POLICY+S0             12  PENDING_UPSTREAM_RESIDUAL
8         P4_E_SELECTIVITY_A_RATE      P4_E_SELECTIVITY_READY            health_employment_rate_pct  B+POLICY+Q+S0             16                      READY
9       P4_E_SELECTIVITY_RESIDUAL      P4_E_SELECTIVITY_READY            health_employment_rate_pct  B+POLICY+Q+S0             16  PENDING_UPSTREAM_RESIDUAL
10          P4_P_STRUCTURE_A_RATE        P4_P_STRUCTURE_READY  graduate_school_progression_rate_pct    B+POLICY+S0             12                      READY
11        P4_P_STRUCTURE_RESIDUAL        P4_P_STRUCTURE_READY  graduate_school_progression_rate_pct    B+POLICY+S0             12  PENDING_UPSTREAM_RESIDUAL
12        P4_P_SELECTIVITY_A_RATE      P4_P_SELECTIVITY_READY  graduate_school_progression_rate_pct  B+POLICY+Q+S0             16                      READY
13      P4_P_SELECTIVITY_RESIDUAL      P4_P_SELECTIVITY_READY  graduate_school_progression_rate_pct  B+POLICY+Q+S0             16  PENDING_UPSTREAM_RESIDUAL
14    P4_E_JOINT_STRUCTURE_A_RATE    P4_JOINT_STRUCTURE_READY            health_employment_rate_pct    B+POLICY+S0             12                      READY
15    P4_P_JOINT_STRUCTURE_A_RATE    P4_JOINT_STRUCTURE_READY  graduate_school_progression_rate_pct    B+POLICY+S0             12                      READY
16  P4_E_JOINT_SELECTIVITY_A_RATE  P4_JOINT_SELECTIVITY_READY            health_employment_rate_pct  B+POLICY+Q+S0             16                      READY
17  P4_P_JOINT_SELECTIVITY_A_RATE  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct  B+POLICY+Q+S0             16                      READY

status phase                                target  PENDING_UPSTREAM_RESIDUAL  READY
0         P1                            a_rate_pct                          0      2
1         P2                            a_rate_pct                          0      2
2         P3                            a_rate_pct                          0      2
3       P4_E            health_employment_rate_pct                          2      4
4       P4_P  graduate_school_progression_rate_pct                          2      4

## Dataset: `P4_MODEL_FAMILY_RECOMMENDATION`

- 역할: Recommended model family table
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv`
- 예상 shape: `(8, 8)`
- 예상 SHA256: `193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c`

In [ ]:
result = inspect_dataset(
    label='P4_MODEL_FAMILY_RECOMMENDATION',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv',
    expected_shape=(8, 8),
    expected_sha256='193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c',
    candidate_keys=[['target_family', 'model_family']],
)

### 5.1 File Identification - `P4_MODEL_FAMILY_RECOMMENDATION`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_MODEL_FAMILY_RECOMMENDATION,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMEN...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv,True,.csv,2305,2026-07-13T11:12:59.630755,193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c,193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c,True

### 5.2 Basic Structure

    shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (8, 8)         (8, 8)         True          8             8                2664       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

        candidate_key_requested          candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0  target_family + model_family  target_family + model_family    True              0                   0                     0                 8

### 5.3 Full Column List

   position                  column dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0         1           target_family   str           8          0     0.000000        3      0.375000        False        False                    False         0.375000
1         2                  target   str           8          0     0.000000        3      0.375000        False        False                    False         0.375000
2         3            model_family   str           8          0     0.000000        7      0.875000        False        False                    False         0.250000
3         4                feasible  bool           8          0     0.000000        1      0.125000        False         True                    False         1.000000
4         5                  reason   str           8          0     0.000000        8      1.000000        False        False                    False         0.125000
5         6        known_limitation   str           8          0     0.000000        8      1.000000        False        False                    False         0.125000
6         7  required_preprocessing   str           8          0     0.000000        7      0.875000        False        False                    False         0.250000
7         8       evaluation_metric   str           8          0     0.000000        8      1.000000        False        False                    False         0.125000

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   target_family           8 non-null      str
 1   target                  8 non-null      str
 2   model_family            8 non-null      str
 3   feasible                8 non-null      bool
 4   reason                  8 non-null      str
 5   known_limitation        8 non-null      str
 6   required_preprocessing  8 non-null      str
 7   evaluation_metric       8 non-null      str
dtypes: bool(1), str(7)
memory usage: 2.6 KB

### 5.5 Head

,target_family,target,model_family,feasible,reason,known_limitation,required_preprocessing,evaluation_metric
0,A_RATE,a_rate_pct,OLS cluster,True,Continuous percent target with no numerator/denominator counts; school clustering available.,"Percent target bounded [0,100], heteroskedasticity likely.",train-only imputation/encoding/scaling; cluster-robust SE by school in inference.,"RMSE, MAE, calibration by decile"
1,A_RATE,a_rate_pct,GAM,True,Nonlinear covariate effects plausible; sample size sufficient.,Requires careful smoothness control and categorical handling.,same folds as linear model; smooth continuous variables only.,out-of-fold RMSE and calibration
2,A_RATE,a_rate_pct,Fractional logit sensitivity,True,"Rate can be scaled to [0,1]; no count denominator needed for quasi-likelihood sensitivity.",No binomial weights because count denominators unavailable.,clip exact 0/1 if estimator requires open interval.,"log-loss-like quasi deviance, MAE on percent scale"
3,EMPLOYMENT,health_employment_rate_pct,Fractional logit primary,True,Bounded employment rate target; count denominator unavailable.,Unweighted fractional model; no binomial precision weights.,"scale y to [0,1], train-only X preprocessing.","MAE/RMSE on percent scale, quasi deviance"
4,EMPLOYMENT,health_employment_rate_pct,OLS cluster sensitivity,True,Useful interpretable sensitivity with school clustering.,"Can predict outside [0,100].",train-only imputation/encoding/scaling.,"RMSE, MAE"

### 5.6 Tail

,target_family,target,model_family,feasible,reason,known_limitation,required_preprocessing,evaluation_metric
3,EMPLOYMENT,health_employment_rate_pct,Fractional logit primary,True,Bounded employment rate target; count denominator unavailable.,Unweighted fractional model; no binomial precision weights.,"scale y to [0,1], train-only X preprocessing.","MAE/RMSE on percent scale, quasi deviance"
4,EMPLOYMENT,health_employment_rate_pct,OLS cluster sensitivity,True,Useful interpretable sensitivity with school clustering.,"Can predict outside [0,100].",train-only imputation/encoding/scaling.,"RMSE, MAE"
5,PROGRESSION,graduate_school_progression_rate_pct,Fractional logit,True,Bounded rate with many zeroes; fractional model appropriate as primary.,No count weights; zero inflation remains.,"scale y to [0,1], handle zeros explicitly.","quasi deviance, MAE/RMSE on percent scale"
6,PROGRESSION,graduate_school_progression_rate_pct,Two-part sensitivity,True,Zero mass expected; model progression>0 and positive rate separately.,Positive-rate subset smaller and selected.,binary classifier plus conditional regression in identical folds.,AUC/Brier for zero part; RMSE/MAE for positive rate
7,PROGRESSION,graduate_school_progression_rate_pct,OLS cluster sensitivity,True,Interpretable sensitivity baseline.,Bounded and zero-inflated target violates simple Gaussian assumptions.,train-only imputation/encoding/scaling.,"RMSE, MAE, zero-group calibration"

### 5.7 Random Sample

,target_family,target,model_family,feasible,reason,known_limitation,required_preprocessing,evaluation_metric
7,PROGRESSION,graduate_school_progression_rate_pct,OLS cluster sensitivity,True,Interpretable sensitivity baseline.,Bounded and zero-inflated target violates simple Gaussian assumptions.,train-only imputation/encoding/scaling.,"RMSE, MAE, zero-group calibration"
4,EMPLOYMENT,health_employment_rate_pct,OLS cluster sensitivity,True,Useful interpretable sensitivity with school clustering.,"Can predict outside [0,100].",train-only imputation/encoding/scaling.,"RMSE, MAE"
6,PROGRESSION,graduate_school_progression_rate_pct,Two-part sensitivity,True,Zero mass expected; model progression>0 and positive rate separately.,Positive-rate subset smaller and selected.,binary classifier plus conditional regression in identical folds.,AUC/Brier for zero part; RMSE/MAE for positive rate
1,A_RATE,a_rate_pct,GAM,True,Nonlinear covariate effects plausible; sample size sufficient.,Requires careful smoothness control and categorical handling.,same folds as linear model; smooth continuous variables only.,out-of-fold RMSE and calibration
3,EMPLOYMENT,health_employment_rate_pct,Fractional logit primary,True,Bounded employment rate target; count denominator unavailable.,Unweighted fractional model; no binomial precision weights.,"scale y to [0,1], train-only X preprocessing.","MAE/RMSE on percent scale, quasi deviance"
0,A_RATE,a_rate_pct,OLS cluster,True,Continuous percent target with no numerator/denominator counts; school clustering available.,"Percent target bounded [0,100], heteroskedasticity likely.",train-only imputation/encoding/scaling; cluster-robust SE by school in inference.,"RMSE, MAE, calibration by decile"
2,A_RATE,a_rate_pct,Fractional logit sensitivity,True,"Rate can be scaled to [0,1]; no count denominator needed for quasi-likelihood sensitivity.",No binomial weights because count denominators unavailable.,clip exact 0/1 if estimator requires open interval.,"log-loss-like quasi deviance, MAE on percent scale"
5,PROGRESSION,graduate_school_progression_rate_pct,Fractional logit,True,Bounded rate with many zeroes; fractional model appropriate as primary.,No count weights; zero inflation remains.,"scale y to [0,1], handle zeros explicitly.","quasi deviance, MAE/RMSE on percent scale"

### 5.8 Numeric Describe

              message
0  No numeric columns

### 5.8 Categorical/String/Boolean Describe

,column,dtype,count,missing_n,missing_pct,nunique,top,freq,top_pct,sample_values
0,target_family,str,8,0,0.000000,3,A_RATE,3,37.500000,A_RATE | EMPLOYMENT | PROGRESSION
1,target,str,8,0,0.000000,3,a_rate_pct,3,37.500000,a_rate_pct | health_employment_rate_pct | graduate_school_progression_rate_pct
2,model_family,str,8,0,0.000000,7,OLS cluster sensitivity,2,25.000000,OLS cluster | GAM | Fractional logit sensitivity | Fractional logit primary | OLS cluster sensitivity
3,feasible,bool,8,0,0.000000,1,True,8,100.000000,True
4,reason,str,8,0,0.000000,8,Continuous percent target with no numerator/denominator counts; school clustering available.,1,12.500000,Continuous percent target with no numerator/denominator counts; school clustering available. | Nonlinear covariate e...
5,known_limitation,str,8,0,0.000000,8,"Percent target bounded [0,100], heteroskedasticity likely.",1,12.500000,"Percent target bounded [0,100], heteroskedasticity likely. | Requires careful smoothness control and categorical han..."
6,required_preprocessing,str,8,0,0.000000,7,train-only imputation/encoding/scaling.,2,25.000000,train-only imputation/encoding/scaling; cluster-robust SE by school in inference. | same folds as linear model; smoo...
7,evaluation_metric,str,8,0,0.000000,8,"RMSE, MAE, calibration by decile",1,12.500000,"RMSE, MAE, calibration by decile | out-of-fold RMSE and calibration | log-loss-like quasi deviance, MAE on percent s..."

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

No missing values

### 5.10 Top Cardinality Columns

                   column dtype  nunique  unique_ratio
4                  reason   str        8      1.000000
5        known_limitation   str        8      1.000000
7       evaluation_metric   str        8      1.000000
2            model_family   str        7      0.875000
6  required_preprocessing   str        7      0.875000
0           target_family   str        3      0.375000
1                  target   str        3      0.375000
3                feasible  bool        1      0.125000

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

     column dtype  nunique  top_value_share
3  feasible  bool        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

     column          check  nan_n  pos_inf_n  neg_inf_n  negative_n  zero_n  violation_n
0  feasible  numeric_basic      0          0          0           0       0            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 1

## Dataset: `P4_DUPLICATE_CONFLICT_RESOLUTION`

- 역할: Duplicate and conflict handling contract
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv`
- 예상 shape: `(36, 14)`
- 예상 SHA256: `24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f`

In [ ]:
result = inspect_dataset(
    label='P4_DUPLICATE_CONFLICT_RESOLUTION',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv',
    expected_shape=(36, 14),
    expected_sha256='24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f',
    candidate_keys=[['group_id', 'outcome_row_id']],
)

### 5.1 File Identification - `P4_DUPLICATE_CONFLICT_RESOLUTION`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_DUPLICATE_CONFLICT_RESOLUTION,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTIO...,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv,True,.csv,13216,2026-07-13T11:12:50.049703,24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f,24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f,True

### 5.2 Basic Structure

      shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (36, 14)       (36, 14)         True         36            14               15436       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

     candidate_key_requested       candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0  group_id + outcome_row_id  group_id + outcome_row_id    True              0                   0                     0                36

### 5.3 Full Column List

    position               column dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1             group_id   str          36          0     0.000000       18      0.500000        False        False                     True         0.055556
1          2       classification   str          36          0     0.000000        3      0.083333        False        False                    False         0.777778
2          3             dept_uid   str          36          0     0.000000       18      0.500000        False        False                     True         0.055556
3          4       outcome_row_id   str          36          0     0.000000       36      1.000000        False        False                     True         0.027778
4          5               school   str          36          0     0.000000        6      0.166667        False        False                    False         0.444444
5          6               campus   str          36          0     0.000000        3      0.083333        False        False                    False         0.583333
6          7           department   str          36          0     0.000000       19      0.527778        False        False                    False         0.111111
7          8                split   str          36          0     0.000000        2      0.055556        False        False                    False         0.944444
8          9    active_sample_ids   str          36          0     0.000000        8      0.222222        False        False                     True         0.416667
9         10           resolution   str          36          0     0.000000        3      0.083333        False        False                    False         0.777778
10        11        model_allowed  bool          36          0     0.000000        2      0.055556        False        False                    False         0.777778
11        12       weight_allowed  bool          36          0     0.000000        1      0.027778        False         True                    False         1.000000
12        13  denominator_allowed  bool          36          0     0.000000        1      0.027778        False         True                    False         1.000000
13        14     exclusion_reason   str           8         28    77.777778        2      0.250000        False        False                    False         0.777778

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group_id             36 non-null     str
 1   classification       36 non-null     str
 2   dept_uid             36 non-null     str
 3   outcome_row_id       36 non-null     str
 4   school               36 non-null     str
 5   campus               36 non-null     str
 6   department           36 non-null     str
 7   split                36 non-null     str
 8   active_sample_ids    36 non-null     str
 9   resolution           36 non-null     str
 10  model_allowed        36 non-null     bool
 11  weight_allowed       36 non-null     bool
 12  denominator_allowed  36 non-null     bool
 13  exclusion_reason     8 non-null      str
dtypes: bool(3), str(11)
memory usage: 15.1 KB

### 5.5 Head

,group_id,classification,dept_uid,outcome_row_id,school,campus,department,split,active_sample_ids,resolution,model_allowed,weight_allowed,denominator_allowed,exclusion_reason
0,DUPCON_001,PARENT_HEADCOUNT_REUSED,DEP_01160bffef8e,OC2024_01626,고려대학교,unknown,사회학과,train,GRADE_ALL|GRADE_SELECTIVITY|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|GRADE_SELECTIVIT...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
1,DUPCON_001,PARENT_HEADCOUNT_REUSED,DEP_01160bffef8e,OC2024_01696,고려대학교,분교,사회학과,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
2,DUPCON_002,PARENT_HEADCOUNT_REUSED,DEP_0e4cb5dc34e5,OC2024_03092,단국대학교,제2캠퍼스,뉴뮤직학부,train,GRADE_ALL|GRADE_STRUCTURE|P2_STRUCTURE_READY|P3_STRUCTURE_READY,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
3,DUPCON_002,PARENT_HEADCOUNT_REUSED,DEP_0e4cb5dc34e5,OC2024_03093,단국대학교,제2캠퍼스,뉴뮤직과,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
4,DUPCON_003,CAMPUS_CONFLICT,DEP_1e8ebec67414,OC2024_09486,한남대학교,unknown,토목환경공학전공,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|P1_SIGNAL_ALIGNMENT_CORE,EXCLUDE_PRIMARY_PENDING_CAMPUS_REVIEW,False,False,False,CAMPUS_CONFLICT_PENDING_REVIEW

### 5.6 Tail

,group_id,classification,dept_uid,outcome_row_id,school,campus,department,split,active_sample_ids,resolution,model_allowed,weight_allowed,denominator_allowed,exclusion_reason
31,DUPCON_016,PARENT_HEADCOUNT_REUSED,DEP_dffa1a933d14,OC2024_01706,고려대학교,분교,영어영문학과,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
32,DUPCON_017,TRUE_DUPLICATE,DEP_eb13903b31fd,OC2024_08822,충남대학교,unknown,미생물분자생명과학과,train,GRADE_ALL|GRADE_SELECTIVITY|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|JOINT_EMP_PROG_SELECTIVITY|P1_SI...,EXCLUDE_PRIMARY_PENDING_CAUSE_REVIEW,False,False,False,TRUE_DUPLICATE_PENDING_REVIEW
33,DUPCON_017,TRUE_DUPLICATE,DEP_eb13903b31fd,OC2024_08823,충남대학교,unknown,미생물분자생명과학과,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|P1_SIGNAL_ALIGNMENT_CORE,EXCLUDE_PRIMARY_PENDING_CAUSE_REVIEW,False,False,False,TRUE_DUPLICATE_PENDING_REVIEW
34,DUPCON_018,PARENT_HEADCOUNT_REUSED,DEP_f35d2a4b373a,OC2024_06740,연세대학교,unknown,수학과,train,GRADE_ALL|GRADE_SELECTIVITY|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|GRADE_SELECTIVIT...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
35,DUPCON_018,PARENT_HEADCOUNT_REUSED,DEP_f35d2a4b373a,OC2024_06831,연세대학교,분교,수학전공,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN

### 5.7 Random Sample

,group_id,classification,dept_uid,outcome_row_id,school,campus,department,split,active_sample_ids,resolution,model_allowed,weight_allowed,denominator_allowed,exclusion_reason
17,DUPCON_009,PARENT_HEADCOUNT_REUSED,DEP_69e8462a106a,OC2024_01667,고려대학교,분교,경제학과,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
9,DUPCON_005,PARENT_HEADCOUNT_REUSED,DEP_40fc3d69b657,OC2024_06804,연세대학교,분교,국어국문학과,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
8,DUPCON_005,PARENT_HEADCOUNT_REUSED,DEP_40fc3d69b657,OC2024_06708,연세대학교,unknown,국어국문학과,train,GRADE_ALL|GRADE_SELECTIVITY|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|GRADE_SELECTIVIT...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
28,DUPCON_015,PARENT_HEADCOUNT_REUSED,DEP_bacbfde4e8ca,OC2024_06767,연세대학교,unknown,의학과,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
24,DUPCON_013,TRUE_DUPLICATE,DEP_b18217983866,OC2024_06719,연세대학교,unknown,문화미디어전공,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|P1_SIGNAL_ALIGNMENT_CORE,EXCLUDE_PRIMARY_PENDING_CAUSE_REVIEW,False,False,False,TRUE_DUPLICATE_PENDING_REVIEW
0,DUPCON_001,PARENT_HEADCOUNT_REUSED,DEP_01160bffef8e,OC2024_01626,고려대학교,unknown,사회학과,train,GRADE_ALL|GRADE_SELECTIVITY|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|GRADE_SELECTIVIT...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
6,DUPCON_004,PARENT_HEADCOUNT_REUSED,DEP_31efbd40bac2,OC2024_06769,연세대학교,unknown,의예과,train,GRADE_ALL|GRADE_SELECTIVITY|GRADE_STRUCTURE|GRADE_SELECTIVITY_STRUCTURE|P2_STRUCTURE_READY|P2_SELECTIVITY_READY|P3_S...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
4,DUPCON_003,CAMPUS_CONFLICT,DEP_1e8ebec67414,OC2024_09486,한남대학교,unknown,토목환경공학전공,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|P1_SIGNAL_ALIGNMENT_CORE,EXCLUDE_PRIMARY_PENDING_CAMPUS_REVIEW,False,False,False,CAMPUS_CONFLICT_PENDING_REVIEW
11,DUPCON_006,PARENT_HEADCOUNT_REUSED,DEP_5775880d8f88,OC2024_01675,고려대학교,분교,국어국문학과,train,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN
14,DUPCON_008,PARENT_HEADCOUNT_REUSED,DEP_6646d76a3796,OC2024_01632,고려대학교,unknown,수학과,train,GRADE_ALL|GRADE_SELECTIVITY|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|GRADE_SELECTIVIT...,ALLOW_CONTEXT_FEATURE_ONLY,True,False,False,NaN

### 5.8 Numeric Describe

              message
0  No numeric columns

### 5.8 Categorical/String/Boolean Describe

,column,dtype,count,missing_n,missing_pct,nunique,top,freq,top_pct,sample_values
0,group_id,str,36,0,0.000000,18,DUPCON_001,2,5.555556,DUPCON_001 | DUPCON_002 | DUPCON_003 | DUPCON_004 | DUPCON_005
1,classification,str,36,0,0.000000,3,PARENT_HEADCOUNT_REUSED,28,77.777778,PARENT_HEADCOUNT_REUSED | CAMPUS_CONFLICT | TRUE_DUPLICATE
2,dept_uid,str,36,0,0.000000,18,DEP_01160bffef8e,2,5.555556,DEP_01160bffef8e | DEP_0e4cb5dc34e5 | DEP_1e8ebec67414 | DEP_31efbd40bac2 | DEP_40fc3d69b657
3,outcome_row_id,str,36,0,0.000000,36,OC2024_01626,1,2.777778,OC2024_01626 | OC2024_01696 | OC2024_03092 | OC2024_03093 | OC2024_09486
4,school,str,36,0,0.000000,6,연세대학교,16,44.444444,고려대학교 | 단국대학교 | 한남대학교 | 연세대학교 | 우석대학교
5,campus,str,36,0,0.000000,3,unknown,21,58.333333,unknown | 분교 | 제2캠퍼스
6,department,str,36,0,0.000000,19,국어국문학과,4,11.111111,사회학과 | 뉴뮤직학부 | 뉴뮤직과 | 토목환경공학전공 | 의예과
7,split,str,36,0,0.000000,2,train,34,94.444444,train | val
8,active_sample_ids,str,36,0,0.000000,8,GRADE_ALL|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|JOINT_EMP_PROG_STRUCTURE|P1_SIGNAL...,15,41.666667,GRADE_ALL|GRADE_SELECTIVITY|EMPLOYMENT_HEALTH|PROGRESSION_GRADSCHOOL|JOINT_EMP_PROG|GRADE_STRUCTURE|GRADE_SELECTIVIT...
9,resolution,str,36,0,0.000000,3,ALLOW_CONTEXT_FEATURE_ONLY,28,77.777778,ALLOW_CONTEXT_FEATURE_ONLY | EXCLUDE_PRIMARY_PENDING_CAMPUS_REVIEW | EXCLUDE_PRIMARY_PENDING_CAUSE_REVIEW
10,model_allowed,bool,36,0,0.000000,2,True,28,77.777778,True | False
11,weight_allowed,bool,36,0,0.000000,1,False,36,100.000000,False
12,denominator_allowed,bool,36,0,0.000000,1,False,36,100.000000,False
13,exclusion_reason,str,8,28,77.777778,2,TRUE_DUPLICATE_PENDING_REVIEW,6,16.666667,CAMPUS_CONFLICT_PENDING_REVIEW | TRUE_DUPLICATE_PENDING_REVIEW

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

    rank            column dtype  missing_n  missing_pct  non_null_n  nunique
13     1  exclusion_reason   str         28    77.777778           8        2

### 5.10 Top Cardinality Columns

                 column dtype  nunique  unique_ratio
3        outcome_row_id   str       36      1.000000
6            department   str       19      0.527778
0              group_id   str       18      0.500000
2              dept_uid   str       18      0.500000
8     active_sample_ids   str        8      0.222222
4                school   str        6      0.166667
1        classification   str        3      0.083333
5                campus   str        3      0.083333
9            resolution   str        3      0.083333
13     exclusion_reason   str        2      0.250000
7                 split   str        2      0.055556
10        model_allowed  bool        2      0.055556
11       weight_allowed  bool        1      0.027778
12  denominator_allowed  bool        1      0.027778

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

                 column dtype  nunique  top_value_share
11       weight_allowed  bool        1         1.000000
12  denominator_allowed  bool        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                column          check  nan_n  pos_inf_n  neg_inf_n  negative_n  zero_n  violation_n
0        model_allowed  numeric_basic      0          0          0           0       8            0
1       weight_allowed  numeric_basic      0          0          0           0      36            0
2  denominator_allowed  numeric_basic      0          0          0           0      36            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 2

## Dataset: `P4_PHASE_DESIGN_MATRIX_RANK`

- 역할: Phase design matrix rank audit
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv`
- 예상 shape: `(32, 17)`
- 예상 SHA256: `17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae`

In [ ]:
result = inspect_dataset(
    label='P4_PHASE_DESIGN_MATRIX_RANK',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv',
    expected_shape=(32, 17),
    expected_sha256='17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae',
    candidate_keys=[['model_id', 'coding']],
)

extra_rank()

### 5.1 File Identification - `P4_PHASE_DESIGN_MATRIX_RANK`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_PHASE_DESIGN_MATRIX_RANK,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv,True,.csv,5830,2026-07-13T11:12:52.229568,17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae,17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae,True

### 5.2 Basic Structure

      shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (32, 17)       (32, 17)         True         32            17                8178       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0       model_id + coding    model_id + coding    True              0                   0                     0                32

### 5.3 Full Column List

    position                       column    dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1                     model_id      str          32          0     0.000000       18      0.562500        False        False                     True         0.062500
1          2                    sample_id      str          32          0     0.000000       12      0.375000        False        False                     True         0.125000
2          3                       target      str          32          0     0.000000        3      0.093750        False        False                    False         0.375000
3          4                       coding      str          32          0     0.000000        2      0.062500        False        False                    False         0.562500
4          5                       status      str          32          0     0.000000        3      0.093750        False        False                    False         0.437500
5          6                      train_n    int64          32          0     0.000000        6      0.187500        False        False                    False         0.281250
6          7            raw_feature_count    int64          32          0     0.000000        6      0.187500        False        False                     True         0.312500
7          8        numeric_feature_count  float64          28          4    12.500000        6      0.214286        False        False                    False         0.250000
8          9    categorical_feature_count  float64          28          4    12.500000        1      0.035714        False         True                    False         0.875000
9         10        encoded_feature_count  float64          28          4    12.500000        6      0.214286        False        False                    False         0.218750
10        11                         rank  float64          28          4    12.500000        4      0.142857        False        False                    False         0.375000
11        12              rank_deficiency  float64          28          4    12.500000        2      0.071429        False        False                    False         0.437500
12        13             condition_number  float64          28          4    12.500000       16      0.571429        False        False                    False         0.125000
13        14             constant_columns      str          14         18    56.250000        1      0.071429        False         True                    False         0.562500
14        15  duplicate_encoded_columns_n  float64          28          4    12.500000        1      0.035714        False         True                    False         0.875000
15        16       perfect_alias_groups_n  float64          28          4    12.500000        2      0.071429        False        False                    False         0.437500
16        17           recommended_action      str          18         14    43.750000        2      0.111111        False        False                    False         0.437500

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   model_id                     32 non-null     str
 1   sample_id                    32 non-null     str
 2   target                       32 non-null     str
 3   coding                       32 non-null     str
 4   status                       32 non-null     str
 5   train_n                      32 non-null     int64
 6   raw_feature_count            32 non-null     int64
 7   numeric_feature_count        28 non-null     float64
 8   categorical_feature_count    28 non-null     float64
 9   encoded_feature_count        28 non-null     float64
 10  rank                         28 non-null     float64
 11  rank_deficiency              28 non-null     float64
 12  condition_number             28 non-null     float64
 13  constant_columns             14 non-null     str
 14  duplicate_encoded_columns_n  28 non-null     float64
 15  perfect_alias_groups_n       28 non-null     float64
 16  recommended_action           18 non-null     str
dtypes: float64(8), int64(2), str(7)
memory usage: 8.0 KB

### 5.5 Head

,model_id,sample_id,target,coding,status,train_n,raw_feature_count,numeric_feature_count,categorical_feature_count,encoded_feature_count,rank,rank_deficiency,condition_number,constant_columns,duplicate_encoded_columns_n,perfect_alias_groups_n,recommended_action
0,P1_STRUCTURE,P1_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,4623,13,8.000000,5.000000,38.000000,34.000000,4.000000,110.609575,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
1,P1_STRUCTURE,P1_STRUCTURE_READY,a_rate_pct,treatment,PASS,4623,13,8.000000,5.000000,33.000000,33.000000,0.000000,28.406045,NaN,0.000000,0.000000,NaN
2,P1_SELECTIVITY,P1_SELECTIVITY_READY,a_rate_pct,onehot_full,WARN,1789,17,12.000000,5.000000,39.000000,35.000000,4.000000,88.918897,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
3,P1_SELECTIVITY,P1_SELECTIVITY_READY,a_rate_pct,treatment,PASS,1789,17,12.000000,5.000000,34.000000,34.000000,0.000000,51.290510,NaN,0.000000,0.000000,NaN
4,P2_S,P2_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.

### 5.6 Tail

,model_id,sample_id,target,coding,status,train_n,raw_feature_count,numeric_feature_count,categorical_feature_count,encoded_feature_count,rank,rank_deficiency,condition_number,constant_columns,duplicate_encoded_columns_n,perfect_alias_groups_n,recommended_action
27,P4_P_JOINT_STRUCTURE_A_RATE,P4_JOINT_STRUCTURE_READY,graduate_school_progression_rate_pct,treatment,PASS,4623,12,7.000000,5.000000,32.000000,32.000000,0.000000,28.732336,NaN,0.000000,0.000000,NaN
28,P4_E_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,health_employment_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
29,P4_E_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,health_employment_rate_pct,treatment,PASS,1789,16,11.000000,5.000000,33.000000,33.000000,0.000000,51.841374,NaN,0.000000,0.000000,NaN
30,P4_P_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
31,P4_P_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,treatment,PASS,1789,16,11.000000,5.000000,33.000000,33.000000,0.000000,51.841374,NaN,0.000000,0.000000,NaN

### 5.7 Random Sample

,model_id,sample_id,target,coding,status,train_n,raw_feature_count,numeric_feature_count,categorical_feature_count,encoded_feature_count,rank,rank_deficiency,condition_number,constant_columns,duplicate_encoded_columns_n,perfect_alias_groups_n,recommended_action
15,P4_E_SELECTIVITY_A_RATE,P4_E_SELECTIVITY_READY,health_employment_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
22,P4_P_SELECTIVITY_A_RATE,P4_P_SELECTIVITY_READY,graduate_school_progression_rate_pct,treatment,PASS,1805,16,11.000000,5.000000,34.000000,34.000000,0.000000,74.634962,NaN,0.000000,0.000000,NaN
0,P1_STRUCTURE,P1_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,4623,13,8.000000,5.000000,38.000000,34.000000,4.000000,110.609575,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
9,P3_S,P3_STRUCTURE_READY,a_rate_pct,treatment,PASS,6302,11,6.000000,5.000000,32.000000,32.000000,0.000000,99.130561,NaN,0.000000,0.000000,NaN
12,P4_E_STRUCTURE_A_RATE,P4_E_STRUCTURE_READY,health_employment_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
4,P2_S,P2_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
11,P3_Q,P3_SELECTIVITY_READY,a_rate_pct,treatment,PASS,2355,15,10.000000,5.000000,33.000000,33.000000,0.000000,76.946289,NaN,0.000000,0.000000,NaN
8,P3_S,P3_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
13,P4_E_STRUCTURE_A_RATE,P4_E_STRUCTURE_READY,health_employment_rate_pct,treatment,PASS,4623,12,7.000000,5.000000,32.000000,32.000000,0.000000,28.732336,NaN,0.000000,0.000000,NaN
27,P4_P_JOINT_STRUCTURE_A_RATE,P4_JOINT_STRUCTURE_READY,graduate_school_progression_rate_pct,treatment,PASS,4623,12,7.000000,5.000000,32.000000,32.000000,0.000000,28.732336,NaN,0.000000,0.000000,NaN

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,train_n,32.000000,"3,494.125000","1,677.090833","1,789.000000","1,789.000000","1,789.000000","1,789.000000","1,789.000000","3,489.000000","4,623.000000","6,140.500000","6,302.000000","6,302.000000","6,302.000000",0,0.000000,0,0.000000,0,0,6
1,raw_feature_count,32.000000,13.875000,2.121320,11.000000,11.000000,11.000000,11.100000,12.000000,14.000000,16.000000,16.000000,16.450000,17.000000,17.000000,0,0.000000,0,0.000000,0,0,6
2,numeric_feature_count,28.000000,8.857143,2.138090,6.000000,6.000000,6.000000,6.000000,7.000000,9.000000,11.000000,11.000000,11.650000,12.000000,12.000000,4,12.500000,0,0.000000,0,0,6
3,categorical_feature_count,28.000000,5.000000,0.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4,12.500000,0,0.000000,0,0,1
4,encoded_feature_count,28.000000,35.285714,2.636737,32.000000,32.000000,32.000000,32.000000,33.000000,35.500000,38.000000,38.000000,38.650000,39.000000,39.000000,4,12.500000,0,0.000000,0,0,6
5,rank,28.000000,33.285714,0.854493,32.000000,32.000000,32.000000,32.000000,33.000000,33.000000,34.000000,34.000000,34.650000,35.000000,35.000000,4,12.500000,0,0.000000,0,0,4
6,rank_deficiency,28.000000,2.000000,2.036700,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4,12.500000,14,43.750000,0,0,2
7,condition_number,28.000000,82.333119,31.713581,28.406045,28.494143,28.732336,28.732336,51.841374,88.898808,102.000314,113.039692,131.099671,137.818430,137.818430,4,12.500000,0,0.000000,0,0,16
8,duplicate_encoded_columns_n,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4,12.500000,28,87.500000,0,0,1
9,perfect_alias_groups_n,28.000000,2.000000,2.036700,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4,12.500000,14,43.750000,0,0,2

### 5.8 Categorical/String/Boolean Describe

               column dtype  count  missing_n  missing_pct  nunique                                      top  freq   top_pct                                                                                               sample_values
0            model_id   str     32          0     0.000000       18                             P1_STRUCTURE     2  6.250000                                                          P1_STRUCTURE | P1_SELECTIVITY | P2_S | P2_Q | P3_S
1           sample_id   str     32          0     0.000000       12                 P4_JOINT_STRUCTURE_READY     4 12.500000  P1_STRUCTURE_READY | P1_SELECTIVITY_READY | P2_STRUCTURE_READY | P2_SELECTIVITY_READY | P3_STRUCTURE_READY
2              target   str     32          0     0.000000        3                               a_rate_pct    12 37.500000                              a_rate_pct | health_employment_rate_pct | graduate_school_progression_rate_pct
3              coding   str     32          0     0.000000        2                                treatment    18 56.250000                                                                                     onehot_full | treatment
4              status   str     32          0     0.000000        3                                     WARN    14 43.750000                                                                     WARN | PASS | PENDING_UPSTREAM_RESIDUAL
5    constant_columns   str     14         18    56.250000        1                       degree_course_대학과정    14 43.750000                                                                                          degree_course_대학과정
6  recommended_action   str     18         14    43.750000        2  Use treatment coding for linear models.    14 43.750000    Use treatment coding for linear models. | Generate required OOF grade residual before fitting this spec.

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

    rank                       column    dtype  missing_n  missing_pct  non_null_n  nunique
13     1             constant_columns      str         18    56.250000          14        1
16     2           recommended_action      str         14    43.750000          18        2
7      3        numeric_feature_count  float64          4    12.500000          28        6
8      4    categorical_feature_count  float64          4    12.500000          28        1
9      5        encoded_feature_count  float64          4    12.500000          28        6
10     6                         rank  float64          4    12.500000          28        4
11     7              rank_deficiency  float64          4    12.500000          28        2
12     8             condition_number  float64          4    12.500000          28       16
14     9  duplicate_encoded_columns_n  float64          4    12.500000          28        1
15    10       perfect_alias_groups_n  float64          4    12.500000          28        2

### 5.10 Top Cardinality Columns

                         column    dtype  nunique  unique_ratio
0                      model_id      str       18      0.562500
12             condition_number  float64       16      0.571429
1                     sample_id      str       12      0.375000
7         numeric_feature_count  float64        6      0.214286
9         encoded_feature_count  float64        6      0.214286
5                       train_n    int64        6      0.187500
6             raw_feature_count    int64        6      0.187500
10                         rank  float64        4      0.142857
2                        target      str        3      0.093750
4                        status      str        3      0.093750
16           recommended_action      str        2      0.111111
11              rank_deficiency  float64        2      0.071429
15       perfect_alias_groups_n  float64        2      0.071429
3                        coding      str        2      0.062500
13             constant_columns      str        1      0.071429
8     categorical_feature_count  float64        1      0.035714
14  duplicate_encoded_columns_n  float64        1      0.035714

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

                         column    dtype  nunique  top_value_share
8     categorical_feature_count  float64        1         0.875000
13             constant_columns      str        1         0.562500
14  duplicate_encoded_columns_n  float64        1         0.875000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                         column              check    nan_n  pos_inf_n  neg_inf_n  negative_n    zero_n  violation_n
0                       train_n      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
1                       train_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
2             raw_feature_count      numeric_basic 0.000000   0.000000   0.000000    0.000000  0.000000            0
3             raw_feature_count  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
4         numeric_feature_count      numeric_basic 4.000000   0.000000   0.000000    0.000000  0.000000            0
5         numeric_feature_count  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
6     categorical_feature_count      numeric_basic 4.000000   0.000000   0.000000    0.000000  0.000000            0
7     categorical_feature_count  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
8         encoded_feature_count      numeric_basic 4.000000   0.000000   0.000000    0.000000  0.000000            0
9         encoded_feature_count  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
10                         rank      numeric_basic 4.000000   0.000000   0.000000    0.000000  0.000000            0
11              rank_deficiency      numeric_basic 4.000000   0.000000   0.000000    0.000000 14.000000            0
12             condition_number      numeric_basic 4.000000   0.000000   0.000000    0.000000  0.000000            0
13  duplicate_encoded_columns_n      numeric_basic 4.000000   0.000000   0.000000    0.000000 28.000000            0
14  duplicate_encoded_columns_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0
15       perfect_alias_groups_n      numeric_basic 4.000000   0.000000   0.000000    0.000000 14.000000            0
16       perfect_alias_groups_n  count_nonnegative      NaN        NaN        NaN         NaN       NaN            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 3

### 6.7 Rank Additional Checks

rank_deficiency > 0

,model_id,sample_id,target,coding,status,train_n,raw_feature_count,numeric_feature_count,categorical_feature_count,encoded_feature_count,rank,rank_deficiency,condition_number,constant_columns,duplicate_encoded_columns_n,perfect_alias_groups_n,recommended_action
0,P1_STRUCTURE,P1_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,4623,13,8.000000,5.000000,38.000000,34.000000,4.000000,110.609575,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
2,P1_SELECTIVITY,P1_SELECTIVITY_READY,a_rate_pct,onehot_full,WARN,1789,17,12.000000,5.000000,39.000000,35.000000,4.000000,88.918897,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
4,P2_S,P2_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
6,P2_Q,P2_SELECTIVITY_READY,a_rate_pct,onehot_full,WARN,2355,15,10.000000,5.000000,38.000000,34.000000,4.000000,93.787695,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
8,P3_S,P3_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
10,P3_Q,P3_SELECTIVITY_READY,a_rate_pct,onehot_full,WARN,2355,15,10.000000,5.000000,38.000000,34.000000,4.000000,93.787695,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
12,P4_E_STRUCTURE_A_RATE,P4_E_STRUCTURE_READY,health_employment_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
15,P4_E_SELECTIVITY_A_RATE,P4_E_SELECTIVITY_READY,health_employment_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
18,P4_P_STRUCTURE_A_RATE,P4_P_STRUCTURE_READY,graduate_school_progression_rate_pct,onehot_full,WARN,4687,12,7.000000,5.000000,38.000000,34.000000,4.000000,118.621976,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
21,P4_P_SELECTIVITY_A_RATE,P4_P_SELECTIVITY_READY,graduate_school_progression_rate_pct,onehot_full,WARN,1805,16,11.000000,5.000000,39.000000,35.000000,4.000000,89.589282,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
24,P4_E_JOINT_STRUCTURE_A_RATE,P4_JOINT_STRUCTURE_READY,health_employment_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
26,P4_P_JOINT_STRUCTURE_A_RATE,P4_JOINT_STRUCTURE_READY,graduate_school_progression_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
28,P4_E_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,health_employment_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
30,P4_P_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.

condition_number > 30

,model_id,sample_id,target,coding,status,train_n,raw_feature_count,numeric_feature_count,categorical_feature_count,encoded_feature_count,rank,rank_deficiency,condition_number,constant_columns,duplicate_encoded_columns_n,perfect_alias_groups_n,recommended_action
0,P1_STRUCTURE,P1_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,4623,13,8.000000,5.000000,38.000000,34.000000,4.000000,110.609575,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
2,P1_SELECTIVITY,P1_SELECTIVITY_READY,a_rate_pct,onehot_full,WARN,1789,17,12.000000,5.000000,39.000000,35.000000,4.000000,88.918897,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
3,P1_SELECTIVITY,P1_SELECTIVITY_READY,a_rate_pct,treatment,PASS,1789,17,12.000000,5.000000,34.000000,34.000000,0.000000,51.290510,NaN,0.000000,0.000000,NaN
4,P2_S,P2_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
5,P2_S,P2_STRUCTURE_READY,a_rate_pct,treatment,PASS,6302,11,6.000000,5.000000,32.000000,32.000000,0.000000,99.130561,NaN,0.000000,0.000000,NaN
6,P2_Q,P2_SELECTIVITY_READY,a_rate_pct,onehot_full,WARN,2355,15,10.000000,5.000000,38.000000,34.000000,4.000000,93.787695,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
7,P2_Q,P2_SELECTIVITY_READY,a_rate_pct,treatment,PASS,2355,15,10.000000,5.000000,33.000000,33.000000,0.000000,76.946289,NaN,0.000000,0.000000,NaN
8,P3_S,P3_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
9,P3_S,P3_STRUCTURE_READY,a_rate_pct,treatment,PASS,6302,11,6.000000,5.000000,32.000000,32.000000,0.000000,99.130561,NaN,0.000000,0.000000,NaN
10,P3_Q,P3_SELECTIVITY_READY,a_rate_pct,onehot_full,WARN,2355,15,10.000000,5.000000,38.000000,34.000000,4.000000,93.787695,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
11,P3_Q,P3_SELECTIVITY_READY,a_rate_pct,treatment,PASS,2355,15,10.000000,5.000000,33.000000,33.000000,0.000000,76.946289,NaN,0.000000,0.000000,NaN
12,P4_E_STRUCTURE_A_RATE,P4_E_STRUCTURE_READY,health_employment_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
15,P4_E_SELECTIVITY_A_RATE,P4_E_SELECTIVITY_READY,health_employment_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
16,P4_E_SELECTIVITY_A_RATE,P4_E_SELECTIVITY_READY,health_employment_rate_pct,treatment,PASS,1789,16,11.000000,5.000000,33.000000,33.000000,0.000000,51.841374,NaN,0.000000,0.000000,NaN
18,P4_P_STRUCTURE_A_RATE,P4_P_STRUCTURE_READY,graduate_school_progression_rate_pct,onehot_full,WARN,4687,12,7.000000,5.000000,38.000000,34.000000,4.000000,118.621976,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
19,P4_P_STRUCTURE_A_RATE,P4_P_STRUCTURE_READY,graduate_school_progression_rate_pct,treatment,PASS,4687,12,7.000000,5.000000,33.000000,33.000000,0.000000,87.530717,NaN,0.000000,0.000000,NaN
21,P4_P_SELECTIVITY_A_RATE,P4_P_SELECTIVITY_READY,graduate_school_progression_rate_pct,onehot_full,WARN,1805,16,11.000000,5.000000,39.000000,35.000000,4.000000,89.589282,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
22,P4_P_SELECTIVITY_A_RATE,P4_P_SELECTIVITY_READY,graduate_school_progression_rate_pct,treatment,PASS,1805,16,11.000000,5.000000,34.000000,34.000000,0.000000,74.634962,NaN,0.000000,0.000000,NaN
24,P4_E_JOINT_STRUCTURE_A_RATE,P4_JOINT_STRUCTURE_READY,health_employment_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
26,P4_P_JOINT_STRUCTURE_A_RATE,P4_JOINT_STRUCTURE_READY,graduate_school_progression_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
28,P4_E_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,health_employment_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
29,P4_E_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,health_employment_rate_pct,treatment,PASS,1789,16,11.000000,5.000000,33.000000,33.000000,0.000000,51.841374,NaN,0.000000,0.000000,NaN
30,P4_P_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,onehot_full,WARN,1789,16,11.000000,5.000000,38.000000,34.000000,4.000000,88.898808,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
31,P4_P_JOINT_SELECTIVITY_A_RATE,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,treatment,PASS,1789,16,11.000000,5.000000,33.000000,33.000000,0.000000,51.841374,NaN,0.000000,0.000000,NaN

condition_number > 100

,model_id,sample_id,target,coding,status,train_n,raw_feature_count,numeric_feature_count,categorical_feature_count,encoded_feature_count,rank,rank_deficiency,condition_number,constant_columns,duplicate_encoded_columns_n,perfect_alias_groups_n,recommended_action
0,P1_STRUCTURE,P1_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,4623,13,8.000000,5.000000,38.000000,34.000000,4.000000,110.609575,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
4,P2_S,P2_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
8,P3_S,P3_STRUCTURE_READY,a_rate_pct,onehot_full,WARN,6302,11,6.000000,5.000000,37.000000,33.000000,4.000000,137.818430,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
12,P4_E_STRUCTURE_A_RATE,P4_E_STRUCTURE_READY,health_employment_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
18,P4_P_STRUCTURE_A_RATE,P4_P_STRUCTURE_READY,graduate_school_progression_rate_pct,onehot_full,WARN,4687,12,7.000000,5.000000,38.000000,34.000000,4.000000,118.621976,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
24,P4_E_JOINT_STRUCTURE_A_RATE,P4_JOINT_STRUCTURE_READY,health_employment_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.
26,P4_P_JOINT_STRUCTURE_A_RATE,P4_JOINT_STRUCTURE_READY,graduate_school_progression_rate_pct,onehot_full,WARN,4623,12,7.000000,5.000000,37.000000,33.000000,4.000000,110.647285,degree_course_대학과정,0.000000,4.000000,Use treatment coding for linear models.

## Dataset: `P4_LINEAR_ALIAS_GROUPS`

- 역할: Linear model alias group audit
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv`
- 예상 shape: `(56, 6)`
- 예상 SHA256: `31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517`

In [ ]:
result = inspect_dataset(
    label='P4_LINEAR_ALIAS_GROUPS',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv',
    expected_shape=(56, 6),
    expected_sha256='31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517',
    candidate_keys=[['group_id']],
)

extra_alias()

### 5.1 File Identification - `P4_LINEAR_ALIAS_GROUPS`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_LINEAR_ALIAS_GROUPS,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv,True,.csv,18248,2026-07-13T11:12:52.232192,31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517,31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517,True

### 5.2 Basic Structure

     shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (56, 6)        (56, 6)         True         56             6               20654       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0                group_id             group_id    True              0                   0                     0                56

### 5.3 Full Column List

   position                 column dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0         1               model_id   str          56          0     0.000000       14      0.250000        False        False                     True         0.071429
1         2                 coding   str          56          0     0.000000        1      0.017857        False         True                    False         1.000000
2         3             alias_type   str          56          0     0.000000        1      0.017857        False         True                    False         1.000000
3         4               group_id   str          56          0     0.000000       56      1.000000        False        False                     True         0.017857
4         5       encoded_features   str          56          0     0.000000       32      0.571429        False        False                    False         0.053571
5         6  recommended_exclusion   str          56          0     0.000000        1      0.017857        False         True                    False         1.000000

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   model_id               56 non-null     str
 1   coding                 56 non-null     str
 2   alias_type             56 non-null     str
 3   group_id               56 non-null     str
 4   encoded_features       56 non-null     str
 5   recommended_exclusion  56 non-null     str
dtypes: str(6)
memory usage: 20.2 KB

### 5.5 Head

,model_id,coding,alias_type,group_id,encoded_features,recommended_exclusion
0,P1_STRUCTURE,onehot_full,svd_nullspace_perfect_alias,P1_STRUCTURE_onehot_full_SVD_001,major_group_7_MED|major_group_7_ART|major_group_7_EDU|major_group_7_SOC|major_group_7_HUM|major_group_7_NAT|major_gr...,use treatment coding or remove hierarchical source features
1,P1_STRUCTURE,onehot_full,svd_nullspace_perfect_alias,P1_STRUCTURE_onehot_full_SVD_002,campus_branch_|campus_branch_분교|degree_course_대학과정|school_type_산업대학|school_type_대학교|school_type_방송통신대학교|school_type_...,use treatment coding or remove hierarchical source features
2,P1_STRUCTURE,onehot_full,svd_nullspace_perfect_alias,P1_STRUCTURE_onehot_full_SVD_003,degree_course_대학과정|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_교육대학|school_type_산업대학|school_type_대학교|campus...,use treatment coding or remove hierarchical source features
3,P1_STRUCTURE,onehot_full,svd_nullspace_perfect_alias,P1_STRUCTURE_onehot_full_SVD_004,school_type_교육대학|school_type_대학교|school_type_각종대학(대학)|school_type_산업대학|school_type_방송통신대학교|region_sido_대구|region_sid...,use treatment coding or remove hierarchical source features
4,P1_SELECTIVITY,onehot_full,svd_nullspace_perfect_alias,P1_SELECTIVITY_onehot_full_SVD_001,major_group_7_ENG|major_group_7_HUM|major_group_7_SOC|major_group_7_NAT|major_group_7_MED|major_group_7_EDU|major_gr...,use treatment coding or remove hierarchical source features

### 5.6 Tail

,model_id,coding,alias_type,group_id,encoded_features,recommended_exclusion
51,P4_E_JOINT_SELECTIVITY_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_E_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_004,major_group_7_EDU|major_group_7_MED|major_group_7_NAT|major_group_7_HUM|major_group_7_ART|major_group_7_ENG|major_gr...,use treatment coding or remove hierarchical source features
52,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_001,school_type_산업대학|school_type_교육대학|school_type_대학교|degree_course_대학과정|major_group_7_SOC|major_group_7_ENG|major_group...,use treatment coding or remove hierarchical source features
53,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_002,degree_course_대학과정|region_sido_대구|region_sido_인천|region_sido_강원|region_sido_대전|region_sido_경기|region_sido_충북|region_...,use treatment coding or remove hierarchical source features
54,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_003,campus_branch_|campus_branch_분교|degree_course_대학과정|major_group_7_NAT|major_group_7_MED|major_group_7_EDU|major_group...,use treatment coding or remove hierarchical source features
55,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_004,major_group_7_EDU|major_group_7_MED|major_group_7_NAT|major_group_7_HUM|major_group_7_ART|major_group_7_ENG|major_gr...,use treatment coding or remove hierarchical source features

### 5.7 Random Sample

,model_id,coding,alias_type,group_id,encoded_features,recommended_exclusion
2,P1_STRUCTURE,onehot_full,svd_nullspace_perfect_alias,P1_STRUCTURE_onehot_full_SVD_003,degree_course_대학과정|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_교육대학|school_type_산업대학|school_type_대학교|campus...,use treatment coding or remove hierarchical source features
0,P1_STRUCTURE,onehot_full,svd_nullspace_perfect_alias,P1_STRUCTURE_onehot_full_SVD_001,major_group_7_MED|major_group_7_ART|major_group_7_EDU|major_group_7_SOC|major_group_7_HUM|major_group_7_NAT|major_gr...,use treatment coding or remove hierarchical source features
44,P4_P_JOINT_STRUCTURE_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_P_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_001,degree_course_대학과정|campus_branch_|campus_branch_분교|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_산업대학|school_...,use treatment coding or remove hierarchical source features
9,P2_S,onehot_full,svd_nullspace_perfect_alias,P2_S_onehot_full_SVD_002,school_type_산업대학|school_type_방송통신대학교|school_type_대학교|school_type_교육대학|school_type_각종대학(대학)|degree_course_대학과정|region...,use treatment coding or remove hierarchical source features
35,P4_P_STRUCTURE_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_P_STRUCTURE_A_RATE_onehot_full_SVD_004,school_type_산업대학|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_대학교|school_type_교육대학|region_sido_대전|region_sid...,use treatment coding or remove hierarchical source features
25,P4_E_STRUCTURE_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_E_STRUCTURE_A_RATE_onehot_full_SVD_002,major_group_7_MED|major_group_7_NAT|major_group_7_ENG|major_group_7_SOC|major_group_7_HUM|major_group_7_EDU|major_gr...,use treatment coding or remove hierarchical source features
42,P4_E_JOINT_STRUCTURE_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_E_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_003,school_type_교육대학|school_type_산업대학|school_type_대학교|school_type_각종대학(대학)|school_type_방송통신대학교|campus_branch_|campus_bra...,use treatment coding or remove hierarchical source features
53,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_002,degree_course_대학과정|region_sido_대구|region_sido_인천|region_sido_강원|region_sido_대전|region_sido_경기|region_sido_충북|region_...,use treatment coding or remove hierarchical source features
43,P4_E_JOINT_STRUCTURE_A_RATE,onehot_full,svd_nullspace_perfect_alias,P4_E_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_004,campus_branch_분교|campus_branch_|region_sido_전북|region_sido_대구|region_sido_부산|region_sido_서울|region_sido_충남|region_si...,use treatment coding or remove hierarchical source features
11,P2_S,onehot_full,svd_nullspace_perfect_alias,P2_S_onehot_full_SVD_004,degree_course_대학과정|campus_branch_|campus_branch_분교|major_group_7_ART|major_group_7_EDU|major_group_7_MED|major_group...,use treatment coding or remove hierarchical source features

### 5.8 Numeric Describe

              message
0  No numeric columns

### 5.8 Categorical/String/Boolean Describe

,column,dtype,count,missing_n,missing_pct,nunique,top,freq,top_pct,sample_values
0,model_id,str,56,0,0.000000,14,P1_STRUCTURE,4,7.142857,P1_STRUCTURE | P1_SELECTIVITY | P2_S | P2_Q | P3_S
1,coding,str,56,0,0.000000,1,onehot_full,56,100.000000,onehot_full
2,alias_type,str,56,0,0.000000,1,svd_nullspace_perfect_alias,56,100.000000,svd_nullspace_perfect_alias
3,group_id,str,56,0,0.000000,56,P1_STRUCTURE_onehot_full_SVD_001,1,1.785714,P1_STRUCTURE_onehot_full_SVD_001 | P1_STRUCTURE_onehot_full_SVD_002 | P1_STRUCTURE_onehot_full_SVD_003 | P1_STRUCTUR...
4,encoded_features,str,56,0,0.000000,32,degree_course_대학과정|campus_branch_|campus_branch_분교|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_산업대학|school_...,3,5.357143,major_group_7_MED|major_group_7_ART|major_group_7_EDU|major_group_7_SOC|major_group_7_HUM|major_group_7_NAT|major_gr...
5,recommended_exclusion,str,56,0,0.000000,1,use treatment coding or remove hierarchical source features,56,100.000000,use treatment coding or remove hierarchical source features

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

No missing values

### 5.10 Top Cardinality Columns

                  column dtype  nunique  unique_ratio
3               group_id   str       56      1.000000
4       encoded_features   str       32      0.571429
0               model_id   str       14      0.250000
1                 coding   str        1      0.017857
2             alias_type   str        1      0.017857
5  recommended_exclusion   str        1      0.017857

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

                  column dtype  nunique  top_value_share
1                 coding   str        1         1.000000
2             alias_type   str        1         1.000000
5  recommended_exclusion   str        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                              message
0  No numeric/range checks applicable

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 3

### 6.7 Alias Additional Checks

                         model_id       coding                   alias_type  alias_group_n
0                  P1_SELECTIVITY  onehot_full  svd_nullspace_perfect_alias              4
1                    P1_STRUCTURE  onehot_full  svd_nullspace_perfect_alias              4
2                            P2_Q  onehot_full  svd_nullspace_perfect_alias              4
3                            P2_S  onehot_full  svd_nullspace_perfect_alias              4
4                            P3_Q  onehot_full  svd_nullspace_perfect_alias              4
5                            P3_S  onehot_full  svd_nullspace_perfect_alias              4
6   P4_E_JOINT_SELECTIVITY_A_RATE  onehot_full  svd_nullspace_perfect_alias              4
7     P4_E_JOINT_STRUCTURE_A_RATE  onehot_full  svd_nullspace_perfect_alias              4
8         P4_E_SELECTIVITY_A_RATE  onehot_full  svd_nullspace_perfect_alias              4
9           P4_E_STRUCTURE_A_RATE  onehot_full  svd_nullspace_perfect_alias              4
10  P4_P_JOINT_SELECTIVITY_A_RATE  onehot_full  svd_nullspace_perfect_alias              4
11    P4_P_JOINT_STRUCTURE_A_RATE  onehot_full  svd_nullspace_perfect_alias              4
12        P4_P_SELECTIVITY_A_RATE  onehot_full  svd_nullspace_perfect_alias              4
13          P4_P_STRUCTURE_A_RATE  onehot_full  svd_nullspace_perfect_alias              4

,model_id,coding,group_id,encoded_features,recommended_exclusion
0,P1_STRUCTURE,onehot_full,P1_STRUCTURE_onehot_full_SVD_001,major_group_7_MED|major_group_7_ART|major_group_7_EDU|major_group_7_SOC|major_group_7_HUM|major_group_7_NAT|major_gr...,use treatment coding or remove hierarchical source features
1,P1_STRUCTURE,onehot_full,P1_STRUCTURE_onehot_full_SVD_002,campus_branch_|campus_branch_분교|degree_course_대학과정|school_type_산업대학|school_type_대학교|school_type_방송통신대학교|school_type_...,use treatment coding or remove hierarchical source features
2,P1_STRUCTURE,onehot_full,P1_STRUCTURE_onehot_full_SVD_003,degree_course_대학과정|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_교육대학|school_type_산업대학|school_type_대학교|campus...,use treatment coding or remove hierarchical source features
3,P1_STRUCTURE,onehot_full,P1_STRUCTURE_onehot_full_SVD_004,school_type_교육대학|school_type_대학교|school_type_각종대학(대학)|school_type_산업대학|school_type_방송통신대학교|region_sido_대구|region_sid...,use treatment coding or remove hierarchical source features
4,P1_SELECTIVITY,onehot_full,P1_SELECTIVITY_onehot_full_SVD_001,major_group_7_ENG|major_group_7_HUM|major_group_7_SOC|major_group_7_NAT|major_group_7_MED|major_group_7_EDU|major_gr...,use treatment coding or remove hierarchical source features
5,P1_SELECTIVITY,onehot_full,P1_SELECTIVITY_onehot_full_SVD_002,degree_course_대학과정|campus_branch_분교|campus_branch_|school_type_교육대학|school_type_산업대학|school_type_대학교|region_sido_전남|...,use treatment coding or remove hierarchical source features
6,P1_SELECTIVITY,onehot_full,P1_SELECTIVITY_onehot_full_SVD_003,campus_branch_분교|campus_branch_|school_type_교육대학|school_type_산업대학|school_type_대학교|region_sido_경북|region_sido_전북|regi...,use treatment coding or remove hierarchical source features
7,P1_SELECTIVITY,onehot_full,P1_SELECTIVITY_onehot_full_SVD_004,school_type_산업대학|school_type_대학교|school_type_교육대학|degree_course_대학과정|major_group_7_MED|major_group_7_ENG|major_group...,use treatment coding or remove hierarchical source features
8,P2_S,onehot_full,P2_S_onehot_full_SVD_001,major_group_7_EDU|major_group_7_NAT|major_group_7_MED|major_group_7_ENG|major_group_7_ART|major_group_7_HUM|major_gr...,use treatment coding or remove hierarchical source features
9,P2_S,onehot_full,P2_S_onehot_full_SVD_002,school_type_산업대학|school_type_방송통신대학교|school_type_대학교|school_type_교육대학|school_type_각종대학(대학)|degree_course_대학과정|region...,use treatment coding or remove hierarchical source features
10,P2_S,onehot_full,P2_S_onehot_full_SVD_003,campus_branch_분교|campus_branch_|school_type_산업대학|school_type_교육대학|school_type_대학교|school_type_방송통신대학교|school_type_각종...,use treatment coding or remove hierarchical source features
11,P2_S,onehot_full,P2_S_onehot_full_SVD_004,degree_course_대학과정|campus_branch_|campus_branch_분교|major_group_7_ART|major_group_7_EDU|major_group_7_MED|major_group...,use treatment coding or remove hierarchical source features
12,P2_Q,onehot_full,P2_Q_onehot_full_SVD_001,school_type_교육대학|school_type_대학교|school_type_산업대학|campus_branch_|campus_branch_분교|major_group_7_HUM|major_group_7_EN...,use treatment coding or remove hierarchical source features
13,P2_Q,onehot_full,P2_Q_onehot_full_SVD_002,degree_course_대학과정|campus_branch_|campus_branch_분교|school_type_대학교|school_type_산업대학|school_type_교육대학|region_sido_대구|...,use treatment coding or remove hierarchical source features
14,P2_Q,onehot_full,P2_Q_onehot_full_SVD_003,campus_branch_|campus_branch_분교|degree_course_대학과정|region_sido_세종|region_sido_대구|region_sido_전북|region_sido_인천|regio...,use treatment coding or remove hierarchical source features
15,P2_Q,onehot_full,P2_Q_onehot_full_SVD_004,major_group_7_ENG|major_group_7_HUM|major_group_7_NAT|major_group_7_SOC|major_group_7_MED|major_group_7_ART|major_gr...,use treatment coding or remove hierarchical source features
16,P3_S,onehot_full,P3_S_onehot_full_SVD_001,major_group_7_EDU|major_group_7_NAT|major_group_7_MED|major_group_7_ENG|major_group_7_ART|major_group_7_HUM|major_gr...,use treatment coding or remove hierarchical source features
17,P3_S,onehot_full,P3_S_onehot_full_SVD_002,school_type_산업대학|school_type_방송통신대학교|school_type_대학교|school_type_교육대학|school_type_각종대학(대학)|degree_course_대학과정|region...,use treatment coding or remove hierarchical source features
18,P3_S,onehot_full,P3_S_onehot_full_SVD_003,campus_branch_분교|campus_branch_|school_type_산업대학|school_type_교육대학|school_type_대학교|school_type_방송통신대학교|school_type_각종...,use treatment coding or remove hierarchical source features
19,P3_S,onehot_full,P3_S_onehot_full_SVD_004,degree_course_대학과정|campus_branch_|campus_branch_분교|major_group_7_ART|major_group_7_EDU|major_group_7_MED|major_group...,use treatment coding or remove hierarchical source features
20,P3_Q,onehot_full,P3_Q_onehot_full_SVD_001,school_type_교육대학|school_type_대학교|school_type_산업대학|campus_branch_|campus_branch_분교|major_group_7_HUM|major_group_7_EN...,use treatment coding or remove hierarchical source features
21,P3_Q,onehot_full,P3_Q_onehot_full_SVD_002,degree_course_대학과정|campus_branch_|campus_branch_분교|school_type_대학교|school_type_산업대학|school_type_교육대학|region_sido_대구|...,use treatment coding or remove hierarchical source features
22,P3_Q,onehot_full,P3_Q_onehot_full_SVD_003,campus_branch_|campus_branch_분교|degree_course_대학과정|region_sido_세종|region_sido_대구|region_sido_전북|region_sido_인천|regio...,use treatment coding or remove hierarchical source features
23,P3_Q,onehot_full,P3_Q_onehot_full_SVD_004,major_group_7_ENG|major_group_7_HUM|major_group_7_NAT|major_group_7_SOC|major_group_7_MED|major_group_7_ART|major_gr...,use treatment coding or remove hierarchical source features
24,P4_E_STRUCTURE_A_RATE,onehot_full,P4_E_STRUCTURE_A_RATE_onehot_full_SVD_001,degree_course_대학과정|campus_branch_|campus_branch_분교|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_산업대학|school_...,use treatment coding or remove hierarchical source features
25,P4_E_STRUCTURE_A_RATE,onehot_full,P4_E_STRUCTURE_A_RATE_onehot_full_SVD_002,major_group_7_MED|major_group_7_NAT|major_group_7_ENG|major_group_7_SOC|major_group_7_HUM|major_group_7_EDU|major_gr...,use treatment coding or remove hierarchical source features
26,P4_E_STRUCTURE_A_RATE,onehot_full,P4_E_STRUCTURE_A_RATE_onehot_full_SVD_003,school_type_교육대학|school_type_산업대학|school_type_대학교|school_type_각종대학(대학)|school_type_방송통신대학교|campus_branch_|campus_bra...,use treatment coding or remove hierarchical source features
27,P4_E_STRUCTURE_A_RATE,onehot_full,P4_E_STRUCTURE_A_RATE_onehot_full_SVD_004,campus_branch_분교|campus_branch_|region_sido_전북|region_sido_대구|region_sido_부산|region_sido_서울|region_sido_충남|region_si...,use treatment coding or remove hierarchical source features
28,P4_E_SELECTIVITY_A_RATE,onehot_full,P4_E_SELECTIVITY_A_RATE_onehot_full_SVD_001,school_type_산업대학|school_type_교육대학|school_type_대학교|degree_course_대학과정|major_group_7_SOC|major_group_7_ENG|major_group...,use treatment coding or remove hierarchical source features
29,P4_E_SELECTIVITY_A_RATE,onehot_full,P4_E_SELECTIVITY_A_RATE_onehot_full_SVD_002,degree_course_대학과정|region_sido_대구|region_sido_인천|region_sido_강원|region_sido_대전|region_sido_경기|region_sido_충북|region_...,use treatment coding or remove hierarchical source features
30,P4_E_SELECTIVITY_A_RATE,onehot_full,P4_E_SELECTIVITY_A_RATE_onehot_full_SVD_003,campus_branch_|campus_branch_분교|degree_course_대학과정|major_group_7_NAT|major_group_7_MED|major_group_7_EDU|major_group...,use treatment coding or remove hierarchical source features
31,P4_E_SELECTIVITY_A_RATE,onehot_full,P4_E_SELECTIVITY_A_RATE_onehot_full_SVD_004,major_group_7_EDU|major_group_7_MED|major_group_7_NAT|major_group_7_HUM|major_group_7_ART|major_group_7_ENG|major_gr...,use treatment coding or remove hierarchical source features
32,P4_P_STRUCTURE_A_RATE,onehot_full,P4_P_STRUCTURE_A_RATE_onehot_full_SVD_001,degree_course_대학과정|campus_branch_|campus_branch_분교|major_group_7_NAT|major_group_7_MED|major_group_7_HUM|major_group...,use treatment coding or remove hierarchical source features
33,P4_P_STRUCTURE_A_RATE,onehot_full,P4_P_STRUCTURE_A_RATE_onehot_full_SVD_002,school_type_교육대학|school_type_각종대학(대학)|school_type_산업대학|school_type_대학교|school_type_방송통신대학교|campus_branch_분교|campus_b...,use treatment coding or remove hierarchical source features
34,P4_P_STRUCTURE_A_RATE,onehot_full,P4_P_STRUCTURE_A_RATE_onehot_full_SVD_003,campus_branch_|campus_branch_분교|major_group_7_NAT|major_group_7_HUM|major_group_7_ART|major_group_7_MED|major_group_...,use treatment coding or remove hierarchical source features
35,P4_P_STRUCTURE_A_RATE,onehot_full,P4_P_STRUCTURE_A_RATE_onehot_full_SVD_004,school_type_산업대학|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_대학교|school_type_교육대학|region_sido_대전|region_sid...,use treatment coding or remove hierarchical source features
36,P4_P_SELECTIVITY_A_RATE,onehot_full,P4_P_SELECTIVITY_A_RATE_onehot_full_SVD_001,school_type_대학교|school_type_산업대학|school_type_교육대학|degree_course_대학과정|campus_branch_분교|campus_branch_|major_group_7_M...,use treatment coding or remove hierarchical source features
37,P4_P_SELECTIVITY_A_RATE,onehot_full,P4_P_SELECTIVITY_A_RATE_onehot_full_SVD_002,campus_branch_|campus_branch_분교|degree_course_대학과정|region_sido_세종|region_sido_서울|region_sido_대전|region_sido_전남|regio...,use treatment coding or remove hierarchical source features
38,P4_P_SELECTIVITY_A_RATE,onehot_full,P4_P_SELECTIVITY_A_RATE_onehot_full_SVD_003,region_sido_대구|region_sido_세종|region_sido_부산|region_sido_인천|region_sido_전남|region_sido_강원|region_sido_경북|region_sido_전북,use treatment coding or remove hierarchical source features
39,P4_P_SELECTIVITY_A_RATE,onehot_full,P4_P_SELECTIVITY_A_RATE_onehot_full_SVD_004,degree_course_대학과정|major_group_7_ART|major_group_7_SOC|major_group_7_HUM|major_group_7_ENG|major_group_7_NAT|major_g...,use treatment coding or remove hierarchical source features
40,P4_E_JOINT_STRUCTURE_A_RATE,onehot_full,P4_E_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_001,degree_course_대학과정|campus_branch_|campus_branch_분교|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_산업대학|school_...,use treatment coding or remove hierarchical source features
41,P4_E_JOINT_STRUCTURE_A_RATE,onehot_full,P4_E_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_002,major_group_7_MED|major_group_7_NAT|major_group_7_ENG|major_group_7_SOC|major_group_7_HUM|major_group_7_EDU|major_gr...,use treatment coding or remove hierarchical source features
42,P4_E_JOINT_STRUCTURE_A_RATE,onehot_full,P4_E_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_003,school_type_교육대학|school_type_산업대학|school_type_대학교|school_type_각종대학(대학)|school_type_방송통신대학교|campus_branch_|campus_bra...,use treatment coding or remove hierarchical source features
43,P4_E_JOINT_STRUCTURE_A_RATE,onehot_full,P4_E_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_004,campus_branch_분교|campus_branch_|region_sido_전북|region_sido_대구|region_sido_부산|region_sido_서울|region_sido_충남|region_si...,use treatment coding or remove hierarchical source features
44,P4_P_JOINT_STRUCTURE_A_RATE,onehot_full,P4_P_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_001,degree_course_대학과정|campus_branch_|campus_branch_분교|school_type_각종대학(대학)|school_type_방송통신대학교|school_type_산업대학|school_...,use treatment coding or remove hierarchical source features
45,P4_P_JOINT_STRUCTURE_A_RATE,onehot_full,P4_P_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_002,major_group_7_MED|major_group_7_NAT|major_group_7_ENG|major_group_7_SOC|major_group_7_HUM|major_group_7_EDU|major_gr...,use treatment coding or remove hierarchical source features
46,P4_P_JOINT_STRUCTURE_A_RATE,onehot_full,P4_P_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_003,school_type_교육대학|school_type_산업대학|school_type_대학교|school_type_각종대학(대학)|school_type_방송통신대학교|campus_branch_|campus_bra...,use treatment coding or remove hierarchical source features
47,P4_P_JOINT_STRUCTURE_A_RATE,onehot_full,P4_P_JOINT_STRUCTURE_A_RATE_onehot_full_SVD_004,campus_branch_분교|campus_branch_|region_sido_전북|region_sido_대구|region_sido_부산|region_sido_서울|region_sido_충남|region_si...,use treatment coding or remove hierarchical source features
48,P4_E_JOINT_SELECTIVITY_A_RATE,onehot_full,P4_E_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_001,school_type_산업대학|school_type_교육대학|school_type_대학교|degree_course_대학과정|major_group_7_SOC|major_group_7_ENG|major_group...,use treatment coding or remove hierarchical source features
49,P4_E_JOINT_SELECTIVITY_A_RATE,onehot_full,P4_E_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_002,degree_course_대학과정|region_sido_대구|region_sido_인천|region_sido_강원|region_sido_대전|region_sido_경기|region_sido_충북|region_...,use treatment coding or remove hierarchical source features
50,P4_E_JOINT_SELECTIVITY_A_RATE,onehot_full,P4_E_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_003,campus_branch_|campus_branch_분교|degree_course_대학과정|major_group_7_NAT|major_group_7_MED|major_group_7_EDU|major_group...,use treatment coding or remove hierarchical source features
51,P4_E_JOINT_SELECTIVITY_A_RATE,onehot_full,P4_E_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_004,major_group_7_EDU|major_group_7_MED|major_group_7_NAT|major_group_7_HUM|major_group_7_ART|major_group_7_ENG|major_gr...,use treatment coding or remove hierarchical source features
52,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_001,school_type_산업대학|school_type_교육대학|school_type_대학교|degree_course_대학과정|major_group_7_SOC|major_group_7_ENG|major_group...,use treatment coding or remove hierarchical source features
53,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_002,degree_course_대학과정|region_sido_대구|region_sido_인천|region_sido_강원|region_sido_대전|region_sido_경기|region_sido_충북|region_...,use treatment coding or remove hierarchical source features
54,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_003,campus_branch_|campus_branch_분교|degree_course_대학과정|major_group_7_NAT|major_group_7_MED|major_group_7_EDU|major_group...,use treatment coding or remove hierarchical source features
55,P4_P_JOINT_SELECTIVITY_A_RATE,onehot_full,P4_P_JOINT_SELECTIVITY_A_RATE_onehot_full_SVD_004,major_group_7_EDU|major_group_7_MED|major_group_7_NAT|major_group_7_HUM|major_group_7_ART|major_group_7_ENG|major_gr...,use treatment coding or remove hierarchical source features

## Dataset: `P4_VIF_TOP30_BY_PHASE`

- 역할: Top VIF values by model phase
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv`
- 예상 shape: `(420, 5)`
- 예상 SHA256: `fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea`

In [ ]:
result = inspect_dataset(
    label='P4_VIF_TOP30_BY_PHASE',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv',
    expected_shape=(420, 5),
    expected_sha256='fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea',
    candidate_keys=[['model_id', 'rank']],
)

extra_vif()

### 5.1 File Identification - `P4_VIF_TOP30_BY_PHASE`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_VIF_TOP30_BY_PHASE,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv,True,.csv,27632,2026-07-13T11:12:52.232858,fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea,fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea,True

### 5.2 Basic Structure

      shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (420, 5)       (420, 5)         True        420             5               29282       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0         model_id + rank      model_id + rank    True              0                   0                     0               420

### 5.3 Full Column List

   position                      column    dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0         1                    model_id      str         420          0     0.000000       14      0.033333        False        False                     True         0.071429
1         2                        rank    int64         420          0     0.000000       30      0.071429        False        False                    False         0.033333
2         3             encoded_feature      str         420          0     0.000000       38      0.090476        False        False                    False         0.033333
3         4                         vif  float64         420          0     0.000000      240      0.571429        False        False                    False         0.007143
4         5  corr_matrix_rank_deficient     bool         420          0     0.000000        1      0.002381        False         True                    False         1.000000

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   model_id                    420 non-null    str
 1   rank                        420 non-null    int64
 2   encoded_feature             420 non-null    str
 3   vif                         420 non-null    float64
 4   corr_matrix_rank_deficient  420 non-null    bool
dtypes: bool(1), float64(1), int64(1), str(2)
memory usage: 28.6 KB

### 5.5 Head

       model_id  rank      encoded_feature        vif  corr_matrix_rank_deficient
0  P1_STRUCTURE     1      school_type_대학교 134.631453                       False
1  P1_STRUCTURE     2     school_type_교육대학  87.177711                       False
2  P1_STRUCTURE     3  school_type_방송통신대학교  28.997865                       False
3  P1_STRUCTURE     4     school_type_산업대학  24.094388                       False
4  P1_STRUCTURE     5       region_sido_서울   4.719472                       False

### 5.6 Tail

                          model_id  rank             encoded_feature      vif  corr_matrix_rank_deficient
415  P4_P_JOINT_SELECTIVITY_A_RATE    26              region_sido_대구 1.563596                       False
416  P4_P_JOINT_SELECTIVITY_A_RATE    27                  a_rate_pct 1.372395                       False
417  P4_P_JOINT_SELECTIVITY_A_RATE    28       student_faculty_ratio 1.325696                       False
418  P4_P_JOINT_SELECTIVITY_A_RATE    29  fulltime_faculty_share_pct 1.317928                       False
419  P4_P_JOINT_SELECTIVITY_A_RATE    30              region_sido_전남 1.250603                       False

### 5.7 Random Sample

                          model_id  rank             encoded_feature      vif  corr_matrix_rank_deficient
53                  P1_SELECTIVITY    24              region_sido_경남 2.244976                       False
386  P4_E_JOINT_SELECTIVITY_A_RATE    27                  a_rate_pct 1.372395                       False
196          P4_E_STRUCTURE_A_RATE    17              region_sido_광주 1.872578                       False
414  P4_P_JOINT_SELECTIVITY_A_RATE    25         credit_forfeit_flag 1.882786                       False
304    P4_E_JOINT_STRUCTURE_A_RATE     5              region_sido_서울 4.656230                       False
343    P4_P_JOINT_STRUCTURE_A_RATE    14           major_group_7_EDU 1.951330                       False
235        P4_E_SELECTIVITY_A_RATE    26              region_sido_대구 1.563596                       False
155                           P3_Q     6              region_sido_경기 3.441780                       False
88                            P2_S    29  fulltime_faculty_share_pct 1.093540                       False
144                           P3_S    25           major_group_7_MED 1.409241                       False

### 5.8 Numeric Describe

  column      count      mean       std      min       1%       5%      10%      25%       50%       75%       90%       95%       99%        max  missing_n  missing_pct  zero_n  zero_pct  negative_n  inf_n  nunique
0   rank 420.000000 15.500000  8.665764 1.000000 1.000000 2.000000 3.900000 8.000000 15.500000 23.000000 27.100000 29.000000 30.000000  30.000000          0     0.000000       0  0.000000           0      0       30
1    vif 420.000000  5.910299 16.898138 1.081570 1.097693 1.158883 1.317632 1.710965  2.261186  3.060192  4.720418 24.095359 87.298190 134.639063          0     0.000000       0  0.000000           0      0      240

### 5.8 Categorical/String/Boolean Describe

                       column dtype  count  missing_n  missing_pct  nunique              top  freq    top_pct                                                                                 sample_values
0                    model_id   str    420          0     0.000000       14     P1_STRUCTURE    30   7.142857                                            P1_STRUCTURE | P1_SELECTIVITY | P2_S | P2_Q | P3_S
1             encoded_feature   str    420          0     0.000000       38  school_type_대학교    14   3.333333  school_type_대학교 | school_type_교육대학 | school_type_방송통신대학교 | school_type_산업대학 | region_sido_서울
2  corr_matrix_rank_deficient  bool    420          0     0.000000        1            False   420 100.000000                                                                                         False

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

No missing values

### 5.10 Top Cardinality Columns

                       column    dtype  nunique  unique_ratio
3                         vif  float64      240      0.571429
2             encoded_feature      str       38      0.090476
1                        rank    int64       30      0.071429
0                    model_id      str       14      0.033333
4  corr_matrix_rank_deficient     bool        1      0.002381

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

                       column dtype  nunique  top_value_share
4  corr_matrix_rank_deficient  bool        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                       column          check  nan_n  pos_inf_n  neg_inf_n  negative_n  zero_n  violation_n
0                        rank  numeric_basic      0          0          0           0       0            0
1                         vif  numeric_basic      0          0          0           0       0            0
2  corr_matrix_rank_deficient  numeric_basic      0          0          0           0     420            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 1

### 6.7 VIF Additional Checks

                         model_id     vif_bucket  feature_n
0                  P1_SELECTIVITY  5 <= VIF < 10          2
1                  P1_SELECTIVITY        VIF < 5         28
2                    P1_STRUCTURE        VIF < 5         26
3                    P1_STRUCTURE      VIF >= 10          4
4                            P2_Q  5 <= VIF < 10          1
5                            P2_Q        VIF < 5         29
6                            P2_S        VIF < 5         26
7                            P2_S      VIF >= 10          4
8                            P3_Q  5 <= VIF < 10          1
9                            P3_Q        VIF < 5         29
10                           P3_S        VIF < 5         26
11                           P3_S      VIF >= 10          4
12  P4_E_JOINT_SELECTIVITY_A_RATE  5 <= VIF < 10          1
13  P4_E_JOINT_SELECTIVITY_A_RATE        VIF < 5         29
14    P4_E_JOINT_STRUCTURE_A_RATE        VIF < 5         26
15    P4_E_JOINT_STRUCTURE_A_RATE      VIF >= 10          4
16        P4_E_SELECTIVITY_A_RATE  5 <= VIF < 10          1
17        P4_E_SELECTIVITY_A_RATE        VIF < 5         29
18          P4_E_STRUCTURE_A_RATE        VIF < 5         26
19          P4_E_STRUCTURE_A_RATE      VIF >= 10          4
20  P4_P_JOINT_SELECTIVITY_A_RATE  5 <= VIF < 10          1
21  P4_P_JOINT_SELECTIVITY_A_RATE        VIF < 5         29
22    P4_P_JOINT_STRUCTURE_A_RATE        VIF < 5         26
23    P4_P_JOINT_STRUCTURE_A_RATE      VIF >= 10          4
24        P4_P_SELECTIVITY_A_RATE  5 <= VIF < 10          1
25        P4_P_SELECTIVITY_A_RATE        VIF < 5         29
26          P4_P_STRUCTURE_A_RATE        VIF < 5         26
27          P4_P_STRUCTURE_A_RATE      VIF >= 10          4

                          model_id  rank      encoded_feature        vif  corr_matrix_rank_deficient     vif_bucket
30                  P1_SELECTIVITY     1       region_sido_서울   6.761274                       False  5 <= VIF < 10
31                  P1_SELECTIVITY     2    major_group_7_ENG   5.112440                       False  5 <= VIF < 10
32                  P1_SELECTIVITY     3      school_type_대학교   4.537521                       False        VIF < 5
33                  P1_SELECTIVITY     4     school_type_산업대학   4.084068                       False        VIF < 5
34                  P1_SELECTIVITY     5    major_group_7_NAT   3.874281                       False        VIF < 5
0                     P1_STRUCTURE     1      school_type_대학교 134.631453                       False      VIF >= 10
1                     P1_STRUCTURE     2     school_type_교육대학  87.177711                       False      VIF >= 10
2                     P1_STRUCTURE     3  school_type_방송통신대학교  28.997865                       False      VIF >= 10
3                     P1_STRUCTURE     4     school_type_산업대학  24.094388                       False      VIF >= 10
4                     P1_STRUCTURE     5       region_sido_서울   4.719472                       False        VIF < 5
90                            P2_Q     1       region_sido_서울   5.897703                       False  5 <= VIF < 10
91                            P2_Q     2    major_group_7_ENG   4.997555                       False        VIF < 5
92                            P2_Q     3      school_type_대학교   4.026779                       False        VIF < 5
93                            P2_Q     4     school_type_산업대학   3.730111                       False        VIF < 5
94                            P2_Q     5    major_group_7_SOC   3.472816                       False        VIF < 5
60                            P2_S     1      school_type_대학교  73.686261                       False      VIF >= 10
61                            P2_S     2     school_type_교육대학  44.524336                       False      VIF >= 10
62                            P2_S     3     school_type_산업대학  18.128883                       False      VIF >= 10
63                            P2_S     4  school_type_방송통신대학교  15.394495                       False      VIF >= 10
64                            P2_S     5       region_sido_서울   4.039519                       False        VIF < 5
150                           P3_Q     1       region_sido_서울   5.897703                       False  5 <= VIF < 10
151                           P3_Q     2    major_group_7_ENG   4.997555                       False        VIF < 5
152                           P3_Q     3      school_type_대학교   4.026779                       False        VIF < 5
153                           P3_Q     4     school_type_산업대학   3.730111                       False        VIF < 5
154                           P3_Q     5    major_group_7_SOC   3.472816                       False        VIF < 5
120                           P3_S     1      school_type_대학교  73.686261                       False      VIF >= 10
121                           P3_S     2     school_type_교육대학  44.524336                       False      VIF >= 10
122                           P3_S     3     school_type_산업대학  18.128883                       False      VIF >= 10
123                           P3_S     4  school_type_방송통신대학교  15.394495                       False      VIF >= 10
124                           P3_S     5       region_sido_서울   4.039519                       False        VIF < 5
360  P4_E_JOINT_SELECTIVITY_A_RATE     1       region_sido_서울   6.803382                       False  5 <= VIF < 10
361  P4_E_JOINT_SELECTIVITY_A_RATE     2    major_group_7_ENG   4.797618                       False        VIF < 5
362  P4_E_JOINT_SELECTIVITY_A_RATE     3      school_type_대학교   4.539127                       False        VIF < 5
363  P4_E_JOINT_SELECTIVITY_A_RATE     4     school_type_산업대학   4.083281                       False        VIF < 5
364  P4_E_JOINT_SELECTIVITY_A_RATE     5    major_group_7_EDU   3.684828                       False        VIF < 5
300    P4_E_JOINT_STRUCTURE_A_RATE     1      school_type_대학교 134.639063                       False      VIF >= 10
301    P4_E_JOINT_STRUCTURE_A_RATE     2     school_type_교육대학  87.298190                       False      VIF >= 10
302    P4_E_JOINT_STRUCTURE_A_RATE     3  school_type_방송통신대학교  29.019462                       False      VIF >= 10
303    P4_E_JOINT_STRUCTURE_A_RATE     4     school_type_산업대학  24.113805                       False      VIF >= 10
304    P4_E_JOINT_STRUCTURE_A_RATE     5       region_sido_서울   4.656230                       False        VIF < 5
210        P4_E_SELECTIVITY_A_RATE     1       region_sido_서울   6.803382                       False  5 <= VIF < 10
211        P4_E_SELECTIVITY_A_RATE     2    major_group_7_ENG   4.797618                       False        VIF < 5
212        P4_E_SELECTIVITY_A_RATE     3      school_type_대학교   4.539127                       False        VIF < 5
213        P4_E_SELECTIVITY_A_RATE     4     school_type_산업대학   4.083281                       False        VIF < 5
214        P4_E_SELECTIVITY_A_RATE     5    major_group_7_EDU   3.684828                       False        VIF < 5
180          P4_E_STRUCTURE_A_RATE     1      school_type_대학교 134.639063                       False      VIF >= 10
181          P4_E_STRUCTURE_A_RATE     2     school_type_교육대학  87.298190                       False      VIF >= 10
182          P4_E_STRUCTURE_A_RATE     3  school_type_방송통신대학교  29.019462                       False      VIF >= 10
183          P4_E_STRUCTURE_A_RATE     4     school_type_산업대학  24.113805                       False      VIF >= 10
184          P4_E_STRUCTURE_A_RATE     5       region_sido_서울   4.656230                       False        VIF < 5
390  P4_P_JOINT_SELECTIVITY_A_RATE     1       region_sido_서울   6.803382                       False  5 <= VIF < 10
391  P4_P_JOINT_SELECTIVITY_A_RATE     2    major_group_7_ENG   4.797618                       False        VIF < 5
392  P4_P_JOINT_SELECTIVITY_A_RATE     3      school_type_대학교   4.539127                       False        VIF < 5
393  P4_P_JOINT_SELECTIVITY_A_RATE     4     school_type_산업대학   4.083281                       False        VIF < 5
394  P4_P_JOINT_SELECTIVITY_A_RATE     5    major_group_7_EDU   3.684828                       False        VIF < 5
330    P4_P_JOINT_STRUCTURE_A_RATE     1      school_type_대학교 134.639063                       False      VIF >= 10
331    P4_P_JOINT_STRUCTURE_A_RATE     2     school_type_교육대학  87.298190                       False      VIF >= 10
332    P4_P_JOINT_STRUCTURE_A_RATE     3  school_type_방송통신대학교  29.019462                       False      VIF >= 10
333    P4_P_JOINT_STRUCTURE_A_RATE     4     school_type_산업대학  24.113805                       False      VIF >= 10
334    P4_P_JOINT_STRUCTURE_A_RATE     5       region_sido_서울   4.656230                       False        VIF < 5
270        P4_P_SELECTIVITY_A_RATE     1       region_sido_서울   6.758974                       False  5 <= VIF < 10
271        P4_P_SELECTIVITY_A_RATE     2    major_group_7_ENG   4.728932                       False        VIF < 5
272        P4_P_SELECTIVITY_A_RATE     3      school_type_대학교   4.538648                       False        VIF < 5
273        P4_P_SELECTIVITY_A_RATE     4     school_type_산업대학   4.082612                       False        VIF < 5
274        P4_P_SELECTIVITY_A_RATE     5    major_group_7_EDU   3.605342                       False        VIF < 5
240          P4_P_STRUCTURE_A_RATE     1      school_type_대학교  68.088522                       False      VIF >= 10
241          P4_P_STRUCTURE_A_RATE     2     school_type_교육대학  44.539759                       False      VIF >= 10
242          P4_P_STRUCTURE_A_RATE     3  school_type_방송통신대학교  15.557422                       False      VIF >= 10
243          P4_P_STRUCTURE_A_RATE     4     school_type_산업대학  12.657303                       False      VIF >= 10
244          P4_P_STRUCTURE_A_RATE     5       region_sido_서울   4.608259                       False        VIF < 5

## Dataset: `P4_TARGET_PROFILE_BY_PHASE`

- 역할: Target distribution profiles by phase sample
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv`
- 예상 shape: `(396, 20)`
- 예상 SHA256: `6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a`

In [ ]:
result = inspect_dataset(
    label='P4_TARGET_PROFILE_BY_PHASE',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv',
    expected_shape=(396, 20),
    expected_sha256='6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a',
    candidate_keys=[['row_type', 'sample_id', 'target', 'group']],
)

extra_target_profile()

### 5.1 File Identification - `P4_TARGET_PROFILE_BY_PHASE`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_TARGET_PROFILE_BY_PHASE,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHAS...,workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv,True,.csv,53599,2026-07-13T11:12:59.628858,6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a,6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a,True

### 5.2 Basic Structure

       shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (396, 20)      (396, 20)         True        396            20               88704       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

                 candidate_key_requested                   candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0  row_type + sample_id + target + group  row_type + sample_id + target + group    True              0                   0                     0               396

### 5.3 Full Column List

    position         column    dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1       row_type      str         396          0     0.000000        3      0.007576        False        False                    False         0.636364
1          2      sample_id      str         396          0     0.000000       12      0.030303        False        False                     True         0.083333
2          3         target      str         396          0     0.000000        3      0.007576        False        False                    False         0.333333
3          4          group      str         396          0     0.000000       11      0.027778        False        False                    False         0.090909
4          5              N    int64         396          0     0.000000       60      0.151515        False        False                    False         0.040404
5          6           mean  float64         144        252    63.636364       48      0.333333        False        False                    False         0.636364
6          7            std  float64         144        252    63.636364       48      0.333333        False        False                    False         0.636364
7          8            min  float64          36        360    90.909091        2      0.055556        False        False                    False         0.909091
8          9            p01  float64          36        360    90.909091        5      0.138889        False        False                    False         0.909091
9         10            p05  float64          36        360    90.909091        9      0.250000        False        False                    False         0.909091
10        11            p25  float64          36        360    90.909091        9      0.250000        False        False                    False         0.909091
11        12         median  float64         144        252    63.636364       43      0.298611        False        False                    False         0.636364
12        13            p75  float64          36        360    90.909091       12      0.333333        False        False                    False         0.909091
13        14            p95  float64          36        360    90.909091       12      0.333333        False        False                    False         0.909091
14        15            p99  float64          36        360    90.909091       11      0.305556        False        False                    False         0.909091
15        16            max  float64          36        360    90.909091        4      0.111111        False        False                    False         0.909091
16        17     zero_ratio  float64         396          0     0.000000      103      0.260101        False        False                    False         0.131313
17        18  hundred_ratio  float64          36        360    90.909091        9      0.250000        False        False                    False         0.909091
18        19       skewness  float64          36        360    90.909091       12      0.333333        False        False                    False         0.909091
19        20     school_icc  float64          36        360    90.909091       12      0.333333        False        False                    False         0.909091

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_type       396 non-null    str
 1   sample_id      396 non-null    str
 2   target         396 non-null    str
 3   group          396 non-null    str
 4   N              396 non-null    int64
 5   mean           144 non-null    float64
 6   std            144 non-null    float64
 7   min            36 non-null     float64
 8   p01            36 non-null     float64
 9   p05            36 non-null     float64
 10  p25            36 non-null     float64
 11  median         144 non-null    float64
 12  p75            36 non-null     float64
 13  p95            36 non-null     float64
 14  p99            36 non-null     float64
 15  max            36 non-null     float64
 16  zero_ratio     396 non-null    float64
 17  hundred_ratio  36 non-null     float64
 18  skewness       36 non-null     float64
 19  school_icc     36 non-null     float64
dtypes: float64(15), int64(1), str(4)
memory usage: 86.6 KB

### 5.5 Head

           row_type           sample_id      target group     N      mean       std      min      p01       p05       p25    median       p75       p95       p99        max  zero_ratio  hundred_ratio  skewness  school_icc
0           overall  P1_STRUCTURE_READY  a_rate_pct   ALL  6270 42.704643 15.614161 0.000000 0.000000 22.433988 33.582043 40.555542 50.019587 71.977246 89.161483 100.000000    0.021372       0.005104  0.469206    0.478688
1  major_zero_ratio  P1_STRUCTURE_READY  a_rate_pct   ART   885       NaN       NaN      NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN    0.012429            NaN       NaN         NaN
2  major_zero_ratio  P1_STRUCTURE_READY  a_rate_pct   EDU   653       NaN       NaN      NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN    0.003063            NaN       NaN         NaN
3  major_zero_ratio  P1_STRUCTURE_READY  a_rate_pct   ENG  1471       NaN       NaN      NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN    0.030591            NaN       NaN         NaN
4  major_zero_ratio  P1_STRUCTURE_READY  a_rate_pct   HUM   758       NaN       NaN      NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN    0.030343            NaN       NaN         NaN

### 5.6 Tail

               row_type                   sample_id                                target  group     N      mean       std  min  p01  p05  p25   median  p75  p95  p99  max  zero_ratio  hundred_ratio  skewness  school_icc
391    major_zero_ratio  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct    NAT   389       NaN       NaN  NaN  NaN  NaN  NaN      NaN  NaN  NaN  NaN  NaN    0.107969            NaN       NaN         NaN
392    major_zero_ratio  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct    SOC   468       NaN       NaN  NaN  NaN  NaN  NaN      NaN  NaN  NaN  NaN  NaN    0.470085            NaN       NaN         NaN
393  split_distribution  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct   test   260 10.220542 13.998796  NaN  NaN  NaN  NaN 3.703704  NaN  NaN  NaN  NaN    0.365385            NaN       NaN         NaN
394  split_distribution  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct  train  1789  9.108809 12.681173  NaN  NaN  NaN  NaN 3.703704  NaN  NaN  NaN  NaN    0.361096            NaN       NaN         NaN
395  split_distribution  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct    val   367  8.366639 12.213201  NaN  NaN  NaN  NaN 3.125000  NaN  NaN  NaN  NaN    0.389646            NaN       NaN         NaN

### 5.7 Random Sample

               row_type                   sample_id                                target  group     N      mean       std  min  p01  p05  p25    median  p75  p95  p99  max  zero_ratio  hundred_ratio  skewness  school_icc
392    major_zero_ratio  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct    SOC   468       NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN    0.470085            NaN       NaN         NaN
317  split_distribution      P4_E_SELECTIVITY_READY            health_employment_rate_pct  train  1789 52.791203 17.430376  NaN  NaN  NaN  NaN 52.941177  NaN  NaN  NaN  NaN    0.006708            NaN       NaN         NaN
267    major_zero_ratio    P4_JOINT_STRUCTURE_READY                            a_rate_pct    ENG  1471       NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN    0.030591            NaN       NaN         NaN
62     major_zero_ratio        P1_SELECTIVITY_READY  graduate_school_progression_rate_pct    SOC   468       NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN    0.470085            NaN       NaN         NaN
47     major_zero_ratio        P1_SELECTIVITY_READY            health_employment_rate_pct    ENG   515       NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN    0.003883            NaN       NaN         NaN
343    major_zero_ratio      P4_P_SELECTIVITY_READY            health_employment_rate_pct    EDU   353       NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN    0.005666            NaN       NaN         NaN
240  split_distribution        P4_P_STRUCTURE_READY                            a_rate_pct  train  4687 42.850189 16.050354  NaN  NaN  NaN  NaN 40.773964  NaN  NaN  NaN  NaN    0.024323            NaN       NaN         NaN
254    major_zero_ratio        P4_P_STRUCTURE_READY  graduate_school_progression_rate_pct    ART   892       NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN    0.449552            NaN       NaN         NaN
216    major_zero_ratio        P4_E_STRUCTURE_READY            health_employment_rate_pct    SOC  1268       NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN    0.014984            NaN       NaN         NaN
375    major_zero_ratio  P4_JOINT_SELECTIVITY_READY            health_employment_rate_pct    ART   177       NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN    0.011299            NaN       NaN         NaN

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,N,396.000000,"1,234.621212","1,555.471839",177.000000,177.000000,205.000000,260.000000,367.000000,715.000000,"1,268.000000","2,439.000000","5,082.750000","6,366.000000","8,561.000000",0,0.000000,0,0.000000,0,0,60
1,mean,144.000000,34.599986,19.039131,6.892592,6.892592,7.540202,7.828509,9.384712,41.966434,52.368176,53.397213,54.470852,55.062893,55.062893,252,63.636364,0,0.000000,0,0,48
2,std,144.000000,14.950619,3.049349,8.366526,8.366526,11.044708,11.589780,12.681173,14.255395,17.440012,19.394930,19.411966,19.895573,19.895573,252,63.636364,0,0.000000,0,0,48
3,min,36.000000,0.966184,2.771545,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.347826,8.695652,8.695652,8.695652,360,90.909091,32,8.080808,0,0,2
4,p01,36.000000,4.707585,8.264899,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.646962,17.450392,25.445820,25.445820,25.445820,360,90.909091,24,6.060606,0,0,5
5,p05,36.000000,15.469769,11.564357,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,25.000000,27.407830,29.061518,29.063290,29.064245,360,90.909091,12,3.030303,0,0,9
6,p25,36.000000,25.096769,18.306400,0.000000,0.000000,0.000000,0.000000,0.000000,33.582043,40.638242,42.539894,42.539894,42.539894,42.539894,360,90.909091,12,3.030303,0,0,9
7,median,144.000000,31.999721,21.574629,0.000000,0.000000,2.040816,2.076881,3.670635,40.072807,52.780748,53.708794,54.347828,54.838711,54.838711,252,63.636364,3,0.757576,0,0,43
8,p75,36.000000,41.605986,22.233492,10.000000,10.000000,10.000000,10.460778,13.899000,48.727021,64.000000,64.383560,64.383560,64.383560,64.383560,360,90.909091,0,0.000000,0,0,12
9,p95,36.000000,63.093525,20.139797,33.983019,33.983019,33.983019,35.515706,38.739367,69.201292,81.638758,85.714287,85.714287,85.714287,85.714287,360,90.909091,0,0.000000,0,0,12
10,p99,36.000000,80.443310,18.803463,54.156422,54.156422,54.156422,55.283156,58.125207,84.674314,100.000000,100.000000,100.000000,100.000000,100.000000,360,90.909091,0,0.000000,0,0,11
11,max,36.000000,96.611958,7.832076,72.093025,72.093025,72.093025,92.857140,95.794998,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,360,90.909091,0,0.000000,0,0,4
12,zero_ratio,396.000000,0.151065,0.216709,0.000000,0.000000,0.000000,0.000000,0.006452,0.019458,0.359526,0.470085,0.637394,0.693827,0.693827,0,0.000000,52,13.131313,0,0,103
13,hundred_ratio,36.000000,0.007228,0.008467,0.000000,0.000000,0.000000,0.000000,0.000000,0.003334,0.012831,0.022967,0.022967,0.022967,0.022967,360,90.909091,10,2.525253,0,0,9
14,skewness,36.000000,0.982439,0.992604,-0.067152,-0.067152,-0.067152,-0.067152,-0.012148,0.587400,1.849425,2.479303,2.641191,2.641191,2.641191,360,90.909091,0,0.000000,12,0,12
15,school_icc,36.000000,0.532483,0.327186,0.183608,0.183608,0.183608,0.183608,0.332008,0.478688,0.690185,0.931104,1.348605,1.348605,1.348605,360,90.909091,0,0.000000,0,0,12

### 5.8 Categorical/String/Boolean Describe

      column dtype  count  missing_n  missing_pct  nunique                 top  freq   top_pct                                                                                               sample_values
0   row_type   str    396          0     0.000000        3    major_zero_ratio   252 63.636364                                                             overall | major_zero_ratio | split_distribution
1  sample_id   str    396          0     0.000000       12  P1_STRUCTURE_READY    33  8.333333  P1_STRUCTURE_READY | P1_SELECTIVITY_READY | P2_STRUCTURE_READY | P2_SELECTIVITY_READY | P3_STRUCTURE_READY
2     target   str    396          0     0.000000        3          a_rate_pct   132 33.333333                              a_rate_pct | health_employment_rate_pct | graduate_school_progression_rate_pct
3      group   str    396          0     0.000000       11                 ALL    36  9.090909                                                                                 ALL | ART | EDU | ENG | HUM

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

    rank         column    dtype  missing_n  missing_pct  non_null_n  nunique
7      1            min  float64        360    90.909091          36        2
8      2            p01  float64        360    90.909091          36        5
9      3            p05  float64        360    90.909091          36        9
10     4            p25  float64        360    90.909091          36        9
12     5            p75  float64        360    90.909091          36       12
13     6            p95  float64        360    90.909091          36       12
14     7            p99  float64        360    90.909091          36       11
15     8            max  float64        360    90.909091          36        4
17     9  hundred_ratio  float64        360    90.909091          36        9
18    10       skewness  float64        360    90.909091          36       12
19    11     school_icc  float64        360    90.909091          36       12
5     12           mean  float64        252    63.636364         144       48
6     13            std  float64        252    63.636364         144       48
11    14         median  float64        252    63.636364         144       43

### 5.10 Top Cardinality Columns

           column    dtype  nunique  unique_ratio
16     zero_ratio  float64      103      0.260101
4               N    int64       60      0.151515
5            mean  float64       48      0.333333
6             std  float64       48      0.333333
11         median  float64       43      0.298611
12            p75  float64       12      0.333333
13            p95  float64       12      0.333333
18       skewness  float64       12      0.333333
19     school_icc  float64       12      0.333333
1       sample_id      str       12      0.030303
14            p99  float64       11      0.305556
3           group      str       11      0.027778
9             p05  float64        9      0.250000
10            p25  float64        9      0.250000
17  hundred_ratio  float64        9      0.250000
8             p01  float64        5      0.138889
15            max  float64        4      0.111111
0        row_type      str        3      0.007576
2          target      str        3      0.007576
7             min  float64        2      0.055556

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

  message
0    None

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

           column          check  nan_n  pos_inf_n  neg_inf_n  negative_n  zero_n  violation_n
0               N  numeric_basic      0          0          0           0       0            0
1            mean  numeric_basic    252          0          0           0       0            0
2             std  numeric_basic    252          0          0           0       0            0
3             min  numeric_basic    360          0          0           0      32            0
4             p01  numeric_basic    360          0          0           0      24            0
5             p05  numeric_basic    360          0          0           0      12            0
6             p25  numeric_basic    360          0          0           0      12            0
7          median  numeric_basic    252          0          0           0       3            0
8             p75  numeric_basic    360          0          0           0       0            0
9             p95  numeric_basic    360          0          0           0       0            0
10            p99  numeric_basic    360          0          0           0       0            0
11            max  numeric_basic    360          0          0           0       0            0
12     zero_ratio  numeric_basic      0          0          0           0      52            0
13  hundred_ratio  numeric_basic    360          0          0           0      10            0
14       skewness  numeric_basic    360          0          0          12       0            0
15     school_icc  numeric_basic    360          0          0           0       0            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS
WARNINGS:
- none

### 6.8 Target Profile Additional Checks

                      sample_id                                target     N  zero_ratio  hundred_ratio  skewness  school_icc
0            P1_STRUCTURE_READY                            a_rate_pct  6270    0.021372       0.005104  0.469206    0.478688
11           P1_STRUCTURE_READY            health_employment_rate_pct  6270    0.019458       0.022967 -0.067152    0.183608
22           P1_STRUCTURE_READY  graduate_school_progression_rate_pct  6270    0.452951       0.000000  2.479303    0.716280
33         P1_SELECTIVITY_READY                            a_rate_pct  2416    0.000000       0.000000  1.256927    0.501903
44         P1_SELECTIVITY_READY            health_employment_rate_pct  2416    0.006209       0.012831 -0.012148    0.348644
55         P1_SELECTIVITY_READY  graduate_school_progression_rate_pct  2416    0.365894       0.000000  1.818274    0.282102
66           P2_STRUCTURE_READY                            a_rate_pct  8561    0.030604       0.007709  0.440454    0.444701
77           P2_STRUCTURE_READY            health_employment_rate_pct  6270    0.019458       0.022967 -0.067152    0.183608
88           P2_STRUCTURE_READY  graduate_school_progression_rate_pct  6366    0.452403       0.001257  2.641191    1.348605
99         P2_SELECTIVITY_READY                            a_rate_pct  3198    0.007817       0.001563  0.701264    0.543174
110        P2_SELECTIVITY_READY            health_employment_rate_pct  2416    0.006209       0.012831 -0.012148    0.348644
121        P2_SELECTIVITY_READY  graduate_school_progression_rate_pct  2439    0.363264       0.000820  1.942877    0.931104
132          P3_STRUCTURE_READY                            a_rate_pct  8561    0.030604       0.007709  0.440454    0.444701
143          P3_STRUCTURE_READY            health_employment_rate_pct  6270    0.019458       0.022967 -0.067152    0.183608
154          P3_STRUCTURE_READY  graduate_school_progression_rate_pct  6366    0.452403       0.001257  2.641191    1.348605
165        P3_SELECTIVITY_READY                            a_rate_pct  3198    0.007817       0.001563  0.701264    0.543174
176        P3_SELECTIVITY_READY            health_employment_rate_pct  2416    0.006209       0.012831 -0.012148    0.348644
187        P3_SELECTIVITY_READY  graduate_school_progression_rate_pct  2439    0.363264       0.000820  1.942877    0.931104
198        P4_E_STRUCTURE_READY                            a_rate_pct  6270    0.021372       0.005104  0.469206    0.478688
209        P4_E_STRUCTURE_READY            health_employment_rate_pct  6270    0.019458       0.022967 -0.067152    0.183608
220        P4_E_STRUCTURE_READY  graduate_school_progression_rate_pct  6270    0.452951       0.000000  2.479303    0.716280
231        P4_P_STRUCTURE_READY                            a_rate_pct  6366    0.021835       0.005341  0.473537    0.542615
242        P4_P_STRUCTURE_READY            health_employment_rate_pct  6270    0.019458       0.022967 -0.067152    0.183608
253        P4_P_STRUCTURE_READY  graduate_school_progression_rate_pct  6366    0.452403       0.001257  2.641191    1.348605
264    P4_JOINT_STRUCTURE_READY                            a_rate_pct  6270    0.021372       0.005104  0.469206    0.478688
275    P4_JOINT_STRUCTURE_READY            health_employment_rate_pct  6270    0.019458       0.022967 -0.067152    0.183608
286    P4_JOINT_STRUCTURE_READY  graduate_school_progression_rate_pct  6270    0.452951       0.000000  2.479303    0.716280
297      P4_E_SELECTIVITY_READY                            a_rate_pct  2416    0.000000       0.000000  1.256927    0.501903
308      P4_E_SELECTIVITY_READY            health_employment_rate_pct  2416    0.006209       0.012831 -0.012148    0.348644
319      P4_E_SELECTIVITY_READY  graduate_school_progression_rate_pct  2416    0.365894       0.000000  1.818274    0.282102
330      P4_P_SELECTIVITY_READY                            a_rate_pct  2439    0.000000       0.000000  1.263302    0.681487
341      P4_P_SELECTIVITY_READY            health_employment_rate_pct  2416    0.006209       0.012831 -0.012148    0.348644
352      P4_P_SELECTIVITY_READY  graduate_school_progression_rate_pct  2439    0.363264       0.000820  1.942877    0.931104
363  P4_JOINT_SELECTIVITY_READY                            a_rate_pct  2416    0.000000       0.000000  1.256927    0.501903
374  P4_JOINT_SELECTIVITY_READY            health_employment_rate_pct  2416    0.006209       0.012831 -0.012148    0.348644
385  P4_JOINT_SELECTIVITY_READY  graduate_school_progression_rate_pct  2416    0.365894       0.000000  1.818274    0.282102

High zero_ratio

,row_type,sample_id,target,group,N,mean,std,min,p01,p05,p25,median,p75,p95,p99,max,zero_ratio,hundred_ratio,skewness,school_icc
22,overall,P1_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6270,7.636097,12.407968,0.000000,0.000000,0.000000,0.000000,2.074115,10.000000,33.983019,56.030244,92.857140,0.452951,0.000000,2.479303,0.716280
286,overall,P4_JOINT_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6270,7.636097,12.407968,0.000000,0.000000,0.000000,0.000000,2.074115,10.000000,33.983019,56.030244,92.857140,0.452951,0.000000,2.479303,0.716280
220,overall,P4_E_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6270,7.636097,12.407968,0.000000,0.000000,0.000000,0.000000,2.074115,10.000000,33.983019,56.030244,92.857140,0.452951,0.000000,2.479303,0.716280
88,overall,P2_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6366,7.937581,13.136645,0.000000,0.000000,0.000000,0.000000,2.083333,10.460778,35.515706,58.823528,100.000000,0.452403,0.001257,2.641191,1.348605
253,overall,P4_P_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6366,7.937581,13.136645,0.000000,0.000000,0.000000,0.000000,2.083333,10.460778,35.515706,58.823528,100.000000,0.452403,0.001257,2.641191,1.348605
154,overall,P3_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6366,7.937581,13.136645,0.000000,0.000000,0.000000,0.000000,2.083333,10.460778,35.515706,58.823528,100.000000,0.452403,0.001257,2.641191,1.348605
55,overall,P1_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2416,9.115710,12.763240,0.000000,0.000000,0.000000,0.000000,3.571429,13.439354,37.540585,54.156422,72.093025,0.365894,0.000000,1.818274,0.282102
319,overall,P4_E_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2416,9.115710,12.763240,0.000000,0.000000,0.000000,0.000000,3.571429,13.439354,37.540585,54.156422,72.093025,0.365894,0.000000,1.818274,0.282102
385,overall,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2416,9.115710,12.763240,0.000000,0.000000,0.000000,0.000000,3.571429,13.439354,37.540585,54.156422,72.093025,0.365894,0.000000,1.818274,0.282102
187,overall,P3_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2439,9.419080,13.311807,0.000000,0.000000,0.000000,0.000000,3.571429,14.052216,39.138961,55.283156,100.000000,0.363264,0.000820,1.942877,0.931104
352,overall,P4_P_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2439,9.419080,13.311807,0.000000,0.000000,0.000000,0.000000,3.571429,14.052216,39.138961,55.283156,100.000000,0.363264,0.000820,1.942877,0.931104
121,overall,P2_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2439,9.419080,13.311807,0.000000,0.000000,0.000000,0.000000,3.571429,14.052216,39.138961,55.283156,100.000000,0.363264,0.000820,1.942877,0.931104
66,overall,P2_STRUCTURE_READY,a_rate_pct,ALL,8561,41.629169,16.967369,0.000000,0.000000,14.871854,32.391911,39.620689,49.716064,72.955978,92.857140,100.000000,0.030604,0.007709,0.440454,0.444701
132,overall,P3_STRUCTURE_READY,a_rate_pct,ALL,8561,41.629169,16.967369,0.000000,0.000000,14.871854,32.391911,39.620689,49.716064,72.955978,92.857140,100.000000,0.030604,0.007709,0.440454,0.444701
231,overall,P4_P_STRUCTURE_READY,a_rate_pct,ALL,6366,42.727283,15.724596,0.000000,0.000000,22.108920,33.566552,40.548687,50.058231,72.206436,89.701153,100.000000,0.021835,0.005341,0.473537,0.542615
0,overall,P1_STRUCTURE_READY,a_rate_pct,ALL,6270,42.704643,15.614161,0.000000,0.000000,22.433988,33.582043,40.555542,50.019587,71.977246,89.161483,100.000000,0.021372,0.005104,0.469206,0.478688
264,overall,P4_JOINT_STRUCTURE_READY,a_rate_pct,ALL,6270,42.704643,15.614161,0.000000,0.000000,22.433988,33.582043,40.555542,50.019587,71.977246,89.161483,100.000000,0.021372,0.005104,0.469206,0.478688
198,overall,P4_E_STRUCTURE_READY,a_rate_pct,ALL,6270,42.704643,15.614161,0.000000,0.000000,22.433988,33.582043,40.555542,50.019587,71.977246,89.161483,100.000000,0.021372,0.005104,0.469206,0.478688
242,overall,P4_P_STRUCTURE_READY,health_employment_rate_pct,ALL,6270,52.423729,19.394930,0.000000,0.000000,20.000000,40.638242,52.727272,64.000000,85.714287,100.000000,100.000000,0.019458,0.022967,-0.067152,0.183608
11,overall,P1_STRUCTURE_READY,health_employment_rate_pct,ALL,6270,52.423729,19.394930,0.000000,0.000000,20.000000,40.638242,52.727272,64.000000,85.714287,100.000000,100.000000,0.019458,0.022967,-0.067152,0.183608

High hundred_ratio

,row_type,sample_id,target,group,N,mean,std,min,p01,p05,p25,median,p75,p95,p99,max,zero_ratio,hundred_ratio,skewness,school_icc
11,overall,P1_STRUCTURE_READY,health_employment_rate_pct,ALL,6270,52.423729,19.394930,0.000000,0.000000,20.000000,40.638242,52.727272,64.000000,85.714287,100.000000,100.000000,0.019458,0.022967,-0.067152,0.183608
209,overall,P4_E_STRUCTURE_READY,health_employment_rate_pct,ALL,6270,52.423729,19.394930,0.000000,0.000000,20.000000,40.638242,52.727272,64.000000,85.714287,100.000000,100.000000,0.019458,0.022967,-0.067152,0.183608
143,overall,P3_STRUCTURE_READY,health_employment_rate_pct,ALL,6270,52.423729,19.394930,0.000000,0.000000,20.000000,40.638242,52.727272,64.000000,85.714287,100.000000,100.000000,0.019458,0.022967,-0.067152,0.183608
77,overall,P2_STRUCTURE_READY,health_employment_rate_pct,ALL,6270,52.423729,19.394930,0.000000,0.000000,20.000000,40.638242,52.727272,64.000000,85.714287,100.000000,100.000000,0.019458,0.022967,-0.067152,0.183608
275,overall,P4_JOINT_STRUCTURE_READY,health_employment_rate_pct,ALL,6270,52.423729,19.394930,0.000000,0.000000,20.000000,40.638242,52.727272,64.000000,85.714287,100.000000,100.000000,0.019458,0.022967,-0.067152,0.183608
242,overall,P4_P_STRUCTURE_READY,health_employment_rate_pct,ALL,6270,52.423729,19.394930,0.000000,0.000000,20.000000,40.638242,52.727272,64.000000,85.714287,100.000000,100.000000,0.019458,0.022967,-0.067152,0.183608
374,overall,P4_JOINT_SELECTIVITY_READY,health_employment_rate_pct,ALL,2416,53.317039,17.468920,0.000000,9.646962,25.000000,42.539894,53.333332,64.383560,81.638758,100.000000,100.000000,0.006209,0.012831,-0.012148,0.348644
341,overall,P4_P_SELECTIVITY_READY,health_employment_rate_pct,ALL,2416,53.317039,17.468920,0.000000,9.646962,25.000000,42.539894,53.333332,64.383560,81.638758,100.000000,100.000000,0.006209,0.012831,-0.012148,0.348644
308,overall,P4_E_SELECTIVITY_READY,health_employment_rate_pct,ALL,2416,53.317039,17.468920,0.000000,9.646962,25.000000,42.539894,53.333332,64.383560,81.638758,100.000000,100.000000,0.006209,0.012831,-0.012148,0.348644
176,overall,P3_SELECTIVITY_READY,health_employment_rate_pct,ALL,2416,53.317039,17.468920,0.000000,9.646962,25.000000,42.539894,53.333332,64.383560,81.638758,100.000000,100.000000,0.006209,0.012831,-0.012148,0.348644
110,overall,P2_SELECTIVITY_READY,health_employment_rate_pct,ALL,2416,53.317039,17.468920,0.000000,9.646962,25.000000,42.539894,53.333332,64.383560,81.638758,100.000000,100.000000,0.006209,0.012831,-0.012148,0.348644
44,overall,P1_SELECTIVITY_READY,health_employment_rate_pct,ALL,2416,53.317039,17.468920,0.000000,9.646962,25.000000,42.539894,53.333332,64.383560,81.638758,100.000000,100.000000,0.006209,0.012831,-0.012148,0.348644
66,overall,P2_STRUCTURE_READY,a_rate_pct,ALL,8561,41.629169,16.967369,0.000000,0.000000,14.871854,32.391911,39.620689,49.716064,72.955978,92.857140,100.000000,0.030604,0.007709,0.440454,0.444701
132,overall,P3_STRUCTURE_READY,a_rate_pct,ALL,8561,41.629169,16.967369,0.000000,0.000000,14.871854,32.391911,39.620689,49.716064,72.955978,92.857140,100.000000,0.030604,0.007709,0.440454,0.444701
231,overall,P4_P_STRUCTURE_READY,a_rate_pct,ALL,6366,42.727283,15.724596,0.000000,0.000000,22.108920,33.566552,40.548687,50.058231,72.206436,89.701153,100.000000,0.021835,0.005341,0.473537,0.542615
0,overall,P1_STRUCTURE_READY,a_rate_pct,ALL,6270,42.704643,15.614161,0.000000,0.000000,22.433988,33.582043,40.555542,50.019587,71.977246,89.161483,100.000000,0.021372,0.005104,0.469206,0.478688
198,overall,P4_E_STRUCTURE_READY,a_rate_pct,ALL,6270,42.704643,15.614161,0.000000,0.000000,22.433988,33.582043,40.555542,50.019587,71.977246,89.161483,100.000000,0.021372,0.005104,0.469206,0.478688
264,overall,P4_JOINT_STRUCTURE_READY,a_rate_pct,ALL,6270,42.704643,15.614161,0.000000,0.000000,22.433988,33.582043,40.555542,50.019587,71.977246,89.161483,100.000000,0.021372,0.005104,0.469206,0.478688
165,overall,P3_SELECTIVITY_READY,a_rate_pct,ALL,3198,40.728928,12.714620,0.000000,5.000000,25.754143,33.248337,38.919750,46.615546,65.302873,80.187144,100.000000,0.007817,0.001563,0.701264,0.543174
99,overall,P2_SELECTIVITY_READY,a_rate_pct,ALL,3198,40.728928,12.714620,0.000000,5.000000,25.754143,33.248337,38.919750,46.615546,65.302873,80.187144,100.000000,0.007817,0.001563,0.701264,0.543174

High absolute skewness

,row_type,sample_id,target,group,N,mean,std,min,p01,p05,p25,median,p75,p95,p99,max,zero_ratio,hundred_ratio,skewness,school_icc,abs_skewness
154,overall,P3_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6366,7.937581,13.136645,0.000000,0.000000,0.000000,0.000000,2.083333,10.460778,35.515706,58.823528,100.000000,0.452403,0.001257,2.641191,1.348605,2.641191
253,overall,P4_P_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6366,7.937581,13.136645,0.000000,0.000000,0.000000,0.000000,2.083333,10.460778,35.515706,58.823528,100.000000,0.452403,0.001257,2.641191,1.348605,2.641191
88,overall,P2_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6366,7.937581,13.136645,0.000000,0.000000,0.000000,0.000000,2.083333,10.460778,35.515706,58.823528,100.000000,0.452403,0.001257,2.641191,1.348605,2.641191
22,overall,P1_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6270,7.636097,12.407968,0.000000,0.000000,0.000000,0.000000,2.074115,10.000000,33.983019,56.030244,92.857140,0.452951,0.000000,2.479303,0.716280,2.479303
286,overall,P4_JOINT_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6270,7.636097,12.407968,0.000000,0.000000,0.000000,0.000000,2.074115,10.000000,33.983019,56.030244,92.857140,0.452951,0.000000,2.479303,0.716280,2.479303
220,overall,P4_E_STRUCTURE_READY,graduate_school_progression_rate_pct,ALL,6270,7.636097,12.407968,0.000000,0.000000,0.000000,0.000000,2.074115,10.000000,33.983019,56.030244,92.857140,0.452951,0.000000,2.479303,0.716280,2.479303
187,overall,P3_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2439,9.419080,13.311807,0.000000,0.000000,0.000000,0.000000,3.571429,14.052216,39.138961,55.283156,100.000000,0.363264,0.000820,1.942877,0.931104,1.942877
352,overall,P4_P_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2439,9.419080,13.311807,0.000000,0.000000,0.000000,0.000000,3.571429,14.052216,39.138961,55.283156,100.000000,0.363264,0.000820,1.942877,0.931104,1.942877
121,overall,P2_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2439,9.419080,13.311807,0.000000,0.000000,0.000000,0.000000,3.571429,14.052216,39.138961,55.283156,100.000000,0.363264,0.000820,1.942877,0.931104,1.942877
55,overall,P1_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2416,9.115710,12.763240,0.000000,0.000000,0.000000,0.000000,3.571429,13.439354,37.540585,54.156422,72.093025,0.365894,0.000000,1.818274,0.282102,1.818274
385,overall,P4_JOINT_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2416,9.115710,12.763240,0.000000,0.000000,0.000000,0.000000,3.571429,13.439354,37.540585,54.156422,72.093025,0.365894,0.000000,1.818274,0.282102,1.818274
319,overall,P4_E_SELECTIVITY_READY,graduate_school_progression_rate_pct,ALL,2416,9.115710,12.763240,0.000000,0.000000,0.000000,0.000000,3.571429,13.439354,37.540585,54.156422,72.093025,0.365894,0.000000,1.818274,0.282102,1.818274
330,overall,P4_P_SELECTIVITY_READY,a_rate_pct,ALL,2439,42.533653,11.286992,8.695652,25.253821,29.064245,34.704824,40.059269,47.737978,66.425338,80.056126,95.794998,0.000000,0.000000,1.263302,0.681487,1.263302
297,overall,P4_E_SELECTIVITY_READY,a_rate_pct,ALL,2416,42.502735,11.207503,8.695652,25.445820,29.061518,34.705626,40.072807,47.712963,65.877535,79.916272,95.794998,0.000000,0.000000,1.256927,0.501903,1.256927
33,overall,P1_SELECTIVITY_READY,a_rate_pct,ALL,2416,42.502735,11.207503,8.695652,25.445820,29.061518,34.705626,40.072807,47.712963,65.877535,79.916272,95.794998,0.000000,0.000000,1.256927,0.501903,1.256927
363,overall,P4_JOINT_SELECTIVITY_READY,a_rate_pct,ALL,2416,42.502735,11.207503,8.695652,25.445820,29.061518,34.705626,40.072807,47.712963,65.877535,79.916272,95.794998,0.000000,0.000000,1.256927,0.501903,1.256927
99,overall,P2_SELECTIVITY_READY,a_rate_pct,ALL,3198,40.728928,12.714620,0.000000,5.000000,25.754143,33.248337,38.919750,46.615546,65.302873,80.187144,100.000000,0.007817,0.001563,0.701264,0.543174,0.701264
165,overall,P3_SELECTIVITY_READY,a_rate_pct,ALL,3198,40.728928,12.714620,0.000000,5.000000,25.754143,33.248337,38.919750,46.615546,65.302873,80.187144,100.000000,0.007817,0.001563,0.701264,0.543174,0.701264
231,overall,P4_P_STRUCTURE_READY,a_rate_pct,ALL,6366,42.727283,15.724596,0.000000,0.000000,22.108920,33.566552,40.548687,50.058231,72.206436,89.701153,100.000000,0.021835,0.005341,0.473537,0.542615,0.473537
0,overall,P1_STRUCTURE_READY,a_rate_pct,ALL,6270,42.704643,15.614161,0.000000,0.000000,22.433988,33.582043,40.555542,50.019587,71.977246,89.161483,100.000000,0.021372,0.005104,0.469206,0.478688,0.469206

## Dataset: `P3_NESTED_CROSSFIT_SMOKE`

- 역할: P3 nested cross-fit smoke result
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv`
- 예상 shape: `(1, 11)`
- 예상 SHA256: `b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808`

In [ ]:
result = inspect_dataset(
    label='P3_NESTED_CROSSFIT_SMOKE',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv',
    expected_shape=(1, 11),
    expected_sha256='b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808',
    candidate_keys=[['status']],
)

extra_nested()

### 5.1 File Identification - `P3_NESTED_CROSSFIT_SMOKE`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P3_NESTED_CROSSFIT_SMOKE,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,True,.csv,1097,2026-07-13T11:13:00.305181,b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808,b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808,True

### 5.2 Basic Structure

     shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (1, 11)        (1, 11)         True          1            11                1008       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0                  status               status    True              0                   0                     0                 1

### 5.3 Full Column List

    position                    column    dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1                    status      str           1          0     0.000000        1      1.000000        False         True                    False         1.000000
1          2       outer_train_schools    int64           1          0     0.000000        1      1.000000        False         True                    False         1.000000
2          3  outer_validation_schools    int64           1          0     0.000000        1      1.000000        False         True                     True         1.000000
3          4               inner_folds    int64           1          0     0.000000        1      1.000000        False         True                    False         1.000000
4          5            selected_alpha  float64           1          0     0.000000        1      1.000000        False         True                    False         1.000000
5          6         raw_feature_count    int64           1          0     0.000000        1      1.000000        False         True                     True         1.000000
6          7        encoded_dimensions    int64           1          0     0.000000        1      1.000000        False         True                    False         1.000000
7          8              prediction_n    int64           1          0     0.000000        1      1.000000        False         True                    False         1.000000
8          9          nan_prediction_n    int64           1          0     0.000000        1      1.000000        False         True                    False         1.000000
9         10      outer_validation_mse  float64           1          0     0.000000        1      1.000000        False         True                     True         1.000000
10        11          inner_score_json      str           1          0     0.000000        1      1.000000        False         True                    False         1.000000

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   status                    1 non-null      str
 1   outer_train_schools       1 non-null      int64
 2   outer_validation_schools  1 non-null      int64
 3   inner_folds               1 non-null      int64
 4   selected_alpha            1 non-null      float64
 5   raw_feature_count         1 non-null      int64
 6   encoded_dimensions        1 non-null      int64
 7   prediction_n              1 non-null      int64
 8   nan_prediction_n          1 non-null      int64
 9   outer_validation_mse      1 non-null      float64
 10  inner_score_json          1 non-null      str
dtypes: float64(2), int64(7), str(2)
memory usage: 1008.0 bytes

### 5.5 Head

,status,outer_train_schools,outer_validation_schools,inner_folds,selected_alpha,raw_feature_count,encoded_dimensions,prediction_n,nan_prediction_n,outer_validation_mse,inner_score_json
0,PASS,158,40,3,100.000000,11,32,1713,0,342.262091,"[{""alpha"": 0.1, ""fold"": 1, ""validation_mse"": 289.8486229478107}, {""alpha"": 0.1, ""fold"": 2, ""validation_mse"": 254.142..."

### 5.6 Tail

,status,outer_train_schools,outer_validation_schools,inner_folds,selected_alpha,raw_feature_count,encoded_dimensions,prediction_n,nan_prediction_n,outer_validation_mse,inner_score_json
0,PASS,158,40,3,100.000000,11,32,1713,0,342.262091,"[{""alpha"": 0.1, ""fold"": 1, ""validation_mse"": 289.8486229478107}, {""alpha"": 0.1, ""fold"": 2, ""validation_mse"": 254.142..."

### 5.7 Random Sample

,status,outer_train_schools,outer_validation_schools,inner_folds,selected_alpha,raw_feature_count,encoded_dimensions,prediction_n,nan_prediction_n,outer_validation_mse,inner_score_json
0,PASS,158,40,3,100.000000,11,32,1713,0,342.262091,"[{""alpha"": 0.1, ""fold"": 1, ""validation_mse"": 289.8486229478107}, {""alpha"": 0.1, ""fold"": 2, ""validation_mse"": 254.142..."

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,outer_train_schools,1.000000,158.000000,NaN,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,0,0.000000,0,0.000000,0,0,1
1,outer_validation_schools,1.000000,40.000000,NaN,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,0,0.000000,0,0.000000,0,0,1
2,inner_folds,1.000000,3.000000,NaN,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,0,0.000000,0,0.000000,0,0,1
3,selected_alpha,1.000000,100.000000,NaN,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,0,0.000000,0,0.000000,0,0,1
4,raw_feature_count,1.000000,11.000000,NaN,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,0,0.000000,0,0.000000,0,0,1
5,encoded_dimensions,1.000000,32.000000,NaN,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,0,0.000000,0,0.000000,0,0,1
6,prediction_n,1.000000,"1,713.000000",NaN,"1,713.000000","1,713.000000","1,713.000000","1,713.000000","1,713.000000","1,713.000000","1,713.000000","1,713.000000","1,713.000000","1,713.000000","1,713.000000",0,0.000000,0,0.000000,0,0,1
7,nan_prediction_n,1.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,1,100.000000,0,0,1
8,outer_validation_mse,1.000000,342.262091,NaN,342.262091,342.262091,342.262091,342.262091,342.262091,342.262091,342.262091,342.262091,342.262091,342.262091,342.262091,0,0.000000,0,0.000000,0,0,1

### 5.8 Categorical/String/Boolean Describe

,column,dtype,count,missing_n,missing_pct,nunique,top,freq,top_pct,sample_values
0,status,str,1,0,0.000000,1,PASS,1,100.000000,PASS
1,inner_score_json,str,1,0,0.000000,1,"[{""alpha"": 0.1, ""fold"": 1, ""validation_mse"": 289.8486229478107}, {""alpha"": 0.1, ""fold"": 2, ""validation_mse"": 254.142...",1,100.000000,"[{""alpha"": 0.1, ""fold"": 1, ""validation_mse"": 289.8486229478107}, {""alpha"": 0.1, ""fold"": 2, ""validation_mse"": 254.142..."

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

No missing values

### 5.10 Top Cardinality Columns

                      column    dtype  nunique  unique_ratio
0                     status      str        1      1.000000
1        outer_train_schools    int64        1      1.000000
2   outer_validation_schools    int64        1      1.000000
3                inner_folds    int64        1      1.000000
4             selected_alpha  float64        1      1.000000
5          raw_feature_count    int64        1      1.000000
6         encoded_dimensions    int64        1      1.000000
7               prediction_n    int64        1      1.000000
8           nan_prediction_n    int64        1      1.000000
9       outer_validation_mse  float64        1      1.000000
10          inner_score_json      str        1      1.000000

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

                      column    dtype  nunique  top_value_share
0                     status      str        1         1.000000
1        outer_train_schools    int64        1         1.000000
2   outer_validation_schools    int64        1         1.000000
3                inner_folds    int64        1         1.000000
4             selected_alpha  float64        1         1.000000
5          raw_feature_count    int64        1         1.000000
6         encoded_dimensions    int64        1         1.000000
7               prediction_n    int64        1         1.000000
8           nan_prediction_n    int64        1         1.000000
9       outer_validation_mse  float64        1         1.000000
10          inner_score_json      str        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                      column              check    nan_n  pos_inf_n  neg_inf_n  negative_n   zero_n  violation_n
0        outer_train_schools      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
1   outer_validation_schools      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
2                inner_folds      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
3             selected_alpha      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
4          raw_feature_count      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
5          raw_feature_count  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
6         encoded_dimensions      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
7               prediction_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
8               prediction_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
9           nan_prediction_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 1.000000            0
10          nan_prediction_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
11      outer_validation_mse      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 11

### 6.9 Nested Crossfit Smoke Additional Checks

   outer_train_N  outer_validation_N  train_school_N  validation_school_N  selected_alpha          alpha_grid  selected_alpha_is_grid_max  prediction_N  NaN_prediction_N  encoded_feature_N
0           6848                1713             158                   40      100.000000  0.1|1.0|10.0|100.0                        True          1713                 0                 32

## Dataset: `P4_FULL_PIPELINE_BOOTSTRAP_SMOKE`

- 역할: P4 full pipeline bootstrap smoke result
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv`
- 예상 shape: `(3, 11)`
- 예상 SHA256: `5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467`

In [ ]:
result = inspect_dataset(
    label='P4_FULL_PIPELINE_BOOTSTRAP_SMOKE',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv',
    expected_shape=(3, 11),
    expected_sha256='5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467',
    candidate_keys=[['iteration']],
)

extra_bootstrap()

### 5.1 File Identification - `P4_FULL_PIPELINE_BOOTSTRAP_SMOKE`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_FULL_PIPELINE_BOOTSTRAP_SMOKE,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOK...,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv,True,.csv,406,2026-07-13T11:13:04.747216,5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467,5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467,True

### 5.2 Basic Structure

     shape expected_shape  shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader   encoding json_raw_type json_top_level_keys
0  (3, 11)        (3, 11)         True          3            11                 408       int64          True                          0  pd.read_csv(low_memory=False)  utf-8-sig          None                None

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0               iteration            iteration    True              0                   0                     0                 3

### 5.3 Full Column List

    position                    column    dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0          1                 iteration    int64           3          0     0.000000        3      1.000000        False        False                    False         0.333333
1          2                    status      str           3          0     0.000000        1      0.333333        False         True                    False         1.000000
2          3         school_resample_n    int64           3          0     0.000000        1      0.333333        False         True                    False         1.000000
3          4           unique_school_n    int64           3          0     0.000000        3      1.000000        False        False                    False         0.333333
4          5           bootstrap_row_n    int64           3          0     0.000000        3      1.000000        False        False                    False         0.333333
5          6  p3_crossfit_prediction_n    int64           3          0     0.000000        3      1.000000        False        False                    False         0.333333
6          7         p3_crossfit_nan_n    int64           3          0     0.000000        1      0.333333        False         True                    False         1.000000
7          8                p4_e_fit_n    int64           3          0     0.000000        3      1.000000        False        False                    False         0.333333
8          9                p4_p_fit_n    int64           3          0     0.000000        3      1.000000        False        False                    False         0.333333
9         10   p4_e_rmse_in_boot_smoke  float64           3          0     0.000000        3      1.000000        False        False                    False         0.333333
10        11   p4_p_rmse_in_boot_smoke  float64           3          0     0.000000        3      1.000000        False        False                    False         0.333333

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   iteration                 3 non-null      int64
 1   status                    3 non-null      str
 2   school_resample_n         3 non-null      int64
 3   unique_school_n           3 non-null      int64
 4   bootstrap_row_n           3 non-null      int64
 5   p3_crossfit_prediction_n  3 non-null      int64
 6   p3_crossfit_nan_n         3 non-null      int64
 7   p4_e_fit_n                3 non-null      int64
 8   p4_p_fit_n                3 non-null      int64
 9   p4_e_rmse_in_boot_smoke   3 non-null      float64
 10  p4_p_rmse_in_boot_smoke   3 non-null      float64
dtypes: float64(2), int64(8), str(1)
memory usage: 408.0 bytes

### 5.5 Head

   iteration status  school_resample_n  unique_school_n  bootstrap_row_n  p3_crossfit_prediction_n  p3_crossfit_nan_n  p4_e_fit_n  p4_p_fit_n  p4_e_rmse_in_boot_smoke  p4_p_rmse_in_boot_smoke
0          1   PASS                186              116             6519                      6519                  0        6519        6519                17.324008                10.421647
1          2   PASS                186              119             6645                      6645                  0        6645        6645                17.322412                10.099755
2          3   PASS                186              122             6271                      6271                  0        6271        6271                17.409185                10.820266

### 5.6 Tail

   iteration status  school_resample_n  unique_school_n  bootstrap_row_n  p3_crossfit_prediction_n  p3_crossfit_nan_n  p4_e_fit_n  p4_p_fit_n  p4_e_rmse_in_boot_smoke  p4_p_rmse_in_boot_smoke
0          1   PASS                186              116             6519                      6519                  0        6519        6519                17.324008                10.421647
1          2   PASS                186              119             6645                      6645                  0        6645        6645                17.322412                10.099755
2          3   PASS                186              122             6271                      6271                  0        6271        6271                17.409185                10.820266

### 5.7 Random Sample

   iteration status  school_resample_n  unique_school_n  bootstrap_row_n  p3_crossfit_prediction_n  p3_crossfit_nan_n  p4_e_fit_n  p4_p_fit_n  p4_e_rmse_in_boot_smoke  p4_p_rmse_in_boot_smoke
2          3   PASS                186              122             6271                      6271                  0        6271        6271                17.409185                10.820266
0          1   PASS                186              116             6519                      6519                  0        6519        6519                17.324008                10.421647
1          2   PASS                186              119             6645                      6645                  0        6645        6645                17.322412                10.099755

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,iteration,3.000000,2.000000,1.000000,1.000000,1.020000,1.100000,1.200000,1.500000,2.000000,2.500000,2.800000,2.900000,2.980000,3.000000,0,0.000000,0,0.000000,0,0,3
1,school_resample_n,3.000000,186.000000,0.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,0,0.000000,0,0.000000,0,0,1
2,unique_school_n,3.000000,119.000000,3.000000,116.000000,116.060000,116.300000,116.600000,117.500000,119.000000,120.500000,121.400000,121.700000,121.940000,122.000000,0,0.000000,0,0.000000,0,0,3
3,bootstrap_row_n,3.000000,"6,478.333333",190.287502,"6,271.000000","6,275.960000","6,295.800000","6,320.600000","6,395.000000","6,519.000000","6,582.000000","6,619.800000","6,632.400000","6,642.480000","6,645.000000",0,0.000000,0,0.000000,0,0,3
4,p3_crossfit_prediction_n,3.000000,"6,478.333333",190.287502,"6,271.000000","6,275.960000","6,295.800000","6,320.600000","6,395.000000","6,519.000000","6,582.000000","6,619.800000","6,632.400000","6,642.480000","6,645.000000",0,0.000000,0,0.000000,0,0,3
5,p3_crossfit_nan_n,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,3,100.000000,0,0,1
6,p4_e_fit_n,3.000000,"6,478.333333",190.287502,"6,271.000000","6,275.960000","6,295.800000","6,320.600000","6,395.000000","6,519.000000","6,582.000000","6,619.800000","6,632.400000","6,642.480000","6,645.000000",0,0.000000,0,0.000000,0,0,3
7,p4_p_fit_n,3.000000,"6,478.333333",190.287502,"6,271.000000","6,275.960000","6,295.800000","6,320.600000","6,395.000000","6,519.000000","6,582.000000","6,619.800000","6,632.400000","6,642.480000","6,645.000000",0,0.000000,0,0.000000,0,0,3
8,p4_e_rmse_in_boot_smoke,3.000000,17.351868,0.049644,17.322412,17.322444,17.322571,17.322731,17.323210,17.324008,17.366596,17.392149,17.400667,17.407481,17.409185,0,0.000000,0,0.000000,0,0,3
9,p4_p_rmse_in_boot_smoke,3.000000,10.447223,0.360936,10.099755,10.106193,10.131944,10.164133,10.260701,10.421647,10.620956,10.740542,10.780404,10.812294,10.820266,0,0.000000,0,0.000000,0,0,3

### 5.8 Categorical/String/Boolean Describe

   column dtype  count  missing_n  missing_pct  nunique   top  freq    top_pct sample_values
0  status   str      3          0     0.000000        1  PASS     3 100.000000          PASS

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

No missing values

### 5.10 Top Cardinality Columns

                      column    dtype  nunique  unique_ratio
0                  iteration    int64        3      1.000000
3            unique_school_n    int64        3      1.000000
4            bootstrap_row_n    int64        3      1.000000
5   p3_crossfit_prediction_n    int64        3      1.000000
7                 p4_e_fit_n    int64        3      1.000000
8                 p4_p_fit_n    int64        3      1.000000
9    p4_e_rmse_in_boot_smoke  float64        3      1.000000
10   p4_p_rmse_in_boot_smoke  float64        3      1.000000
1                     status      str        1      0.333333
2          school_resample_n    int64        1      0.333333
6          p3_crossfit_nan_n    int64        1      0.333333

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

              column  dtype  nunique  top_value_share
1             status    str        1         1.000000
2  school_resample_n  int64        1         1.000000
6  p3_crossfit_nan_n  int64        1         1.000000

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                      column              check    nan_n  pos_inf_n  neg_inf_n  negative_n   zero_n  violation_n
0                  iteration      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
1          school_resample_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
2          school_resample_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
3            unique_school_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
4            unique_school_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
5            bootstrap_row_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
6            bootstrap_row_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
7   p3_crossfit_prediction_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
8   p3_crossfit_prediction_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
9          p3_crossfit_nan_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 3.000000            0
10         p3_crossfit_nan_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
11                p4_e_fit_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
12                p4_e_fit_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
13                p4_p_fit_n      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
14                p4_p_fit_n  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
15   p4_e_rmse_in_boot_smoke      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
16   p4_p_rmse_in_boot_smoke      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS_WITH_WARNINGS
WARNINGS:
- constant columns: 3

### 6.10 Bootstrap Smoke Additional Checks

   iteration  school_resample_n  P3_success  P4_E_success  P4_P_success                            stored_metric
0          1                186        True          True          True   17.32400778871686 | 10.421646835894284
1          2                186        True          True          True   17.32241164509775 | 10.099755056451666
2          3                186        True          True          True  17.409184830818283 | 10.820265923116253

## Dataset: `P4_FINAL_MODELING_READINESS`

- 역할: Final modeling readiness status JSON
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json`
- 예상 shape: `None`
- 예상 SHA256: `8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea`

In [ ]:
result = inspect_dataset(
    label='P4_FINAL_MODELING_READINESS',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json',
    expected_shape=None,
    expected_sha256='8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea',
    candidate_keys=[['key']],
)

extra_final_json()

### 5.1 File Identification - `P4_FINAL_MODELING_READINESS`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_FINAL_MODELING_READINESS,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINES...,workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json,True,.json,1079,2026-07-13T11:13:04.749244,8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea,8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea,True

### JSON raw structure and flattened table

JSON structure summary

{
  "overall_status": "str",
  "P1_MODELING_STATUS": "str",
  "P2_S_MODELING_STATUS": "str",
  "P2_Q_MODELING_STATUS": "str",
  "P3_S_MODELING_STATUS": "str",
  "P3_Q_MODELING_STATUS": "str",
  "P4_E_STRUCTURE_STATUS": "str",
  "P4_P_STRUCTURE_STATUS": "str",
  "P4_JOINT_STRUCTURE_STATUS": "str",
  "P4_E_SELECTIVITY_STATUS": "str",
  "P4_P_SELECTIVITY_STATUS": "str",
  "P4_JOINT_SELECTIVITY_STATUS": "str",
  "P5_2024_EXPLORATORY_STATUS": "str",
  "P7_STATUS": "str",
  "P8_STATUS": "str",
  "rank_block": "bool",
  "sample_block": "bool",
  "pending_residual_spec_n": "int",
  "created_at": "str",
  "active_d08_sha256": "str",
  "active_d08_shape": {
    "type": "list",
    "length": 2,
    "item_structure": "int"
  },
  "input_file_n": "int",
  "duplicate_conflict_excluded_row_n": "int",
  "OTHER_after_resolution": "int"
}

JSON raw preview

{
  "overall_status": "READY_WITH_WARNINGS",
  "P1_MODELING_STATUS": "READY_WITH_WARNINGS",
  "P2_S_MODELING_STATUS": "READY_WITH_WARNINGS",
  "P2_Q_MODELING_STATUS": "READY_WITH_WARNINGS",
  "P3_S_MODELING_STATUS": "READY_WITH_WARNINGS",
  "P3_Q_MODELING_STATUS": "READY_WITH_WARNINGS",
  "P4_E_STRUCTURE_STATUS": "READY_WITH_WARNINGS",
  "P4_P_STRUCTURE_STATUS": "READY_WITH_WARNINGS",
  "P4_JOINT_STRUCTURE_STATUS": "READY_WITH_WARNINGS",
  "P4_E_SELECTIVITY_STATUS": "READY_WITH_WARNINGS",
  "P4_P_SELECTIVITY_STATUS": "READY_WITH_WARNINGS",
  "P4_JOINT_SELECTIVITY_STATUS": "READY_WITH_WARNINGS",
  "P5_2024_EXPLORATORY_STATUS": "READY",
  "P7_STATUS": "PENDING_TASK_MATRIX",
  "P8_STATUS": "NOT_AVAILABLE",
  "rank_block": false,
  "sample_block": false,
  "pending_residual_spec_n": 4,
  "created_at": "2026-07-13T02:13:04.748261+00:00",
  "active_d08_sha256": "598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962",
  "active_d08_shape": [
    10242,
    151
  ],
  "input_file_n": 10,
  "duplicate_conflict_excluded_row_n": 8,
  "OTHER_after_resolution": 0
}

Flattened table preview

                                  key                                                             value
0                      overall_status                                               READY_WITH_WARNINGS
1                  P1_MODELING_STATUS                                               READY_WITH_WARNINGS
2                P2_S_MODELING_STATUS                                               READY_WITH_WARNINGS
3                P2_Q_MODELING_STATUS                                               READY_WITH_WARNINGS
4                P3_S_MODELING_STATUS                                               READY_WITH_WARNINGS
5                P3_Q_MODELING_STATUS                                               READY_WITH_WARNINGS
6               P4_E_STRUCTURE_STATUS                                               READY_WITH_WARNINGS
7               P4_P_STRUCTURE_STATUS                                               READY_WITH_WARNINGS
8           P4_JOINT_STRUCTURE_STATUS                                               READY_WITH_WARNINGS
9             P4_E_SELECTIVITY_STATUS                                               READY_WITH_WARNINGS
10            P4_P_SELECTIVITY_STATUS                                               READY_WITH_WARNINGS
11        P4_JOINT_SELECTIVITY_STATUS                                               READY_WITH_WARNINGS
12         P5_2024_EXPLORATORY_STATUS                                                             READY
13                          P7_STATUS                                               PENDING_TASK_MATRIX
14                          P8_STATUS                                                     NOT_AVAILABLE
15                         rank_block                                                             False
16                       sample_block                                                             False
17            pending_residual_spec_n                                                                 4
18                         created_at                                  2026-07-13T02:13:04.748261+00:00
19                  active_d08_sha256  598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962
20                   active_d08_shape                                                      [10242, 151]
21                       input_file_n                                                                10
22  duplicate_conflict_excluded_row_n                                                                 8
23             OTHER_after_resolution                                                                 0

### 5.2 Basic Structure

,shape,expected_shape,shape_match,row_count,column_count,memory_usage_bytes,index_dtype,index_unique,exact_duplicate_row_count,loader,encoding,json_raw_type,json_top_level_keys
0,"(24, 2)",None,None,24,2,2246,int64,True,0,json.load + pd.json_normalize,None,dict,"[overall_status, P1_MODELING_STATUS, P2_S_MODELING_STATUS, P2_Q_MODELING_STATUS, P3_S_MODELING_STATUS, P3_Q_MODELING..."

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0                     key                  key    True              0                   0                     0                24

### 5.3 Full Column List

   position column   dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0         1    key     str          24          0     0.000000       24      1.000000        False        False                     True         0.041667
1         2  value  object          24          0     0.000000       11      0.458333        False        False                    False         0.500000

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   key     24 non-null     str
 1   value   24 non-null     object
dtypes: object(1), str(1)
memory usage: 967.0+ bytes

### 5.5 Head

                    key                value
0        overall_status  READY_WITH_WARNINGS
1    P1_MODELING_STATUS  READY_WITH_WARNINGS
2  P2_S_MODELING_STATUS  READY_WITH_WARNINGS
3  P2_Q_MODELING_STATUS  READY_WITH_WARNINGS
4  P3_S_MODELING_STATUS  READY_WITH_WARNINGS

### 5.6 Tail

                                  key                                                             value
19                  active_d08_sha256  598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962
20                   active_d08_shape                                                      [10242, 151]
21                       input_file_n                                                                10
22  duplicate_conflict_excluded_row_n                                                                 8
23             OTHER_after_resolution                                                                 0

### 5.7 Random Sample

                                  key                                                             value
6               P4_E_STRUCTURE_STATUS                                               READY_WITH_WARNINGS
22  duplicate_conflict_excluded_row_n                                                                 8
5                P3_Q_MODELING_STATUS                                               READY_WITH_WARNINGS
12         P5_2024_EXPLORATORY_STATUS                                                             READY
13                          P7_STATUS                                               PENDING_TASK_MATRIX
8           P4_JOINT_STRUCTURE_STATUS                                               READY_WITH_WARNINGS
15                         rank_block                                                             False
11        P4_JOINT_SELECTIVITY_STATUS                                               READY_WITH_WARNINGS
19                  active_d08_sha256  598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962
17            pending_residual_spec_n                                                                 4

### 5.8 Numeric Describe

              message
0  No numeric columns

### 5.8 Categorical/String/Boolean Describe

  column   dtype  count  missing_n  missing_pct  nunique                  top  freq   top_pct                                                                                             sample_values
0    key     str     24          0     0.000000       24       overall_status     1  4.166667  overall_status | P1_MODELING_STATUS | P2_S_MODELING_STATUS | P2_Q_MODELING_STATUS | P3_S_MODELING_STATUS
1  value  object     24          0     0.000000       11  READY_WITH_WARNINGS    12 50.000000                                 READY_WITH_WARNINGS | READY | PENDING_TASK_MATRIX | NOT_AVAILABLE | False

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

No missing values

### 5.10 Top Cardinality Columns

  column   dtype  nunique  unique_ratio
0    key     str       24      1.000000
1  value  object       11      0.458333

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

  message
0    None

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

                              message
0  No numeric/range checks applicable

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS
WARNINGS:
- none

### 6.11 Final Readiness JSON Key-Value Table

                                  key                                                             value
0                      overall_status                                               READY_WITH_WARNINGS
1                  P1_MODELING_STATUS                                               READY_WITH_WARNINGS
2                P2_S_MODELING_STATUS                                               READY_WITH_WARNINGS
3                P2_Q_MODELING_STATUS                                               READY_WITH_WARNINGS
4                P3_S_MODELING_STATUS                                               READY_WITH_WARNINGS
5                P3_Q_MODELING_STATUS                                               READY_WITH_WARNINGS
6               P4_E_STRUCTURE_STATUS                                               READY_WITH_WARNINGS
7               P4_P_STRUCTURE_STATUS                                               READY_WITH_WARNINGS
8           P4_JOINT_STRUCTURE_STATUS                                               READY_WITH_WARNINGS
9             P4_E_SELECTIVITY_STATUS                                               READY_WITH_WARNINGS
10            P4_P_SELECTIVITY_STATUS                                               READY_WITH_WARNINGS
11        P4_JOINT_SELECTIVITY_STATUS                                               READY_WITH_WARNINGS
12         P5_2024_EXPLORATORY_STATUS                                                             READY
13                          P7_STATUS                                               PENDING_TASK_MATRIX
14                          P8_STATUS                                                     NOT_AVAILABLE
15                         rank_block                                                             False
16                       sample_block                                                             False
17            pending_residual_spec_n                                                                 4
18                         created_at                                  2026-07-13T02:13:04.748261+00:00
19                  active_d08_sha256  598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962
20                   active_d08_shape                                                      [10242, 151]
21                       input_file_n                                                                10
22  duplicate_conflict_excluded_row_n                                                                 8
23             OTHER_after_resolution                                                                 0

## Dataset: `P4_MODELING_REVIEW_BUNDLE_MANIFEST`

- 역할: Review bundle manifest JSON
- 경로: `workbook/p2/p2_4/p4_modeling_readiness_v4/P4_MODELING_REVIEW_BUNDLE_MANIFEST.json`
- 예상 shape: `None`
- 예상 SHA256: `None`

In [ ]:
result = inspect_dataset(
    label='P4_MODELING_REVIEW_BUNDLE_MANIFEST',
    path='workbook/p2/p2_4/p4_modeling_readiness_v4/P4_MODELING_REVIEW_BUNDLE_MANIFEST.json',
    expected_shape=None,
    expected_sha256=None,
    candidate_keys=[['label']],
)

extra_bundle_manifest()

### 5.1 File Identification - `P4_MODELING_REVIEW_BUNDLE_MANIFEST`

,label,absolute_path,relative_path,exists,file_extension,file_size,mtime,actual_SHA256,expected_SHA256,hash_match
0,P4_MODELING_REVIEW_BUNDLE_MANIFEST,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/P4_MODELING_REVIEW_BUNDLE_MANIFEST...,workbook/p2/p2_4/p4_modeling_readiness_v4/P4_MODELING_REVIEW_BUNDLE_MANIFEST.json,True,.json,8543,2026-07-13T11:13:04.784825,9afa80278fcec363790fb844c056b78c623ac98f46a5556e0049aae24615da79,None,None

### JSON raw structure and flattened table

JSON structure summary

{
  "created_at": "str",
  "files": {
    "type": "list",
    "length": 15,
    "item_structure": {
      "label": "str",
      "path": "str",
      "relative_path": "str",
      "shape": {
        "type": "list",
        "length": 2,
        "item_structure": "int"
      },
      "row_count": "int",
      "column_count": "int",
      "size_bytes": "int",
      "mtime": "str",
      "sha256": "str"
    }
  }
}

JSON raw preview

{
  "created_at": "2026-07-13T02:13:04.784644+00:00",
  "files": [
    {
      "label": "mart_department_model_base_2024.parquet",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet",
      "relative_path": "workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet",
      "shape": [
        10242,
        151
      ],
      "row_count": 10242,
      "column_count": 151,
      "size_bytes": 2103297,
      "mtime": "2026-07-12T21:47:51.507501",
      "sha256": "598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962"
    },
    {
      "label": "P4_PHASE_SAMPLE_REGISTRY_FINAL.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv",
      "shape": [
        12,
        11
      ],
      "row_count": 12,
      "column_count": 11,
      "size_bytes": 1587,
      "mtime": "2026-07-13T11:12:50.205743",
      "sha256": "6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e"
    },
    {
      "label": "P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet",
      "shape": [
        10242,
        21
      ],
      "row_count": 10242,
      "column_count": 21,
      "size_bytes": 273814,
      "mtime": "2026-07-13T11:12:50.209943",
      "sha256": "58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6"
    },
    {
      "label": "department_model_column_registry_v4.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv",
      "shape": [
        151,
        22
      ],
      "row_count": 151,
      "column_count": 22,
      "size_bytes": 58300,
      "mtime": "2026-07-13T11:12:50.014680",
      "sha256": "ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94"
    },
    {
      "label": "P4_PHASE_FEATURE_SET_FINAL.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv",
      "shape": [
        250,
        11
      ],
      "row_count": 250,
      "column_count": 11,
      "size_bytes": 39889,
      "mtime": "2026-07-13T11:12:50.386869",
      "sha256": "dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320"
    },
    {
      "label": "P4_PHASE_MODEL_SPEC_FINAL.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv",
      "shape": [
        18,
        10
      ],
      "row_count": 18,
      "column_count": 10,
      "size_bytes": 2618,
      "mtime": "2026-07-13T11:12:50.388366",
      "sha256": "d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48"
    },
    {
      "label": "P4_DUPLICATE_CONFLICT_RESOLUTION.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv",
      "shape": [
        36,
        14
      ],
      "row_count": 36,
      "column_count": 14,
      "size_bytes": 13216,
      "mtime": "2026-07-13T11:12:50.049703",
      "sha256": "24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f"
    },
    {
      "label": "P4_PHASE_DESIGN_MATRIX_RANK.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv",
      "shape": [
        32,
        17
      ],
      "row_count": 32,
      "column_count": 17,
      "size_bytes": 5830,
      "mtime": "2026-07-13T11:12:52.229568",
      "sha256": "17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae"
    },
    {
      "label": "P4_LINEAR_ALIAS_GROUPS.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv",
      "shape": [
        56,
        6
      ],
      "row_count": 56,
      "column_count": 6,
      "size_bytes": 18248,
      "mtime": "2026-07-13T11:12:52.232192",
      "sha256": "31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517"
    },
    {
      "label": "P4_VIF_TOP30_BY_PHASE.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv",
      "shape": [
        420,
        5
      ],
      "row_count": 420,
      "column_count": 5,
      "size_bytes": 27632,
      "mtime": "2026-07-13T11:12:52.232858",
      "sha256": "fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea"
    },
    {
      "label": "P4_TARGET_PROFILE_BY_PHASE.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv",
      "shape": [
        396,
        20
      ],
      "row_count": 396,
      "column_count": 20,
      "size_bytes": 53599,
      "mtime": "2026-07-13T11:12:59.628858",
      "sha256": "6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a"
    },
    {
      "label": "P4_MODEL_FAMILY_RECOMMENDATION.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv",
      "shape": [
        8,
        8
      ],
      "row_count": 8,
      "column_count": 8,
      "size_bytes": 2305,
      "mtime": "2026-07-13T11:12:59.630755",
      "sha256": "193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c"
    },
    {
      "label": "P3_NESTED_CROSSFIT_SMOKE.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv",
      "shape": [
        1,
        11
      ],
      "row_count": 1,
      "column_count": 11,
      "size_bytes": 1097,
      "mtime": "2026-07-13T11:13:00.305181",
      "sha256": "b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808"
    },
    {
      "label": "P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv",
      "shape": [
        3,
        11
      ],
      "row_count": 3,
      "column_count": 11,
      "size_bytes": 406,
      "mtime": "2026-07-13T11:13:04.747216",
      "sha256": "5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467"
    },
    {
      "label": "P4_FINAL_MODELING_READINESS.json",
      "path": "/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json",
      "relative_path": "workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json",
      "shape": [
        24,
        null
      ],
      "row_count": 24,
      "column_count": null,
      "size_bytes": 1079,
      "mtime": "2026-07-13T11:13:04.749244",
      "sha256": "8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea"
    }
  ]
}

Flattened table preview

,label,path,relative_path,shape,row_count,column_count,size_bytes,mtime,sha256
0,mart_department_model_base_2024.parquet,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024...,workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet,"[10242, 151]",10242,151.000000,2103297,2026-07-12T21:47:51.507501,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962
1,P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,"[12, 11]",12,11.000000,1587,2026-07-13T11:12:50.205743,6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e
2,P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FI...,workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,"[10242, 21]",10242,21.000000,273814,2026-07-13T11:12:50.209943,58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6
3,department_model_column_registry_v4.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv,"[151, 22]",151,22.000000,58300,2026-07-13T11:12:50.014680,ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94
4,P4_PHASE_FEATURE_SET_FINAL.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FIN...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv,"[250, 11]",250,11.000000,39889,2026-07-13T11:12:50.386869,dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320
5,P4_PHASE_MODEL_SPEC_FINAL.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINA...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv,"[18, 10]",18,10.000000,2618,2026-07-13T11:12:50.388366,d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48
6,P4_DUPLICATE_CONFLICT_RESOLUTION.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTIO...,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv,"[36, 14]",36,14.000000,13216,2026-07-13T11:12:50.049703,24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f
7,P4_PHASE_DESIGN_MATRIX_RANK.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv,"[32, 17]",32,17.000000,5830,2026-07-13T11:12:52.229568,17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae
8,P4_LINEAR_ALIAS_GROUPS.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv,"[56, 6]",56,6.000000,18248,2026-07-13T11:12:52.232192,31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517
9,P4_VIF_TOP30_BY_PHASE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv,"[420, 5]",420,5.000000,27632,2026-07-13T11:12:52.232858,fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea
10,P4_TARGET_PROFILE_BY_PHASE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHAS...,workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv,"[396, 20]",396,20.000000,53599,2026-07-13T11:12:59.628858,6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a
11,P4_MODEL_FAMILY_RECOMMENDATION.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMEN...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv,"[8, 8]",8,8.000000,2305,2026-07-13T11:12:59.630755,193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c
12,P3_NESTED_CROSSFIT_SMOKE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,"[1, 11]",1,11.000000,1097,2026-07-13T11:13:00.305181,b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808
13,P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOK...,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv,"[3, 11]",3,11.000000,406,2026-07-13T11:13:04.747216,5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467
14,P4_FINAL_MODELING_READINESS.json,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINES...,workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json,"[24, None]",24,NaN,1079,2026-07-13T11:13:04.749244,8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea

### 5.2 Basic Structure

     shape expected_shape shape_match  row_count  column_count  memory_usage_bytes index_dtype  index_unique  exact_duplicate_row_count                         loader encoding json_raw_type  json_top_level_keys
0  (15, 9)           None        None         15             9                7395       int64          True                          0  json.load + pd.json_normalize     None          dict  [created_at, files]

#### Candidate Key Check

  candidate_key_requested candidate_key_actual  exists  null_key_rows  duplicate_key_rows  duplicate_key_groups  unique_key_count
0                   label                label    True              0                   0                     0                15

### 5.3 Full Column List

   position         column    dtype  non_null_n  missing_n  missing_pct  nunique  unique_ratio  is_all_null  is_constant  is_identifier_candidate  top_value_share
0         1          label      str          15          0     0.000000       15      1.000000        False        False                     True         0.066667
1         2           path      str          15          0     0.000000       15      1.000000        False        False                     True         0.066667
2         3  relative_path      str          15          0     0.000000       15      1.000000        False        False                     True         0.066667
3         4          shape   object          15          0     0.000000       15      1.000000        False        False                     True         0.066667
4         5      row_count    int64          15          0     0.000000       14      0.933333        False        False                    False         0.133333
5         6   column_count  float64          14          1     6.666667       11      0.785714        False        False                    False         0.266667
6         7     size_bytes    int64          15          0     0.000000       15      1.000000        False        False                    False         0.066667
7         8          mtime      str          15          0     0.000000       15      1.000000        False        False                    False         0.066667
8         9         sha256      str          15          0     0.000000       15      1.000000        False        False                     True         0.066667

### 5.4 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   label          15 non-null     str
 1   path           15 non-null     str
 2   relative_path  15 non-null     str
 3   shape          15 non-null     object
 4   row_count      15 non-null     int64
 5   column_count   14 non-null     float64
 6   size_bytes     15 non-null     int64
 7   mtime          15 non-null     str
 8   sha256         15 non-null     str
dtypes: float64(1), int64(2), object(1), str(5)
memory usage: 5.9+ KB

### 5.5 Head

,label,path,relative_path,shape,row_count,column_count,size_bytes,mtime,sha256
0,mart_department_model_base_2024.parquet,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024...,workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet,"[10242, 151]",10242,151.000000,2103297,2026-07-12T21:47:51.507501,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962
1,P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,"[12, 11]",12,11.000000,1587,2026-07-13T11:12:50.205743,6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e
2,P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FI...,workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,"[10242, 21]",10242,21.000000,273814,2026-07-13T11:12:50.209943,58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6
3,department_model_column_registry_v4.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv,"[151, 22]",151,22.000000,58300,2026-07-13T11:12:50.014680,ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94
4,P4_PHASE_FEATURE_SET_FINAL.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FIN...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv,"[250, 11]",250,11.000000,39889,2026-07-13T11:12:50.386869,dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320

### 5.6 Tail

,label,path,relative_path,shape,row_count,column_count,size_bytes,mtime,sha256
10,P4_TARGET_PROFILE_BY_PHASE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHAS...,workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv,"[396, 20]",396,20.000000,53599,2026-07-13T11:12:59.628858,6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a
11,P4_MODEL_FAMILY_RECOMMENDATION.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMEN...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv,"[8, 8]",8,8.000000,2305,2026-07-13T11:12:59.630755,193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c
12,P3_NESTED_CROSSFIT_SMOKE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,"[1, 11]",1,11.000000,1097,2026-07-13T11:13:00.305181,b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808
13,P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOK...,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv,"[3, 11]",3,11.000000,406,2026-07-13T11:13:04.747216,5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467
14,P4_FINAL_MODELING_READINESS.json,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINES...,workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json,"[24, None]",24,NaN,1079,2026-07-13T11:13:04.749244,8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea

### 5.7 Random Sample

,label,path,relative_path,shape,row_count,column_count,size_bytes,mtime,sha256
14,P4_FINAL_MODELING_READINESS.json,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINES...,workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json,"[24, None]",24,NaN,1079,2026-07-13T11:13:04.749244,8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea
9,P4_VIF_TOP30_BY_PHASE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv,"[420, 5]",420,5.000000,27632,2026-07-13T11:12:52.232858,fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea
6,P4_DUPLICATE_CONFLICT_RESOLUTION.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTIO...,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv,"[36, 14]",36,14.000000,13216,2026-07-13T11:12:50.049703,24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f
4,P4_PHASE_FEATURE_SET_FINAL.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FIN...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv,"[250, 11]",250,11.000000,39889,2026-07-13T11:12:50.386869,dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320
0,mart_department_model_base_2024.parquet,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024...,workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet,"[10242, 151]",10242,151.000000,2103297,2026-07-12T21:47:51.507501,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962
12,P3_NESTED_CROSSFIT_SMOKE.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,"[1, 11]",1,11.000000,1097,2026-07-13T11:13:00.305181,b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808
2,P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FI...,workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,"[10242, 21]",10242,21.000000,273814,2026-07-13T11:12:50.209943,58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6
1,P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,"[12, 11]",12,11.000000,1587,2026-07-13T11:12:50.205743,6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e
3,department_model_column_registry_v4.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv,"[151, 22]",151,22.000000,58300,2026-07-13T11:12:50.014680,ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94
5,P4_PHASE_MODEL_SPEC_FINAL.csv,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINA...,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv,"[18, 10]",18,10.000000,2618,2026-07-13T11:12:50.388366,d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48

### 5.8 Numeric Describe

,column,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max,missing_n,missing_pct,zero_n,zero_pct,negative_n,inf_n,nunique
0,row_count,15.000000,"1,459.400000","3,568.457986",1.000000,1.280000,2.400000,5.000000,15.000000,36.000000,323.000000,"6,313.200000","10,242.000000","10,242.000000","10,242.000000",0,0.000000,0,0.000000,0,0,14
1,column_count,14.000000,22.714286,37.310400,5.000000,5.130000,5.650000,6.600000,10.250000,11.000000,19.250000,21.700000,67.150000,134.230000,151.000000,1,6.666667,0,0.000000,0,0,11
2,size_bytes,15.000000,"173,527.800000","538,273.641099",406.000000,500.220000,877.100000,"1,086.200000","1,946.000000","13,216.000000","46,744.000000","187,608.400000","822,658.900000","1,847,169.380000","2,103,297.000000",0,0.000000,0,0.000000,0,0,15

### 5.8 Categorical/String/Boolean Describe

,column,dtype,count,missing_n,missing_pct,nunique,top,freq,top_pct,sample_values
0,label,str,15,0,0.000000,15,mart_department_model_base_2024.parquet,1,6.666667,mart_department_model_base_2024.parquet | P4_PHASE_SAMPLE_REGISTRY_FINAL.csv | P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parq...
1,path,str,15,0,0.000000,15,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024...,1,6.666667,/home/sieg/projects-wsl/SBS_dataScience/workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024...
2,relative_path,str,15,0,0.000000,15,workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet,1,6.666667,workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet | workbook/p2/p2_4/p4_modeling_...
3,shape,object,15,0,0.000000,15,"[10242, 151]",1,6.666667,"[10242, 151] | [12, 11] | [10242, 21] | [151, 22] | [250, 11]"
4,mtime,str,15,0,0.000000,15,2026-07-12T21:47:51.507501,1,6.666667,2026-07-12T21:47:51.507501 | 2026-07-13T11:12:50.205743 | 2026-07-13T11:12:50.209943 | 2026-07-13T11:12:50.014680 | ...
5,sha256,str,15,0,0.000000,15,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962,1,6.666667,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962 | 6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f...

### 5.8 Datetime Describe

               message
0  No datetime columns

### 5.9 Top Missing Columns

   rank        column    dtype  missing_n  missing_pct  non_null_n  nunique
5     1  column_count  float64          1     6.666667          14       11

### 5.10 Top Cardinality Columns

          column    dtype  nunique  unique_ratio
0          label      str       15      1.000000
1           path      str       15      1.000000
2  relative_path      str       15      1.000000
3          shape   object       15      1.000000
6     size_bytes    int64       15      1.000000
7          mtime      str       15      1.000000
8         sha256      str       15      1.000000
4      row_count    int64       14      0.933333
5   column_count  float64       11      0.785714

### 5.11 All-null / Constant / Near-constant Columns

All-null columns

  message
0    None

Constant columns

  message
0    None

Near-constant columns

  message
0    None

### 5.12 Duplicate Check

   exact_duplicate_row_count  exact_duplicate_group_count  candidate_key_duplicate_row_count  candidate_key_duplicate_group_count
0                          0                            0                                  0                                    0

                        message
0  No duplicate rows to display

### 5.13 Range and Basic Outlier Checks

         column              check    nan_n  pos_inf_n  neg_inf_n  negative_n   zero_n  violation_n
0     row_count      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0
1     row_count  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
2  column_count      numeric_basic 1.000000   0.000000   0.000000    0.000000 0.000000            0
3  column_count  count_nonnegative      NaN        NaN        NaN         NaN      NaN            0
4    size_bytes      numeric_basic 0.000000   0.000000   0.000000    0.000000 0.000000            0

Range violations

               message
0  No range violations

### 5.14 Cell Final Status

DATASET_STATUS:
PASS
WARNINGS:
- none

### 6.12 Review Bundle Manifest Files

,label,relative_path,shape,size_bytes,sha256,mtime
0,mart_department_model_base_2024.parquet,workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet,"[10242, 151]",2103297,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962,2026-07-12T21:47:51.507501
1,P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,"[12, 11]",1587,6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e,2026-07-13T11:12:50.205743
2,P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,"[10242, 21]",273814,58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6,2026-07-13T11:12:50.209943
3,department_model_column_registry_v4.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv,"[151, 22]",58300,ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94,2026-07-13T11:12:50.014680
4,P4_PHASE_FEATURE_SET_FINAL.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv,"[250, 11]",39889,dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320,2026-07-13T11:12:50.386869
5,P4_PHASE_MODEL_SPEC_FINAL.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv,"[18, 10]",2618,d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48,2026-07-13T11:12:50.388366
6,P4_DUPLICATE_CONFLICT_RESOLUTION.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv,"[36, 14]",13216,24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f,2026-07-13T11:12:50.049703
7,P4_PHASE_DESIGN_MATRIX_RANK.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv,"[32, 17]",5830,17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae,2026-07-13T11:12:52.229568
8,P4_LINEAR_ALIAS_GROUPS.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv,"[56, 6]",18248,31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517,2026-07-13T11:12:52.232192
9,P4_VIF_TOP30_BY_PHASE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv,"[420, 5]",27632,fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea,2026-07-13T11:12:52.232858
10,P4_TARGET_PROFILE_BY_PHASE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv,"[396, 20]",53599,6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a,2026-07-13T11:12:59.628858
11,P4_MODEL_FAMILY_RECOMMENDATION.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv,"[8, 8]",2305,193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c,2026-07-13T11:12:59.630755
12,P3_NESTED_CROSSFIT_SMOKE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,"[1, 11]",1097,b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808,2026-07-13T11:13:00.305181
13,P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv,"[3, 11]",406,5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467,2026-07-13T11:13:04.747216
14,P4_FINAL_MODELING_READINESS.json,workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json,"[24, None]",1079,8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea,2026-07-13T11:13:04.749244

## Final Integrated Summary

In [ ]:

display(Markdown("## 7. Final Integrated Summary"))

def simple_md_table(df, max_rows=200):
    if df.empty:
        return "(empty)"
    view = df.head(max_rows).copy()
    cols = list(view.columns)
    def clean(value):
        if isinstance(value, (list, tuple, dict)):
            text = json.dumps(value, ensure_ascii=False)
        elif pd.isna(value):
            text = ""
        else:
            text = str(value)
        return text.replace("|", "\\|").replace("\n", " ")
    lines = [
        "| " + " | ".join(cols) + " |",
        "| " + " | ".join(["---"] * len(cols)) + " |",
    ]
    for _, row in view.iterrows():
        lines.append("| " + " | ".join(clean(row[c]) for c in cols) + " |")
    return "\n".join(lines)

inventory = pd.DataFrame(DATASET_RESULTS)
inventory["actual shape"] = inventory["actual_shape"].astype(str)
inventory["expected shape"] = inventory["expected_shape"].astype(str)
inventory_final = inventory[["label", "path", "actual shape", "expected shape", "shape_match", "actual_sha256", "expected_sha256", "hash_match", "status", "warning_n"]].copy()
inventory_path = QA_DIR / "dataset_inventory_final.csv"
inventory_final.to_csv(inventory_path, index=False, encoding="utf-8-sig")
display(Markdown("### 7.1 Dataset inventory"))
display(inventory_final)

missing_frames = []
for profile_path in PROFILE_DIR.glob("*__column_profile.csv"):
    dataset = profile_path.name.replace("__column_profile.csv", "")
    prof = pd.read_csv(profile_path, encoding="utf-8-sig")
    prof.insert(0, "dataset", dataset)
    missing_frames.append(prof[["dataset", "column", "dtype", "missing_n", "missing_pct"]])
all_missing = pd.concat(missing_frames, ignore_index=True).sort_values(["missing_pct", "missing_n"], ascending=False).head(100)
all_missing_path = QA_DIR / "all_datasets_top_missing.csv"
all_missing.to_csv(all_missing_path, index=False, encoding="utf-8-sig")
display(Markdown("### 7.2 All datasets top missing"))
display(all_missing)

anomalies = pd.DataFrame(ANOMALY_ROWS)
if anomalies.empty:
    anomalies = pd.DataFrame(columns=["dataset", "anomaly_type", "column", "detail"])

rank_path = OUT_ROOT / "qa/P4_PHASE_DESIGN_MATRIX_RANK.csv"
if rank_path.exists():
    rank = pd.read_csv(rank_path, low_memory=False)
    for _, row in rank[pd.to_numeric(rank["rank_deficiency"], errors="coerce").fillna(0) > 0].iterrows():
        anomalies.loc[len(anomalies)] = {"dataset": "P4_PHASE_DESIGN_MATRIX_RANK", "anomaly_type": "rank deficiency", "column": row.get("model_id"), "detail": f"coding={row.get('coding')} rank_deficiency={row.get('rank_deficiency')}"}

vif_path = OUT_ROOT / "qa/P4_VIF_TOP30_BY_PHASE.csv"
if vif_path.exists():
    vif = pd.read_csv(vif_path, low_memory=False)
    for _, row in vif[pd.to_numeric(vif["vif"], errors="coerce").fillna(0) >= 10].iterrows():
        anomalies.loc[len(anomalies)] = {"dataset": "P4_VIF_TOP30_BY_PHASE", "anomaly_type": "high VIF", "column": row.get("encoded_feature"), "detail": f"model_id={row.get('model_id')} vif={row.get('vif')}"}

anomaly_path = QA_DIR / "all_dataset_anomalies.csv"
anomalies.to_csv(anomaly_path, index=False, encoding="utf-8-sig")
display(Markdown("### 7.3 All dataset anomalies"))
display(anomalies)

spec = pd.read_csv(OUT_ROOT / "artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv", low_memory=False)
rank = pd.read_csv(OUT_ROOT / "qa/P4_PHASE_DESIGN_MATRIX_RANK.csv", low_memory=False)
sample = pd.read_csv(OUT_ROOT / "artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv", low_memory=False)
focus_models = ["P1_STRUCTURE", "P1_SELECTIVITY", "P2_S", "P2_Q", "P3_S", "P3_Q", "P4_E_STRUCTURE_A_RATE", "P4_E_SELECTIVITY_A_RATE", "P4_P_STRUCTURE_A_RATE", "P4_P_SELECTIVITY_A_RATE"]
phase_map = spec[spec["model_id"].isin(focus_models)].merge(sample[["sample_id", "row_n", "school_n"]], on="sample_id", how="left")
treatment = rank[rank["coding"].eq("treatment")][["model_id", "raw_feature_count", "encoded_feature_count", "rank_deficiency", "status"]].rename(columns={"status": "rank_status"})
phase_map = phase_map.merge(treatment, on="model_id", how="left")
phase_map = phase_map.assign(dataframe="mart_department_model_base_2024", warning=np.where(pd.to_numeric(phase_map["rank_deficiency"], errors="coerce").fillna(0) > 0, "rank_deficiency", ""))
phase_map = phase_map[["phase", "sample_id", "dataframe", "target", "raw_feature_count", "encoded_feature_count", "row_n", "school_n", "status", "warning"]]
phase_map_path = QA_DIR / "phase_data_map.csv"
phase_map.to_csv(phase_map_path, index=False, encoding="utf-8-sig")
display(Markdown("### 7.4 Phase data map"))
display(phase_map)

report_path = REPORT_DIR / "P4_DATASET_INSPECTION_REPORT.md"
summary_path = REPORT_DIR / "P4_DATASET_INSPECTION_SUMMARY.json"
report = f"""# P4 Dataset Inspection Report

- executed_at: {datetime.now(timezone.utc).isoformat()}
- notebook: `{rel(OUT_ROOT / 'p2_G4_dataset_cell_inspection.ipynb')}`
- dataset_count: {len(inventory_final)}
- fail_count: {int(inventory_final['status'].astype(str).str.startswith('FAIL').sum())}
- warning_dataset_count: {int((inventory_final['warning_n'] > 0).sum())}
- anomaly_rows: {len(anomalies)}

## Dataset Status

{simple_md_table(inventory_final)}

## Phase Data Map

{simple_md_table(phase_map)}
"""
report_path.write_text(report, encoding="utf-8")
summary = {
    "executed_at": datetime.now(timezone.utc).isoformat(),
    "dataset_count": int(len(inventory_final)),
    "fail_count": int(inventory_final["status"].astype(str).str.startswith("FAIL").sum()),
    "warning_dataset_count": int((inventory_final["warning_n"] > 0).sum()),
    "anomaly_rows": int(len(anomalies)),
    "inventory_path": rel(inventory_path),
    "all_missing_path": rel(all_missing_path),
    "anomaly_path": rel(anomaly_path),
    "phase_map_path": rel(phase_map_path),
    "report_path": rel(report_path),
}
profile_files = sorted(PROFILE_DIR.glob("*.csv"))
qa_files = sorted(QA_DIR.glob("*.csv"))
report_files = sorted(REPORT_DIR.glob("*"))
env_path = LOG_DIR / "dataset_inspection_environment.json"
run_manifest_path = LOG_DIR / "dataset_inspection_run_manifest.json"
environment = {
    "working_directory": str(PROJECT_ROOT),
    "python_version": platform.python_version(),
    "pandas_version": pd.__version__,
    "numpy_version": np.__version__,
    "pyarrow_version": pyarrow.__version__,
    "platform": platform.platform(),
    "git_commit": GIT_COMMIT,
    "random_state": RANDOM_STATE,
    "run_started_at": RUN_STARTED_AT,
    "run_completed_at": summary["executed_at"],
}
env_path.write_text(json.dumps(environment, ensure_ascii=False, indent=2), encoding="utf-8")
output_files = profile_files + qa_files + report_files + [env_path]
output_records = []
for output_path in output_files:
    output_records.append({
        "path": rel(output_path),
        "size_bytes": output_path.stat().st_size if output_path.exists() else None,
        "sha256": sha256_file(output_path),
    })
run_manifest = {
    **summary,
    "profile_file_count": len(profile_files),
    "qa_file_count": len(qa_files),
    "report_file_count": len(report_files),
    "environment_path": rel(env_path),
    "outputs": output_records,
}
run_manifest_path.write_text(json.dumps(run_manifest, ensure_ascii=False, indent=2), encoding="utf-8")
summary["profile_file_count"] = len(profile_files)
summary["qa_file_count"] = len(qa_files)
summary["report_file_count"] = len(report_files)
summary["environment_path"] = rel(env_path)
summary["run_manifest_path"] = rel(run_manifest_path)
summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
display(Markdown("### Saved final outputs"))
display(pd.DataFrame([summary]))
print("INSPECTION_STATUS:")
print("PASS" if summary["fail_count"] == 0 else "FAIL")

## 7. Final Integrated Summary

### 7.1 Dataset inventory

,label,path,actual shape,expected shape,shape_match,actual_sha256,expected_sha256,hash_match,status,warning_n
0,mart_department_model_base_2024,workbook/p2/p2_3/p4_handoff_candidate/shared/mart_department_model_base_2024.parquet,"(10242, 151)","(10242, 151)",True,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962,598b68b31b5358dfd23839d4c138cc64838d05876b7791980b376c0453f29962,True,PASS_WITH_WARNINGS,3
1,P4_PHASE_SAMPLE_MEMBERSHIP_FINAL,workbook/p2/p2_4/p4_modeling_readiness_v4/data/P4_PHASE_SAMPLE_MEMBERSHIP_FINAL.parquet,"(10242, 21)","(10242, 21)",True,58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6,58d0308aa92f04badea3c7fc2db44fc28d0d93580db9bff4f16d47d870ebc7c6,True,PASS_WITH_WARNINGS,1
2,P4_PHASE_SAMPLE_REGISTRY_FINAL,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_SAMPLE_REGISTRY_FINAL.csv,"(12, 11)","(12, 11)",True,6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e,6483fdf67cca469ed7bd2500e5ef917ffd01007194c83461f5c827b03f16805e,True,PASS_WITH_WARNINGS,1
3,department_model_column_registry_v4,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/department_model_column_registry_v4.csv,"(151, 22)","(151, 22)",True,ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94,ab75225547d42ddc8e6cdf686be61ecc8bf87512729d8d9d053652b521093b94,True,PASS_WITH_WARNINGS,1
4,P4_PHASE_FEATURE_SET_FINAL,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_FEATURE_SET_FINAL.csv,"(250, 11)","(250, 11)",True,dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320,dc851803d22a22e891a7fdd9a31dbe0c3d2ac56421a9798e06a9e87e20ce2320,True,PASS_WITH_WARNINGS,1
5,P4_PHASE_MODEL_SPEC_FINAL,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_PHASE_MODEL_SPEC_FINAL.csv,"(18, 10)","(18, 10)",True,d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48,d7f560167ec752938b73dbee3c5f9dddc84fbc009d9eeaa3905b20946cc7dc48,True,PASS,0
6,P4_MODEL_FAMILY_RECOMMENDATION,workbook/p2/p2_4/p4_modeling_readiness_v4/artifacts/P4_MODEL_FAMILY_RECOMMENDATION.csv,"(8, 8)","(8, 8)",True,193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c,193db8e4da1201fa9ef8fbe635803de560d563e4c1446770129066fbc497c68c,True,PASS_WITH_WARNINGS,1
7,P4_DUPLICATE_CONFLICT_RESOLUTION,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_DUPLICATE_CONFLICT_RESOLUTION.csv,"(36, 14)","(36, 14)",True,24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f,24d2e000661b3e67a353877383c7ef68b8e156f52bd11ac22f4b1fd724be8d4f,True,PASS_WITH_WARNINGS,1
8,P4_PHASE_DESIGN_MATRIX_RANK,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_PHASE_DESIGN_MATRIX_RANK.csv,"(32, 17)","(32, 17)",True,17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae,17414355de01f8ecd9170e810b4826886e5825a57191dacc5d43a1f7b8f336ae,True,PASS_WITH_WARNINGS,1
9,P4_LINEAR_ALIAS_GROUPS,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_LINEAR_ALIAS_GROUPS.csv,"(56, 6)","(56, 6)",True,31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517,31340edd978ec94763e6890bda4fef7d63eb414727a30015a054bc7898e59517,True,PASS_WITH_WARNINGS,1
10,P4_VIF_TOP30_BY_PHASE,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_VIF_TOP30_BY_PHASE.csv,"(420, 5)","(420, 5)",True,fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea,fdb9ded6ac3dd41eaa3828a34eb671144fe680f3db2c3be094f0c381a6e348ea,True,PASS_WITH_WARNINGS,1
11,P4_TARGET_PROFILE_BY_PHASE,workbook/p2/p2_4/p4_modeling_readiness_v4/profiles/P4_TARGET_PROFILE_BY_PHASE.csv,"(396, 20)","(396, 20)",True,6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a,6f3fdb25676ccfdf59b0b2f458e5cdb5dd66dfb6f61e037b2e711418efffc25a,True,PASS,0
12,P3_NESTED_CROSSFIT_SMOKE,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P3_NESTED_CROSSFIT_SMOKE.csv,"(1, 11)","(1, 11)",True,b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808,b784b40c0a8ca7e2d011715594d31d399183539b93303e577ac915c775e25808,True,PASS_WITH_WARNINGS,1
13,P4_FULL_PIPELINE_BOOTSTRAP_SMOKE,workbook/p2/p2_4/p4_modeling_readiness_v4/qa/P4_FULL_PIPELINE_BOOTSTRAP_SMOKE.csv,"(3, 11)","(3, 11)",True,5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467,5a80872860be75498b84987ebe861e7c17b4180edd6ad4ed2e2cc4acdcbf3467,True,PASS_WITH_WARNINGS,1
14,P4_FINAL_MODELING_READINESS,workbook/p2/p2_4/p4_modeling_readiness_v4/reports/P4_FINAL_MODELING_READINESS.json,"(24, 2)",NaN,None,8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea,8fcd0df2cee25f2b31ba498806ea5956e82e5da74580ce01573aa01c201ffbea,True,PASS,0
15,P4_MODELING_REVIEW_BUNDLE_MANIFEST,workbook/p2/p2_4/p4_modeling_readiness_v4/P4_MODELING_REVIEW_BUNDLE_MANIFEST.json,"(15, 9)",NaN,None,9afa80278fcec363790fb844c056b78c623ac98f46a5556e0049aae24615da79,NaN,None,PASS,0

### 7.2 All datasets top missing

                                 dataset                                   column    dtype  missing_n  missing_pct
121      mart_department_model_base_2024                  ctx24_industry_top3_pct  Float32      10242   100.000000
122      mart_department_model_base_2024                       ctx24_industry_hhi  Float32      10242   100.000000
158           P4_TARGET_PROFILE_BY_PHASE                                      min  float64        360    90.909091
159           P4_TARGET_PROFILE_BY_PHASE                                      p01  float64        360    90.909091
160           P4_TARGET_PROFILE_BY_PHASE                                      p05  float64        360    90.909091
161           P4_TARGET_PROFILE_BY_PHASE                                      p25  float64        360    90.909091
163           P4_TARGET_PROFILE_BY_PHASE                                      p75  float64        360    90.909091
164           P4_TARGET_PROFILE_BY_PHASE                                      p95  float64        360    90.909091
165           P4_TARGET_PROFILE_BY_PHASE                                      p99  float64        360    90.909091
166           P4_TARGET_PROFILE_BY_PHASE                                      max  float64        360    90.909091
168           P4_TARGET_PROFILE_BY_PHASE                            hundred_ratio  float64        360    90.909091
169           P4_TARGET_PROFILE_BY_PHASE                                 skewness  float64        360    90.909091
170           P4_TARGET_PROFILE_BY_PHASE                               school_icc  float64        360    90.909091
232     P4_DUPLICATE_CONFLICT_RESOLUTION                         exclusion_reason      str         28    77.777778
200            P4_PHASE_MODEL_SPEC_FINAL                missing_required_features      str         14    77.777778
255  department_model_column_registry_v4                       derivation_formula      str         98    64.900662
156           P4_TARGET_PROFILE_BY_PHASE                                     mean  float64        252    63.636364
157           P4_TARGET_PROFILE_BY_PHASE                                      std  float64        252    63.636364
162           P4_TARGET_PROFILE_BY_PHASE                                   median  float64        252    63.636364
14       mart_department_model_base_2024                    selectivity_proxy_pct  Float32       6505    63.512986
215          P4_PHASE_DESIGN_MATRIX_RANK                         constant_columns      str         18    56.250000
87       mart_department_model_base_2024                        competition_ratio  Float32       4985    48.672134
88       mart_department_model_base_2024                    admission_yield_ratio  Float32       4985    48.672134
89       mart_department_model_base_2024                admit_per_applicant_ratio  Float32       4982    48.642843
218          P4_PHASE_DESIGN_MATRIX_RANK                       recommended_action      str         14    43.750000
258  department_model_column_registry_v4                                valid_min  float64         59    39.072848
259  department_model_column_registry_v4                                valid_max  float64         59    39.072848
93       mart_department_model_base_2024                    student_faculty_ratio  Float32       3863    37.717243
94       mart_department_model_base_2024               fulltime_faculty_share_pct  Float32       3863    37.717243
18       mart_department_model_base_2024                      employment_rate_pct  Float32       2765    26.996680
19       mart_department_model_base_2024               health_employment_rate_pct  Float32       2765    26.996680
20       mart_department_model_base_2024                     progression_rate_pct  Float32       2655    25.922671
21       mart_department_model_base_2024  vocational_college_progression_rate_pct  Float32       2655    25.922671
22       mart_department_model_base_2024          university_progression_rate_pct  Float32       2655    25.922671
23       mart_department_model_base_2024     graduate_school_progression_rate_pct  Float32       2655    25.922671
24       mart_department_model_base_2024            domestic_progression_rate_pct  Float32       2655    25.922671
25       mart_department_model_base_2024            overseas_progression_rate_pct  Float32       2655    25.922671
90       mart_department_model_base_2024                           leave_rate_pct  Float32       1801    17.584456
91       mart_department_model_base_2024                 female_student_share_pct  Float32       1801    17.584456
92       mart_department_model_base_2024          international_student_share_pct  Float32       1801    17.584456
37       mart_department_model_base_2024                         headcount_row_id      str       1681    16.412810
53       mart_department_model_base_2024                  headcount_grain_version      str       1681    16.412810
54       mart_department_model_base_2024                      headcount_grain_uid   string       1681    16.412810
55       mart_department_model_base_2024                  grain_resolution_method      str       1681    16.412810
56       mart_department_model_base_2024                      grain_review_needed  boolean       1681    16.412810
57       mart_department_model_base_2024                          raw_row_lineage   string       1681    16.412810
58       mart_department_model_base_2024                             school_uid_y   string       1681    16.412810
61       mart_department_model_base_2024                           kedi_dept_code   string       1681    16.412810
62       mart_department_model_base_2024                              school_type   string       1681    16.412810
63       mart_department_model_base_2024                            degree_course   string       1681    16.412810
64       mart_department_model_base_2024                        school_status_raw   string       1681    16.412810
65       mart_department_model_base_2024                          day_evening_raw   string       1681    16.412810
66       mart_department_model_base_2024                        campus_name_raw_y   string       1681    16.412810
67       mart_department_model_base_2024                        campus_name_std_y   string       1681    16.412810
68       mart_department_model_base_2024                              region_sido   string       1681    16.412810
69       mart_department_model_base_2024                           region_sigungu   string       1681    16.412810
70       mart_department_model_base_2024                       hc_major_group_raw   string       1681    16.412810
71       mart_department_model_base_2024                         hc_major_group_7   string       1681    16.412810
72       mart_department_model_base_2024                        field_middle_name   string       1681    16.412810
73       mart_department_model_base_2024                         field_small_name   string       1681    16.412810
74       mart_department_model_base_2024                     admission_capacity_n    Int32       1681    16.412810
75       mart_department_model_base_2024                            recruitment_n    Int32       1681    16.412810
76       mart_department_model_base_2024                             applicants_n    Int32       1681    16.412810
77       mart_department_model_base_2024                                 admits_n    Int32       1681    16.412810
78       mart_department_model_base_2024                      enrolled_students_n    Int32       1681    16.412810
79       mart_department_model_base_2024                         leave_students_n    Int32       1681    16.412810
80       mart_department_model_base_2024                              graduates_n    Int32       1681    16.412810
81       mart_department_model_base_2024                       fulltime_faculty_n    Int32       1681    16.412810
82       mart_department_model_base_2024                    nonfulltime_faculty_n    Int32       1681    16.412810
83       mart_department_model_base_2024                 international_students_n    Int32       1681    16.412810
84       mart_department_model_base_2024                        female_students_n    Int32       1681    16.412810
85       mart_department_model_base_2024                       masters_students_n    Int32       1681    16.412810
86       mart_department_model_base_2024                      doctoral_students_n    Int32       1681    16.412810
95       mart_department_model_base_2024                    log_enrolled_students  Float32       1681    16.412810
96       mart_department_model_base_2024                            log_graduates  Float32       1681    16.412810
177     P4_PHASE_SAMPLE_MEMBERSHIP_FINAL                              school_type   string       1681    16.412810
178     P4_PHASE_SAMPLE_MEMBERSHIP_FINAL                              region_sido   string       1681    16.412810
209          P4_PHASE_DESIGN_MATRIX_RANK                    numeric_feature_count  float64          4    12.500000
210          P4_PHASE_DESIGN_MATRIX_RANK                categorical_feature_count  float64          4    12.500000
211          P4_PHASE_DESIGN_MATRIX_RANK                    encoded_feature_count  float64          4    12.500000
212          P4_PHASE_DESIGN_MATRIX_RANK                                     rank  float64          4    12.500000
213          P4_PHASE_DESIGN_MATRIX_RANK                          rank_deficiency  float64          4    12.500000
214          P4_PHASE_DESIGN_MATRIX_RANK                         condition_number  float64          4    12.500000
216          P4_PHASE_DESIGN_MATRIX_RANK              duplicate_encoded_columns_n  float64          4    12.500000
217          P4_PHASE_DESIGN_MATRIX_RANK                   perfect_alias_groups_n  float64          4    12.500000
273   P4_MODELING_REVIEW_BUNDLE_MANIFEST                             column_count  float64          1     6.666667
41       mart_department_model_base_2024                              match_score  float64        365     3.563757
286           P4_PHASE_FEATURE_SET_FINAL                          source_decision      str          4     1.600000
287           P4_PHASE_FEATURE_SET_FINAL                   source_decision_reason      str          4     1.600000
98       mart_department_model_base_2024                            major_group_7      str        143     1.396212
108      mart_department_model_base_2024                 ctx24_reference_sample_n  Float32        143     1.396212
109      mart_department_model_base_2024                 ctx24_mean_income_10kkrw  Float32        143     1.396212
110      mart_department_model_base_2024               ctx24_median_income_10kkrw  Float32        143     1.396212
111      mart_department_model_base_2024                 ctx24_income_300plus_pct  Float32        143     1.396212
112      mart_department_model_base_2024                 ctx24_income_400plus_pct  Float32        143     1.396212
113      mart_department_model_base_2024                  ctx24_large_company_pct  Float32        143     1.396212
114      mart_department_model_base_2024                    ctx24_mid_company_pct  Float32        143     1.396212
115      mart_department_model_base_2024                  ctx24_small_company_pct  Float32        143     1.396212
116      mart_department_model_base_2024              ctx24_large_mid_company_pct  Float32        143     1.396212
117      mart_department_model_base_2024               ctx24_public_nonprofit_pct  Float32        143     1.396212

### 7.3 All dataset anomalies

                                 dataset     anomaly_type                            column                                                       detail
0        mart_department_model_base_2024         all-null           ctx24_industry_top3_pct                                              missing_n=10242
1        mart_department_model_base_2024         all-null                ctx24_industry_hhi                                              missing_n=10242
2        mart_department_model_base_2024         constant                     analysis_year                                                    nunique=1
3        mart_department_model_base_2024         constant                     rate_range_qa                                                    nunique=1
4        mart_department_model_base_2024         constant                       source_file                                                    nunique=1
5        mart_department_model_base_2024         constant                     source_sha256                                                    nunique=1
6        mart_department_model_base_2024         constant                       match_score                                                    nunique=1
7        mart_department_model_base_2024         constant       degree_course_conflict_flag                                                    nunique=1
8        mart_department_model_base_2024         constant               major_conflict_flag                                                    nunique=1
9        mart_department_model_base_2024         constant  forbidden_modifier_conflict_flag                                                    nunique=1
10       mart_department_model_base_2024         constant           headcount_grain_version                                                    nunique=1
11       mart_department_model_base_2024         constant           grain_resolution_method                                                    nunique=1
12       mart_department_model_base_2024         constant               grain_review_needed                                                    nunique=1
13       mart_department_model_base_2024         constant                     degree_course                                                    nunique=1
14       mart_department_model_base_2024         constant                masters_students_n                                                    nunique=1
15       mart_department_model_base_2024         constant               doctoral_students_n                                                    nunique=1
16       mart_department_model_base_2024         constant           ctx24_industry_top3_pct                                                    nunique=0
17       mart_department_model_base_2024         constant                ctx24_industry_hhi                                                    nunique=0
18       mart_department_model_base_2024         constant           goms_profile_start_year                                                    nunique=1
19       mart_department_model_base_2024         constant             goms_profile_end_year                                                    nunique=1
20       mart_department_model_base_2024         constant              goms_profile_years_n                                                    nunique=1
21       mart_department_model_base_2024         constant           goms_aggregation_method                                                    nunique=1
22       mart_department_model_base_2024         constant        goms_source_years_observed                                                    nunique=1
23       mart_department_model_base_2024         constant           goms_mapping_confidence                                                    nunique=1
24       mart_department_model_base_2024         constant                goms_row_qa_status                                                    nunique=1
25       mart_department_model_base_2024  range violation              goms_profile_years_n                   year_reasonable_1900_2100 violations=10099
26       mart_department_model_base_2024  range violation        goms_income_trend_per_year                   year_reasonable_1900_2100 violations=10099
27       mart_department_model_base_2024  range violation         goms_hours_trend_per_year                   year_reasonable_1900_2100 violations=10099
28       mart_department_model_base_2024  range violation  goms_firm_300plus_trend_per_year                   year_reasonable_1900_2100 violations=10099
29       mart_department_model_base_2024  range violation     goms_permanent_trend_per_year                   year_reasonable_1900_2100 violations=10099
30       mart_department_model_base_2024  range violation        goms_source_years_observed                   year_reasonable_1900_2100 violations=10099
31       mart_department_model_base_2024  range violation   goms_year_over_year_review_flag                   year_reasonable_1900_2100 violations=10099
32      P4_PHASE_SAMPLE_MEMBERSHIP_FINAL         constant                     analysis_year                                                    nunique=1
33        P4_PHASE_SAMPLE_REGISTRY_FINAL         constant                          major7_n                                                    nunique=1
34        P4_PHASE_SAMPLE_REGISTRY_FINAL         constant               excluded_conflict_n                                                    nunique=1
35        P4_PHASE_SAMPLE_REGISTRY_FINAL         constant                            status                                                    nunique=1
36   department_model_column_registry_v4         constant                             grain                                                    nunique=1
37            P4_PHASE_FEATURE_SET_FINAL         constant              included_in_contract                                                    nunique=1
38        P4_MODEL_FAMILY_RECOMMENDATION         constant                          feasible                                                    nunique=1
39      P4_DUPLICATE_CONFLICT_RESOLUTION         constant                    weight_allowed                                                    nunique=1
40      P4_DUPLICATE_CONFLICT_RESOLUTION         constant               denominator_allowed                                                    nunique=1
41           P4_PHASE_DESIGN_MATRIX_RANK         constant         categorical_feature_count                                                    nunique=1
42           P4_PHASE_DESIGN_MATRIX_RANK         constant                  constant_columns                                                    nunique=1
43           P4_PHASE_DESIGN_MATRIX_RANK         constant       duplicate_encoded_columns_n                                                    nunique=1
44                P4_LINEAR_ALIAS_GROUPS         constant                            coding                                                    nunique=1
45                P4_LINEAR_ALIAS_GROUPS         constant                        alias_type                                                    nunique=1
46                P4_LINEAR_ALIAS_GROUPS         constant             recommended_exclusion                                                    nunique=1
47                 P4_VIF_TOP30_BY_PHASE         constant        corr_matrix_rank_deficient                                                    nunique=1
48              P3_NESTED_CROSSFIT_SMOKE         constant                            status                                                    nunique=1
49              P3_NESTED_CROSSFIT_SMOKE         constant               outer_train_schools                                                    nunique=1
50              P3_NESTED_CROSSFIT_SMOKE         constant          outer_validation_schools                                                    nunique=1
51              P3_NESTED_CROSSFIT_SMOKE         constant                       inner_folds                                                    nunique=1
52              P3_NESTED_CROSSFIT_SMOKE         constant                    selected_alpha                                                    nunique=1
53              P3_NESTED_CROSSFIT_SMOKE         constant                 raw_feature_count                                                    nunique=1
54              P3_NESTED_CROSSFIT_SMOKE         constant                encoded_dimensions                                                    nunique=1
55              P3_NESTED_CROSSFIT_SMOKE         constant                      prediction_n                                                    nunique=1
56              P3_NESTED_CROSSFIT_SMOKE         constant                  nan_prediction_n                                                    nunique=1
57              P3_NESTED_CROSSFIT_SMOKE         constant              outer_validation_mse                                                    nunique=1
58              P3_NESTED_CROSSFIT_SMOKE         constant                  inner_score_json                                                    nunique=1
59      P4_FULL_PIPELINE_BOOTSTRAP_SMOKE         constant                            status                                                    nunique=1
60      P4_FULL_PIPELINE_BOOTSTRAP_SMOKE         constant                 school_resample_n                                                    nunique=1
61      P4_FULL_PIPELINE_BOOTSTRAP_SMOKE         constant                 p3_crossfit_nan_n                                                    nunique=1
62           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency                      P1_STRUCTURE                       coding=onehot_full rank_deficiency=4.0
63           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency                    P1_SELECTIVITY                       coding=onehot_full rank_deficiency=4.0
64           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency                              P2_S                       coding=onehot_full rank_deficiency=4.0
65           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency                              P2_Q                       coding=onehot_full rank_deficiency=4.0
66           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency                              P3_S                       coding=onehot_full rank_deficiency=4.0
67           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency                              P3_Q                       coding=onehot_full rank_deficiency=4.0
68           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency             P4_E_STRUCTURE_A_RATE                       coding=onehot_full rank_deficiency=4.0
69           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency           P4_E_SELECTIVITY_A_RATE                       coding=onehot_full rank_deficiency=4.0
70           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency             P4_P_STRUCTURE_A_RATE                       coding=onehot_full rank_deficiency=4.0
71           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency           P4_P_SELECTIVITY_A_RATE                       coding=onehot_full rank_deficiency=4.0
72           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency       P4_E_JOINT_STRUCTURE_A_RATE                       coding=onehot_full rank_deficiency=4.0
73           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency       P4_P_JOINT_STRUCTURE_A_RATE                       coding=onehot_full rank_deficiency=4.0
74           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency     P4_E_JOINT_SELECTIVITY_A_RATE                       coding=onehot_full rank_deficiency=4.0
75           P4_PHASE_DESIGN_MATRIX_RANK  rank deficiency     P4_P_JOINT_SELECTIVITY_A_RATE                       coding=onehot_full rank_deficiency=4.0
76                 P4_VIF_TOP30_BY_PHASE         high VIF                   school_type_대학교                 model_id=P1_STRUCTURE vif=134.63145338703697
77                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_교육대학                  model_id=P1_STRUCTURE vif=87.17771068620128
78                 P4_VIF_TOP30_BY_PHASE         high VIF               school_type_방송통신대학교                  model_id=P1_STRUCTURE vif=28.99786457065051
79                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_산업대학                 model_id=P1_STRUCTURE vif=24.094387815365742
80                 P4_VIF_TOP30_BY_PHASE         high VIF                   school_type_대학교                          model_id=P2_S vif=73.68626099472041
81                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_교육대학                          model_id=P2_S vif=44.52433557521237
82                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_산업대학                          model_id=P2_S vif=18.12888304328652
83                 P4_VIF_TOP30_BY_PHASE         high VIF               school_type_방송통신대학교                          model_id=P2_S vif=15.39449460542059
84                 P4_VIF_TOP30_BY_PHASE         high VIF                   school_type_대학교                          model_id=P3_S vif=73.68626099472041
85                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_교육대학                          model_id=P3_S vif=44.52433557521237
86                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_산업대학                          model_id=P3_S vif=18.12888304328652
87                 P4_VIF_TOP30_BY_PHASE         high VIF               school_type_방송통신대학교                          model_id=P3_S vif=15.39449460542059
88                 P4_VIF_TOP30_BY_PHASE         high VIF                   school_type_대학교        model_id=P4_E_STRUCTURE_A_RATE vif=134.63906341390071
89                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_교육대학         model_id=P4_E_STRUCTURE_A_RATE vif=87.29818957464633
90                 P4_VIF_TOP30_BY_PHASE         high VIF               school_type_방송통신대학교        model_id=P4_E_STRUCTURE_A_RATE vif=29.019462190493584
91                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_산업대학         model_id=P4_E_STRUCTURE_A_RATE vif=24.11380533334556
92                 P4_VIF_TOP30_BY_PHASE         high VIF                   school_type_대학교          model_id=P4_P_STRUCTURE_A_RATE vif=68.0885217695231
93                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_교육대학         model_id=P4_P_STRUCTURE_A_RATE vif=44.53975855523501
94                 P4_VIF_TOP30_BY_PHASE         high VIF               school_type_방송통신대학교        model_id=P4_P_STRUCTURE_A_RATE vif=15.557422305963096
95                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_산업대학        model_id=P4_P_STRUCTURE_A_RATE vif=12.657302529074856
96                 P4_VIF_TOP30_BY_PHASE         high VIF                   school_type_대학교  model_id=P4_E_JOINT_STRUCTURE_A_RATE vif=134.63906341390071
97                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_교육대학   model_id=P4_E_JOINT_STRUCTURE_A_RATE vif=87.29818957464633
98                 P4_VIF_TOP30_BY_PHASE         high VIF               school_type_방송통신대학교  model_id=P4_E_JOINT_STRUCTURE_A_RATE vif=29.019462190493584
99                 P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_산업대학   model_id=P4_E_JOINT_STRUCTURE_A_RATE vif=24.11380533334556
100                P4_VIF_TOP30_BY_PHASE         high VIF                   school_type_대학교  model_id=P4_P_JOINT_STRUCTURE_A_RATE vif=134.63906341390071
101                P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_교육대학   model_id=P4_P_JOINT_STRUCTURE_A_RATE vif=87.29818957464633
102                P4_VIF_TOP30_BY_PHASE         high VIF               school_type_방송통신대학교  model_id=P4_P_JOINT_STRUCTURE_A_RATE vif=29.019462190493584
103                P4_VIF_TOP30_BY_PHASE         high VIF                  school_type_산업대학   model_id=P4_P_JOINT_STRUCTURE_A_RATE vif=24.11380533334556

### 7.4 Phase data map

  phase               sample_id                        dataframe                                target  raw_feature_count  encoded_feature_count  row_n  school_n status warning
0    P1      P1_STRUCTURE_READY  mart_department_model_base_2024                            a_rate_pct                 13              33.000000   6270       186  READY
1    P1    P1_SELECTIVITY_READY  mart_department_model_base_2024                            a_rate_pct                 17              34.000000   2416       130  READY
2    P2      P2_STRUCTURE_READY  mart_department_model_base_2024                            a_rate_pct                 11              32.000000   8561       198  READY
3    P2    P2_SELECTIVITY_READY  mart_department_model_base_2024                            a_rate_pct                 15              33.000000   3198       146  READY
4    P3      P3_STRUCTURE_READY  mart_department_model_base_2024                            a_rate_pct                 11              32.000000   8561       198  READY
5    P3    P3_SELECTIVITY_READY  mart_department_model_base_2024                            a_rate_pct                 15              33.000000   3198       146  READY
6  P4_E    P4_E_STRUCTURE_READY  mart_department_model_base_2024            health_employment_rate_pct                 12              32.000000   6270       186  READY
7  P4_E  P4_E_SELECTIVITY_READY  mart_department_model_base_2024            health_employment_rate_pct                 16              33.000000   2416       130  READY
8  P4_P    P4_P_STRUCTURE_READY  mart_department_model_base_2024  graduate_school_progression_rate_pct                 12              33.000000   6366       195  READY
9  P4_P  P4_P_SELECTIVITY_READY  mart_department_model_base_2024  graduate_school_progression_rate_pct                 16              34.000000   2439       136  READY

### Saved final outputs

,executed_at,dataset_count,fail_count,warning_dataset_count,anomaly_rows,inventory_path,all_missing_path,anomaly_path,phase_map_path,report_path,profile_file_count,qa_file_count,report_file_count,environment_path,run_manifest_path
0,2026-07-13T02:54:20.425855+00:00,16,0,12,104,workbook/p2/p2_4/p4_modeling_readiness_v4/dataset_inspection/qa/dataset_inventory_final.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/dataset_inspection/qa/all_datasets_top_missing.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/dataset_inspection/qa/all_dataset_anomalies.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/dataset_inspection/qa/phase_data_map.csv,workbook/p2/p2_4/p4_modeling_readiness_v4/dataset_inspection/reports/P4_DATASET_INSPECTION_REPORT.md,80,4,2,workbook/p2/p2_4/p4_modeling_readiness_v4/dataset_inspection/logs/dataset_inspection_environment.json,workbook/p2/p2_4/p4_modeling_readiness_v4/dataset_inspection/logs/dataset_inspection_run_manifest.json

INSPECTION_STATUS:
PASS